### ISSUE TITLE
Cool project

### ISSUE THREAD

**Issue by remorses** [shuding/nextra#1]
I opened this issue just to let you know I am developing a similar solution called [dokz](https://github.com/remorses/dokz), it would be cool to join the efforts if you want

It also has a playground to preview react components

I would love to have your opinion on the project

Thank you for your awesome work at @vercel

**Comment by shuding** [comment]
@remorses wow I didn't know that dokz exists, great project! 

I created Nextra because I wanted to make a docs site for my own open source projects and use Next.js of course. It seems dokz covers almost all the features that I need, I think I can contribute to dokz instead :)

**Comment by hunvreus** [comment]
@shuding would you still recommend using Nextra then, or would dokz be a better pick for the long term?

**Comment by remorses** [comment]
Use what you like the most

**Comment by shuding** [comment]
@hunvreus dokz will be a better pick, since this project is more like an experiment and I don’t have bandwidth to actively maintain it for now.

**Comment by hunvreus** [comment]
Thanks for the follow up @shuding, cheers.
