### ISSUE TITLE
Bugs when reading markdown

### ISSUE THREAD

**Issue by tvvignesh** [shuding/nextra#101]
Hi. I tried to load the existing md/mdx files with nextra but I did face errors for some files when the server started (it worked well with Docusaurus before without any issues). I had to delete the files with errors temporarily so that I can test how nextra works.

These are the errors I get:

<img width="320" alt="1" src="https://user-images.githubusercontent.com/1165845/110496817-e28e2a80-811b-11eb-8630-8c735a17e31b.PNG">
<img width="572" alt="2" src="https://user-images.githubusercontent.com/1165845/110496824-e3bf5780-811b-11eb-91a4-51637d4ed656.PNG">

For context, these are the files I was trying to load:
https://github.com/dotansimha/graphql-code-generator/tree/master/website/docs

And was using https://github.com/vercel/swr-site as the boilerplate to start off.

Thanks.

**Comment by shuding** [comment]
It seems like that file isn't valid Markdown, do all files have this error?

**Comment by tvvignesh** [comment]
@shuding Not all the files, but few of them. I may be wrong, but shouldn't invalid markdown be treated as text rather than throwing a syntactical error? I mean, its basically a text file right?

**Comment by shuding** [comment]
> but shouldn't invalid markdown be treated as text rather than throwing a syntactical error? I mean, its basically a text file right?

No, they're not text files. Nextra is using MDX by default, and the code (from your screenshot) isn't valid in MDX (/JSX).
