### ISSUE TITLE
hidden _meta in base project, hidden _meta in subfolders

### ISSUE THREAD

**Issue by alexanderfsm** [shuding/nextra#1017]
"docs": {
    "title": "Documentação",
    "type": "page",
    "display": "hidden"
  },
![image](https://user-images.githubusercontent.com/94754185/205467656-9d996b27-c399-483c-8fe1-cfb57efd67a1.png)

"docs": {
    "title": "Documentação",
    "type": "page"
  },

![image](https://user-images.githubusercontent.com/94754185/205467676-21af9817-5121-4115-823f-efb06d8e0514.png)

i want remove documentação from navbar

![image](https://user-images.githubusercontent.com/94754185/205467721-dbbd8a16-ccb7-4828-a1f6-cb63c6c0799b.png)

without remove from subfolder

**Comment by Subham-Maity** [comment]
You can do something like this https://github.com/shuding/nextra/blob/e1fc506a0bdf73fe9fcf679e3de39918697aa352/docs/pages/_meta.json#L14-L21

**Comment by B2o5T** [comment]
Remove `type: page` if you want to remove the link from navbar
