### ISSUE TITLE
Fallback to `.md` if file with locale not found

### ISSUE THREAD

**Issue by tvvignesh** [shuding/nextra#102]
Hi. Currently, using locale and suffixing with `en-US` works without any issues in markdown files.

What I wanted to do was set the default locale to `en-US` and suffix files wherever possible. In case a file with a locale suffix is not found, but if the same name without locale suffix does exist, it can probably route to that.

**Comment by dimaMachina** [comment]
Closing since i18n starting from v3 doesn’t contain suffixes
