### ISSUE TITLE
Is it possible to redirect feedback to another link instead of the  docsRepositoryBase

### ISSUE THREAD

**Issue by Lingyun-Mira** [shuding/nextra#1029]
**Rather than using the GitHub issues section, I would like to add my own feedback section. Is it possible to redirect to another link instead?**

![image](https://user-images.githubusercontent.com/84528271/205594508-23dfff3b-ab7d-4a5a-93f2-2b884d3f4eb9.png)

**Comment by shuding** [comment]
We should add support for that, maybe an optional `feedback.link: (currentTitle, currentURL) => string`

**Comment by mrmckeb** [comment]
I was looking for this today as well, that sounds like a great fix @shuding. Do you want a hand implementing that?

**Comment by shuding** [comment]
@mrmckeb yeah would love to accept a PR for that ❤️

**Comment by B2o5T** [comment]
@shuding I don’t think we need the new option, since we have `toc.extraContent` option for this case https://github.com/shuding/nextra/blob/e34eff493eff00a350b87e86e31aa9625fec957b/packages/nextra-theme-docs/src/types.ts#L107
