### ISSUE TITLE
hydration failed at preview deploy

### ISSUE THREAD

**Issue by promer94** [shuding/nextra#1031]
[Preview deploy](https://nextra-v2-git-fork-promer94-fix-doc-preview-shuding1.vercel.app/docs) is not working currently. 

MDX component does not hydrate correctly in preview deploy.

<img width="1250" alt="Screenshot 2022-12-05 at 20 01 25" src="https://user-images.githubusercontent.com/15878786/205632637-2bbcd467-dc6a-4562-983d-05bf9821e6c5.png">

Production:
<img width="1128" alt="Screenshot 2022-12-05 at 20 01 06" src="https://user-images.githubusercontent.com/15878786/205632631-cd87dc83-15e6-4fa8-be40-704c14e01d8c.png">

**Comment by B2o5T** [comment]
Closed https://github.com/shuding/nextra/pull/1168
