### ISSUE TITLE
HTTP Request plugin/component

### ISSUE THREAD

**Issue by pablolaggerUALA** [shuding/nextra#1033]
Hello! we use nextra in our public documentation (https://developers.ualabis.com.ar/) and we want to know if you plan to add any component/plugin that allows compatibility with swagger to simulate HTTP requests on the page?

**Comment by shuding** [comment]
Since you can use MDX, I think something like https://github.com/swagger-api/swagger-ui/tree/master/flavors/swagger-ui-react (or another component) can be directly added to a page. Is that what you need?

**Comment by pablolaggerUALA** [comment]
Yes sir! but
