### ISSUE TITLE
local development: command "pnpm i" causes dependency error in nextra-theme-docs 2.0.1 

### ISSUE THREAD

**Issue by mi-hol** [shuding/nextra#1035]
Just did a fresh "deploy" from https://nextra.site/docs/docs-theme/start

As documented in README.md
![image](https://user-images.githubusercontent.com/22799428/205881186-d83460b9-851c-4dc4-82c4-01a536103df4.png)

when I run `pnpm i` below error is caused.

```
dependencies:
+ next 13.0.6
+ nextra 2.0.1
+ nextra-theme-docs 2.0.1
+ react 18.2.0
+ react-dom 18.2.0

 WARN  Issues with peer dependencies found
.
└─┬ nextra-theme-docs 2.0.1
  └─┬ @reach/skip-nav 0.17.0
    ├── ✕ unmet peer react@"^16.8.0 || 17.x": found 18.2.0
    ├── ✕ unmet peer react-dom@"^16.8.0 || 17.x": found 18.2.0
    └─┬ @reach/utils 0.17.0
      ├── ✕ unmet peer react@"^16.8.0 || 17.x": found 18.2.0
      └── ✕ unmet peer react-dom@"^16.8.0 || 17.x": found 18.2.0
```

**Comment by mi-hol** [comment]
pnpm-lock.yaml generated in my local repository has the highlighted differences compared to same file in https://github.com/shuding/nextra-docs-template 
Any suggestions for a workaround?

![image](https://user-images.githubusercontent.com/22799428/205876971-9304e3fd-1f85-43b4-a842-e2443901dcb2.png)

**Comment by mi-hol** [comment]
root cause seems https://github.com/reach/reach-ui/issues/925

**Comment by phenomen** [comment]
> root cause seems [reach/reach-ui#925](https://github.com/reach/reach-ui/issues/925)

Considering that Reach UI is [not maintained anymore](https://github.com/reach/reach-ui/issues/972) it might worth considering getting rid of that library.

**Comment by mi-hol** [comment]
@phenomen thanks for hint

@shuding radix  as used in https://github.com/UMAprotocol/voter-dapp-v2/pull/118/commits/527b1e0f72ad2521d4090591d42c652f06539e06 looks like a quick and easy approach to fixing it. What is your thought?

**Comment by shuding** [comment]
Makes sense to move away from Reach to Radix! Happy to accept a PR or I can do it next week 👍

**Comment by mi-hol** [comment]
reach/skip-nav is used only in examples/swr-site/pages/_document.js

would replacement with <div role="navigation"> as in https://www.w3.org/WAI/ARIA/apg/example-index/landmarks/navigation.html be a proper replacement?

**Comment by shuding** [comment]
I don't think that does the same job. `skip-nav` provides [this](https://swr.vercel.app) "skip to content" link when using tab to navigate the site:

<img width="1252" alt="CleanShot 2022-12-07 at 00 32 25@2x" src="https://user-images.githubusercontent.com/3676859/206048083-39330b29-b367-4e8e-b542-8f251f146feb.png">

**Comment by mi-hol** [comment]
Unfortunately I have no idea how to fix this issue :(

**Comment by mi-hol** [comment]
update:

after I removed the mdx file using "callout", build succeeded but it seems to indicate another error in nextra-theme-docs


./pages/99_HowToEditSite/2 Advanced formatting in Markdown.mdx
Module not found: Package path ./callout is not exported from package /vercel/path0/node_modules/nextra-theme-docs (see exports field in /vercel/path0/node_modules/nextra-theme-docs/package.json)

**Comment by arsnl** [comment]
Solution proposed in https://github.com/shuding/nextra/pull/1051
