### ISSUE TITLE
Nextra site tagged as porn

### ISSUE THREAD

**Issue by kabeza** [shuding/nextra#1042]
Hi
Not an issue, but Fortinet rules contain that nextra website is tagged as porn, and blocks it
Hope there's a way to report it and whitelist it, because the link to report it here throws 404, and firewall managers aren't very reach-able

![imagen_1064](https://user-images.githubusercontent.com/274856/206182387-57575dc1-fa61-4261-b1e4-7a9164645d5e.jpg)

**Comment by SagaGG** [comment]
lol, I could reach the team to see if it will help.
