### ISSUE TITLE
Getting syntax errors in a valid md

### ISSUE THREAD

**Issue by govizlora** [shuding/nextra#1044]
With a .md file with content:
```
<OK>
```

I got this build error:
```
./pages/test.md
Expected a closing tag for `<OK>` (1:1-1:5)
```

The issue seems to be that nextra tries to read `<OK>` as HTML. I've checked the doc and cannot find a way to prevent nextra from interpreting markdown as HTML.

(I'm trying to use`typedoc` + `typedoc-plugin-markdown` to generate API docs, and the generated md has lots of cases similar to above.)

**Comment by B2o5T** [comment]
Typedoc plugin markdown doesn’t support mdx 2

Use the following patch https://github.com/tgreyuk/typedoc-plugin-markdown/issues/305 since you need to escape all opening `<`
