### ISSUE TITLE
Add custom font

### ISSUE THREAD

**Issue by mirecatercero** [shuding/nextra#1048]
First of all, thank you very much for this awesome tool guys, it's really amazing. 

Something that i would like to change is the default font and some styles about the mdx. Do you know if is it possible?

Thanks!!

**Comment by shuding** [comment]
For sure! Since Nextra is on top of Next.js, you can check this out: https://nextjs.org/docs/basic-features/font-optimization :)

Another way is to have global CSS: https://nextjs.org/docs/basic-features/built-in-css-support
