### ISSUE TITLE
Twitter Link, Incorrect HREF

### ISSUE THREAD

**Issue by Saintpreston** [shuding/nextra#1049]
**Link Missing Underscore**

I believe the docs are meant to link to Shu's Twitter here. (in the code block)
<img width="882" alt="Screenshot 2022-12-08 at 3 23 42 PM" src="https://user-images.githubusercontent.com/90055250/206560084-eb1b0790-a680-4396-ac78-7500efcc3a07.png">

However, it links to a stranger's Twitter - because [Shu's Twitter](https://twitter.com/shuding_) page URL has an underscore. 
[This](https://twitter.com/shuding) does not.

To repeat behavior:
Go [here](https://nextra.site/docs/docs-theme/theme-configuration#chat-link)

**Comment by shuding** [comment]
Oh good catch, thanks! :D
