### ISSUE TITLE
theme.config.tsx | frontMatter.suffix: is not working

### ISSUE THREAD

**Issue by ojasuno** [shuding/nextra#1052]
in the new config file `theme.config.tsx` how do we configure this:

` titleSuffix:` is what was used in the old version `theme.config.js`

i tried this, but it is not working ?!

```
<meta property="og:suffix" content={frontMatter.suffix || "."} />
```

instead, it is still defaulting to

`- Nextra`

...any & all help is appreciated.

**Comment by B2o5T** [comment]
https://github.com/shuding/nextra/issues/969#issuecomment-1311782968

**Comment by B2o5T** [comment]
`useNextSeoProps: () => ({ titleTemplate: '%s your suffix' })`
