### ISSUE TITLE
links are not crawlable next js

### ISSUE THREAD

**Issue by tuanducdesign** [shuding/nextra#1053]
I need to handle this when checking SEO tools

How to show full url? 

Example: https://example.com/

**Comment by shuding** [comment]
Sorry I don't understand your question. Did you mean that links are having the relative URL like `<a href="/docs">`, but you want to contain domains?

**Comment by tuanducdesign** [comment]
Yes

**Comment by shuding** [comment]
I believe 99.99% search engine crawler supports that (e.g. if you check GitHub or CNN websites, they just use relative URLs). Using an absolute URL makes it hard to maintain when changing the domain.

If you want to you can still use `[Example](https://example.com)` though.
