### ISSUE TITLE
Feature Request: 'Back to top' button and 'Feedback' form

### ISSUE THREAD

**Issue by C-EO** [shuding/nextra#1061]
In my strong opinion, I think it would be great and useful if the Nextra Docs theme had a `Back to top` button and a `Feedback` form.

### Scenario(s)

A great scenario for the feedback form would be the implementation used by Vercel on their documentation website.

**Reference:** https://vercel.com/docs

Feedback

![image](https://user-images.githubusercontent.com/85847352/206889112-066124b9-0975-4b85-b9f0-d594ab642e59.png)

![image](https://user-images.githubusercontent.com/85847352/206889164-fe1f15a4-2d06-4755-abaf-9d5cc132f446.png)

Back to top

![Web capture_11-12-2022_91030_vercel com](https://user-images.githubusercontent.com/85847352/206889276-4e657ce9-d896-4b8c-a836-2b87ff331e97.jpeg)

**Comment by LuciferUchiha** [comment]
I would also strongly up this :) 

Regarding the feedback form I was able to integrate Giscus into my Nextra app: https://github.com/LuciferUchiha/nextra-garden

**Comment by LuciferUchiha** [comment]
@C-EO @shuding I have also managed to add a scroll to the top button which was then added via the "main" argument in the theme.config. 

https://github.com/LuciferUchiha/nextra-garden/blob/main/components/BackToTop/backToTop.tsx
https://github.com/LuciferUchiha/nextra-garden/blob/main/theme.config.tsx#L55
