### ISSUE TITLE
Visibility Issue ⭐

### ISSUE THREAD

**Issue by luke-klein** [shuding/nextra#1062]
**Users should be able to easily find the topics with more prominent header content(increase the size of the text and more prominent contrast** 

![image](https://user-images.githubusercontent.com/120297915/206891372-2f66cc75-73b1-4bff-a4b3-d1fd6510c8b3.png)

**And the side contrast should be fixed according to the dark theme something like this** 

![image](https://user-images.githubusercontent.com/120297915/206891619-8bd06035-9ff2-4ec9-8661-152fbf6292aa.png)

**Comment by shuding** [comment]
Thanks for the feedback, we will try our best to make the website more accessible. The reason we didn't make active items in the navbar very prominent is totally a design consideration: if it's eye-catching in everywhere, the content becomes less prominent and that's missing the point. That said, I agree something can be done to improve it though. Will keep this one open!

**Comment by Subham-Maity** [comment]
@luke-klein Depending on your preference, you can change it like this 

Make a custom CSS and change it globally (optional)
 ```css
a {
    color: #212534;
    text-decoration: none;
    font-family: sans-serif;
    font-weight: bold;
}
```
