### ISSUE TITLE
codeblock render very differently between nextra-theme-blog version 0.1.2 and 0.1.4

### ISSUE THREAD

**Issue by YikSanChan** [shuding/nextra#108]
Hi,

I tried to bump nextra and nextra-theme-blog version for my site, but my codeblocks render differently.

PR: https://github.com/YikSanChan/site/pull/19
Check codeblock before the bump: https://yiksanchan.com/posts/practical-mlsys-goodreads
Check codeblock after the bump: https://site-git-bump-nextra-yishengdd.vercel.app/posts/practical-mlsys-goodreads

basically, before:
![image](https://user-images.githubusercontent.com/17229109/111852212-0ee24c00-8951-11eb-806f-415433c8cc87.png)
after:
![image](https://user-images.githubusercontent.com/17229109/111852226-16a1f080-8951-11eb-9f13-03cd8318cd3a.png)

Is there a way to maintain backward compatibility, or some upgrade guide? Thank you!

**Comment by YikSanChan** [comment]
@shuding Hi Shu, could you please help take a look? Thanks!

**Comment by emptypockets-dev** [comment]
I have the same issue with a default/new setup using Vercel

**Comment by zjhou** [comment]
It seems that the THEME configuration  affects the inline style of the prism-code element, making the text black.
https://github.com/shuding/nextra/blob/836156ea7ecc2ee7d23045e082a03072a6f29b4b/packages/nextra-theme-blog/src/mdx-theme.js#L11

**Comment by shuding** [comment]
I’ll take a look soon!
