### ISSUE TITLE
Extracting MDX to components

### ISSUE THREAD

**Issue by pawelkrystkiewicz** [shuding/nextra#1086]
I want to extract repeating segments in my MDX to components. How should I go about it for extra to detect and compile MDX?

Example 1
```
## Sizes

This component supports `size` prop with values `sm`, `md`, `lg`.
```

This is my workaround for having text marked as `code` but it only semi-works as it doesn't have all of the nextra classes for code tag
```
const multipleWarning = (
  <>
    If multiple is set, the type of <code>value</code> will be <code>T[]</code>
  </>
)
```

**Comment by B2o5T** [comment]
you can just import `.md`/`.mdx` file

exampe:
https://github.com/dotansimha/graphql-code-generator/blob/2f7e5477726da8866f0d9db2e7fc9daafd5325bf/website/src/pages/plugins/java/java.mdx?plain=1#L6

**Comment by shuding** [comment]
This is our current recommend way:

https://nextra.site/docs/guide/syntax-highlighting#with-dynamic-content

> handles MDX transformation to jsx

We can't do syntax highlighting in runtime with Shiki unfortunately.
