### ISSUE TITLE
Substring highlight when in filename

### ISSUE THREAD

**Issue by lukadev-0** [shuding/nextra#1088]
I'm experiencing an issue where it seems to be highlighting a substring when the substring is inside the filename.

~~~mdx
```js filename="a/hello/file.js
console.log("hello")
```
~~~

This highlights the hello part even though its inside of the filename.

![image](https://user-images.githubusercontent.com/47296785/208125947-16a2ffe3-994a-4421-89d6-217c831a8395.png)

**Comment by B2o5T** [comment]
will be fixed with `filterMetaString` option in  https://github.com/shuding/nextra/pull/1211
