### ISSUE TITLE
Hot reload of TOC sidebar not working

### ISSUE THREAD

**Issue by danez** [shuding/nextra#1090]
First of all thanks for this great framework. It is so easy and I love it. 💜

While working with it I noticed that the TOC sidebar on the right is not updating when I make changes to the headlines in `*.mdx` files. Not a big deal, but would be a nice touch if that would work when running `next dev`. :)

I use the latest version 2.0.1 with the docs template, the repo is here: https://github.com/reactjs/react-docgen/tree/main/packages/website

Thanks

**Comment by B2o5T** [comment]
this is tricky since toc's headings passed as props and with fast refresh component state rest the same.

@shuding any thoughts on how this can be fixed? I was thinking about `// @refresh reset` comments but seems like they do not work anymore https://github.com/swc-project/swc/issues/6022

**Comment by shuding** [comment]
Managed to fix it with webpack's HMR (`module.hot`), gonna open a PR soon

**Comment by B2o5T** [comment]
Amazing 😍 can’t wait to see your solution

**Comment by shuding** [comment]
@B2o5T Let me know what do you think about #1144 🙌

**Comment by B2o5T** [comment]
I could review only after 03/01
