### ISSUE TITLE
When will the documentation for using a custom theme be ready?

### ISSUE THREAD

**Issue by okanji** [shuding/nextra#1098]
I would really like to use a custom theme and anticipate the release of the docs

**Comment by prisis** [comment]
You can check my example out [https://github.com/visulima/visulima/tree/main/packages/nextra-theme-docs](https://github.com/visulima/visulima/tree/main/packages/nextra-theme-docs,)  
  
The problem that i had was the prefix of the tailwind css classes

**Comment by AbhijithGanesh** [comment]
@shuding Can I please contribute to this ?

**Comment by shuding** [comment]
Hi! We're still making changes to some internal APIs (especially the global Nextra internals and context), but you can take a look at https://github.com/shuding/nextra-example as an example for now.

Feel free to contribute the docs though (not just custom theme, there're still a lot of missing things)!

**Comment by okanji** [comment]
Great, thank you!

**Comment by shuding** [comment]
We have the docs ready here: https://nextra.site/docs/custom-theme
