### ISSUE TITLE
Extra Dark Mode Button

### ISSUE THREAD

**Issue by luke-klein** [shuding/nextra#1102]
Is it possible to add an extra dark mode button like the previous version of Nextra? 

![image](https://user-images.githubusercontent.com/120297915/208546084-81bb90e4-7392-4537-b9f9-ebb2ca9c8094.png)

**Comment by shuding** [comment]
Yes I think you can do that with extra content in the navbar, and use the hook from `next-themes`.

An example needs to be added to the docs.
