### ISSUE TITLE
Tailwindcss support

### ISSUE THREAD

**Issue by chris23lngr** [shuding/nextra#1104]
Is there a way to use tailwindcss to design the theme? Components styled with tailwind take on the classes, but not the styles.

**Comment by chris23lngr** [comment]
Ok, so after digging through the code I found out, that tailwind is supported by default, with the ```nx-``` Prefix. This does help, but still I'm wondering, why I would have to use a prefix all the time? And also, how would you add new Fonts, or link tags to the page? I suppose, that creating a custom ```_document``` file, would probably crash the application (?).

**Comment by lukadev-0** [comment]
Setup tailwind like you normally would, the nx- prefix is to prevent your own styles to conflict with nextra's styles.

You can add link tags through the [`head` property of the theme configuration](https://nextra.site/docs/docs-theme/theme-configuration#head-tags).

**Comment by chris23lngr** [comment]
Exactly what I was looking for, seems like I should browse through the docs a little bit more. Thanks a lot!

**Comment by anaclumos** [comment]
> @lukadev-0 can you elaborate on what you mean by "what you normally would", I tried using the installation steps provided in [tailwind's documentation](https://tailwindcss.com/docs/guides/nextjs) but it doesn't seem to work.

Would love to hear the reply to this as well!

**Comment by lukadev-0** [comment]
> > @lukadev-0 can you elaborate on what you mean by "what you normally would", I tried using the installation steps provided in [tailwind's documentation](https://tailwindcss.com/docs/guides/nextjs) but it doesn't seem to work.
> 
> Would love to hear the reply to this as well!

Make sure you add `.mdx` and the `./theme.config.tsx` file to your config, and set `"darkMode"` to dark so it syncs with Nextra's theme switcher.

(sorry for the late response btw)
