### ISSUE TITLE
Default `gitTimestamp` component breaks hydration occasionally

### ISSUE THREAD

**Issue by jaredLunde** [shuding/nextra#1108]
Because a user's time zone may be different than the server the page was generated on, this component will break hydration intermittently.

https://github.com/shuding/nextra/blob/73241b3fee58f0318e9349a5eb7650a7cd55a4e3/packages/nextra-theme-docs/src/constants.tsx#L58-L62

Options for fixing include:

- Prefer setting the date on the client instead while leaving a placeholder on the server
- Pin the date to a specific time zone, e.g. 
```tsx
      <>
        Last updated on{' '}
        <time dateTime={timestamp.toISOString()}>
          {timestamp.toLocaleDateString(locale, {
            day: 'numeric',
            month: 'long',
            year: 'numeric',
            timeZone: 'UTC'
          })}
        </time>
      </>
```

Obviously a user can make this change on their own via the config, but as a default I think it would be better to never break hydration.

**Comment by B2o5T** [comment]
you are right, we need to use `useMounted` hook and display updated time only on the client
