### ISSUE TITLE
i18n Support for Docs theme search field and TOC-Sidebar title

### ISSUE THREAD

**Issue by philippbruhin** [shuding/nextra#1109]
Not sure if I am doing wrong or if the option is not available. Would it be possible to make following texts (search input field and TOC title) multilang?

![image](https://user-images.githubusercontent.com/7021907/209132442-98308065-b20e-4fb3-9eae-d1b50a85c690.png)

It can be modified in `themes.config.tsx` as follows (German example), but there only for all languages once.

```
  toc: {
    title: "Auf dieser Seite"
  },
```

Many thanks to everyone who is working on Nextra and is driving this great project forward.

**Comment by B2o5T** [comment]
use `toc.title` https://nextra.site/docs/docs-theme/theme-configuration#table-of-contents 
and `search.placeholder` https://nextra.site/docs/docs-theme/theme-configuration#search

example https://github.com/shuding/nextra/blob/dc9cdf220c2a4cf03b3733c02d8d22e6eda8ec80/packages/nextra-theme-docs/src/constants.tsx#L133-L139
