### ISSUE TITLE
SEO and Description for each page 

### ISSUE THREAD

**Issue by luke-klein** [shuding/nextra#1110]
I used this for SEO titles and summaries in my previous website 
```
---
published: true
publishedAt: "2020-11-22"
updatedAt: "2020-11-22"
title: REST Architecture
seoTitle: What is Statelessness ?
summary: The statelessness constraint means that the server does not store any state about the client between requests
---
```

If I wish to rank my pages with Nextra, how do I do that for each page?

**Comment by B2o5T** [comment]
use `useNextSeoProps`, see working example https://github.com/shuding/nextra/blob/2bda6e6a83eb99eff8b35adf0aa2f7b96b63ee59/examples/docs/src/theme.config.js#L21-L73
