### ISSUE TITLE
Is nextra bundling external remark plugins into the client bundle?

### ISSUE THREAD

**Issue by pomber** [shuding/nextra#1112]
I have a `theme.config.js` that looks like this (I'm using nextra-theme-docs@2.0.1):

```js
import { remarkCodeHike } from "@code-hike/mdx"
import theme from "shiki/themes/nord.json"

export default {
  logo: <span>My Nextra Documentation</span>,
  project: {
    link: "https://github.com/shuding/nextra",
  },
  remarkPlugins: [[remarkCodeHike, { theme }]],
}
```

And I get this error `Module not found: Can't resolve 'fs'`, which usually happens when someone tries to bundle `@code-hike/mdx` with a `web` target.

Is that the case here?

**Comment by B2o5T** [comment]
you are wrong, `remarkPlugins` should be set inside `next.config.js` not inside `theme.config.js`
