### ISSUE TITLE
Custom theme from OFFICIAL_THEMES?

### ISSUE THREAD

**Issue by tuanducdesign** [shuding/nextra#1114]
In the loader.mjs file on the nextra package, I found OFFICIAL_THEMES

Can I fully customize nextra's existing classes?

![Screen Shot 2022-12-24 at 10 11 05](https://user-images.githubusercontent.com/69758022/209419227-c4bfabfb-727d-485e-b9b9-d4a170021313.png)

**Comment by B2o5T** [comment]
this code is needed to auto-inject CSS of official themes for your app, and of course, you can override existing classes, just import your CSS file in `_app.jsx`
