### ISSUE TITLE
How to show images?

### ISSUE THREAD

**Issue by indarjoko** [shuding/nextra#1115]
I have tried this method but still didn't appeared anything. Can you help me to show how the best method? thanks.

**Comment by indarjoko** [comment]
https://nextra.site/docs/guide/image#static-image

**Comment by indarjoko** [comment]
Here's my mdx code 

![Hello](/aasets/images/connection1.png)

**Comment by B2o5T** [comment]
can you share your source markdown code?

**Comment by indarjoko** [comment]
here's my markdown code
![image](https://user-images.githubusercontent.com/19380635/209490021-b6b4f67d-b5c5-4d34-a9bf-99de015da09e.png)

my theme.config.ts code
![image](https://user-images.githubusercontent.com/19380635/209490112-45052957-bc8f-42bd-a0a4-ac608727def8.png)

**Comment by B2o5T** [comment]
You need to put your `assets` folder inside `public` folder

**Comment by indarjoko** [comment]
oke, but I tried to load image from public folder as seen on last pictures. still didn't load images. btw, I deploy from vercel and remote to local PC.

**Comment by B2o5T** [comment]
See examples folder in repo with working examples

**Comment by indarjoko** [comment]
Allright, so I put images folder to .github as seen below and it works.

![image](https://user-images.githubusercontent.com/19380635/209496161-66d08083-ab78-4cb8-9abd-5f91cdcae510.png)

**Comment by indarjoko** [comment]
here's the result

![image](https://user-images.githubusercontent.com/19380635/209496216-db9e2b0a-d144-4766-b2c9-21b09a4db1a6.png)

**Comment by shuding** [comment]
Please read https://nextjs.org/docs/basic-features/static-file-serving. Next.js only serves files inside `public` as accessible static files.
