### ISSUE TITLE
Possible to use FrontMatter page props in the current mdx page?

### ISSUE THREAD

**Issue by bgiovand** [shuding/nextra#1120]
Is it possible to use props defined in frontmatter in the same page? Trying to de-duplicate content.

Something like the following:
<img width="392" alt="image" src="https://user-images.githubusercontent.com/179564/209454353-299e9440-d04f-4092-af90-05132a77aab1.png">

**Comment by B2o5T** [comment]
```jsx
import { useConfig } from 'nextra-theme-docs'

export function FrontMatter({ prop }) {
  const config = useConfig()
  return config.frontMatter[prop]
}

<FrontMatter prop="summary" />
```
