### ISSUE TITLE
Group Documentations

### ISSUE THREAD

**Issue by chris23lngr** [shuding/nextra#1122]
## Problem 

Currently, there is no possibility to group individual sections of a documentation. An example: A documentation consists of several groups:

- cars
- Fruits

These groups should all be separated by a serperator and each of these groups contains several pages and folders. Currently the folder structure would look like this:

```
citrus/
├─ lemon.mdx
├─ oragne.mdx
apple.tsx
audi.mdx
banana.mdx
bmw.mdx
index.mdx
mercedes.mdx
_meta.json
```

This creates a problem with the folder structure. If you use this approach, the folder structure quickly becomes very confusing and messy, because all pages are in the ```pages``` folder.

## Possible solution

One approach to solving this problem would be to use a specific symbol, similar to Next.js 13, to identify folders as a group rather than a path. This would enable a better and clearer folder structure. The folder structure could then look like this:

```
(cars)/
├─ audi.mdx
├─ bmw.mdx
├─ mercedes.mdx
(fruits)/
├─ citrus/
│  ├─ oragne.mdx
│  ├─ lemon.mdx
├─ apple.tsx
├─ banana.mdx
├─ _meta.json
├─ _meta.json
index.mdx
```

## Why not use folders?
In certain cases, such a solution can be very helpful. For example: The groups should always be open and cannot be closed.  Such a structure of the documentation gives the user a better user experience and an easier overview.

_This ticket should only be seen as a suggestion for a new feature. I welcome any criticism and feedback on this idea_

**Comment by C-EO** [comment]
@chris23Ingr, in what way is this different from what's documentated [here](https://nextra.site/docs/guide/organize-files)?

**Comment by C-EO** [comment]
I don't know if I am confused by your question but I see no difference

**Comment by shuding** [comment]
The app directory in Next.js 13 already supports grouped routes, however Nextra requires pages directory still which is very tricky.

**Comment by chris23lngr** [comment]
(Sorry for the late repsonse, currently on vacation)

> I don't know if I am confused by your question but I see no difference

When I posed the problem, I was already aware that it is probably difficult to understand and could lead to misunderstandings. 

The documentation describes how to structure your files and folders, but not about how to group them.

The most obvious solution is probably to use the new `app` directory from Next.js, as @shuding  already mentioned, which to my understanding isn’t possible at the moment. Hence the question: Does Nextra have any plans switching to the `app` directory in the future or will it continue to use the `pages` directory?

**Comment by shuding** [comment]
> Does Nextra have any plans switching to the app directory in the future or will it continue to use the pages directory?

It will continue to use pages/.

**Comment by chris23lngr** [comment]
Okay, sounds like there is no good solution to this issues, might as well close the issue at this point. Thanks for the feedback anyways!

**Comment by chris23lngr** [comment]
Short addition:

If you start individual pages with a certain "prefix" (for example, `fruit.`), the files are of course automatically organised alphabetically. This is not a perfect solution, but it comes pretty close.
