### ISSUE TITLE
Generate OpenGraph Tags from Frontmatter

### ISSUE THREAD

**Issue by LucaNerlich** [shuding/nextra#113]
It would be greate, if (for each page) the opengraph tags could be generated based on the frontmatter from the corresponding markdown file. This would then generate the "share" preview card, when the blog url gets posted on social media, discord, slack etc.

Example: 
```markdown
---
title: my blog test
date: 2021/3/27
tag: code, tech
author: Luca Nerlich
description: test description
image: /images/blog/test.jpg
---
```

Example OG Tags

https://ogp.me/

```html
<html prefix="og: https://ogp.me/ns#">
<head>
<title>my blog test</title>
<meta property="og:title" content="The Rock" />
<meta property="og:type" content="article" />
<meta property="og:url" content="<get this from next router>" />
<meta property="og:image" content="<get this from next router>/images/blog/test.jpg" />
...
</head>
...
</html>
```

**Comment by RayhanADev** [comment]
I agree, that is a good idea!

**Comment by shuding** [comment]
Great feature to have, thanks!

**Comment by buccalon** [comment]
It would be nice to have an option to define custom meta tags too.
In my case, I'd like to have each page accessible to citation managers like Zotero.
See: https://www.zotero.org/support/dev/exposing_metadata

**Comment by B2o5T** [comment]
Integration of `next-seo` will be available in the future beta release.

you can take a look at an example of the configuration of `getNextSeoProps()` theme option here https://github.com/shuding/nextra/blob/core/examples/docs/src/theme.config.js#L20-L73

Also you can access to parsed frontMatter data in `getNextSeoProps` function via `useConfig` hook.
