### ISSUE TITLE
public/sitemap.xml is not found (404)

### ISSUE THREAD

**Issue by rojarsmith** [shuding/nextra#1130]
I use i18n, it works fine.

I generate the sitemap.xml in the public. 

![Screenshot 2022-12-26 155550](https://user-images.githubusercontent.com/10322636/209521408-024355b7-b0ed-4de6-adbd-b69c4a374118.png)

But when I access

http://localhost/sitemap.xml

It shows 404 not found.

How to service the sitemap.xml correctly ?

**Comment by rojarsmith** [comment]
I had try:

Including non-page files in the pages directory
[[https://nextjs.org/docs/api-reference/next.config.js/custom-page-extensions](url)](https://nextjs.org/docs/api-reference/next.config.js/custom-page-extensions#including-non-page-files-in-the-pages-directory)

I will fix the public file list in pageExtensions but route '/' will show 404 not found. 😱

**Comment by shuding** [comment]
Please show your `next.config.js` content here. It is not necessary to set `pageExtensions`.
