### ISSUE TITLE
Large number of pages causing build error with high memory usage

### ISSUE THREAD

**Issue by ryadav96** [shuding/nextra#1131]
I am encountering an error when trying to build my site with around 1500 dummy mdx pages. Is there a way to successfully build a site with a large number of pages without increasing the amount of memory used?

![image](https://user-images.githubusercontent.com/30411972/209524680-ce3eb66b-01ee-43fb-93df-fc93a4f9ae31.png)

**Comment by B2o5T** [comment]
Hey! Do you still have this problem on v2.2.13?

**Comment by B2o5T** [comment]
Closing due silence
