### ISSUE TITLE
May provide a method to make sidebar don't scan non exist i18n ?

### ISSUE THREAD

**Issue by rojarsmith** [shuding/nextra#1132]
Some pages are only available in Language A, 

some pages are only available in Language B, 

But the sidebar doesn't distinguish between them.

Is there an easy way to fix this?

**Comment by shuding** [comment]
I guess the current workaround is to have different meta configs and hide pages conditionally.

**Comment by rojarsmith** [comment]
It works but it is trouble with a lots markdown files.

**Comment by B2o5T** [comment]
Wontfix, will be fixed by ne i18n approach https://github.com/shuding/nextra/issues/176
