### ISSUE TITLE
Improve documentation for nextra-theme-blog

### ISSUE THREAD

**Issue by Djiit** [shuding/nextra#114]
Hey, 

I'm starting to use the blog theme and would like to document my findings and setup. Is there any preferred structure for the doc ? e.g. is "Nextra Docs" in the sidebar about "Nextra Docs Theme" or simply "Nextra Documentation" (more generic) ?

I can open a PR with a little guidance.

Thanks !

**Comment by shuding** [comment]
Hi! It's about "Nextra Docs Theme" in my mind, feel free to improve it :)

**Comment by Djiit** [comment]
Hey, alright, thanks, will suggest some base docs :)
