### ISSUE TITLE
Styling margin issue with nested <ul> elements for docs theme

### ISSUE THREAD

**Issue by mkrtchian** [shuding/nextra#1140]
When nesting `<ul>` elements with docs theme, we get sometimes bigger and sometimes smaller top margin.

Here is an example ([available live here](https://mkrtchian.github.io/reading-notes/books/designing-data-intensive-applications/)):
![Screenshot](https://user-images.githubusercontent.com/6060774/209873610-5d4d5999-bf9a-4fdd-977c-f19566162d1b.png)

The problem seems that `<ul>` elements have `nx-mt-6` giving `margin-top: 1.5rem;`, and `first:nx-mt-0` giving `margin-top: 0;` only if the `<ul>` is the first child element of its parent. ([the styling is here](https://github.com/shuding/nextra/blob/cf9b886785ec5cc947791d2873cfc9670ed0f81f/packages/nextra-theme-docs/src/mdx-components.tsx#L246))

Sometimes it is the first child, sometimes not, this doesn't seem to me a relevant condition to add a top margin. It probably rather should not add the margin in case it is a direct child of a `<li>` element or something like that.

**Comment by B2o5T** [comment]
duplicate https://github.com/shuding/nextra/issues/863

**Comment by mkrtchian** [comment]
Thanks, I'm closing this one.
