### ISSUE TITLE
Static Images is not working in Dev mode: Bad character escape sequence

### ISSUE THREAD

**Issue by SonMooSans** [shuding/nextra#1146]
The error only happens in dev mode, I can deploy the website to Vercel with no problems
However, when using `pnpm run dev` on my pc, this error will be thrown
```
./pages/index.mdx
Error: 
  x Bad character escape sequence, expected 4 hex characters
    ,----
 16 | import $nextraImage0 from "C:\Users\user\Dev\test\public\image.png";
    :                                    ^^
    `----

Caused by:
    0: failed to process input file
    1: Syntax Error
```
This is my index.mdx
```mdx
# Introduction

Welcome to Nextra! This is a basic docs template. You can use it as a starting point for your own project :)

## What is Nextra?

A **simple**, **powerful** and **flexible** site generation framework with everything you love from Next.js.
![Hello](/image.png)

## Documentation

The documentation is available at [https://nextra.site](https://nextra.site).

```
The Github repo: https://github.com/SonMooSans/test

**Comment by SonMooSans** [comment]
It does work on wsl, but that is painful for me to do web dev on wsl
Are there any people using windows 11 and having issues with static images? Or that is only happening on my dev machine

**Comment by stephzero1** [comment]
> It does work on wsl, but that is painful for me to do web dev on wsl Are there any people using windows 11 and having issues with static images? Or that is only happening on my dev machine

Same here, it's painful for me too.

Os: Windows 11
Nextra(docs): 2.0.3
Next: 13.0.6
Node: 18

**Comment by SonMooSans** [comment]
After take a look to [This file](https://github.com/shuding/nextra/blob/main/packages/nextra/src/mdx-plugins/static-image.ts)
I found that the main problem is that it is giving a absolute path which cannot be compiled
It might be fixed by disabling staticImage and create our own plugin for that

**Comment by B2o5T** [comment]
> It might be fixed by disabling staticImage and create our own plugin for that

@SonMooSans why just not try to fix it for you and make a PR for other windows users?

**Comment by B2o5T** [comment]
try to modify this line https://github.com/shuding/nextra/blob/a3f1a90c664feb18030eb5f411440dbe4acd123e/packages/nextra/src/mdx-plugins/static-image.ts#L71

to
```js
url = slash(urlPath) 
```

and import on the top
```js
import slash from 'slash'
```

**Comment by stephzero1** [comment]
> 

This one worked for me! Thanks! <3

**Comment by SonMooSans** [comment]
> > It might be fixed by disabling staticImage and create our own plugin for that
> 
> 
> 
> @SonMooSans why just not try to fix it for you and make a PR for other windows users?

Sorry for delay, I had some busy jobs to do that day so I don't have enough time for that... Anyway thanks for your solution!
