### ISSUE TITLE
[blog-theme]: url slug in meta

### ISSUE THREAD

**Issue by juliusmarminge** [shuding/nextra#1153]
in the config, would be nice to expose the url as part of the meta:

```ts
const theme = {
  head: ({ meta }: { meta: MetaWithReadingTime }) => {
    // dynamic OG's - want to show the url in the img
    const ogImgLink = getOgImgLink(meta);
    return (
      <>
        <meta name="url" content={meta.url} />
        <meta name="og:image" content={ogImgLink}
      </>
    );
  },
};
```

also, is there an "official" type for the meta here? I made my own typesafe frontmatter parsing and use the type from there but that doesn't include the props Nextra adds internally?

https://github.com/juliusmarminge/jumr.dev/blob/main/src/lib/blog.ts

**Comment by numToStr** [comment]
You can use `pathname` from `useRouter()`.

```tsx
import { useRouter } from "next/router";

const theme = {
  head: ({ meta }: { meta: MetaWithReadingTime }) => {
    const { pathname } = useRouter();
    // ...
  } 
}
```
