### ISSUE TITLE
Clarify how to handle light/dark mode logo

### ISSUE THREAD

**Issue by MikeCarbone** [shuding/nextra#1161]
Right now it's not very clear how to handle switching the logo fill color based on light / dark mode. For the time being I'm using `fill="currentColor"`, but would be great if I can customize which fill colors get rendered for light mode / dark mode.

Possible solution can be to use a function for `logo` in `theme.config.tsx` that gets passed the current state of `light` or `dark`. Then we can manually switch the rendered logos or colors based on that state. Or some other method for accessing the color scheme value... 🤔

**Comment by B2o5T** [comment]
not nextra-related issue, you can handle it in whatever you want a solution, tailwindcss classes or CSS styles

> Possible solution can be to use a function for logo in theme.config.tsx that gets passed the current state of light or dark. Then we can manually switch the rendered logos or colors based on that state. Or some other method for accessing the color scheme value... 🤔

no need to overcomplicate

**Comment by fanyf22** [comment]
I'm also looking into this problem, and I found that you can use `useTheme` hook to retrieve the current theme.

```javascript
import { useTheme } from 'nextra-theme-docs'

const { theme, systemTheme } = useTheme()

if (theme == 'system') {
  var current = systemTheme
} else {
  var current = theme
}
```

I'm using Nextra3, so I'm not sure whether Nextra has this hook.
