### ISSUE TITLE
[blog-theme] Expose reading time in metadata

### ISSUE THREAD

**Issue by numToStr** [shuding/nextra#1164]
### Problem

I want to show reading time in OG images but reading time is not accessible from metadata.

**Sample OG image (hardcoded reading time)**

![og](https://user-images.githubusercontent.com/24727447/210355447-ecea26ae-1900-469e-bac9-c45ba7d0e410.png)

### Solution

If possible, expose reading time in metadata. Or in other way, that can easily be accessible from `config.head`

**Comment by B2o5T** [comment]
you can access it by

```js
import { useBlogContext } from 'nextra-theme-blog'

const { opts } = useBlogContext()

const readingTime = opts.readingTime?.text
```
