### ISSUE TITLE
Live code

### ISSUE THREAD

**Issue by emersonlaurentino** [shuding/nextra#1167]
Hi, I'm using Nextra on a project and want to create a Playground to do live code. Searching about live code in MDX, I found this [documentation](https://v1.mdxjs.com/guides/live-code/#live-code) by mdxjs official, so, do you have any plans to add this?

**Comment by shuding** [comment]
You can take a look at Sandpack or React Live to see how to add them to Next.js.

**Comment by dimaMachina** [comment]
will be available in next v3 alpha
