### ISSUE TITLE
Search in code blocks

### ISSUE THREAD

**Issue by mpinter** [shuding/nextra#1170]
Hey! Thanks for a great project - we are currently migrating [our docs](https://bratislava.github.io/) from Docusaurus to Nextra.

I've noticed that the fulltext search does not seem to index code blocks in markdown pages. I'd find such feature useful, as we have pieces of code or bash scripts I'd quickly want to reference scattered across our doc pages.

Is this on purpose or a bug ? If on purpose, is there a way to extend the flexsearch config ?

Thank you.

**Comment by B2o5T** [comment]
https://github.com/shuding/nextra/blob/main/examples/swr-site/next.config.js#L4-L6
