### ISSUE TITLE
KaTex Syntax is not working 

### ISSUE THREAD

**Issue by donghhan** [shuding/nextra#1182]
After upgrading the version of nextra, I tried to use KaTeX for math representation.
I refered to [here](https://github.com/shuding/nextra/pull/1143)

Here's my `package.json` file looks:

```json
{
  "name": "docs",
  "private": true,
  "scripts": {
    "dev": "next",
    "start": "next start",
    "build": "next build"
  },
  "author": "Shu Ding",
  "license": "MIT",
  "dependencies": {
    "@code-hike/mdx": "^0.7.4",
    "clsx": "^1.2.1",
    "framer-motion": "^7.3.2",
    "mdx-mermaid": "^1.3.2",
    "mermaid": "^9.3.0",
    "next": "^13.0.5",
    "nextra": "2.0.1",
    "nextra-theme-docs": "2.0.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-icons": "^4.7.1",
    "rehype-katex": "^6.0.2",
    "remark-math": "^5.1.1",
    "shiki": "^0.11.1"
  },
  "devDependencies": {
    "@types/node": "^18.11.9",
    "autoprefixer": "^10.4.13",
    "postcss": "^8.4.19",
    "tailwindcss": "^3.2.4",
    "typescript": "^4.9.3"
  }
}
```

and here's my `next.config.mjs` file

```js
import { remarkCodeHike } from "@code-hike/mdx";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";
import githubDarkDimmed from "shiki/themes/github-dark-dimmed.json" assert { type: "json" };
import nextra from "nextra";

const withNextra = nextra({
  theme: "nextra-theme-docs",
  themeConfig: "./theme.config.tsx",
  staticImage: true,
  flexsearch: {
    codeblocks: false,
  },
  defaultShowCopyCode: true,
  mdxOptions: {
    remarkPlugins: [
      [
        remarkCodeHike,
        {
          lineNumbers: false,
          showCopyButton: false,
          theme: githubDarkDimmed,
          autoImport: true,
        },
      ],
      [remarkMath],
    ],
    rehypePlugins: [rehypeKatex],
  },
  latex: true
});

export default withNextra({
  reactStrictMode: true,
  i18n: {
    locales: ["en", "ko"],
    defaultLocale: "en",
  },
  latex: true
});
```

Normally, I can use `$ ... $` sign for inserting the mathmatical representation but then it just produce normal text with printing twice weirdly. Is KaTeX support not ready yet? Or am I doing something wrong? 

![image](https://user-images.githubusercontent.com/84304078/210505576-7ec4b55b-4ea3-43a5-91db-f03c8083dbce.png)

**Comment by B2o5T** [comment]
See the working example (u miss `latex: true`)

https://github.com/shuding/nextra/blob/main/examples/docs/next.config.js

**Comment by donghhan** [comment]
@B2o5T It still produce the same problem. 

```js
import { remarkCodeHike } from "@code-hike/mdx";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";
import githubDarkDimmed from "shiki/themes/github-dark-dimmed.json" assert { type: "json" };
import nextra from "nextra";

const withNextra = nextra({
  theme: "nextra-theme-docs",
  themeConfig: "./theme.config.tsx",
  staticImage: true,
  flexsearch: {
    codeblocks: false,
  },
  defaultShowCopyCode: true,
  mdxOptions: {
    remarkPlugins: [
      [
        remarkCodeHike,
        {
          lineNumbers: false,
          showCopyButton: false,
          theme: githubDarkDimmed,
          autoImport: true,
        },
      ],
      [remarkMath],
    ],
    rehypePlugins: [rehypeKatex],
  },
  latex: true,
});

export default withNextra({
  reactStrictMode: true,
  i18n: {
    locales: ["en", "ko"],
    defaultLocale: "en",
  },
});
```

![image](https://user-images.githubusercontent.com/84304078/210677262-ce635085-90cd-4018-b193-cabda0fb75d2.png)

**Comment by shuding** [comment]
You don't need to add remarkMath and rehypeKatex plugins manually, the option already does that.

**Comment by donghhan** [comment]
@shuding Are you sure? Then should I need to use `require` one? It seems `import` does not work properly. 
I deleted `remarkMath` and `rehypeKatex` as you said but it seems it does not work. Also, it somehow recognizes as variable at some point. 

```js
import { remarkCodeHike } from "@code-hike/mdx";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";
import githubDarkDimmed from "shiki/themes/github-dark-dimmed.json" assert { type: "json" };
import nextra from "nextra";

const withNextra = nextra({
  theme: "nextra-theme-docs",
  themeConfig: "./theme.config.tsx",
  staticImage: true,
  flexsearch: {
    codeblocks: false,
  },
  defaultShowCopyCode: true,
  mdxOptions: {
    remarkPlugins: [
      [
        remarkCodeHike,
        {
          lineNumbers: false,
          showCopyButton: false,
          theme: githubDarkDimmed,
          autoImport: true,
        },
      ],
    ],
  },
  latex: true,
});

export default withNextra({
  reactStrictMode: true,
  i18n: {
    locales: ["en", "ko"],
    defaultLocale: "en",
  },
});
```

Results are below:
![image](https://user-images.githubusercontent.com/84304078/210700647-be72031c-1590-427c-8618-306d905939a5.png)

And if I use `=` in equation as below:
![image](https://user-images.githubusercontent.com/84304078/210700708-b7d01424-648f-4a36-8879-42ce92daeaaa.png)

It shows this error:
![image](https://user-images.githubusercontent.com/84304078/210700728-e2b3cf56-8539-4217-9d9d-23e4e4f4b84d.png)

**Comment by donghhan** [comment]
@shuding @B2o5T 
Fixed issue by upgrading nextra package from `2.0.1` to `^2.0.3`. It seems there was version issue. Closing issue.

**Comment by shuding** [comment]
Yep that feature was added in 2.0.2: https://github.com/shuding/nextra/releases/tag/nextra%402.0.2

**Comment by textreme** [comment]
@donghhan I am experiencing the same issue that you were. However, have the "nextra": "latest" as a dependency, which I believe fixed the issue for you. Could you share what you had for package.json & next.config.js that fixed the problem for you?

**Comment by donghhan** [comment]
> @donghhan I am experiencing the same issue that you were. However, have the "nextra": "latest" as a dependency, which I believe fixed the issue for you. Could you share what you had for package.json & next.config.js that fixed the problem for you?

I also updated up-to-date package of `nextra-theme-docs`. I haven't tried the KaTeX working or not but here's my dependencies with `next.config.mjs`. Take those as your referrence if you need. 

```json
"dependencies": {
    "nextra-theme-docs": "2.12.3"
}
```

```js
import { remarkCodeHike } from "@code-hike/mdx";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";
import githubDarkDimmed from "shiki/themes/github-dark-dimmed.json" assert { type: "json" };
import nextra from "nextra";

const withNextra = nextra({
  theme: "nextra-theme-docs",
  themeConfig: "./theme.config.tsx",
  staticImage: true,
  flexsearch: {
    codeblocks: false,
  },
  latex: true,
  defaultShowCopyCode: true,
  mdxOptions: {
    remarkPlugins: [
      [
        remarkCodeHike,
        {
          lineNumbers: false,
          showCopyButton: true,
          theme: githubDarkDimmed,
          autoImport: true,
        },
      ],
    ],
  },
});

export default withNextra({
  reactStrictMode: true,
  i18n: {
    locales: ["en", "ko"],
    defaultLocale: "en",
  },
});

```

**Comment by textreme** [comment]
That worked, thanks.

I noticed that Katex is rendering in .mdx, but not in a react component I am importing into that .mdx file. Any help on this would be greatly appreciated.
![Screen Shot 2023-10-08 at 2 53 31 PM](https://github.com/shuding/nextra/assets/2476027/1f970e9d-d7c2-40fc-ad42-8420f6e0b679)
