### ISSUE TITLE
NFR: Only show its own tab's TOC when there are headings in tabs 

### ISSUE THREAD

**Issue by sxhuan** [shuding/nextra#1191]
### Request
If we can show the anchors owned by each tab only, I think it would be more make sense. 
or, keep the current design - show all tabs anchors together but need support switch tab automatically while clicking the anchors which do not belong current tab.

### Reproduce
eg. I have 3 tabs with their own anchors, if I click the anchor, not in the current tab nothing happened, it's confusing.

<img width="1093" alt="Screenshot 2023-01-05 at 4 26 47 PM" src="https://user-images.githubusercontent.com/16263180/210905440-948849ac-34d7-474c-8dd5-ae66dabab323.png">

### Using version
- nextra 2.0.1

**Comment by SagaGG** [comment]
From a practical perspective or scenario, IMO, I like the way only shows the current tabs anchor.
here is an example from [Atlassian](https://atlassian.design/components/empty-state/examples)

**Comment by d1onys1us** [comment]
I believe this is a useful feature to have. Mainly because sometimes you want to abstract away certain parts of a MD document and only show what is necessary for the tab the reader is interested in. An example of how we use this is here: https://taiko.xyz/docs/guides/deploy-a-contract

**Comment by B2o5T** [comment]
since these headings are in tabs which inside dynamic component we need to hide them

**Comment by ElementalCrisis** [comment]
I understand the reasoning behind hiding them as it was a bug but I do think having the option to show the correct headers for the selected Tab, like how [Atlassian](https://atlassian.design/components/empty-state/examples) does it would also be a nice alternative.

**Comment by ElementalCrisis** [comment]
Ah I see, thanks for the clarification!
