### ISSUE TITLE
Back To Top Features 

### ISSUE THREAD

**Issue by luke-klein** [shuding/nextra#1193]
Hey, just curious if you guys have any plans to add this feature to Nextra? It would be super useful.

![image](https://user-images.githubusercontent.com/120297915/210932281-3ac63663-fc42-4ea7-a5fd-ad93a30b3db5.png)

**Comment by C-EO** [comment]
@shuding An issue was opened regarding this by me last month. See #1061

**Comment by shuding** [comment]
Ah, closing this one then
