### ISSUE TITLE
How to add dynamic content within code block

### ISSUE THREAD

**Issue by collinglass** [shuding/nextra#1195]
Hi, I have a use case where i need to inject a customer specific ID into the code blocks.

I set a query param with the unique Id `XXXXXXXXX` and then inject it in the page.

```
` ``js copy
<script src="https://foobar.com/widget.js?widgetId=XXXXXXXXX" async defer></script>
` ``
```

Is this supported? How can I do this?

**Comment by shuding** [comment]
This is a bit tricky for both MDX (no syntax to include JSX inside code blocks) and Shiki (does highlighting during build time). But for your case I think we can work around it in client. I added an example in the docs:

https://nextra.site/docs/guide/syntax-highlighting#with-dynamic-content

Although I think with that, we now have a bug with copy which holds only the initial state. I guess we need to get the current value when hitting the copy button.

**Comment by tonyxiao** [comment]
@shuding what if the value of `XXXXX` is known at build time, but I need to be able to pass a javascript value into the markdown?

More specifically I'm using webpack raw loader to load a `.ts` file from disk as string, and I'd like to be able to display the content of the said `.ts` file in a code block.
