### ISSUE TITLE
Formatting like links in headings breaks page title

### ISSUE THREAD

**Issue by lachlanjc** [shuding/nextra#12]
![D2AAC37C-F58F-45FA-A782-6D6CF5EA4FA8](https://user-images.githubusercontent.com/5074763/98625572-d6b16980-22dd-11eb-8236-9029557021c7.jpeg)

Having a Markdown link in the h1 causes `[object Object]` in the page title. Would expect it to remove formatting & use plaintext/the text content for the title.

**Comment by shuding** [comment]
@lachlanjc Thanks for reporting! This bug should be fixed in `nextra-theme-docs@0.2.8` 👍
