### ISSUE TITLE
Improve docs for `next export`

### ISSUE THREAD

**Issue by shuding** [shuding/nextra#1202]
### Discussed in https://github.com/shuding/nextra/discussions/1197

<div type='discussions-op-text'>

<sup>Originally posted by **RPDeshaies** January  6, 2023</sup>
Hi, I'm currently testing using Nextra in replacement for a Vuepress project I had and I was wondering if it was possible to use the command `next build && next export` with Nextra?

I've tried running the command and looking at the exported assets, but I'm getting a bunch of 404 of the static assets (js/css/etc)

![image](https://user-images.githubusercontent.com/6224111/211076260-a4ef5359-d795-4f55-a99b-813147fa55ae.png)

I initially had an error about using next/images which I fixed by overriding a config in the next config, but I'm not sure at all that's the proper way of doing things. 

```sh
info  - No "exportPathMap" found in "/next.config.js". Generating map from "./pages"
Error: Image Optimization using Next.js' default loader is not compatible with `next export`.
  Possible solutions:
    - Use `next start` to run a server, which includes the Image Optimization API.
    - Configure `images.unoptimized = true` in `next.config.js` to disable the Image Optimization API.
  Read more: https://nextjs.org/docs/messages/export-image-api
```

```tsx
// next.config.js
const withNextra = require("nextra")({
  theme: "nextra-theme-docs",
  themeConfig: "./theme.config.jsx",
});

module.exports = {
  ...withNextra(),
  images: {
    unoptimized: true,
  },
};
```

Thanks in advance for the help. And also, Nextra looks absolutely fantastic, I'm really eager to make it work!</div>

**Comment by gunaseelan13** [comment]
`const withNextra = require('nextra')({
  theme: 'nextra-theme-docs',
  themeConfig: './theme.config.tsx',
  staticImage: false,
  images: {
    unoptimized: true, 
  },
})

module.exports = withNextra()`
 Might solve this issue

**Comment by gunaseelan13** [comment]
'staticImage: false' in Config might solve this

**Comment by pplonski** [comment]
I got the same error and switched image optimization off.

**Comment by thekidnamedkd** [comment]
> I got the same error and switched image optimization off.

Same error as OP. Playing with next config and various solutions, but I suspect something isn't parsing between nextConfig and withNextra() on export.

@pplonski can you share your working config? Thanks!

**Comment by pplonski** [comment]
I just used:

```jsx
// next.config.js
const withNextra = require("nextra")({
  theme: "nextra-theme-docs",
  themeConfig: "./theme.config.jsx",
});

module.exports = {
  ...withNextra(),
  images: {
    unoptimized: true,
  },
};
```

From what I read the `yarn next export` doesnt work with optimized images.

**Comment by thekidnamedkd** [comment]
Interesting! You're deploying to Netlify? What are your build & deploy commands if so? I keep getting the same image problem when deploying to Fleek, but it builds fine. Also to note, this config breaks the Vercel demo build entirely via logs, which was working as expected out of the box.

**Comment by thekidnamedkd** [comment]
Working for me on non-Vercel & Vercel deploys: 
* updated build command on line 6 in package.json to: 
  ```"build": "node ./scripts/gen-rss.js && next build && next export"```
* updated next.config.js to: 
```js
const withNextra = require('nextra')(https://github.com/shuding/nextratheme-blog', './theme.config.js')


const nextConfig = {
  images: {
    loader: 'akamai',
    path: '/'
  }
}
module.exports = withNextra(nextConfig)
```


  * set build commands in deploy to:
  ```yarn install && yarn run build```

**Comment by dimaMachina** [comment]
closed by https://github.com/shuding/nextra/pull/2563
