### ISSUE TITLE
How to preserve query parameters on page changes

### ISSUE THREAD

**Issue by collinglass** [shuding/nextra#1203]
When I click links in the sidebar or any other internal links, I want to preserve query parameters in the URL. Is this supported?

**Comment by B2o5T** [comment]
You should implement this on your own website

**Comment by collinglass** [comment]
@B2o5T You mean extend the nextra functionality. can you give me an idea of how to start?

**Comment by shuding** [comment]
Many things such as routing issues are usually not related to Nextra itself, you can search and find a Next.js solution: https://github.com/vercel/next.js/discussions/10698.
