### ISSUE TITLE
Lots of code smells

### ISSUE THREAD

**Issue by R-Bower** [shuding/nextra#1207]
Hey there, great package.  I've spent some time to migrate over from Docusaurus and am loving the ergonomics provided by nextra-theme-docs.  I'm also a huge Next.js fan, so this was a no-brainer.  

In using this package, I've stumbled on some errors that prompted me to check the source code.  There are several code smells in the nextra and nextra-theme-docs package.  Surprisingly, the packages don't use `eslint-plugin-react` or `eslint-plugin-react-hooks` which would help catch most of these mistakes.  

I'm frequently seeing this warning in local dev mode:

Warning: React has detected a change in the order of Hooks called by ... This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks

This is typically indicative of code that doesn't follow React's rules of hooks.  

More code smells:

1. This callback is being declared after it's used earlier in the function.
https://github.com/shuding/nextra/blob/main/packages/nextra-theme-docs/src/components/search.tsx#L179

3. This hook is being called conditionally, which is an anti-pattern: 
https://github.com/shuding/nextra/blob/main/packages/nextra-theme-docs/src/mdx-components.tsx#L86

4. The return result of this hook is being set to a variable outside of React's lifecycle.  Pretty sure this is also an anti-pattern.
https://github.com/shuding/nextra/blob/main/packages/nextra-theme-docs/src/mdx-components.tsx#L86

5. The definition for `HeaderLink` is a bit confusing.  I don't see a need for this to be curried.  Why not make it a simple function component?
https://github.com/shuding/nextra/blob/main/packages/nextra-theme-docs/src/mdx-components.tsx#L77

```
// potential fix:
function HeaderLink({
  children,
  id,
  context,
  Tag,
  ...props
}: ComponentProps<TagType> & {
  Tag: TagType
  context: { index: number }
}): ReactElement {
  // ...
}
...

h2: props => <HeaderLink context={context} Tag={'h2'} {...props} />,
h3: props => <HeaderLink context={context} Tag={'h3'} {...props} />,
...
```

There are more issues in other files as well.  

@shuding I'm happy to create a PR with some fixes.  Let me know, thanks!

**Comment by B2o5T** [comment]
Enabling react, react-hooks, jsx-a11y, and next plugins in my todo list, recently eslint/typescript-recommended configs we’re already enabled

**Comment by shuding** [comment]
Feel free to open PR for these, thanks!

**Comment by B2o5T** [comment]
fixed 1,2,4 in attached PR
