### ISSUE TITLE
Zod errors from 2.1.0 from 2.0.3

### ISSUE THREAD

**Issue by rbox-risk** [shuding/nextra#1212]
In local dev mode I am seeing the following zod errors

```
  {
    "code": "invalid_string",
    "validation": {
      "startsWith": "https://"
    },
    "message": "Invalid input: must start with \"https://\"",
    "path": [
      "project",
      "link"
    ]
  }
```
Is this meant to rule out `http://localhost...` 

With 
```
sidebar: {
      defaultMenuCollapseLevel: 0
    }
```
I see this zod error

```
{
    "code": "too_small",
    "minimum": 2,
    "type": "number",
    "inclusive": true,
    "exact": false,
    "message": "Number must be greater than or equal to 2",
    "path": [
      "sidebar",
      "defaultMenuCollapseLevel"
    ]
  }
```

This is related to 

```
sidebar: z.object({
      defaultMenuCollapseLevel: z.number().min(2).int(),
     ...
    }),
```

Although, docs state `defaultMenuCollapseLevel` can be set to 0

![image](https://user-images.githubusercontent.com/59801351/211220796-ef0e09fc-9796-418d-ac45-0daf5014a619.png)

I'm using default `toc` settings (i.e. no `toc` object), but getting this error. Looks like default docs theme does not populate `toc.extraContent`

```
  {
    "code": "custom",
    "message": "Must be React.ReactNode or React.FC",
    "path": [
      "toc",
      "extraContent"
    ]
  }
```

**Comment by B2o5T** [comment]
See my comment https://github.com/shuding/nextra/issues/1210#issuecomment-1374912682

**Comment by rbox-risk** [comment]
@B2o5T thanks - overlapping opening issues!
