### ISSUE TITLE
[_meta.json] `{ "display": "hidden" }` cause a sub doc page to lose sidebar & toc

### ISSUE THREAD

**Issue by SukkaW** [shuding/nextra#1225]
```json
{
  "guide": {
    "title": "Using DNS.SB",
    "type": "page"
  },
  "dot": {
    "title": "DNS over TLS",
    "type": "page"
  },
  "doh": {
    "title": "DNS over HTTPS",
    "type": "page"
  }
}
```

Preview: https://533b33be.dns-sb-preview-sukka.pages.dev/guide/
Source code: https://github.com/SukkaW/dns.sb/tree/3d8319b29bec1695a756d4c2ab9b46d288727996

<img width="1732" alt="image" src="https://user-images.githubusercontent.com/40715044/211608159-4227abc6-f339-4559-aa1e-24ea06bb7e8c.png">

At this moment, everything is working.

And then, I want to put those three navbar items into a menu, so I did this:

```diff
{
  "guide": {
    "title": "Using DNS.SB",
-    "type": "page"
+    "type": "page",
+    "display": "hidden"
  },
  "dot": {
    "title": "DNS over TLS",
-    "type": "page"
+    "type": "page",
+    "display": "hidden"
  },
  "doh": {
    "title": "DNS over HTTPS",
-    "type": "page"
+    "type": "page",
+    "display": "hidden"
  },
+  "how-to-use-dnssb": {
+    "title": "Using DNS.SB",
+    "type": "menu",
+    "items": {
+      "tos": {
+        "title": "Using DNS.SB",
+        "href": "/guide/"
+      },
+      "servers": {
+        "title": "DNS over TLS",
+        "href": "/dot/"
+      },
+      "privacy": {
+        "title": "DNS over HTTPS",
+        "href": "/doh/"
+      }
+    }
+  }
}
```

The `_meta.json` now becomes:

```json
{
  "guide": {
    "title": "Using DNS.SB",
    "type": "page",
    "display": "hidden"
  },
  "dot": {
    "title": "DNS over TLS",
    "type": "page",
    "display": "hidden"
  },
  "doh": {
    "title": "DNS over HTTPS",
    "type": "page",
    "display": "hidden"
  },
  "how-to-use-dnssb": {
    "title": "Using DNS.SB",
    "type": "menu",
    "items": {
      "tos": {
        "title": "Using DNS.SB",
        "href": "/guide/"
      },
      "servers": {
        "title": "DNS over TLS",
        "href": "/dot/"
      },
      "privacy": {
        "title": "DNS over HTTPS",
        "href": "/doh/"
      }
    }
  }
}
```

Preview: https://448c8870.dns-sb-preview-sukka.pages.dev/guide/
Source code: https://github.com/SukkaW/dns.sb/tree/nextra-issue-reproduction

<img width="1734" alt="image" src="https://user-images.githubusercontent.com/40715044/211609302-1b037991-1788-4221-b7b0-1b9fe0395efa.png">

**There is no more Sidebar and ToC**.

Also, the menu remains bold, even when non of its items is active:

https://448c8870.dns-sb-preview-sukka.pages.dev/tos/

<img width="1737" alt="image" src="https://user-images.githubusercontent.com/40715044/211609710-40e3bdd8-4e37-4b73-a241-c7f6356c829d.png">

---

Seems to be the same issue as #1017?

**Comment by nickarvanitas** [comment]
@SukkaW @promer94 I figured out a workaround to this. 

The trick is to nest everything within an additional folder and have additional _meta.json files. 

My top level folder _meta.json lists out all of the pages and adds `{ "display": "hidden" }` to each of them, as well as defining a navbar menu with these items. 

My sub-folder re-defines the pages, but this time without `{ "display": "hidden" }`.

And then within my sub-folder I have individual folders for each of my sub-docs.
