### ISSUE TITLE
Improper behavior: grey screen causing nav menu to be inactive, in the multi-task mode (Windows)

### ISSUE THREAD

**Issue by raproid** [shuding/nextra#1232]
OS: Windows 11
Browser: Chrome v108.0359

Normal behavior: When I have two non-fullscreen windows, e.g. a Chrome window and another Chrome windows, and open Nextra-powered docs in one of them, the nav menu is showing and behaving as expected.

Problem: In the same situation, when I pull a non-fullscreen browser window to a screen corner, causing Windows to enable the multi-task mode (two non-fullscreen windows next to each other), the nav menu becomes inaccessible — I see a grey shade on the docs page and the nav menu "goes to background", under the shade. 

Bug reproduction: look at the video, starting from 00m:09s.

https://user-images.githubusercontent.com/22454517/211792326-3b61bf8a-17aa-4fa5-ab38-30b74caf03c7.mov

**Comment by B2o5T** [comment]
I don’t use windows, can you debug in developer tools what’s the issue?

**Comment by raproid** [comment]
Honestly, I don't use it either. It's a bug from one of our users. I guess there's a fair share of them on Windows...

**Comment by raproid** [comment]
So, I cannot debug it, as I'm not running a Windows copy either...

**Comment by B2o5T** [comment]
Thanks for the answer, closing it for now

**Comment by raproid** [comment]
@B2o5T on a completely unrelated issue, would love for a theme like this to come to Nextra... 
Would love so much! 

https://preview.readme.io/reference/post_ankr-getaccountbalance?url=https%3A%2F%2Fsanjose.api.ankrscan.io%2Fdocs%2Fswagger.json


So far, we're able to use that sad thing (non-interactive Redocly): https://www.ankr.com/docs/advanced-api/specification/

**Comment by B2o5T** [comment]
Please create a new issue for it
