### ISSUE TITLE
Property 'i18n' is missing in DocsThemeConfig

### ISSUE THREAD

**Issue by kanecom** [shuding/nextra#1233]
Hi, I'm trying to update nextra from 2.0.1 to 2.1.0.  
In `nextra-theme-docs@2.1.0`, `DocsThemeConfig` now requires `i18n` option, but there is no documantation in https://nextra.site/docs/docs-theme/theme-configuration.

```log
Property 'i18n' is missing in type '{ logo: JSX.Element; project: { link: string; }; chat: { link: string; }; docsRepositoryBase: string; footer: { text: string; }; toc: { extraContent: JSX.Element; }; }' but required in type '{ navigation?: boolean | { next: boolean; prev: boolean; }; banner?: { dismissible?: boolean; key?: string; text?: ReactNode | FC<{}>; }; chat?: { icon?: ReactNode | FC<{}>; link?: string; }; ... 23 more ...; i18n: { ...; }[]; }'.ts(2741)
index.d.ts(872, 5): 'i18n' is declared here.
```

I could understand the necessary properties by checking `index.d.ts`, but it would be very helpful if there was a description of the i18n options in the documentation.

**Comment by B2o5T** [comment]
Will be fixed soon https://github.com/shuding/nextra/pull/1206
