### ISSUE TITLE
Icon for website not working (Favicon)

### ISSUE THREAD

**Issue by nabilfatih** [shuding/nextra#1252]
im trying to add an icon on my website, but it seems it doesn't work, the icon not shows up... here is my code in theme.config.tsx inside const config: DocsThemeConfig = {}, inside head: () => {}:

`<link href="/favicon.ico" rel="shortcut icon" />`
`<link rel="mask-icon" href="/safari-pinned-tab.svg" />`

all the images are in public folder -> e.g  /public/favicon.ico

am i doing it correctly? or is there something that i need to change?
I really appreciate your help :)

**Comment by charanquartz** [comment]
same problem here

**Comment by steida** [comment]
Nextra head can't resolve nested `<></>`

**Comment by feynon** [comment]
I'm still struggling with setting the favicon, any help would be appreicated.

**Comment by TheMikeyRoss** [comment]
@nabilfatih why was this issue closed, did you figure it out? I'm having the same issue
