### ISSUE TITLE
bug: navbar items have the same key

### ISSUE THREAD

**Issue by d1onys1us** [shuding/nextra#1256]
<img width="377" alt="image" src="https://user-images.githubusercontent.com/13951458/212429410-3ede963e-8bfc-40c8-9c6f-ff95e679a053.png">

and here is my meta.json:
<img width="366" alt="image" src="https://user-images.githubusercontent.com/13951458/212429457-5aff6cad-4af6-4e6d-be62-48c64cc3fe4a.png">

if i remove the type "page" from either of them, the key issue goes away.

**Comment by B2o5T** [comment]
there is no issue, they should not contain `type: page` because they are external links
