### ISSUE TITLE
Support inline markdown for sidebar entries

### ISSUE THREAD

**Issue by leodr** [shuding/nextra#126]
Hey! Love the project!

Currently it is not possible to use inline markdown to style the sidebar entries, e.g. make one of the entries look like inline code.

If you surround the item name with backticks they just get written out as text:

![image](https://user-images.githubusercontent.com/39763575/113866255-63892200-97ad-11eb-9293-10f382eef1cd.png)

**Comment by B2o5T** [comment]
@shuding I don’t think we should implement this:
1. Never saw it in some site
2. Tricky to implement

**Comment by shuding** [comment]
@B2o5T Agreed! So far I couldn't think of an efficient way to do this

**Comment by B2o5T** [comment]
Closing since no interested of implementing (sorry 😞)
