### ISSUE TITLE
How to collapse all folders with sidebar.defaultMenuCollapseLevel in v.2.2.2+?

### ISSUE THREAD

**Issue by alex-flea** [shuding/nextra#1261]
According to the docs:

> You can change it by setting sidebar.defaultMenuCollapseLevel to a different number. For example, when set to 1, every folder will be collapsed by default...

However, setting `sidebar.defaultMenuCollapseLevel` to 1 in reality expands the contents of all folders on the first level.

At the same time, as a workaround in `v.2.0.X` I used `sidebar.defaultMenuCollapseLevel` set to `0`. However, the `v2.2.2` sees 0 as wrong value:

> [nextra] Error in config `sidebar.defaultMenuCollapseLevel`: invalid theme config

**Comment by B2o5T** [comment]
0 and 1 have the same effect, now min value is 1

**Comment by shuding** [comment]
Should be fixed in 2.2.3, `1` means it will be collapse from the first folder level which is your expected behavior.
