### ISSUE TITLE
i18n index files do not work for subfolders

### ISSUE THREAD

**Issue by alex-flea** [shuding/nextra#1263]
Somewhere between 2.0.0 and 2.2.3 index files for **subfolders** such as `index.en.mdx` or `index.ro.mdx` stopped working when referencing them by pretty urls, i.e `localhost:3000/subfolder` produces 404 error, but `localhost:3000/subfolder/index` returns the corresponding page.

At the same time indexes for root folder work fine, i.e. `localhost:3000` or `localhost:3000/ro`.

**Comment by mattvb91** [comment]
@alex-flea did you get this working? Same issue

**Comment by mattvb91** [comment]
yea unfortunately everything I look at i18n is completely broken it seems

**Comment by ysm-dev** [comment]
+1

**Comment by irangarcia** [comment]
+1

**Comment by tiagobarros01** [comment]
+1

**Comment by devjvao** [comment]
+1

**Comment by Prottoy2938** [comment]
Any solve yet?

**Comment by Prottoy2938** [comment]
> > @alex-flea did you get this working? Same issue
> 
> Nope. Each new update I check if it fixed but as for 2.2.9 it's still broken. As workaround I'm using `index1.en.mdx` hack.

whats the `index1.en.mdx` hack? It didn' worked for me. I still have to go to "/subfolder/index1" to reach the desired page instead of "/subfolders". Can you explain?

**Comment by erichosick** [comment]
As of July 16th, 2023, this is still an issue.

**Comment by B2o5T** [comment]
closed by https://github.com/shuding/nextra/pull/2250

https://github.com/shuding/nextra/releases/tag/nextra%403.0.0-alpha.0
