### ISSUE TITLE
Tabs items is not working properly ℹ️

### ISSUE THREAD

**Issue by luke-klein** [shuding/nextra#1274]
"When there are more than 8 tab items, it can be a little tricky to access them on a desktop screen, but they're still easily accessible on phone devices.

<Tabs items={['name', 'version', 'private',`dependencies`,`scripts`,`eslintConfig`,`browserslist`,`development` ,'name', 'version', 'private',`dependencies`,`scripts`,`eslintConfig`,`browserslist`,`development`]}>

https://user-images.githubusercontent.com/120297915/212561382-3ba88cbb-e259-4252-9820-a4c91b951876.mp4

**Comment by B2o5T** [comment]
fixed for both table/tabs
try https://nextra-theme-docs-25bixu8i5.vercel.sh/docs/advanced/scrollbar-x
