### ISSUE TITLE
Feedback for “Introduction”

### ISSUE THREAD

**Issue by Power186** [shuding/nextra#1278]
Hi,
I followed the docs exactly and it's giving me an error of:
Swift.DecodingError.dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON."

The repository was installed correctly(url):
https://mockend.com/Power186/MockFakeData/Data

However, that url says:
Almost there...

Failed to get installation. Please check that Mockend is installed on this repo.

I have checked multiple times, and it is installed on this repo:
https://github.com/Power186/MockDataFake

Not sure where the JSON data is malformed as I can decode and encode just fine in swift using multi-line json string:
https://github.com/Power186/MockDataFake/blob/main/Data/.mockend.json

**Comment by SonMooSans** [comment]
It seems like not related to nextra, you should send this feedback to Mockend instead
