### ISSUE TITLE
Feedback for “Custom Theme”

### ISSUE THREAD

**Issue by uguremirmustafa** [shuding/nextra#1287]
I would like to hide my documentation behind an authentication system.

Can we use `Custom Theme` to handle authentication on client side? Do you have any guide for this kind of use case?

**Comment by B2o5T** [comment]
see https://github.com/shuding/nextra/issues/1121#issuecomment-1374958546

**Comment by uguremirmustafa** [comment]
Thanks for quick reply. `_app` component will definitely be useful for this case. I totally forgot it.
