### ISSUE TITLE
Import markdown from parent directory

### ISSUE THREAD

**Issue by andreaswilli** [shuding/nextra#1303]
Thanks for the nice project!

I'm currently migrating from v1 to v2 and I'm getting this error when I try to import a markdown file from outside of the docs directory:
```
Module not found: Can't resolve 'nextra-theme-docs/style.css'
> 1 | import 'nextra-theme-docs/style.css'
  2 | /*@jsxRuntime automatic @jsxImportSource react*/
  3 | import {useMDXComponents as _provideComponents} from "nextra/mdx";
  4 | import $NextImageNextra from "next/image";
```
Here is my [repo](https://github.com/andreaswilli/react-verification-input). The nextra site is located in `/docs-src` while I want to include a part of the `README.md` file.
With v1 this worked fine, but I can't get it working with the latest version.
Any help is appreciated.

**Comment by shuding** [comment]
I saw you are using `2.0.0` in your repo, did you try latest version?

**Comment by andreaswilli** [comment]
It is the latest version. `^2.0.0` means install the latest version < v3
You can see it in the [lock file](https://github.com/andreaswilli/react-verification-input/blob/master/docs-src/yarn.lock#L1522).

**Comment by B2o5T** [comment]
I didn't get any errors from `next build` and in `next dev` I was able to render `README.md` 
<img width="1538" alt="image" src="https://user-images.githubusercontent.com/7361780/213791049-41f2afb2-45fa-4887-a5ed-5c561b15cad9.png">

<img width="619" alt="image" src="https://user-images.githubusercontent.com/7361780/213791157-ca818f57-d4c9-486f-883d-197cea01d257.png">


closing it, more information is required

**Comment by B2o5T** [comment]
oh I need to change `README.md` path

**Comment by andreaswilli** [comment]
Yes, I added a copy script as a workaround.
Sorry, should have mentioned that.

**Comment by andreaswilli** [comment]
Thanks for the quick patch! My problem is solved 🎉

**Comment by B2o5T** [comment]
Thanks for reporting it 😍
