### ISSUE TITLE
The Sidebar is loading all tsx files under page folder

### ISSUE THREAD

**Issue by medkrimi** [shuding/nextra#1315]
I am using Nextra into an existing NextJS app. I upgraded from 2.0.1 to 2.2.7. 

Now, all tsx files within the page folder, are displayed as an item into the left sidebar menu. 
In 2.0.1 it was only taking mdx files.

**Comment by onceLearner** [comment]
Same issue with version 2.2.9
Normally only `/dev` folder should be on the sidebar.
<img width="210" alt="image" src="https://user-images.githubusercontent.com/41970812/213674421-ddc50be9-15d2-4304-9f76-891c48f0a3bd.png">
