### ISSUE TITLE
display different images depending on theme

### ISSUE THREAD

**Issue by pplonski** [shuding/nextra#1325]
Hi! 

Thank you for amazing framework! I would like to display different images in `mdx` file depending on current theme. I have no idea how to do this? Any tips?

Thank you!

**Comment by B2o5T** [comment]
closing since not related to nextra, you can achive this in a different ways, for example with tailwindcss
```jsx
import lightImg from '...'
import darkImg from '...'
import Image from 'next/image'

<Image src={lightImg} className="dark:hidden" />
<Image src={darkImg} className="hidden dark:block" />
```

or with CSS https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by pplonski** [comment]
Thank you @B2o5T!
