### ISSUE TITLE
Error in config ``: invalid theme config

### ISSUE THREAD

**Issue by ChristianIvicevic** [shuding/nextra#1335]
Recently I have been running into a reported zod error during validation of my custom theme config. The structure of my file is the following:
```jsx
// @ts-check
/** @type {import('nextra-theme-docs').DocsThemeConfig} */
const config = {
  banner: { text: '...' },
  editLink: { component: () => null },
  feedback: { content: () => null },
  footer: { component: () => null },
  head: (<>{/* ... */}</>),
  logo: (<>{/* ... */}</>),
  navigation: { next: false, prev: false },
  search: { placeholder: '...' },
  titleSuffix: '...',
  toc: { float: true },
  useNextSeoProps: () => ({ titleTemplate: '...' })
};

module.exports = config;
```
Do you have any suggestions how I might debug this to deduce what's wrong with the config? To clarify, the offending key in the error message is literally an empty string:
![image](https://user-images.githubusercontent.com/45569997/213875563-5abe118a-a06a-444f-89ba-f4f0e9cd54fd.png)

**Comment by ChristianIvicevic** [comment]
The `titleSuffix` property I had was superseded by the `useNextSeoProps` as far as I can tell and was the cause for the error. Keeping this issue open though since the error message isn't really pointing out the correct key.

**Comment by B2o5T** [comment]
Yeah, error message should be fixed
