### ISSUE TITLE
Allow for changing search input placeholder text (nextra-theme-docs)

### ISSUE THREAD

**Issue by dami-i** [shuding/nextra#134]
The title is pretty straight-forward.

I find it would be extremely useful allowing the developer to change the placeholder text of the search input.
This comes very handy when developing apps in languages other than English.

This could be easily defined within a key/value pair inside `theme.config.js`, maybe something such as:
```js
// ...
  nextLinks: true,
  prevLinks: true,
  search: true,
  searchPlaceholder: 'Search ("/" to focus)', // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  customSearch: null,
  darkMode: true,
  footer: true,
// ...
```

Thank you for this awesome template.

**Comment by dami-i** [comment]
On second thought, we could be able to define one placeholder for every language.

**Comment by Andrewnt219** [comment]
Hi @shuding, I'd love to help with the issue, but I can't seem to find where the logic is defined. Can you tell me where to first look at?

**Comment by B2o5T** [comment]
Closing since it’s possible with below theme property https://github.com/shuding/nextra/blob/708d95d91d01e90cb6e1f0dafb58157199e8e6fd/packages/nextra-theme-docs/src/types.ts#L76
