### ISSUE TITLE
Updates to `pages/_meta.json` without updating `index.mdx` don't cause the page to get recreated on Vercel

### ISSUE THREAD

**Issue by ChristianIvicevic** [shuding/nextra#1342]
As the title says, I have changed multiple pages and paths across my `pages/_meta.json` but the deployment on Vercel still shows the old sidebar with dead links. When navigating to other pages (old and new) the sidebar is up to date. The only way to "fix" this is to manually trigger a redeploy without using the build cache.

What's the expected behavior here? Is there anything I can do to prevent this anomaly in the future?

**Comment by icsl-Jeon** [comment]
Same here. Is there any update? 😒

**Comment by vietanhdev** [comment]
Same here. Any fix?

**Comment by StubbornDeer** [comment]
Same, please help! Updating the .mdx files doesn't help, I updated ALL the .mdx files in the docs folder but the sidebar is still the same. What should I do?

**Comment by ChristianIvicevic** [comment]
@StubbornDeer You need to rebuild the project on Vercel without build cache by triggering a new deployment from their UI

**Comment by StubbornDeer** [comment]
@ChristianIvicevic looks like it helped! Thanks! (I still believe it should be mentioned in the documentation, though :) )

**Comment by colbyfayock** [comment]
would love to eventually see a solution that doesn't require bypassing build cache 🙏

**Comment by dimaMachina** [comment]
Should be fixed in Nextra 3
