### ISSUE TITLE
Hiding sidebar or TOC only hides the content, not respective containers

### ISSUE THREAD

**Issue by eat-sleep-code** [shuding/nextra#1351]
In my _meta.json I have the following to hide the TOC and Sidebar from the front page.

```
...
"index": {
	"title": "Home",
	"display": "hidden",
	"theme": {
		"breadcrumb": false,
		"sidebar": false,
		"toc": false
	}
},
...
```

This does hide the TOC and Sidebar content.   But it leaves the containers in place, consuming their original width.   This means the page content is still limited to the middle.   

<img width="1659" alt="Screenshot 2023-01-22 at 8 19 12 AM" src="https://user-images.githubusercontent.com/3846471/213923767-29ec8ac9-7276-4148-93f3-2dd4c6561d12.png">

**Comment by B2o5T** [comment]
@shuding I think it's explicit behaviour? if you want completely hide sidebar and toc use - `"layout": "full"`

**Comment by shuding** [comment]
Yes this is the expected behavior, the builtin theme always keep the content centered. You can use what @B2o5T mentioned to customize the layout.
