### ISSUE TITLE
`next build` throws "ENOENT: no such file or directory, open '/xxx/public/index-default.toml'"

### ISSUE THREAD

**Issue by YikSanChan** [shuding/nextra#136]
I am following https://nextra.vercel.app/docs/get-started , but when I try to run `next build` it throws

```
$ yarn build
yarn run v1.22.10
warning package.json: No license field
$ next build
info  - Using webpack 4. Reason: future.webpack5 option not enabled https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types
info  - Creating an optimized production build ...node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: ENOENT: no such file or directory, open '/Users/chenyisheng/source/yiksanchan/docs/public/index-default.toml'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/chenyisheng/source/yiksanchan/docs/public/index-default.toml'
}
error Command failed with exit code 1.
```

I wonder how to resolve this? My repo https://gitlab.com/YikSanChan/docs

Thanks!

**Comment by havelaer** [comment]
@YikSanChan I just encountered the same issue, not in GitLab CI but another CI platform. I've found the bug and it seems to be fixed [here](https://github.com/shuding/nextra/commit/4560775abe275e0d525bddf58c96a7b879cb894c) but not released yet. 

Until the fix is released I am temporary using the following:
```
// next.config.js
const withNextra = require('nextra')({
    theme: 'nextra-theme-docs',
    themeConfig: './theme.config.js',
});

module.exports = withNextra({
    webpack(config) {
        config.plugins.pop(); // remove stork plugin which was added by nextra
        return config;
    }
});
```

**Comment by YikSanChan** [comment]
@havelaer That works, Thanks!

**Comment by YikSanChan** [comment]
> @YikSanChan I just encountered the same issue, not in GitLab CI but another CI platform. I've found the bug and it seems to be fixed [here](https://github.com/shuding/nextra/commit/4560775abe275e0d525bddf58c96a7b879cb894c) but not released yet.
> 
> Until the fix is released I am temporary using the following:
> 
> ```
> // next.config.js
> const withNextra = require('nextra')({
>     theme: 'nextra-theme-docs',
>     themeConfig: './theme.config.js',
> });
> 
> module.exports = withNextra({
>     webpack(config) {
>         config.plugins.pop(); // remove stork plugin which was added by nextra. Remove when nextra version is bumped!
>         return config;
>     }
> });
> ```

I will close the comment once the fix is released
