### ISSUE TITLE
Feature Request: Expose the styled MDX components for use in custom components

### ISSUE THREAD

**Issue by ChristianIvicevic** [shuding/nextra#1370]
Last year I figured out in #799 that components in MDX files are styled inconsistently. Since then I have been manually writing HTML based tables in my MDX files and wrapping certain parts in curly braces as suggested in the issue and the resulting docs. Unfortunately I am maintaining multiple dozen pages in my nextra instance with a bunch of repetetive markup. However if I use a custom component to dynamically create the tables they have no styling.

I'd like to have the possibility to either have access to the class names you pass to the MDX renderer to reuse them like this:
```tsx
export const MyTable = () => {
  const styles = useNextraStyles();

  return <table className={styles.table}>...</table>;
};
```
Or alternantively have the components directly usable such as
```tsx
export const MyTable = () => {
  // Of course with a better name
  return <MdxStyledTable>...</MdxStyledTable>;
};
```
The reason is that I'd like to have my tables look as if they were rendered by the MDX renderer without custom styling and I'd like to stay away from hardcoding certain class names that are not guaranteed to be stable.

**Comment by B2o5T** [comment]
You can create Table similar to Nextra, you will need the following 

## Table component (`<table />` element)
https://github.com/shuding/nextra/blob/1e26811bdd4f0e6ab571f93497ef116c06fee06c/packages/nextra-theme-docs/src/mdx-components.tsx#L270-L273

## Tr, Th, Td components (`<tr />`, `<th />` and `<td />` elements)

https://github.com/shuding/nextra/blob/1e26811bdd4f0e6ab571f93497ef116c06fee06c/packages/nextra-theme-docs/src/mdx-components.tsx#L276-L278

Import them from

```js
import { Table, Td, Th, Tr } from 'nextra/components'
```

**Comment by ChristianIvicevic** [comment]
Oh yeah thanks for pointing out these components and I confirm that this works indeed but there is one minor issue. The `Table` component (similar to other components in the linked file) takes a bunch of class names that are hardcoded right now. If I copy & paste them I am in risk of breaking changes if the Tailwind classes get pruned (for example if you drop `nx-mt-6` in favor of `nx-mt-4`) at some point or simple things such as `nextra-scrollbar` being renamed etc.

Due to these reasons I wanted to discuss the possibility to export them safely so that I can always reference those even if there are changes so that I do not have to track them myself. Would you consider exporting those class names that you pass through to MDX?

**Comment by questgugou** [comment]
thankyou good
