### ISSUE TITLE
Open `http` links in new window

### ISSUE THREAD

**Issue by B2o5T** [shuding/nextra#1375]
### Discussed in https://github.com/shuding/nextra/discussions/1181

<div type='discussions-op-text'>

<sup>Originally posted by **1nfinite9** January  4, 2023</sup>
Is there any way to provide an option to open just a regular Markdown link in a new window? I understand this is currently available for links in the menu and sidebar, but would be quite useful when using the docs theme to create a collection of links, both internal and external.</div>

**Comment by 1nfinite9** [comment]
Thanks!
