### ISSUE TITLE
Export `<Steps />`, `<Card />` from nextra.site to docs theme

### ISSUE THREAD

**Issue by B2o5T** [shuding/nextra#1377]
### Discussed in https://github.com/shuding/nextra/discussions/1305

<div type='discussions-op-text'>

<sup>Originally posted by **1nfinite9** January 19, 2023</sup>
Are there any plans to provide documentation around how to show numbered steps like on this [page](https://nextra.site/docs/docs-theme/start)?</div>

**Comment by boostvolt** [comment]
Would also be handy if the `<OptionTable /> `component is extracted.

**Comment by C-EO** [comment]
Been waiting for the `<Card />` feature for long 😄

**Comment by Sanster** [comment]
+1. Super useful for the doc theme.

Here's how I currently do it. Copy `.steps-container` related css from https://github.com/shuding/nextra/blob/73241b3fee58f0318e9349a5eb7650a7cd55a4e3/docs/style.css to your `style.css`, and warp your `###` title in 
```jsx
<div className="steps-container">
### step1 
### step2
</div>
```

**Comment by Valcoholics** [comment]
> +1. Super useful for the doc theme.
> 
> Here's how I currently do it. Copy `.steps-container` related css from https://github.com/shuding/nextra/blob/73241b3fee58f0318e9349a5eb7650a7cd55a4e3/docs/style.css to your `style.css`, and warp your `###` title in
> 
> ```js
> <div className="steps-container">
> ### step1 
> ### step2
> </div>
> ```

This doesn't render in my docs theme currently. Not sure where I would start configuring my repo to use tailwind.

**Comment by Valcoholics** [comment]
Thank you!!

**Comment by 1nfinite9** [comment]
Thank you!
