### ISSUE TITLE
Improve the error message for missing configuration keys

### ISSUE THREAD

**Issue by TomasHubelbauer** [shuding/nextra#1378]
Hi folks, I was just fixing up a broken Nextra side and I found the issue in the end but I believe there is potential to improve the experience.

The problem was that while the application was set up by following the docs, here and here:
- https://nextra.site/docs
- https://nextra.site/docs/docs-theme/start

It still wasn't working.
The Nextra configuration looked like this:

`theme.config.jsx`:
```js
export default {
  logo: <span>My Nextra Documentation</span>,
  project: {
    link: 'https://github.com/shuding/nextra',
  },
  // ...
}
```

You'll notice this is the exact code snippet from the `docs` theme setup guide.

At runtime though, it would fail with this error:

```
ZodError: [
  {
    "code": "custom",
    "message": "Must be React.ReactNode or React.FC",
    "path": [
      "toc",
      "extraContent"
    ]
  }
]

handleResult
javascript/node_modules/.pnpm/zod@3.20.2/node_modules/zod/lib/index.mjs (502:0)
ZodObject.safeParse
javascript/node_modules/.pnpm/zod@3.20.2/node_modules/zod/lib/index.mjs (615:0)
ZodObject.parse
javascript/node_modules/.pnpm/zod@3.20.2/node_modules/zod/lib/index.mjs (595:0)
ConfigProvider
../node_modules/.pnpm/nextra-theme-docs@2.2.0_s75y6mxmikaw2mhqmuko6w7njm/node_modules/nextra-theme-docs/dist/index.js (187:0)
```

I'll say that the `ConfigProvider` step in the call stack is a bit of a hint as to what the actual problem is and it helped me to solve the issue, but it wasn't super straightforward. The fix was to add `toc.extraContent` to the config, like so:

`theme.config.jsx`:
```js
export default {
  logo: <span>My Nextra Documentation</span>,
  project: {
    link: 'https://github.com/shuding/nextra',
  },
  toc: {
    extraContent: <></>
  }
}
```

Why is `toc` a required field on the config? I suppose unless this is some weird and specific issue for my project, this will happen for anyone setting up a Nextra docs site according to the guide on the site, right?

Would it be welcome for me to update the guide content to include the `toc`? (Assuming that that is the real problem and I am not overseeing anything.)

Similarly, would it be welcome for me to attempt to improve the config parsing such that the Zod error is wrapped in a user-friendly rethrow which tells the user to look at the `nextra.config.tsx` file?

**Comment by B2o5T** [comment]
use the latest nextra 2.2.13
