### ISSUE TITLE
"footer": false is not working 

### ISSUE THREAD

**Issue by luke-klein** [shuding/nextra#1379]
That was my previous setup, but now I see the footer is visible after the update 
  
  "playground": {
    "title": "Playground",
    "type": "page",
    "theme": {
      "toc": false,
      "layout": "raw",
      "footer": false
    }
  },

**Comment by B2o5T** [comment]
please provide reproduction

**Comment by gaurav-pantelwar** [comment]
@luke-klein  May be try updating `theme.config.jsx` like this

```
export default {
  postFooter: null,
  footer: {
    component: null,
  },
};

```

**Comment by B2o5T** [comment]
@luke-klein yep, can confirm that bug, will be fixed in next release
