### ISSUE TITLE
"darkMode": false is not working

### ISSUE THREAD

**Issue by gaurav-pantelwar** [shuding/nextra#1389]
I want to have a light theme only on my API docs platform, but I am not able to do using "darkMode": false flag.

**Comment by gaurav-pantelwar** [comment]
Is this flag supposed to force the light theme or just for hiding the theme toggle button?

**Comment by B2o5T** [comment]
> Is this flag supposed to force the light theme or just for hiding the theme toggle button?

just for hiding the theme switch button

> I want to have a light theme only on my API docs platform, but I am not able to do using "darkMode": false flag.

use `nextThemes.forcedTheme` for it

I think we'll fix it to by setting `nextThemes.forcedTheme` to `light` when `darkMode` is `false`

**Comment by B2o5T** [comment]
see my comment on how to fix it https://github.com/shuding/nextra/issues/1630#issuecomment-1467079236
