### ISSUE TITLE
[Feature Request] Optional comment system (in cusdis) for blog theme

### ISSUE THREAD

**Issue by YikSanChan** [shuding/nextra#139]
Hi,

It is not uncommon for people wanting to add a comment system to their blog. There are a few options:
- A common choice is [disqus](https://disqus.com/), but it's not open source, and it charges if you don't want to show ads.
- [utterances](https://utteranc.es/) is an open source implementation that basically leverages github issues as the storage. It's smart, but it requires commenters to log into their GitHub account first to be able to leave a comment. Not friendly for anyone who doesn't code, basically.
- [cusdis](https://cusdis.com/). Open source, available to be self-hosted as well as hosted-on-vercel with your own postgresql db. It allows anyone to comment, and it also provides a admin dashboard to moderate the comments. I believe there are more exciting features to come.

It will be great if nextra blog theme can enable an optional cusdis support for each post.

**Comment by shuding** [comment]
I think for most comment plugins it's easy, we can have an option to inject scripts/html to the footer of the layout like: [cusdis](https://cusdis.com/doc#/integration/docsify). Definitely something nice to have.

**Comment by djyde** [comment]
Hi. Cusdis creator here.

FYI, we just released [react-cusdis](https://github.com/Cusdis/sdk/tree/master/packages/react-cusdis) for React application. Maybe we can use it in themes. I'll try later.

**Comment by bhaveshmoney** [comment]
hi , i want know about the feature of  disable the nested chat in comment or not

**Comment by bhaveshmoney** [comment]
Please , improve the documentation in cusdis

**Comment by djyde** [comment]
> hi , i want know about the feature of disable the nested chat in comment or not

Hi, if you are asking about Cusdis, please create issue on https://github.com/djyde/cusdis repo

**Comment by B2o5T** [comment]
Closing since blog has cusdis comments
