### ISSUE TITLE
Table content disappearing from the page

### ISSUE THREAD

**Issue by luke-klein** [shuding/nextra#1394]
Making a table bigger results in the content disappearing from the page

![Untitled-2023-01-16-2241s](https://user-images.githubusercontent.com/120297915/214455965-aef10036-7a89-438f-835e-a49c02cc4369.png)

## **Table** 
******
|**Student ID**|**First Name**|**Last Name**|**Major**|**GPA**|**Graduation Year**|**Email**|**Phone Number**|**Address**|**Date of Birth**|**Gender**|**Class Standing**|**Enrollment Status**|**Enrollment Date**|**Graduation Date**|**Advisor ID**|
|:----|:----|:----|:----|:----|:----|:----|:----|:----|:----|:----|:----|:----|:----|:----|:----|
|    12345|John|Doe|Computer Science|3.5|2024|johndoe@example.com|555-555-5555|123 Main St, Anytown USA|01/01/2000|M|Junior|Full-time|01/01/2022|05/01/2024|54321|
|    67890|Jane|Smith|Biology|3.2|2023|janesmith@example.com|555-555-5555|456 Park Ave, Anytown USA|02/02/1999|F|Senior|Full-time|01/01/2019|12/01/2022|56789|
|    11111|Bob|Johnson|Mathematics|3.7|2022|bobjohnson@example.com|555-555-5555|789 Elm St, Anytown USA|03/03/1998|M|Senior|Part-time|01/01/2021|05/01/2022|98765|
|    22222|Samantha|Williams|Chemistry|3.3|2024|samanthawilliams@example.com|555-555-5555|321 Oak St, Anytown USA|04/04/1997|F|Junior|Full-time|01/01/2022|05/01/2024|54321|
|    33333|Michael|Brown|Political Science|3.0|2023|michaelbrown@example.com|555-555-5555|159 Pine St, Anytown USA|05/05/1996|M|Senior|Full-time|01/01/2019|12/01/2022|56789|
|    44444|Ashley|Moore|Business|3.5|2022|ashleymoore@example.com|555-555-5555|753 Birch St, Anytown USA|06/06/1995|F|Senior|Part-time|01/01/2021|05/01/2022|98765|
|    55555|David|Taylor|Engineering|3.9|2024|davidtaylor@example.com|555-555-5555|964 Maple St, Anytown USA|07/07/1994|M|Junior|Full-time|01/01/2022|05/01/2024|54321|
|    77777|Jessica|Anderson|Communications|3.6|2023|jessicaanderson@example.com|555-555-5555|111 Cedar St, Anytown USA|08/08/1993|F|Senior|Full-time|01/01/2019|12/01/2022|56789|

```md
|**Student ID**|**First Name**|**Last Name**|**Major**|**GPA**|**Graduation Year**|**Email**|**Phone Number**|**Address**|**Date of Birth**|**Gender**|**Class Standing**|**Enrollment Status**|**Enrollment Date**|**Graduation Date**|**Advisor ID**|
|:----|:----|:----|:----|:----|:----|:----|:----|:----|:----|:----|:----|:----|:----|:----|:----|
|    12345|John|Doe|Computer Science|3.5|2024|johndoe@example.com|555-555-5555|123 Main St, Anytown USA|01/01/2000|M|Junior|Full-time|01/01/2022|05/01/2024|54321|
|    67890|Jane|Smith|Biology|3.2|2023|janesmith@example.com|555-555-5555|456 Park Ave, Anytown USA|02/02/1999|F|Senior|Full-time|01/01/2019|12/01/2022|56789|
|    11111|Bob|Johnson|Mathematics|3.7|2022|bobjohnson@example.com|555-555-5555|789 Elm St, Anytown USA|03/03/1998|M|Senior|Part-time|01/01/2021|05/01/2022|98765|
|    22222|Samantha|Williams|Chemistry|3.3|2024|samanthawilliams@example.com|555-555-5555|321 Oak St, Anytown USA|04/04/1997|F|Junior|Full-time|01/01/2022|05/01/2024|54321|
|    33333|Michael|Brown|Political Science|3.0|2023|michaelbrown@example.com|555-555-5555|159 Pine St, Anytown USA|05/05/1996|M|Senior|Full-time|01/01/2019|12/01/2022|56789|
|    44444|Ashley|Moore|Business|3.5|2022|ashleymoore@example.com|555-555-5555|753 Birch St, Anytown USA|06/06/1995|F|Senior|Part-time|01/01/2021|05/01/2022|98765|
|    55555|David|Taylor|Engineering|3.9|2024|davidtaylor@example.com|555-555-5555|964 Maple St, Anytown USA|07/07/1994|M|Junior|Full-time|01/01/2022|05/01/2024|54321|
|    77777|Jessica|Anderson|Communications|3.6|2023|jessicaanderson@example.com|555-555-5555|111 Cedar St, Anytown USA|08/08/1993|F|Senior|Full-time|01/01/2019|12/01/2022|56789|
```

**Comment by B2o5T** [comment]
fixed for both table/tabs
try https://nextra-theme-docs-25bixu8i5.vercel.sh/docs/advanced/scrollbar-x
