### ISSUE TITLE
add docs about `codeHighlight: false` for nextraConfig

### ISSUE THREAD

**Issue by harish-sethuraman** [shuding/nextra#1400]
I wanted to over write the syntax highlighting with some other highlighter other than `shiki` while trying to do so I stumbled upon this thing. When I try to override the `pre` through `theme.config` the children I receive are already syntax highlighted

```js
const a = b;
```

For the above fenced pre block I got the following result

```js
  pre: (props) => {
      // This is console's output which is already syntax highlighted
      // {
      //   '$$typeof': Symbol(react.element),
      //   type: 'span',
      //   key: null,
      //   ref: null,
      //   props: { style: { color: 'var(--shiki-token-keyword)' }, children: 'const' },
      //   _owner: null,
      //   _store: {}
      // }
      console.log(props.children.props.children.props.children[0]);
      return props.children;
    },
```

This way I have to strip out the content without any highlighting to apply some custom syntax highlighter. It'd be nice if this returned the actual child as string ie: `const a = b;`. This way it allows us to use any syntax highlighter.

If the `pre` mdx component is being written then it shouldn't highlight otherwise it could make use of highlighting 😅 
 

Here is the actual codesandbox link: https://codesandbox.io/p/sandbox/nextra-doubt-g21l5k

**Comment by B2o5T** [comment]
set this to `false` in your next.config to disable syntax highlighting 

https://github.com/shuding/nextra/blob/a404ef7c6ea321995cff431a915c2bc407a45c8a/packages/nextra/src/types.ts#L147

**Comment by harish-sethuraman** [comment]
Wow it worked! Thanks 😄

**Comment by harish-sethuraman** [comment]
Shall I send a PR for adding it to documentation?

**Comment by B2o5T** [comment]
sure, this will be awesome contribution 😍
