### ISSUE TITLE
Do beta releases by default

### ISSUE THREAD

**Issue by shuding** [shuding/nextra#1405]
I think it's more practical to release beta versions by default, and only do stable every once in a while (e.g. weekly?). Since we have `nextra.site` using the main branch, we will be able to catch some obvious UI problems and beta users can also report issues, without affecting stable users.

**Comment by shuding** [comment]
It is a lot of work to maintain something that contains both UI pieces and compiler/bundler logic. And many features are on top of other libraries that are totally unrelated to each other. It's pretty neutral that some bugs will be introduced while adding new features, so we will try to add more tests when working on features/fixes. At the same time keeping a good channel for feedback & testers would be amazing.

**Comment by B2o5T** [comment]
I totally agree with you 👍

**Comment by C-EO** [comment]
Sounds like a good idea
