### ISSUE TITLE
Task list not rendered

### ISSUE THREAD

**Issue by YikSanChan** [shuding/nextra#141]
Hi,

According to https://nextra.vercel.app/features/mdx#task-list, task list rendering is supported, however https://yiksanchan.gitlab.io/docs/task-list-not-rendered doesn't agree ...

![image](https://user-images.githubusercontent.com/17229109/115995427-b9632400-a60d-11eb-93e0-807f7b836c42.png)

Here's the code https://gitlab.com/YikSanChan/docs/-/blob/master/pages/task-list-not-rendered.md

```
# Task list not rendered

- [x] Done
- [ ] Todo 1
- [ ] Todo 2
```

Note: It can be reproduced by simply `yarn dev`.

Any help? Thanks!

**Comment by brandonpittman** [comment]
see: #127
