### ISSUE TITLE
Bugs with hide sidebar, the toggle creates a white spot ⬜️ when I click on it

### ISSUE THREAD

**Issue by luke-klein** [shuding/nextra#1412]
Bug cause `toggleButton: true` https://github.com/shuding/nextra/pull/1418

### First bug - In the sidebar, all text is squeezed when I switch between two pages 

https://user-images.githubusercontent.com/120297915/215263429-20a3dcaf-c993-44f2-b9b2-2ee9016e16ab.mp4

### Second bug - The toggle creates a white spot when I click on it

https://user-images.githubusercontent.com/120297915/215263493-4fc8be90-9429-4e3e-a39c-ad332ccdfdf0.mp4

![image](https://user-images.githubusercontent.com/120297915/215263528-fc9ebb8d-b79f-4184-ac16-b098f762ae8c.png)

**Comment by B2o5T** [comment]
fixed both, thx for the report
