### ISSUE TITLE
Anchor link not clickable after deploying to GitLab Pages

### ISSUE THREAD

**Issue by YikSanChan** [shuding/nextra#142]
Hi,

I have a page with anchor links (Title 1), after moving my mouse over the link, this is how it looks when running `yarn dev`.

![image](https://user-images.githubusercontent.com/17229109/115995723-f24fc880-a60e-11eb-9f19-d6016a9c0191.png)

However, the `#` doesn't show up when running in GitLab Pages, when I move my mouse over it.

![image](https://user-images.githubusercontent.com/17229109/115995737-05fb2f00-a60f-11eb-8088-70c046c89c7c.png)

Also, the URL http://localhost:3000/docs/not-scroll-to-anchor-link#title-2 leads me to the right place when running `yarn dev`, while in production, https://yiksanchan.gitlab.io/docs/not-scroll-to-anchor-link#title-2 leads me to the top of https://yiksanchan.gitlab.io/docs/not-scroll-to-anchor-link.

Here's my page https://gitlab.com/YikSanChan/docs/-/blob/master/pages/not-scroll-to-anchor-link.md. Any help?

**Comment by B2o5T** [comment]
Closing due time, will reopen if someone has similar problem

**Comment by jasjamjos** [comment]
anchor link not working

**Comment by B2o5T** [comment]
> anchor link not working

Could you send more info about your next/nextra version?

**Comment by jasjamjos** [comment]
its the most recent one.. i think it could be because im using NPM instead of yarn? because on 1 click deploy to vercel it works... and when I clone it deploy to AWS using npm it doesn't work

**Comment by 0-Chan** [comment]
Me neither.. next/nextra version is 
`next : 12.3.1`,
`nextra : 1.1.0`,
`nextra-theme-docs : 1.2.6`

**Comment by B2o5T** [comment]
@0-Chan there will be no updates for v1, use latest v2 beta
