### ISSUE TITLE
Navigation link causes line break when navigated to

### ISSUE THREAD

**Issue by n1ru4l** [shuding/nextra#1431]
![image](https://user-images.githubusercontent.com/14338007/215449799-4b1e56a4-bee8-4246-9d11-85278c88f069.png)
![image](https://user-images.githubusercontent.com/14338007/215449841-d54c01b0-ad7b-4bce-87e5-d3150847189d.png)

Source: https://the-guild.dev/graphql/codegen/docs/getting-started/development-workflow

Seems like a common workaround for line-shifting through applying font-weight is to use text-shadow instead: https://stackoverflow.com/q/556153/4202031

**Comment by shuding** [comment]
Not sure what's the best solution to this TBH. Text shadow won't look good, and using a pseudo element can potentially cause overflowed content if it's very long.

**Comment by dimaMachina** [comment]
Was fixed in v3
