### ISSUE TITLE
focus outline is cut off

### ISSUE THREAD

**Issue by n1ru4l** [shuding/nextra#1432]
<img width="305" alt="image" src="https://github.com/shuding/nextra/assets/14338007/bee75b27-ad2e-4624-8cc5-ff3a390720b8">
<img width="409" alt="image" src="https://github.com/shuding/nextra/assets/14338007/01646b73-502c-4ccc-adfe-936aaec51a04">

**Comment by dimaMachina** [comment]
will be fixed in next alpha
