### ISSUE TITLE
How to disable ToC for a specific page?

### ISSUE THREAD

**Issue by raproid** [shuding/nextra#1440]
I'm trying to integrate API docs via Rapidoc. 

I need to disable ToC for only one page — the API reference page. For the API docs to fully fit into the layout of the page.
I need to keep the left nav menu on the page for users to be able to navigate to other doc pages.

How can I do this?

**Comment by SonMooSans** [comment]
You can easily do this by using the "theme" option in the `_meta.json` file
Just basically add `"toc": false` and it should be worked

Go [here](https://nextra.site/docs/docs-theme/page-configuration#theme-components) for more information
