### ISSUE TITLE
Enable comments in _meta.json

### ISSUE THREAD

**Issue by brandonchinn178** [shuding/nextra#1455]
I'm generating one of my `_meta.json` files, and it'd be nice to add a "DO NOT EDIT" comment to the top, but JSON doesn't support comments.

Even better would be to use a JSON5 parser, to also enable trailing commas

**Comment by B2o5T** [comment]
I don't like the idea of adding complexity with `json5` since we could have plain javascript for it

@shuding maybe use `_meta.js` for that and check
- if `export default` is a function - consider dynamic meta
- if object - consider it's regular `_meta.json`

**Comment by shuding** [comment]
Like that idea of using `_meta.js` @B2o5T !

**Comment by B2o5T** [comment]
you already implemented it @shuding so for anyone who what to use comments in your `_meta.json` files - just refactor it to `_meta.js`

<img width="422" alt="image" src="https://user-images.githubusercontent.com/7361780/216786010-93be9613-1c34-4939-a38d-7137768940fb.png">
