### ISSUE TITLE
Question about FlexSearch index

### ISSUE THREAD

**Issue by ChaseRensberger** [shuding/nextra#1464]
How can I reset the FlexSearch index easily? The search shows results for pages that no longer exist.

**Comment by ChristianIvicevic** [comment]
If this is while your docs are deployed on Vercel you could try to rebuild the active deployment without using the caches. This used to help in my use-case.

**Comment by ChaseRensberger** [comment]
> If this is while your docs are deployed on Vercel you could try to rebuild the active deployment without using the caches. This used to help in my use-case.

This worked! Thanks!
