### ISSUE TITLE
Title missing from the list

### ISSUE THREAD

**Issue by luke-klein** [shuding/nextra#1468]
As you can see, one chapter is missing, and when I press react, react native appears. If I reload the page, the same issue occurs 

```_meta.json```
```json
  "-- WebDev --": {
    "type": "separator",
    "title": "Web Development"
  },
  "html": "HTML Tutorial",
  "tailwindcss": "Tailwind CSS Tutorial",
  "js" : "JavaScript Tutorial",
  "react": "React Tutorial",
  "reactnative": "React NativeTutorial",
  ```

https://user-images.githubusercontent.com/120297915/216807001-12b214d1-fc15-4a91-b103-51a14b9366e7.mp4

**Comment by B2o5T** [comment]
Please provide a reproduction

**Comment by B2o5T** [comment]
@luke-klein Maybe this solution https://github.com/shuding/nextra/issues/1564#issuecomment-1447419595 will help you?
