### ISSUE TITLE
The first link in the sidebar list is being created twice.

### ISSUE THREAD

**Issue by kidow** [shuding/nextra#1472]
I am using nextra to organize the component list into code. However, among the sidebar sub doc items, the first item has duplicate links. The duplicated link is moved to the bottom of the list. It's hard to explain in detail, so I attach a link to my repository and a screenshot. What's the matter? What should I do??

<img width="284" alt="image" src="https://user-images.githubusercontent.com/39021158/216928325-3fea3ca1-09a4-414f-9f05-e0ceb0e36c7e.png">

```json
// pages/archive/feedback/_meta.ko.json
{
  "Alert": "Alert",
  "Backdrop": "Backdrop",
  "Dialog": "Dialog",
  "Modal": "Modal",
  "Notice": "Notice",
  "Progress": "Progress",
  "Skeleton": "Skeleton",
  "Spinner": "Spinner",
  "Toast": "Toast"
}
```

[Project Link](https://github.com/kidow/kidow.me)

<img width="240" alt="image" src="https://user-images.githubusercontent.com/39021158/216929069-3282a1aa-b41d-40f7-9961-a7d0ee3b87af.png">

**Comment by B2o5T** [comment]
I guess it's because you have a mix of letter casing - `Alert` and `alert`
<img width="293" alt="image" src="https://user-images.githubusercontent.com/7361780/216942363-45842c76-2574-45b5-8558-e0cf2be89955.png">

**Comment by kidow** [comment]
Ah... Thx. I wondered why it worked in development mode, but on github, the case of the file was not being verified. I also remember now why this happened.
The problem solved. thank you!
