### ISSUE TITLE
Feature request: access to original components in theme.config

### ISSUE THREAD

**Issue by SwimmingPolar** [shuding/nextra#1478]
I specifically need access to navbar component in `theme.config`. I see navbar props in theme.config give us many options
but how about if we can get the original component rendered by nextra and just wrap it inside our own component?

```javascript
navbar: {
  component: ({ Navbar }: NavbarProps) => {
    return (
      <div className="div-with-styles">
        // Untouched
        <Navbar />
        <SecondNavbar />
        <FixedBadgeUnderNavbar />
      </div>
    )
  }
}
```

Maybe same thing to `feedback`, `editLink` and others too.

**Comment by SwimmingPolar** [comment]
> just import `Navbar` from `nextra-theme-docs`

Thanks for the reply. I just did that. Is it on the docs? I believe I never encountered this info.

**Comment by B2o5T** [comment]
feel free to add it to docs
