### ISSUE TITLE
Nextra v2.2.13 breaks position sticky of elements

### ISSUE THREAD

**Issue by yairhaimo** [shuding/nextra#1481]
In nextra v 2.2.13  a `overflow-x: hidden` was added (https://github.com/shuding/nextra/commit/fd020ca9d4834bb4ffa7ebdace2cb9d221b143c6#diff-8310a54b1ec9da38ed7c74e8c1328e33f07848d25bd9779811614642e3268747R51) which breaks `sticky` elements.

Ran into it with CodeHike's Scrollycoding (https://github.com/code-hike/codehike/issues/322). See CodeHike's issue for repro sandbox.

**Comment by B2o5T** [comment]
it was a fix of bug https://github.com/shuding/nextra/issues/1284, PR welcome to support both

**Comment by pomber** [comment]
I think `overflow-x: clip` should support both
