### ISSUE TITLE
Can I enable 'showLineNumbers' as default like 'copy' button?

### ISSUE THREAD

**Issue by KushajveerSingh** [shuding/nextra#1492]
As the title says, is there a way I can enable `showLineNumbers` as default.

In case this functionality does not exist, can you give me some guidance on how to implement this. I can work on a PR. There is already support for copy=false, so I think adding this functionality should be pretty easy.

**Comment by B2o5T** [comment]
Please request this feature in https://github.com/atomiks/rehype-pretty-code

**Comment by irangarcia** [comment]
I think this feature already exists on rehype-pretty-code, take a look at the "Line numbers" section on their [site](https://rehype-pretty-code.netlify.app/)
