### ISSUE TITLE
theme toggle not respecting tailwind "dark" colors.

### ISSUE THREAD

**Issue by engageintellect** [shuding/nextra#1495]
Example:

I have deployed the nextra-docs template using the vercel deployment button.

Let's say I have a component like:
```
<div className="bg-red-500 dark:bg-blue-500">hello world</div>
```

If my system/browser settings are set to light, it appears blue. Dark - red.

However, the theme toggle won't trigger the change. Is this intentional? 

I also forked the who nextra repo, where everything appears to work as expected. So, my issue appears to be with the nextra-docs template.

I hope this makes sense... happy to clarify more if needed.

TIA

**Comment by B2o5T** [comment]
Please provide a reproduction

**Comment by B2o5T** [comment]
closing it due silence

**Comment by dsernst** [comment]
I was able to get Tailwind's `dark:` pseudo classes to respect my current Nextra theme color by adding:

```diff
module.exports = {
+  darkMode: 'class',
  // ...
}
```

To the top level of my `tailwind.config.js` file, as described here: https://tailwindcss.com/docs/dark-mode#customizing-the-class-name

Hope this helps

**Comment by cglacet** [comment]
To use dark theme we need to had the follofing in `tailwind.config.js`:

```ts
module.exports = {
  prefix: "nx-",
  darkMode: ["class", '[data-mode="dark"]'],
};
```

In case this changes in the future here is how I'll describe how I found the solution (TLDR; don't remove the `nx-` prefix, instead have a look at your theme's tailwind config, for exemple in the **docs** theme the config is [here](https://github.com/shuding/nextra/blob/main/packages/nextra-theme-docs/tailwind.config.js), and look at how the dark theme selector is defined, copy it to your config).

## Problem

You could make this work by completetly removing the prefix from your local config:

```ts
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./components/**/*.{ts,tsx}",
    "./pages/**/*.{md,mdx}",
    "./theme.config.tsx",
  ],
};
```

Example code using this config (working): 

```tsx
<div className="bg-white dark:bg-black"><p>stuff</p></div>
```

But then you would have some duplicated classes on classes (for example `dark:nx-border-gray-700` exist in the theme so if you use `dark:border-gray-700` then both identical classes will be generated).

The documentation suggests this : 

```ts
/** @type {import('tailwindcss').Config} */
module.exports = {
  prefix: "nx-",
  darkMode: ["class", '[data-mode="dark"]'],
  content: [
    "./components/**/*.{ts,tsx}",
    "./pages/**/*.{md,mdx}",
    "./theme.config.tsx",
  ],
};
```

But then, the previous code using prefixes doesn't work (the dark class is not created):

```tsx
<div className="nx-bg-white dark:nx-bg-black"><p>stuff</p></div>
```

## Solution 

After a bit of digging I found that the generated HTML contains the following:

```html
<html style="color-scheme: dark;" > ... </html>
```

Which you can find the origin in the [tailwind config file](https://github.com/shuding/nextra/blob/9e465cb9f4c53ae5947435517f5914a998b9f15c/packages/nextra-theme-docs/tailwind.config.js#L76) from the **docs** theme. So we only need to copy this configuration in our local tailwind config: 

```ts
/** @type {import('tailwindcss').Config} */
module.exports = {
  prefix: "nx-",
  darkMode: ["class", 'html[class~="dark"]'],
  content: [
    "./components/**/*.{ts,tsx}",
    "./pages/**/*.{md,mdx}",
    "./theme.config.tsx",
  ],
};
```

And now the previous code works as expected.

**Comment by engageintellect** [comment]
> closing it due silence

Sorry for radio silence, I wasn't seeing these notifications.

It appears other users were able to explain solutions to this issue. I think I'm all good. 👍🏻

**Comment by engageintellect** [comment]
> To use dark theme we need to had the follofing in `tailwind.config.js`:
> 
> 
> 
> ```ts
> 
> module.exports = {
> 
>   prefix: "nx-",
> 
>   darkMode: ["class", '[data-mode="dark"]'],
> 
> };
> 
> ```
> 
> 
> 
> In case this changes in the future here is how I'll describe how I found the solution (TLDR; don't remove the `nx-` prefix, instead have a look at your theme's tailwind config, for exemple in the **docs** theme the config is [here](https://github.com/shuding/nextra/blob/main/packages/nextra-theme-docs/tailwind.config.js), and look at how the dark theme selector is defined, copy it to your config).
> 
> 
> 
> ## Problem
> 
> 
> 
> You could make this work by completetly removing the prefix from your local config:
> 
> 
> 
> ```ts
> 
> /** @type {import('tailwindcss').Config} */
> 
> module.exports = {
> 
>   content: [
> 
>     "./components/**/*.{ts,tsx}",
> 
>     "./pages/**/*.{md,mdx}",
> 
>     "./theme.config.tsx",
> 
>   ],
> 
> };
> 
> ```
> 
> 
> 
> Example code using this config (working): 
> 
> 
> 
> ```tsx
> 
> <div className="bg-white dark:bg-black"><p>stuff</p></div>
> 
> ```
> 
> 
> 
> But then you would have some duplicated classes on classes (for example `dark:nx-border-gray-700` exist in the theme so if you use `dark:border-gray-700` then both identical classes will be generated).
> 
> 
> 
> The documentation suggests this : 
> 
> 
> 
> ```ts
> 
> /** @type {import('tailwindcss').Config} */
> 
> module.exports = {
> 
>   prefix: "nx-",
> 
>   darkMode: ["class", '[data-mode="dark"]'],
> 
>   content: [
> 
>     "./components/**/*.{ts,tsx}",
> 
>     "./pages/**/*.{md,mdx}",
> 
>     "./theme.config.tsx",
> 
>   ],
> 
> };
> 
> ```
> 
> 
> 
> But then, the previous code using prefixes doesn't work (the dark class is not created):
> 
> 
> 
> ```tsx
> 
> <div className="nx-bg-white dark:nx-bg-black"><p>stuff</p></div>
> 
> ```
> 
> 
> 
> ## Solution 
> 
> 
> 
> After a bit of digging I found that the generated HTML contains the following:
> 
> 
> 
> ```html
> 
> <html style="color-scheme: dark;" > ... </html>
> 
> ```
> 
> 
> 
> Which you can find the origin in the [tailwind config file](https://github.com/shuding/nextra/blob/9e465cb9f4c53ae5947435517f5914a998b9f15c/packages/nextra-theme-docs/tailwind.config.js#L76) from the **docs** theme. So we only need to copy this configuration in our local tailwind config: 
> 
> 
> 
> ```ts
> 
> /** @type {import('tailwindcss').Config} */
> 
> module.exports = {
> 
>   prefix: "nx-",
> 
>   darkMode: ["class", 'html[class~="dark"]'],
> 
>   content: [
> 
>     "./components/**/*.{ts,tsx}",
> 
>     "./pages/**/*.{md,mdx}",
> 
>     "./theme.config.tsx",
> 
>   ],
> 
> };
> 
> ```
> 
> 
> 
> And now the previous code works as expected.

Exactly what I was looking for. You're a gentleman, and a scholar. 🙏🏻

**Comment by cglacet** [comment]
I think the solution is not perfect yet. 

Using the above mentioned configuration there is still an issue but I think the problem comes from the docs theme. If I use the `nx-` prefix and that I use `nx-hidden` `className` anywhere in my own files it breaks the docs theme (search bar/toc/ and some other components are not visible anymore).
