### ISSUE TITLE
Warning: React has detected a change in the order of Hooks called by Search.

### ISSUE THREAD

**Issue by steida** [shuding/nextra#1498]
When I click on "search documentation" input.

**Comment by adhrinae** [comment]
Just in case, here's an additional information.

<img width="657" alt="image" src="https://user-images.githubusercontent.com/14539203/229415782-db2bb91e-50a3-4e0e-a84c-fdaf6632a7bd.png">

**Comment by masonkristopher** [comment]
In case it helps anyone else, this will happen when you are running dev before running the build locally.
