### ISSUE TITLE
Footnotes not formatted correctly here?

### ISSUE THREAD

**Issue by jasonchitla** [shuding/nextra#1499]
Seen at https://demo.vercel.blog/posts/markdown (and also experiencing with my forked blog) the issue of the footnotes showing correctly below:
<img width="414" alt="image" src="https://user-images.githubusercontent.com/3611926/218291557-bfc7a1e3-82b1-4400-86fd-17a9990cebb8.png">

**Comment by B2o5T** [comment]
Should be fixed by https://github.com/shuding/nextra/pull/2104
