### ISSUE TITLE
Math typesetting 

### ISSUE THREAD

**Issue by gr-qft** [shuding/nextra#150]
Hi, I just wanted to ask if there was a plan to enable math equations? It seems to me this is not a trivial issue. 

Thanks!

**Comment by shuding** [comment]
No plan for that yet but can definitely accept a PR for it! 👍

**Comment by gr-qft** [comment]
@shuding Ok I'm going to work on this. No warranty though because I have other things going on but I'll try get it done, I also need it.

**Comment by kallydev** [comment]
@shuding Do you assign it to me? I'm confident to implement this feature.

**Comment by shuding** [comment]
@kallydev Yes feel free to take it, thanks! 👍
