### ISSUE TITLE
Add print style support

### ISSUE THREAD

**Issue by CLCK0622** [shuding/nextra#1502]
Recently I would like to export *.PDF from my nextra site, however, a problem appears that it's still using the web style. 
Is there any way to add a print style change so that the PDF will be better for reading?
e.g.: remove the nav bar, change the footer position, etc.
Many thanks.

**Comment by MrWillCom** [comment]
That's a cool idea, I'd like to work on it! 🤩

**Comment by aeilot** [comment]
Cool! I think [this](https://developer.mozilla.org/en-US/docs/Web/Guide/Printing) may help.

**Comment by CLCK0622** [comment]
> That's a cool idea, I'd like to work on it! 🤩

I found a guide, and I suppose it would help:
https://developer.mozilla.org/en-US/docs/Web/Guide/Printing#using_a_print_style_sheet
