### ISSUE TITLE
Assign MD/MDX file path in _meta.json

### ISSUE THREAD

**Issue by riccox** [shuding/nextra#1503]
Is there any way to assign the rendered file path of specified sidebar items like below.

```json
{
  "changelog": {
    "title": "CHANGE LOG",
    "path": "../../../CHANGELOG.md"
  }
}
```

**Comment by B2o5T** [comment]
currently, there is no way

**Comment by riccox** [comment]
I think that it could be a wonderful feature for this project.
Or, is there any good tips for me to find out if I wanna create a PR to complete this feature, like which file can control this behavior.

**Comment by B2o5T** [comment]
No good tips, just look at a source code

**Comment by B2o5T** [comment]
Use symlinks instead
