### ISSUE TITLE
Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.

### ISSUE THREAD

**Issue by steida** [shuding/nextra#1505]
Default installation. 

web:build: info  - Linting and checking validity of types...
web:build: info  - Creating an optimized production build...
web:build: <w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of /Users/danielsteigerwald/dev/evolu/node_modules/.pnpm/nextra@2.2.14_3vryta7zmbcsw4rrqf4axjqggm/node_modules/nextra/dist/plugin.mjs for build dependencies failed at 'import(filePath)'.
web:build: <w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
web:build: <w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Can't resolve './__temp__' in '/Users/danielsteigerwald/dev/evolu/node_modules/.pnpm/nextra@2.2.14_3vryta7zmbcsw4rrqf4axjqggm/node_modules/nextra/dist'
web:build: <w> while resolving './__temp__' in /Users/danielsteigerwald/dev/evolu/node_modules/.pnpm/nextra@2.2.14_3vryta7zmbcsw4rrqf4axjqggm/node_modules/nextra/dist as file
web:build: <w>  at resolve esm file ./__temp__
web:build: <w>  at file dependencies /Users/danielsteigerwald/dev/evolu/node_modules/.pnpm/nextra@2.2.14_3vryta7zmbcsw4rrqf4axjqggm/node_modules/nextra/dist/compile.mjs
web:build: <w>  at file /Users/danielsteigerwald/dev/evolu/node_modules/.pnpm/nextra@2.2.14_3vryta7zmbcsw4rrqf4axjqggm/node_modules/nextra/dist/compile.mjs
web:build: <w>  at resolve esm file ./compile.mjs
web:build: <w>  at file dependencies /Users/danielsteigerwald/dev/evolu/node_modules/.pnpm/nextra@2.2.14_3vryta7zmbcsw4rrqf4axjqggm/node_modules/nextra/dist/loader.mjs
web:build: <w>  at file /Users/danielsteigerwald/dev/evolu/node_modules/.pnpm/nextra@2.2.14_3vryta7zmbcsw4rrqf4axjqggm/node_modules/nextra/dist/loader.mjs
web:build: <w>  at resolve esm file ./dist/loader.mjs
web:build: <w>  at file dependencies /Users/danielsteigerwald/dev/evolu/node_modules/.pnpm/nextra@2.2.14_3vryta7zmbcsw4rrqf4axjqggm/node_modules/nextra/loader.js
web:build: <w>  at file /Users/danielsteigerwald/dev/evolu/node_modules/.pnpm/nextra@2.2.14_3vryta7zmbcsw4rrqf4axjqggm/node_modules/nextra/loader.js
web:build: <w>  at resolve commonjs /Users/danielsteigerwald/dev/evolu/node_modules/.pnpm/nextra@2.2.14_3vryta7zmbcsw4rrqf4axjqggm/node_modules/nextra/loader.js
web:build: <w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of /Users/danielsteigerwald/dev/evolu/node_modules/.pnpm/nextra@2.2.14_3vryta7zmbcsw4rrqf4axjqggm/node_modules/nextra/dist/plugin.mjs for build dependencies failed at 'import(filePath)'.
web:build: <w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
web:build: <w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Can't resolve './__temp__' in '/Users/danielsteigerwald/dev/evolu/node_modules/.pnpm/nextra@2.2.14_3vryta7zmbcsw4rrqf4axjqggm/node_modules/nextra/dist'
web:build: <w> while resolving './__temp__' in /Users/danielsteigerwald/dev/evolu/node_modules/.pnpm/nextra@2.2.14_3vryta7zmbcsw4rrqf4axjqggm/node_modules/nextra/dist as file
web:build: <w>  at resolve esm file ./__temp__
web:build: <w>  at file dependencies /Users/danielsteigerwald/dev/evolu/node_modules/.pnpm/nextra@2.2.14_3vryta7zmbcsw4rrqf4axjqggm/node_modules/nextra/dist/compile.mjs
web:build: <w>  at file /Users/danielsteigerwald/dev/evolu/node_modules/.pnpm/nextra@2.2.14_3vryta7zmbcsw4rrqf4axjqggm/node_modules/nextra/dist/compile.mjs
web:build: <w>  at resolve esm file ./compile.mjs
web:build: <w>  at file dependencies /Users/danielsteigerwald/dev/evolu/node_modules/.pnpm/nextra@2.2.14_3vryta7zmbcsw4rrqf4axjqggm/node_modules/nextra/dist/loader.mjs
web:build: <w>  at file /Users/danielsteigerwald/dev/evolu/node_modules/.pnpm/nextra@2.2.14_3vryta7zmbcsw4rrqf4axjqggm/node_modules/nextra/dist/loader.mjs
web:build: <w>  at resolve esm file ./dist/loader.mjs
web:build: <w>  at file dependencies /Users/danielsteigerwald/dev/evolu/node_modules/.pnpm/nextra@2.2.14_3vryta7zmbcsw4rrqf4axjqggm/node_modules/nextra/loader.js
web:build: <w>  at file /Users/danielsteigerwald/dev/evolu/node_modules/.pnpm/nextra@2.2.14_3vryta7zmbcsw4rrqf4axjqggm/node_modules/nextra/loader.js
web:build: <w>  at resolve commonjs /Users/danielsteigerwald/dev/evolu/node_modules/.pnpm/nextra@2.2.14_3vryta7zmbcsw4rrqf4axjqggm/node_modules/nextra/loader.js

**Comment by transitive-bullshit** [comment]
Likely the same issue as https://github.com/shuding/nextra/issues/1564
