### ISSUE TITLE
Regeneration of `pnpm-lock.yaml` results in TypeScript errors during `pnpm install`

### ISSUE THREAD

**Issue by robbear** [shuding/nextra#1506]
A general question of whether this is or should be part of any test suite?

1. Clone the repo
2. `rm pnpm-lock.yaml`
3. `pnpm install`

Currently, this fails due to TypeScript issues in `packages/nextra/src/compile.ts`. It prevents projects that integrate with source copies of `./packages` to generate their own lock files.

**Comment by robbear** [comment]
Because we have dependencies on other code (internal and external) that we inline, and by rebuilding the lock file we can reestablish a reproducible build baseline as we go.

**Comment by C-EO** [comment]
@robbear couldn't you use `pnpm install --no-frozen-lockfile`?

I think that might help. Helped me a lot

**Comment by AndreyGrek** [comment]
> @robbearне могли бы вы использовать `pnpm install --no-frozen-lockfile`? (Если у вас есть оригинальный файл блокировки)
> 
> Я думаю, это может помочь. Мне очень помог

Does not help me, I can not run the project
<img width="1462" alt="image" src="https://github.com/shuding/nextra/assets/42175541/100d7a9a-cfab-44d9-8146-8195b7401604">

**Comment by B2o5T** [comment]
Closing since I think there is nothing wrong with Nextra here
