### ISSUE TITLE
Keep .md files as the regular markdown file without trying to parse JSX

### ISSUE THREAD

**Issue by liuruenshen** [shuding/nextra#1510]
I try to use Nextra as our new internal knowledge base solution. So far, our team has maintained it in GitLab with MD files. There are tons of notations in these MD files that will be misinterpreted as JSX in Nextra. 

Can Nextra process those MD files as the regular markdown file without enabling JSX? 

I can persuade my colleagues to migrate to the new knowledge base without too much effort while encouraging them to use the enhanced markdown MDX file, so we can gradually adopt this solution.
Thanks :)

**Comment by B2o5T** [comment]
Nextra already parses .md as plain markdown, use the latest version of nextra
