### ISSUE TITLE
Nextra TypeScript API Docs Generation

### ISSUE THREAD

**Issue by n1ru4l** [shuding/nextra#1511]
It would be great for TypeScript library authors to have a built-in/additional library solution for generating neat TypeScript code definitions.

For docusaurus, we have something like https://github.com/milesj/docusaurus-plugin-typedoc-api/blob/master/packages/plugin/README.md (Demo: https://boostlib.dev/api/)

Our needs are both for single package repositories and mono repositories.

**Comment by transitive-bullshit** [comment]
Related: #1025

**Comment by transitive-bullshit** [comment]
I have a working example of this here: https://sklearn.vercel.app (see the linked github repo for details)

**Comment by n1ru4l** [comment]
Duplicate of https://github.com/shuding/nextra/issues/1025
