### ISSUE TITLE
Broken theming in _meta.json, breadcrumbs, prevLink-nextLink because of trailingSlash: true in Nextra v2.0.2 through 2.2.14 

### ISSUE THREAD

**Issue by raproid** [shuding/nextra#1514]
Updated Nextra to 2.2.14.
Now the sidebar is showing and the toc is showing anywhere, regardless if I set them to false or not (they behaved as I wanted them to before).

Bug reproduction: https://ankr-docs-9eodsjax5-ankr-docs-team.vercel.app/advanced-api/specification/ (should have no sidebar or toc).
Proof that the params are set correctly: https://github.com/Ankr-network/ankr-docs/blob/DOCS-529-update-nextra-to-latest-version/pages/advanced-api/_meta.json

**Comment by raproid** [comment]
Tried it with Nextra 2.2.5 — same result. 

Disabling only works for 1st level _meta.json in the "pages" folder. Any level deeper, in a subfolder, it stops working and the toc and sidebar are always there.

**Comment by raproid** [comment]
I singled out the problem cause: the layout gets Fd up with the "trailingSlash: true" param in the nextConfig. 
Unfortunately, I need this param on.

How can I fix the issue? Is there any way to do it right now? Or do you, guys, fix it in the next Nextra update?

**Comment by raproid** [comment]
This is the layout without trailingSlash: true
<img width="1453" alt="image" src="https://user-images.githubusercontent.com/22454517/219593122-d8328476-3db6-4cfc-b342-9db9971764fb.png">

And this is the layout with trailingSlash: true 
<img width="1453" alt="image" src="https://user-images.githubusercontent.com/22454517/219593430-005debd4-6ab3-4dc2-9650-66d6cebe9c79.png">

**Comment by raproid** [comment]
This is the layout without trailingSlash: true
<img width="1547" alt="image" src="https://user-images.githubusercontent.com/22454517/219596619-befaf3fa-dda9-4540-9488-d4e46a01749e.png">

**Comment by raproid** [comment]
And this is the layout with trailingSlash: true
<img width="1547" alt="image" src="https://user-images.githubusercontent.com/22454517/219596823-97746546-c920-4bcf-b466-34de2ae930d3.png">

**Comment by raproid** [comment]
@B2o5T

**Comment by raproid** [comment]
Also, breadcrumbs disappear because of trailingSlash: true

**Comment by raproid** [comment]
Please fix these in the next version of Nextra

**Comment by raproid** [comment]
@shuding

**Comment by raproid** [comment]
also, the prevPage and nextPage bottom navigation is broken because of trailingSlash: true

**Comment by raproid** [comment]
Or tell me how I can fix it on my side please

**Comment by raproid** [comment]
I see the trailingSlash issue has been addressed here: https://github.com/shuding/nextra/pull/1443 2 weeks ago.
The last 2.2.14 release was 3 weeks ago. 

I hope https://github.com/shuding/nextra/pull/1443 fixes all three issues I found in 2.2.14 with `trailingSlash: true`: 
1. page theming not working in _meta.json
2. breadcrumbs disappear 
3. prevPage-nexPage navigation is stuck showing always only the main page in the nextPage.

**Comment by raproid** [comment]
really looking forward to a new release that includes https://github.com/shuding/nextra/pull/1443

**Comment by B2o5T** [comment]
Please stop spam ⚠️

related issue https://github.com/shuding/nextra/issues/1425 seems it was already fixed and will be included in the next release

**Comment by raproid** [comment]
@B2o5T I spend a whole bloody day trying to find the cause of the issue. Found 3 bugs on the way. Found the cause of the issue. Reported it here. And only after found the pr that fixed it.

a day of my time, a lot of effort, 3 bugs reported. Don't you date call it spam!

**Comment by B2o5T** [comment]
@raproid Sorry for this, but this was true spam with many messages, you just made a noise
