### ISSUE TITLE
Is it possible to deploy to github pages?

### ISSUE THREAD

**Issue by FriendlyUser** [shuding/nextra#1515]
Wondering how I can deploy a nextra site to github pages, I know it can deploy to vercel, but I am looking to deploy html pages to github pages.

**Comment by C-EO** [comment]
@FriendlyUser Nextra converts the code used in the repo to html pages.

Why would you want to deploy html pages?

But to answer your question, just create a Github Action to do that or browse through the Github Actions marketplace

**Comment by FriendlyUser** [comment]
can you let me know which folder hosts the static build that can be deployed to github pages? I couldnt find it.

**Comment by C-EO** [comment]
@FriendlyUser Such a folder will exist only after you create the Github Action. The action workflow file should be stored in the `.github/workflows` directory to work.

Your deployed static website can be found on Vercel if you're using Vercel to deploy.

To locate it, just visit the latest deployment, then navigate to the `Source` tab and look through. I haven't figured a way to download the source so you'll have to copy and paste everything.

**Comment by FriendlyUser** [comment]
I am trying to run https://nextjs.org/docs/advanced-features/static-html-export#next-export

unless nextra automatically makes a set of static html pages, seems to be it just produces a next production build which can be deployed to vercel, but requires a next server to run.

I can run next run build manually, getting the errors above when trying to produce html pages with next export.

**Comment by C-EO** [comment]
Are you deploying from your local machine/PC?

**Comment by FriendlyUser** [comment]
So I can deploy from my computer or in a github action, I do not want to deploy to vercel as there is a custom domain I want to use thats tied to github already.

**Comment by C-EO** [comment]
@FriendlyUser Just create an action then.

Below are links to some resources you can use:

- https://dev.to/franciscojarceo/deploying-a-next-js-site-using-github-actions-1g1e
- https://franciscojavierarceo.github.io/post/github-actions (Practically same as above)
- https://itnext.io/deploy-next-js-apps-using-github-actions-6322261757bc (You could ignore useless details)
- https://fedeantuna.github.io/article/deploy-nextjs-app-to-github-pages

Hope this helps

**Comment by FriendlyUser** [comment]
See goes back to point 1, `next export` throw an error as I cannot configure disabling image optimization.

**Comment by C-EO** [comment]
> So I can deploy from my computer or in a github action, I do not want to deploy to vercel as there is a custom domain I want to use thats tied to github already.

You can deploy from your machine or Github Actions

**Comment by C-EO** [comment]
Can you provide a link to an example repo?

**Comment by FriendlyUser** [comment]
https://github.com/FriendlyUser/latex-diagrams-docs/blob/main/next.config.js

**Comment by C-EO** [comment]
Try this code and see if it works

```js
const withNextra = require('nextra')({
  theme: 'nextra-theme-docs',
  themeConfig: './theme.config.tsx',
})

module.exports = {
  ...withNextra(),
  images: {
    unoptimized: true,
  },
};
```

**Comment by C-EO** [comment]
Paste it in your `next.config.js` file

**Comment by FriendlyUser** [comment]
seems to work, thanks for your help.
