### ISSUE TITLE
Bug - Latex wrapping in Callouts

### ISSUE THREAD

**Issue by LuciferUchiha** [shuding/nextra#1516]
When using Latex in Callouts the wrapping does not work correctly on mobile:

It looks to me like it includes the width of the emoji for the wrapping of the latex. 

![image](https://user-images.githubusercontent.com/47121010/219479289-511fd4e8-72fe-4b1d-a964-59897bfe2429.png)

**Comment by B2o5T** [comment]
I don't see any issue here, your callout content can’t be wrapped on new line

**Comment by LuciferUchiha** [comment]
Shouldn't it then at least be horizontally scrollable?

![image](https://user-images.githubusercontent.com/47121010/219667744-71a65785-fd25-4974-8cf3-db087632ec9e.png)

**Comment by C-EO** [comment]
@B2o5T There is actually a problem. The content of the callout seems to flow outside its edges

**Comment by LuciferUchiha** [comment]
Adding `overflow-x-auto` to the outer Callout div should fix it or to the div surrounding the `{{children}}`. Depending on the wanted behavior. In my opinion, callouts should be able to have titles here mimicked with "Examples" in the body of the callout which would then stay with the emoji and the lower content should scroll.

**Comment by B2o5T** [comment]
Feel free to send a pr
