### ISSUE TITLE
Components not rendering / imports showing as markdown 

### ISSUE THREAD

**Issue by JeffjHoyt** [shuding/nextra#1517]
These components were working as of two weeks ago. Now all of the components are not working and all of the imported files are showing as regular markdown. Example picture below.

<img width="590" alt="Screen Shot 2023-02-16 at 4 40 51 PM" src="https://user-images.githubusercontent.com/101358655/219493312-cea3a60f-dfec-4bb9-9240-e327ab5b2867.png">

**Comment by B2o5T** [comment]
Seems like you use `.md` extension, change it to mdx. Md files are now treated as plain markdown

**Comment by JeffjHoyt** [comment]
Thank you!
