### ISSUE TITLE
[Style] `nextra-theme-docs` main `article` doesn't grow to full width correctly

### ISSUE THREAD

**Issue by ndom91** [shuding/nextra#1523]
Pages with only short strings will not cause the main `article` to grow to the max available size. For example, check out these examples:

### Shrunk width example

![image](https://user-images.githubusercontent.com/7415984/219875194-a7fe604e-2274-4bf2-80df-3c7c4d470bfc.png)

### Full width example

![image](https://user-images.githubusercontent.com/7415984/219875417-9a15fb66-d77d-4d74-9278-c9780a1984a7.png)

[Here](https://github.com/shuding/nextra/blob/792e82dd4a32813e1acd538cb78191ba019803db/packages/nextra-theme-docs/src/index.tsx#L194) we have `flex-grow: 1`, but thats designed for growing into the available height, right? As its in a flex-column context. So in addition to a `nx-max-w-[90rem]`, what about a simple `width: 100%`? Seems to fix it in my project's use of Nextra :+1:

**Comment by ndom91** [comment]
Put up a quick PR if this makes sense to you too :blush: 

https://github.com/shuding/nextra/pull/1525

**Comment by B2o5T** [comment]
Can you send an example of page with short content?

> [Here](https://github.com/shuding/nextra/blob/792e82dd4a32813e1acd538cb78191ba019803db/packages/nextra-theme-docs/src/index.tsx#L194) we have flex-grow: 1

i don't see flex-grow: 1

**Comment by ndom91** [comment]
Ah yeah sorry, wasn't directly in the markup there. Look here: 

![image.png](https://volta.s3.fr-par.scw.cloud/image_4e6878aaea.png)

And thats in a flex column context (from the parent `<div dir="ltr"> ..`

**Comment by ndom91** [comment]
Thats clearly way too small, no? Here is that same page without the highlighting from devtools:

![image](https://user-images.githubusercontent.com/7415984/220405274-ff91b449-65cf-493f-b159-a12a000151c8.png)

And heres that same page with `width: 100%` applied to that same `div`. This is the normal width of every other page which has content wide enough to grow the middle content `article` to full width

![image](https://user-images.githubusercontent.com/7415984/220405375-7e5326a7-d4fc-468b-902f-bed0987e78c2.png)

**Comment by ndom91** [comment]
Ahh im sorry, I think a lot of this is due to customizations we made that I wasn't aware of. Closing this for now :sweat_smile:
