### ISSUE TITLE
Bug/Regression - cusdis comments no longer appear

### ISSUE THREAD

**Issue by scowalt** [shuding/nextra#1529]
With `nextra@2.2.14` and `nextra-theme-blog@2.2.14`, cusdis comments won't load. [Demo repo](https://github.com/scowalt/nextra-theme-blog-cusdis-bug) | [Demo site](https://nextra-theme-blog-cusdis-bug.vercel.app/post)
<img width="691" alt="image" src="https://user-images.githubusercontent.com/1100550/219978700-62143fd0-ca75-4039-b866-c4ff242907fa.png">

With the same code with `nextra@2.0.0-beta.5` and `nextra-theme-blog@0.1.6`, cusdis comments load. [Demo repo](https://github.com/scowalt/nextra-theme-blog-cusdis-bug/tree/working) | [Demo site](https://nextra-theme-blog-cusdis-bug-q6r4.vercel.app/post)
<img width="775" alt="image" src="https://user-images.githubusercontent.com/1100550/219978792-59f4a59c-00a4-4fb5-a01e-9e287bd179b1.png">

I wanted to try to bisect this, bug I couldn't figure out how to do it without hitting other bugs.

**Comment by B2o5T** [comment]
You need to install react-cusdis https://github.com/shuding/nextra/blob/863a750eff9e29f3d1ab113797b97e81225570db/packages/nextra-theme-blog/package.json#L61

**Comment by scowalt** [comment]
> You need to install react-cusdis
> 
> https://github.com/shuding/nextra/blob/863a750eff9e29f3d1ab113797b97e81225570db/packages/nextra-theme-blog/package.json#L61

I added `react-cusdis` and that didn't fix the bug. I updated the repro site and repo with this change

**Comment by C-EO** [comment]
Are u using `pnpm` to run your blog?

**Comment by scowalt** [comment]
> Are u using `pnpm` to run your blog?

In the example I'm using yarn, but I believe both my example and `pnpm` use Plug'n'Play module resolution

**Comment by BlackBerry009** [comment]
> > You need to install react-cusdis
> > https://github.com/shuding/nextra/blob/863a750eff9e29f3d1ab113797b97e81225570db/packages/nextra-theme-blog/package.json#L61
> 
> I added `react-cusdis` and that didn't fix the bug. I updated the repro site and repo with this change

you can use cusdis like this or custom whatever commets you like

```jsx
const Cusdis = dynamic(() => import("nextra-theme-blog/cusdis"));

export default {
  cusdis: {
    appId: '[appId]',
  },
  comments: <Cusdis />
}
```

**Comment by B2o5T** [comment]
@BlackBerry009 already replied

for anyone occurred this issue see [examples/blog](https://github.com/shuding/nextra/tree/main/examples/blog) how to use cusdis components https://github.com/shuding/nextra/blob/main/examples/blog/theme.config.jsx#L5
