### ISSUE TITLE
Headings auto links and internalization

### ISSUE THREAD

**Issue by alex-flea** [shuding/nextra#1537]
Autolinks for headings are great but they create one problem for the internalization. As the header is translated to another language you are not able to use manual internal markdown linking.

For example, let's suppose we have a header

page1

```
  ## Example
```

page2

```
  [Veamos un ejemplo](/page1#example)
```

It'll work great for one language but it'll break on localized content as Example will convert into Ejemplo in Spanish:

```
  ## Ejemplo
```

and the link on page2 will stop working:

```
  [Let's see an example](/page1#example)
```

Is there an option to manually define heading links?

**Comment by B2o5T** [comment]
Currently, it's not possible, there was an attempt here https://github.com/shuding/nextra/pull/553, PR welcome

**Comment by B2o5T** [comment]
implemented by https://github.com/shuding/nextra/pull/1645
