### ISSUE TITLE
Not able to set dark mode only

### ISSUE THREAD

**Issue by niikeec** [shuding/nextra#1538]
With this recent change [da585a8](https://github.com/shuding/nextra/commit/da585a82af9d00b1268939ab0aefa8ab23a5dc4f), you can't have a site in dark mode only without the `ThemeSwitch` being displayed as `darkTheme: false` forces light mode.

I would be down to fill a PR.

**Comment by B2o5T** [comment]
I made a rollback of https://github.com/shuding/nextra/commit/da585a82af9d00b1268939ab0aefa8ab23a5dc4f
