### ISSUE TITLE
Headings in nested content not included in TOC

### ISSUE THREAD

**Issue by WCByrne** [shuding/nextra#1540]
To better organize our project, I started breaking up pages in to smaller mdx files but I noticed that any headings are not rendered in the table of contents. 

For example, in a page I might have:
```mdx
import { UploadFile } from "../components/uploadFile.mdx";

# Creating Content

Create new content via out API...

<UploadFile />
```

If `uploadFile.mdx` contains headings, such as the following, they are not included in the TOC.
```mdx
## Uploading a file

To upload a file do this...
```

Any workarounds for this?

**Comment by B2o5T** [comment]
This is a known limitation, a similar issue to https://github.com/facebook/docusaurus/issues/3915

Unfortunately, there is no workaround at the moment

**Comment by WCByrne** [comment]
Copy that. Thanks.

**Comment by B2o5T** [comment]
@WCByrne happy to say that I fixed this confusing behaviour!

<img width="155" alt="image" src="https://github.com/shuding/nextra/assets/7361780/681eeabc-5a0c-41dd-9c25-fa16f22dcca1">
<img width="248" alt="image" src="https://github.com/shuding/nextra/assets/7361780/72e011f9-9ec3-481a-895d-7e7881e773c1">
<img width="263" alt="image" src="https://github.com/shuding/nextra/assets/7361780/3e81de01-2213-4492-85ba-8c40b4407a58">
<img width="1100" alt="image" src="https://github.com/shuding/nextra/assets/7361780/fb00441f-cd65-4d2c-912c-b3555cba09bb">

**Comment by WCByrne** [comment]
Great! Thank you.
