### ISSUE TITLE
Feedback for “Theme Configuration”

### ISSUE THREAD

**Issue by siddharthborderwala** [shuding/nextra#1541]
@shuding I love nextra, it is a truly amazing tool for building MDX powered sites. I had a query about hosting nextra-theme-docs site on GitHub pages.

Hosting on GitHub pages means that the static docs will be visible at a sub-directory. For e.g. if the repository is `siddharthborderwala/awesome-docs`, then I can view it on `https://siddharthborderwala.github.io/awesome-docs`.

Is there an existing solution for this?

Thank you for your time and for creating this amazing tool!

**Comment by C-EO** [comment]
@siddharthborderwala Firstly, please change your title to be more appropriate. Secondly, there is a way.

**Comment by siddharthborderwala** [comment]
Aah, I'm sorry should have added a more appropriate title. Thanks for the response, I found out the correct way to do it.
