### ISSUE TITLE
Feedback for “Theme Configuration”, 404 reference

### ISSUE THREAD

**Issue by Hikachhu** [shuding/nextra#1549]
Hello everyone :)

In this section: https://nextra.site/docs/docs-theme/theme-configuration#dynamic-tags-based-on-page
The link to the api section for **useConfig** sends to a 404 error page

I searched the site and the github but I can't find the page that would describe the **useConfig**

Has it been moved? Renamed? Completely deleted and redone? Does anyone know please?

**Comment by B2o5T** [comment]
duplicate https://github.com/shuding/nextra/issues/1139
