### ISSUE TITLE
Markdown Tables Broke

### ISSUE THREAD

**Issue by RayhanADev** [shuding/nextra#155]
I have a development server running [here](https://docs.replapiit.repl.co/) and as you can see on the landing the table is broken. In a previous build [here](https://replapi-it.js.org/) however the table is working fine. My guess is something broke in one of your markdown parsers and now tables are not rendering properly.

**Comment by shuding** [comment]
Closing as duplicate of #127

**Comment by RayhanADev** [comment]
Oops my bad.
