### ISSUE TITLE
How to force dark theme

### ISSUE THREAD

**Issue by equinusocio** [shuding/nextra#1550]
The latest update introduced a forced light theme, without providing a way to force a dark theme without enabling the theme switcher as before.

❌ Setting `darkMode: false` the theme is forced to Light without the switcher
❌ Setting `darkMode: true` the theme is forced to Dark but with the theme switcher enabled.

How we can force the dark theme as the default and only theme without enabling the switcher? before it was working by setting `darkMode: false`, now the latest patch introduced a breaking change.

**Comment by B2o5T** [comment]
I made a rollback PR https://github.com/shuding/nextra/pull/1551 try 2.2.16 version

**Comment by equinusocio** [comment]
Thanks! My sugestion is to revisit the config api by adding specific keys like `defualtTheme` and `enableThemeSwitcher`

**Comment by equinusocio** [comment]
Just saw there is a `nextThemes.forcedTheme' option. If this is going to work with the previous change it's, but we need control over enabling or not the theme switcher.
