### ISSUE TITLE
Page Responsiveness Error for Cards Component

### ISSUE THREAD

**Issue by C-EO** [shuding/nextra#1556]
@B2o5T  I encounter a responsiveness issue for the cards component on devices with a `1920 x 1080 px` display.

This happens at 100% zoom in most browsers. It reverts to normal if I scale the zoom to 90% or 110%+ and the issue repeats again at 80% zoom downwards

# Screenshots

**100% zoom**:
![image](https://user-images.githubusercontent.com/85847352/221351630-fd1fd9e4-2742-470c-9b0c-85282640b6f5.png)

**90% zoom**:
![image](https://user-images.githubusercontent.com/85847352/221351701-8342bdf2-4924-4542-881a-f70c784a7740.png)

**110% zoom**:
![image](https://user-images.githubusercontent.com/85847352/221351739-5c649a6b-d59b-4735-ad92-81875d7274ab.png)

**80% zoom**:
![image](https://user-images.githubusercontent.com/85847352/221351716-dc468400-218c-45f7-8ca7-02ef94be442c.png)

**Comment by B2o5T** [comment]
You need to set https://github.com/shuding/nextra/blob/73241b3fee58f0318e9349a5eb7650a7cd55a4e3/docs/pages/showcase.mdx?plain=1#L8 to 2

**Comment by C-EO** [comment]
Thanks
