### ISSUE TITLE
Language switching issue with links containing anchor tags

### ISSUE THREAD

**Issue by whhjdi** [shuding/nextra#1561]
### What's the problem 
Unable to switch to Chinese language after opening an English page, clicking on an anchor tag, refreshing the page, and attempting to switch to Chinese language. 

https://user-images.githubusercontent.com/22634897/221399499-5c7d9e91-4ae4-4ecb-ba07-08b207098113.mp4

### How to reproduce
1. opening an English page, clicking on an anchor tag
2. refreshing the page
3. switch to Chinese language

[demo repo](https://github.com/whhjdi/nextra-demo)

**Comment by aminggoodboy** [comment]
After setting the default Chinese language, each document should be modified to. zh.md, right?

**Comment by dimaMachina** [comment]
should be fixed in Nextra v3, try to upgrade
