### ISSUE TITLE
[nextra-theme-blog] Add transitioning between dark and light theme

### ISSUE THREAD

**Issue by KodiCraft** [shuding/nextra#1569]
Currently, the transition between light and dark theme is instantaneous which can be rather uncomfortable for users. CSS supports transitioning between colors smoothly using the `transition` property, and using it for the transition could be helpful for accessibility and user comfort.

**Comment by B2o5T** [comment]
You are wrong, blog theme has transition, docs theme not

https://github.com/shuding/nextra/blob/6665f7e10133f2a20c395b3c99fdfc0a3af4b02d/packages/nextra-theme-blog/src/index.tsx#L45

https://github.com/shuding/nextra/blob/6665f7e10133f2a20c395b3c99fdfc0a3af4b02d/packages/nextra-theme-docs/src/contexts/config.tsx#L116

**Comment by lacymorrow** [comment]
Can this be enabled easily in the docs theme?
