### ISSUE TITLE
Broken navbars after build

### ISSUE THREAD

**Issue by katsuki-yuri** [shuding/nextra#1570]
When running project on development, everything is working fine. However, as soon as I build and start the project or just deploy it to vercel, navbars break. I tried to clear caches and data but still doesn't help. 

**Navigation:**

![Screenshot 2023-02-28 at 10 39 12](https://user-images.githubusercontent.com/54666588/221764906-e1de7a9d-7850-49b9-975f-66d5b0508b19.png)

![Screenshot 2023-02-28 at 10 39 16](https://user-images.githubusercontent.com/54666588/221764854-ae02c6ec-0abd-4fd7-9acd-98042395c017.png)

**Navbar:**

![Screenshot 2023-02-28 at 10 46 10](https://user-images.githubusercontent.com/54666588/221765023-fd54924d-2824-43ff-9ea8-2e8790c24920.png)

![Screenshot 2023-02-28 at 10 46 17](https://user-images.githubusercontent.com/54666588/221765151-5f978423-e399-4e5f-85a4-a79be8856e6a.png)

**Comment by B2o5T** [comment]
Maybe this solution https://github.com/shuding/nextra/issues/1564#issuecomment-1447419595 will help you?

**Comment by katsuki-yuri** [comment]
> 

Resolved the issue! Many thanks!!
