### ISSUE TITLE
Warning: Prop `href` did not match. Server: "\\" Client: "/"

### ISSUE THREAD

**Issue by surjithctly** [shuding/nextra#158]
I'm getting this error on latest Next.js (10.2.0), I'm not sure because of this, the next navigation does not work properly.

![image](https://user-images.githubusercontent.com/1884712/118518947-83d1c800-b6ed-11eb-90d9-fa298c767005.png)

**Comment by B2o5T** [comment]
Hi @surjithctly do you still have this issue?
