### ISSUE TITLE
[nextra-theme-doc] Inconsistent package manager commands on Get Started

### ISSUE THREAD

**Issue by colbyfayock** [shuding/nextra#1583]
Page: https://nextra.site/docs/docs-theme/start

The final `pnpm next` command at the end doesn't switch depending on the package manager context. Or at least it doesn't include the ability to change the package manager like the first step.

<img width="858" alt="image" src="https://user-images.githubusercontent.com/1045274/222315391-5d76a908-984d-4a11-a23b-ccfcd6e8a3ab.png">

<img width="869" alt="image" src="https://user-images.githubusercontent.com/1045274/222315416-a62d38a0-dfb2-44ce-a4af-11418b95ae85.png">

**Comment by B2o5T** [comment]
Do you have any thoughts on how we can improve it?

**Comment by Complexlity** [comment]
One way to make it clearer would be to add a 5th section `#Updating Scripts` where it shows adding the necessary `next` scripts for development and then after that, updating the command to run a local server. 
The installation part makes use of a `Tabs` component. Changing the  `And run the pnpm next..` to also use `Tabs` component would accommodate both npm and yarn would do

**Comment by colbyfayock** [comment]
> The installation part makes use of a Tabs component. Changing the And run the pnpm next.. to also use Tabs component would accommodate both npm and yarn

this is pretty much what i had in mind to fix the immediate issue

> One way to make it clearer would be to add a 5th section #Updating Scripts where it shows adding the necessary next scripts to package.json for local development and then after that, updating the command to run the server.

a bit bigger scope of a change than i was originally thinking but having more guidance never hurts

out of curiosity, was it intentional to not use a starter template for this project?

```
pnpm create next-app -e https://github.com/path/to/nextra/docs
```

Would make getting up and running a lot simpler. I thought I remembered seeing this before the reworked docs but i'm not 100% sure on that.

**Comment by B2o5T** [comment]
Closed by https://github.com/shuding/nextra/pull/1998
