### ISSUE TITLE
Is there a word-wrap functionality for code blocks when viewing in desktop?

### ISSUE THREAD

**Issue by sourabhxyz** [shuding/nextra#1585]

**Comment by sourabhxyz** [comment]
I could see a mention of this for mobile but would love to see it for desktop as well.

**Comment by B2o5T** [comment]
this feature is available only for mobile

**Comment by sourabhxyz** [comment]
@B2o5T I see, thanks. Is there a plan to bring it for desktop as well? I in particular feel it would be helpful & docusaurus has it too.

**Comment by B2o5T** [comment]
No plans, sorry, lack of interest
