### ISSUE TITLE
App crashes whenever I change any _meta.json file

### ISSUE THREAD

**Issue by dserranog1** [shuding/nextra#1587]
As the title states, when creating/editing/deleting any _meta.json file the app crashses and I must reload in order for it to be functional again.

Let's say I have /pages/section-1 and pages/section-2

With just the act of creating a /_meta.json a saving it as an empty json the app automatically crashes. Happens also if I update it with, for example:

```json 
{
"section-1" : "Section 1",
"section-2" : "Section 2"
 }
```

and save. I need to reload the page in order for it to work again.

**Comment by dserranog1** [comment]
https://github.com/dserranog1/nextra-crash

I just also found out that just moving, creating or deleting a .md file, or editing the theme.config.tsx crashes the app, in addition to what I already mention. @C-EO

**Comment by B2o5T** [comment]
should be fixed in `2.2.17`
