### ISSUE TITLE
Custom theme + MDX components

### ISSUE THREAD

**Issue by irangarcia** [shuding/nextra#1592]
It's possible to provide a custom theme instead the `nextra-theme-docs`/`nextra-theme-blog` and at the same time provide an object with the MDX components on the `theme.config.tsx`? Or I have to create a custom MDX provider and deal with the components myself

**Comment by SonMooSans** [comment]
Yes, there's a Mdx provider exported from the Nextra core 
```ts
import { MDXProvider } from 'nextra/mdx'
```

For example, [here](https://github.com/shuding/nextra/blob/68804aebf7499ffc34d7fe8a5fb8078a6c54d3cf/packages/nextra-theme-docs/src/index.tsx#L225) is how docs theme use the mdx provider

**Comment by B2o5T** [comment]
@SonMooSans gave a response
