### ISSUE TITLE
The key shortcut in the search component always shows `Esc` when having search value + loses focus

### ISSUE THREAD

**Issue by SukkaW** [shuding/nextra#1606]
**Reproduction**

Open https://nextra.site/, the search input shows `Command + K` for key shortcut:

<img width="620" alt="image" src="https://user-images.githubusercontent.com/40715044/223315397-ad89d8f0-2815-4968-88e2-5deb70548dcd.png">

Use <kbd>Command</kbd> + <kbd>K</kbd> to focus on the search input and type something, the search input shows `Esc`:

<img width="629" alt="image" src="https://user-images.githubusercontent.com/40715044/223315516-88b6dc4e-9aea-4685-9a8b-288c90f88dd3.png">

Manually use the mouse to let search input lose focus, search input still shows `Esc`.

<img width="628" alt="image" src="https://user-images.githubusercontent.com/40715044/223315604-5fc19017-b348-4db8-9eb3-154c7a9d8ea3.png">

But without search input focus, I can't use <kbd>Esc</kbd> to reset the search.

**Possible way to fix**

- Always show `Command + K` when search input loses focus
- Allows `Esc` to reset search value even when search input loses focus

**Comment by SukkaW** [comment]
@B2o5T I'd like to create a PR to fix this, but which behavior do you prefer though?

**Comment by B2o5T** [comment]
> Always show Command + K when search input loses focus

Seems the best approach

PR always welcome, thanks!
