### ISSUE TITLE
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by jeffreys-cat** [shuding/nextra#1618]
I have more than 1000 md files. when I build with nextra, I got ```JavaScript heap out of memory``` error

The codebase is here [selectdb-docs-template](https://github.com/jeffreys-cat/selectdb-docs-template)

![image](https://user-images.githubusercontent.com/11832969/223907647-6dfc7c3f-ad0e-4656-b900-91ca5a42c77b.png)

**Comment by jeffreys-cat** [comment]
Add ```export NODE_OPTIONS='--max_old_space_size=8192' ``` it works, But ```Vercel deploy``` still failed.

**Comment by B2o5T** [comment]
Try to use _app.mdx

**Comment by jeffreys-cat** [comment]
@B2o5T It works! thank you!
