### ISSUE TITLE
Hide headings from TOC Sidebar 

### ISSUE THREAD

**Issue by niteshsrivats** [shuding/nextra#1619]
Is there a way to hide a heading from the TOC sidebar?

For example, on a page I might have:
```
### Node

#### Properties

type: A | B | C

##### Additional properties for type C

Lorem ipsum dolor sit amet...
```
But I might not want the H5 heading in my sidebar

# Request

I add a /ignore flag that doesn't include my H5 from the TOC sidebar
```
### Node

#### Properties

type: A | B | C

##### Additional Properties for type C /ignore

Lorem ipsum dolor sit amet...
```
# Current Workaround

Copying the CSS classes being applied into a HTML tag.
```
### Node

#### Properties

type: A | B | C

<h5 className={'nx-font-semibold nx-tracking-tight nx-text-slate-900 dark:nx-text-slate-100 nx-mt-8 nx-text-lg'}>
Additional Properties for type C
</h5>

Lorem ipsum dolor sit amet...
```

**Comment by B2o5T** [comment]
you can just hide them with css
```css
.nextra-toc a.ltr:nx-ml-12,
.nextra-toc a.ltr:nx-ml-16 {
  display: none;
}
```

**Comment by B2o5T** [comment]
or for advanced usage use follow function https://github.com/nodejs/nodejs.org/blob/e7251994629c9fa0553216e74f03620753df4ea4/next.config.mjs#L11-L18
to filter `pageOpts.headings` to exclude headings with depth 5 and 6
