### ISSUE TITLE
Improve installation guide 

### ISSUE THREAD

**Issue by Complexlity** [shuding/nextra#1622]
On the [docs theme](https://nextra.site/docs/docs-theme/start) (and blog theme pages)
![image](https://user-images.githubusercontent.com/105590967/224155118-d2c4c15b-e7bf-49d3-917f-1a62162d35da.png)
It shows to run `pnpm next` to start developing but some people may have installed using npm or yarn

Suggestion
An update to the docs on adding `scripts` to package.json similar to the one below
![image](https://user-images.githubusercontent.com/105590967/224158715-35efaf59-d489-42ea-b5eb-9dbd051715c1.png)
and some instructions in the similar `Tabs` format to start dev server using either pnpm, npm or yarn would make it clearer to start a new next project

**Comment by C-EO** [comment]
@Complexlity npm provides support for other package managers like Yarn and pnpm. Read their docs on how to get at it.

**Comment by Complexlity** [comment]
Hello. When you say `support`, you mean they could install pnpm or yarn from npm?  If this is the case, I do know that but the guide doesn't state to install them. 
Coming from the beginner point of view (and anyone who only has npm installed on their machine) , running `pnpm next` would return `command not found` as they would not have pnpm installed in their machine and the guide didn't explicitly say to install pnpm.

**Comment by B2o5T** [comment]
duplicate https://github.com/shuding/nextra/issues/1583
