### ISSUE TITLE
Dark mode only

### ISSUE THREAD

**Issue by williamlmao** [shuding/nextra#1630]
Currently there is an option to hide the dark mode switcher and force light mode only. 

https://nextra.site/docs/docs-theme/theme-configuration#dark-mode-and-themes

Would love to be able to force dark mode only and hide the theme switcher.

**Comment by B2o5T** [comment]
use `nextThemes.forcedTheme` option in your theme.config to force dark/light theme, you could contribute to docs!

more info on next-themes https://github.com/pacocoursey/next-themes#themeprovider
