### ISSUE TITLE
Feedback: using _app.mdx vs _app.tsx is weird and more error prone

### ISSUE THREAD

**Issue by transitive-bullshit** [shuding/nextra#1632]
I got my use case working with `_app.tsx`, but after https://github.com/shuding/nextra/pull/1448, the guidance and console logs tell you to use `_app.mdx`.

This feels really weird to me as an end user. I tried using `_app.mdx` and kept running into weird transpilation issues, and all existing docs and examples from the greater Next.js ecosystem use `_app.tsx`.

For context, I'm not using `mdx` at all for https://sklearn.vercel.app (solely `md`).

My recommendation would be to find a way to have `_app.tsx` / `_document.tsx` be the default methods for injecting custom JS/TS.

**Comment by B2o5T** [comment]
Please provide your reproduction of weird behavior with _app.mdx

**Comment by transitive-bullshit** [comment]
This is not a bug report; rather just general feedback.

As for a repro:

```
git clone git@github.com:transitive-bullshit/scikit-learn-ts.git
cd scikit-learn-ts
git checkout d3adcf4bccd8010d4edae6e7bc487d545f7c46ff # current HEAD
pnpm i
cd docs
pnpm build # builds fine with pages/_app.tsx
mv pages/_app.tsx pages/_app.mdx
pnpm build # obfuscated error with the mdx version
```

<img width="893" alt="CleanShot 2023-03-13 at 12 26 18@2x" src="https://user-images.githubusercontent.com/552829/224779870-0e95ab65-5b78-4e02-bed4-4ba355a8180c.png">

**Comment by transitive-bullshit** [comment]
Thanks @B2o5T. Removing the TS types from the mdx file makes the build work.

My original feedback still stands, however. I'd greatly prefer to use `_app.tsx` / `_document.tsx` for editor support / familiarity / tooling / existing code / typescript support / examples / etc.

Really appreciate the quick response btw – thanks for all your hard work! 🙏 💕

**Comment by B2o5T** [comment]
We'll try to improve it in Nextra 3

**Comment by transitive-bullshit** [comment]
Thanks @B2o5T 🙏

**Comment by prisis** [comment]
One more point to allow `_app.tsx` would be to allow for example https://github.com/dequelabs/axe-core with the current mdx, i can not use it.
