### ISSUE TITLE
Medium number of doc pages results in OOM

### ISSUE THREAD

**Issue by transitive-bullshit** [shuding/nextra#1633]
Related: https://github.com/shuding/nextra/issues/1131 and https://github.com/shuding/nextra/issues/1543

For https://sklearn.vercel.app/, I'm auto-generating ~257 TS classes from Python, and then using `typedoc` to auto-generate markdown docs to use with `nextra`.

In general, this works really well, but I ran into some major bumps along the way.

The first version generated ~1200 files with lots of intermediate `interface` types that I ended up having to inline because `next build` would OOM similar to the previously linked issues. I got it working by removing all of these intermediate types & files, but it still uses a lot more memory and CPU while building than I'd expect (e.g., I'm the author of https://github.com/transitive-bullshit/nextjs-notion-starter-kit, and am used to building pretty large Next.js projects based on dynamic Notion workspaces).

I was not using any `_app` or `_document` overrides with these OOMs, and I had disabled `flexsearch` in my `next.config.mjs` because it was incredibly slow at runtime and didn't rank top-level file results ahead of sub-fields.

Anyhow, I'm opening this issue because this is still a major pain point, and I'm honestly not sure what `nextra` is doing under the hood to spin its wheels so much when all of the content is `md` files (no `mdx`). Definitely seems like an algorithmic issue somewhere in `nextra` or `nextra-theme-docs`.

Thanks! 🙏

**Comment by B2o5T** [comment]
All memory issues for large number of files should be solved with _app.mdx

**Comment by transitive-bullshit** [comment]
@B2o5T I wasn't using any `_app.tsx` / `_app.mdx`. This is unrelated to that change.

**Comment by B2o5T** [comment]
It’s very related, in _app.mdx Nextra stores generated pageMap for building sidebar, toc and navbar links

**Comment by transitive-bullshit** [comment]
Hmmm, so if I don't provide any `_app.mdx`, the default solution just OOMs for a few hundred markdown files?

Wouldn't the default have to generate an `_app` for next.js and store the `pageMap` there? Again, this is for a previous version of the repo which didn't have any `_app.*` overrides and was just using the default `nextra` generated next.js files.

**Comment by B2o5T** [comment]
> so if I don't provide any _app.mdx, the default solution OOMs for a few hundred markdown files?

the more pages you have the bigger pageMap you'll have, without _app.mdx pageMap is included in each compiled md/mdx page

**Comment by B2o5T** [comment]
duplicate https://github.com/shuding/nextra/issues/1543
