### ISSUE TITLE
Is config.darkTheme updating properly?

### ISSUE THREAD

**Issue by sinclairnick** [shuding/nextra#1636]
I'm trying to adapt the homepage logo according to dark mode being on or off, however, the `config.darkMode` property never updates. Also, `prefer-color-scheme` doesn't seem to behave as expected either.

Am I missing something here, or is this a bug?

```tsx
const config = useConfig()
// config.darkMode never updates
```

**Comment by B2o5T** [comment]
config.darkMode is your setting for show or hide the dark mode toggle button.

use below code for checking current theme
https://github.com/shuding/nextra/blob/4736e2fd355e975c2c55385f5005b9af0ec29112/packages/nextra-theme-blog/src/theme-switch.tsx#L8

**Comment by sinclairnick** [comment]
Wow my bad. Thanks for the heads up 👍
