### ISSUE TITLE
useConfig API link is broken.

### ISSUE THREAD

**Issue by NafiurSiddiqui** [shuding/nextra#1640]
The link `https://nextra.site/docs/docs-theme/api/use-config` is not found. Did not find any such directory there either in the codebase. 

I come across this while reading for dynamic tags based on pages [here](https://nextra.site/docs/docs-theme/theme-configuration#dynamic-tags-based-on-page).

**Comment by B2o5T** [comment]
https://github.com/shuding/nextra/issues/1139#issuecomment-1368197184
