### ISSUE TITLE
Export the docs as PDF

### ISSUE THREAD

**Issue by abhaytalreja** [shuding/nextra#1641]
Is there a way to export the documents created as pages in a pdf. 

In the context of writing a book of sorts, it will be easy to just publish this and have a pdf version.

This is more of a feature request than an issue.

**Comment by C-EO** [comment]
@B2o5T This is a duplicate of  #1560

**Comment by abhaytalreja** [comment]
@C-EO Slightly different but can be merged under the same topic. I am looking to generate the entire thing into a pdf book. I will close this ticket and we track it with #1560
