### ISSUE TITLE
Bug: Testing problems when importing `nextra/x`

### ISSUE THREAD

**Issue by irangarcia** [shuding/nextra#1647]
Jest fails when trying to run test that imports a component from `nextra/mdx`. 

The sames happens in another file that I import `getAllPages` from  `nextra/context`

Error: 
```
 ● Test suite failed to run

    Cannot find module 'nextra/mdx' from 'src/components/MdxProvider/index.tsx'

    Require stack:
      src/components/MdxProvider/index.tsx
      src/components/MdxProvider/index.test.tsx
```

MRE:

MdxProvider/index.tsx
```tsx 
import {MDXProvider as NextraMdxProvider} from 'nextra/mdx';

const CustomLink = ({href}) => <Link href={href} />;

const components = {
    a: CustomLink
    ..... // other components
}

export const MdxProvider = ({children}) => (
    <NextraMdxProvider components={components}>
        {children}
    </NextraMdxProvider>
);
```

**Comment by B2o5T** [comment]
PR with fix welcome

**Comment by irangarcia** [comment]
I'd like to help! Could you give me a hint where/what file/thing I need to adjust?

**Comment by B2o5T** [comment]
Idk, it is up to you to find out why you have this problem and how this can be fixed..

**Comment by promer94** [comment]
Jest used to have a problem for supporting subpath export. 
You might need to upgrade your jest verion
https://github.com/facebook/jest/issues/12270#issuecomment-1111533936
