### ISSUE TITLE
Search hangs and crashes tab after runaway heap allocation

### ISSUE THREAD

**Issue by kshehadeh** [shuding/nextra#1655]
We have created a nextra documentation site using the latest version of Nextra (2.2.19).  When our documentation was relatively small and organized with little nesting, we didn't have any issue with search.  Once we started adding more folder structure, we started seeing this problem:  when the user starts typing in the search input, the page immediately hangs and eventually crashes the tab.  

I would be happy to share the index file that is being generated.   But I'm not sure exactly which change caused the problem so I'm not sure yet how to reproduce with a simple example.

**Comment by B2o5T** [comment]
Please provide reproduction

**Comment by B2o5T** [comment]
should be fixed by https://github.com/shuding/nextra/pull/2207, feel free to ask reopen and share index file if you'll have still this issue!
