### ISSUE TITLE
[Nextra-theme-docs] _meta.json content remains unchanged after saving.

### ISSUE THREAD

**Issue by tuanductran** [shuding/nextra#1658]
![Screen Shot 2023-03-19 at 17 27 38](https://user-images.githubusercontent.com/69758022/226169333-bb1c48be-fea0-4e45-9134-f78194893699.png)

After saving, I need to reload localhost to see the updated content.

![Screen Shot 2023-03-19 at 17 30 04](https://user-images.githubusercontent.com/69758022/226169459-02afdcd0-0e1f-4ab7-ba4c-1331861a4a51.png)

**Comment by C-EO** [comment]
@B2o5T this is happening to me also

**Comment by dimaMachina** [comment]
Should be fixed in Nextra 3
