### ISSUE TITLE
Can I visit the syntax tree of mdx  in jsx?

### ISSUE THREAD

**Issue by hoonliu** [shuding/nextra#1665]
I'm trying to implement a Playground component like React Live by myself.
Is there a way to visit the source syntax tree?

**Comment by irangarcia** [comment]
Take a look at the [MDX playground](https://mdxjs.com/playground/)

**Comment by irangarcia** [comment]
Maybe [MDX playground](https://mdxjs.com/playground/)?

**Comment by B2o5T** [comment]
nothing to add, thanks @irangarcia !
