### ISSUE TITLE
[theme-blog] Export built-in components

### ISSUE THREAD

**Issue by numToStr** [shuding/nextra#1676]
### Problem

Currently, only docs-theme exports [built-in components](https://nextra.site/docs/docs-theme/built-ins) but blog-theme does not.

### Solution

Export those built-in components from `nextra/components/{component}` so that blog and docs theme can import and use those components.

---

There could be an argument that you could use any UI library if you need components, but I think those components can be a nice option for simple blogs that doesn't need any fancy UI.

**Comment by B2o5T** [comment]
In the next release nextra will export `<Callout />` component, thank to @tristandubbeld, also he wanted to move another components too

**Comment by tristandubbeld** [comment]
Working on this in #1905!
