### ISSUE TITLE
Reversing the sidebar (higher number first) and front matters

### ISSUE THREAD

**Issue by anaclumos** [shuding/nextra#1679]
- I am looking to reverse the order of the sidebar so that the higher numbers are displayed first.
- In addition, I would like to understand what kinds of front matters are supported, which doesn't seem documented in the docs.

**Comment by C-EO** [comment]
By reversing, please provide an example for better explanation

**Comment by anaclumos** [comment]
Sidebar elements in Z-A order. I know I can use `_meta.json` to set manual orders, but all I need is reversing the order so I thought there could be a better solution like `reverse: true`

**Comment by B2o5T** [comment]
you can use `_meta.js` instead https://github.com/shuding/nextra/issues/1455#issuecomment-1416831614 by generating right order by yourself

I am not plan to add such as option
