### ISSUE TITLE
Wrong Sidebar Behavior (_meta.json)

### ISSUE THREAD

**Issue by anaclumos** [shuding/nextra#1680]
I have this:

```json
{
  "12": "12",
  "11": "11",
  "10": "10",
  "09": "09",
  "08": "08",
  "07": "07",
  "06": "06",
  "05": "05",
  "04": "04",
  "03": "03",
  "02": "02",
  "01": "01"
}
```

But the sidebar is rendered as following:

![image](https://user-images.githubusercontent.com/31657298/227813284-3a473604-18d4-4736-ae10-680b2cfa7d63.png)

**Comment by anaclumos** [comment]
```json
{
  "26": "26",
  "25": "25",
  "24": "24",
  "23": "23",
  "22": "22",
  "21": "21",
  "20": "20"
}
```

This also gives:

![image](https://user-images.githubusercontent.com/31657298/227813988-71d76b0c-7a5f-4427-aaa0-be3b5f43f3ed.png)

**Comment by wazawoo** [comment]
Can you post your folder structure and where this `_meta.json` file is located? Curious about file names...

**Comment by anaclumos** [comment]
The filenames were only numbers.

**Comment by anaclumos** [comment]
<img width="294" alt="image" src="https://user-images.githubusercontent.com/31657298/231034653-8d9aa021-27f6-4bb8-8a94-8c5c5e17b9e9.png">

Also does not work correctly with sorting zero-prefixed files. This is without any _meta.json, where the expected behavior will be sorted numerically.

https://github.com/anaclumos/hn.cho.sh ← repo

**Comment by dimaMachina** [comment]
I added in docs why this happens, closing https://nextra.site/docs/guide/organize-files#allowed-keys-values

**Comment by JonathanSeriesX** [comment]
Please advise @dimaMachina 

Any chance to work around this limitation in Nextra 3? Maybe pass sorting function to nextra-site-map generator, or specify order in _meta file itself.

Any chance this could be fixed in Nextra 4? Maybe allow users to export Array instead of Object from _meta files, since arrays remember order of items

Thanks!

**Comment by JonathanSeriesX** [comment]
@dimaMachina @shuding please kindly provide us with an option to respect manual sorting of integer-named pages in Nextra 5. 

There are many use cases to this, mostly revolving around keeping URLs short and clean. Let's say `/march/31` in a diary, or `/iphone/12` in a catalogue.

Thanks!
