### ISSUE TITLE
Export Link component from nextra-theme-docs

### ISSUE THREAD

**Issue by terrymun** [shuding/nextra#1693]
Aside from [the components](https://github.com/shuding/nextra/blob/main/packages/nextra-theme-docs/src/index.tsx#L257-L273) such as Card, Cards, FileTree, Callout, and etc., would it be possible to export the Link component, too?

The reason being that I cannot use variable interpolation to declare links in MDX, e.g. `[Text](url)`, if I want to use a variable for the URL: https://github.com/mdx-js/mdx/issues/2173

This forces me to use `<Link href={url}>{text}</Link>` instead, but it is unstyled as I can only import it from `next/link`. It would be nice to have access to the styled Link component used by theme docs :)

**Comment by tuanducdesign** [comment]
Custom MDXComponents :)

**Comment by tuanducdesign** [comment]
Create MDXComponents.jsx from folder Components

```tsx
import cn from 'clsx'
import { Callout } from '../Callout'
import Link from '../Link'
import { Tab, Tabs } from '../Tabs'

export const MDXComponents = {
  Callout: (props) => <Callout {...props} />,
  a: (props) => (
    <Link
      {...props}
      className="font-semibold !no-underline !border-b-[1px] !border-b-primary-600 hover:!border-b-2 !rounded-none"
    />
  ),
  blockquote: (props) => (
    <blockquote
      className={cn(
        'sm:my-[1.3333333333em] my-[1.6em] lg:my-[1.6666666667em] xl:my-[1.6em] 2xl:my-[1.7777777778em] border-gray-300 italic text-gray-700 dark:border-gray-700 dark:text-gray-400',
        'first:my-0 border-l-[0.25em] sm:pl-[1.1111111111em] pl-[1em] lg:pl-[1em] xl:pl-[1.0666666667em] 2xl:pl-[1.1111111111em] font-medium'
      )}
      {...props}
    />
  ),
  p: (props) => <p {...props} className="leading-7 [&:not(:first-child)]:mt-6" />,
  ul: (props) => <ul className="my-6 ml-6 list-disc" {...props} />,
  ol: (props) => <ol className="my-6 ml-6 list-decimal" {...props} />,
  li: (props) => <li className="mt-2" {...props} />,
  Tab: (props) => <Tab {...props} />,
  Tabs: (props) => <Tabs {...props} />,
}
```
From root projects add to theme.config.tsx

eg:

```tsx
import { MDXComponents } from '@components/MDXComponents'

const theme = {
  components: MDXComponents,
}

export default theme
```

**Comment by terrymun** [comment]
@tuanducdesign but that means having to hardcode CSS classes to my Link component, while all I want is to use the same styles as the one that Nextra uses internally. 

Hardcoding the class names make the custom MDX component non-futureproof, and therefore isn’t really a viable solution for me.

**Comment by tuanducdesign** [comment]
@terrymun You can customize the class :)
