### ISSUE TITLE
How to export static html?

### ISSUE THREAD

**Issue by noyobo** [shuding/nextra#1694]
I want to export static file content, and I added export configuration.

```diff
const withNextra = require('nextra')({
  theme: 'nextra-theme-docs',
  themeConfig: './theme.config.jsx',
});

/**
 * @type {import('next').NextConfig}
 */
const nextConfig = {
+  output: 'export',
+  distDir: 'dist',
  compiler: {
    styledComponents: {
      ssr: true,
      displayName: process.env.NODE_ENV !== 'production',
      minify: true,
    },
  },
};

module.exports = withNextra(nextConfig);
```

will be get a error:

```
> next dev --port 3001

ready - started server on 0.0.0.0:3001, url: http://localhost:3001
Error: Specified "rewrites" cannot but used with "output: export". See more info here: https://nextjs.org/docs/advanced-features/static-html-export
```

I see nextra exists a default configuration like this:

<img width="660" alt="image" src="https://user-images.githubusercontent.com/1292082/228229865-ae5b7776-d09a-4d1f-8999-22f3729474c8.png">

**Comment by terrymun** [comment]
There is no need to add the `output` config. As far as I know Nextra’s `withNextra` handles the generation of the appropriate final config automagically. 

If you run `next build && next export` you should be able to find the exported site in the default `.next` folder.

**Comment by B2o5T** [comment]
closed since @terrymun is right

**Comment by noyobo** [comment]
Thank you.

I saw that the documentation  `next export` nextjs 13.3 will be deprecated, and thought that nextra already supports it.

**Comment by jucian0** [comment]
Getting an error when running `next build && next export`, even with `images.unoptimized = true` configured.

Error: `Error: Image Optimization using Next.js' default loader is not compatible with `next export`.`

**Comment by zburk** [comment]
![Screenshot 2023-04-18 at 5 37 13 PM](https://user-images.githubusercontent.com/5782327/232910818-d8cbb64d-9dfb-4b80-8456-43907a7bdd26.png)
This is how I have mine configured and don't get that error. Can you post your `next.config.js` file?

**Comment by jucian0** [comment]
Thanks @zburk, I fixed it.
