### ISSUE TITLE
Feedback for “How To Use - Vehicles - Documentation”

### ISSUE THREAD

**Issue by royeshao** [shuding/nextra#1718]
I bought the Model-Y from Playlolly, I try to convert to Add-on mode, but after I execute the Game and try to spaw this car, will occur the "err_sys_invalidresource_5", please give me some advise, thanks

**Comment by royeshao** [comment]
Hi B2o5T,

    I play the GTA-5 for SP mode, so if I cannot convert to the add-on, how to deploy the car into the GTA-5 for spawning? thanks

**Comment by B2o5T** [comment]
@royeshao you created an issue in the wrong repo
