### ISSUE TITLE
Feature request: Let editLink prop to take `null` not to render editLink component.

### ISSUE THREAD

**Issue by enk0de** [shuding/nextra#1719]
I have a need not to render `editLink` component. Please change a specification of editLink prop to take `nullish` value.

**Comment by tgrassl** [comment]
Right now you could set the editLink.component to null to hide it:
```
editLink: {
    component: null,
},
```
This will show a validation error, but still build the site without a problem.
<img width="559" alt="CleanShot 2023-04-15 at 22 37 28@2x" src="https://user-images.githubusercontent.com/34568407/232252223-e06fdd57-508b-4368-9e9d-6ef03d42fa8b.png">
