### ISSUE TITLE
Best practice to modify navbar background image

### ISSUE THREAD

**Issue by mysteriouscenter** [shuding/nextra#1722]
Loving this project - very helpful to get me going with SSG despite not being a guru. 

However I'm curious about the best practices for making minor tweaks to CSS. 

Do I need to install tailwindcss separately? Can I modify the nx- prefixed tailwindcss classes? Does this require a separate theme? 

I've used tailwind in the past and found it to simplify the design process for me, but my uneducated self is having trouble understanding how to leverage this within nextra. 

I saw that I am able to add tailwindcss independently, and added nextra's theme config with an @config in gobals.css and added the darkMode=dark. Not sure what to do after that, or if this is even necessary if I just want to modify .nextra-nav-container, etc.

**Comment by B2o5T** [comment]
Just use plain css or see working examples with tailwind support

https://github.com/shuding/nextra/tree/main/examples/swr-site
https://github.com/shuding/nextra/tree/main/docs
