### ISSUE TITLE
Deploy to CloudFlare error

### ISSUE THREAD

**Issue by Misaka-blog** [shuding/nextra#1723]
I got this error when deploying to CloudFlare Pages

![image](https://user-images.githubusercontent.com/122191366/229583033-d5bb6407-4eba-4364-8005-8c3897da2ef1.png)

What should I do for this? Please help me

**Comment by B2o5T** [comment]
https://github.com/shuding/nextra/issues/1202#issuecomment-1381821147

**Comment by mrinalcs** [comment]
Till not working

**Comment by B2o5T** [comment]
please do not comment on closed issue, update to latest nextra, if issue still persist create an new issue
