### ISSUE TITLE
Hydration issue for Internationalization 

### ISSUE THREAD

**Issue by abhaytalreja** [shuding/nextra#1726]
Hi There,

I am getting hydration issue, as the server is trying to access `en#` where as the client just access the regular version with the `#`

The url I try to load is `http://localhost:3000/xyz/introduction/about-the-course`

```
Prop `href` did not match. 
Server: "/xyz/introduction/about-the-course.en#" 
Client: "/xyz/introduction/about-the-course#"
```

Any help will be great. I am having 3 locales - en, es, hi.

Regards,
Abhay

**Comment by B2o5T** [comment]
Should be fixed by https://github.com/shuding/nextra/pull/2154
