### ISSUE TITLE
Feedback for “Theme Configuration”

### ISSUE THREAD

**Issue by ranjanagg01** [shuding/nextra#1734]
Can you add an example for Last updated Date? I am not able to show it on page. My code below for reference.

` gitTimestamp: ({ timestamp }) => {
    const month = timestamp.toLocaleString("default", { month: "long" });
    const date = timestamp.getDate();
    const year = timestamp.getFullYear();
    return (
      <>
        Last updated on {month} {date}, {year}
      </>
    );
  }`

**Comment by B2o5T** [comment]
https://github.com/shuding/nextra/blob/b86b7818dc3c46175e3b4fb1765631bcf9652924/packages/nextra-theme-docs/src/constants.tsx#L214
