### ISSUE TITLE
i18n 404 page cannot recognize locale in file name

### ISSUE THREAD

**Issue by jeremycos** [shuding/nextra#1737]
Hello,

I followed steps to add i18n to my project (https://nextra.site/docs/guide/i18n).

I cannot access it as expected, I have 404 page. I can access it with the normal slug (with the local extension). Examples : "http://localhost:3000/docs/mypage.fr" or "http://localhost:3000/docs/mypage.en".

I don't really know where is the problem. 

Can it come from my dependencies ? 

  "dependencies": {
    "@headlessui/react": "^1.7.13",
    "@heroicons/react": "^2.0.16",
    "@stripe/stripe-js": "1.47",
    "animate.css": "^4.1.1",
    "axios": "1.2",
    "eslint": "8.36.0",
    "eslint-config-next": "13.2.4",
    "fs": "^0.0.1-security",
    "gray-matter": "^4.0.3",
    "next": "13.2.4",
    "next-mdx-remote": "^4.4.1",
    "nextra": "^2.3.0",
    "nextra-theme-docs": "^2.3.0",
    "path": "^0.12.7",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "stripe": "^11.15.0"
  },
  "devDependencies": {
    "@tailwindcss/typography": "^0.5.9",
    "autoprefixer": "^10.4.14",
    "postcss": "^8.4.21",
    "tailwindcss": "^3.2.7"
  }
}

Thanks for your help

**Comment by abhaytalreja** [comment]
I have tried the i18n settings and it works. If you don't mind sharing details of all the 4 steps mentioned (on how you implemented), I can help you.

**Comment by B2o5T** [comment]
Please provide reproduction repo

**Comment by abhaytalreja** [comment]
MAy be related to https://github.com/shuding/nextra/issues/1760

**Comment by Kenzo-Wada** [comment]
same issue occurs for me

**Comment by dimaMachina** [comment]
Should be fixed in v3
