### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/app/apps/docs/.next/server/edge-chunks/wasm_a7e702bc5ba9227243abda7977c8096f59478d3f.wasm

### ISSUE THREAD

**Issue by jeffreys-cat** [shuding/nextra#1757]
It works fine on dev but got a strange error on production. I can't find ant useful info.

![image](https://user-images.githubusercontent.com/11832969/232179494-a2f620d9-69b2-4e82-adbe-c6c17e34e349.png)

**Comment by jeffreys-cat** [comment]
Find the problem [Fix Failed to copy traced files for Edge functions](https://github.com/vercel/next.js/pull/43326/commits/6153876c2fb524658423f315a5292e1fd260f924)

**Comment by jeffreys-cat** [comment]
downgrade to 13.2.4 works for me, close the issue

**Comment by chentsulin** [comment]
We're running into the same issue with `next@13.3.0` and output file tracing enabled. I think we should reopen this issue because it's not fixed yet.

**Comment by jeffreys-cat** [comment]
hi, @chentsulin , in my opinion, the problem is nextjs not nextra, so we should not reopen the issue here
