### ISSUE TITLE
Sidebar breaks wrap v2.4 -  on Safari

### ISSUE THREAD

**Issue by gfazioli** [shuding/nextra#1758]
I noticed the below just on Safari atm

<img width="287" alt="image" src="https://user-images.githubusercontent.com/432181/232210326-b5511afc-a945-414e-8912-1dacb7773bce.png">

anyone got the same?

**Comment by abhaytalreja** [comment]
I tried it, it is not happening for me. Here is my app, let me know if you see it there. https://teachingagile.com

**Comment by alexanderwe** [comment]
I do experience this issue as well. Links which have subpages do have a big right margin on Safari which breaks the UI in same cases
