### ISSUE TITLE
Add a placeholder/optional "afterMainContent" the content and before the pagination

### ISSUE THREAD

**Issue by abhaytalreja** [shuding/nextra#1759]
Hi There,

This is more of an enhancement request. I am looking to add an author profile for all my pages (for SEO). However, in the `docs-theme` there is no way to add any content in between the 2. If we add it in the `main` it gets added after the page.

Can we have a placeholder as `afterMainContent` just like we have it for the `sidebar` - That ways we can add custom components in there?

**Comment by B2o5T** [comment]
> However, in the docs-theme there is no way to add any content in between the 2

can you attach a screenshot where you want to add

**Comment by abhaytalreja** [comment]
Yes, I meant `extraContent`

What i mean is, we can have `extraMainContent`? - Here is the location. It is above the pagination section

![Screenshot 2023-04-22 at 12 27 53 PM](https://user-images.githubusercontent.com/1915902/233795929-b2ecc17c-cdec-4b5f-a80f-fa98a21e621b.png)

**Comment by abhaytalreja** [comment]
@B2o5T - I was able to repurpose the `gittimestamp` component. However, I lose the functionality to display the last updated date. Is there a way to customize the component but also continue to display the last updated date?
