### ISSUE TITLE
When using i18n - The href urls for the server and client are different

### ISSUE THREAD

**Issue by abhaytalreja** [shuding/nextra#1760]
There is a warning thrown in development environment that the `href` is different for client and server.

![Screenshot 2023-04-16 at 11 39 17 AM](https://user-images.githubusercontent.com/1915902/232324031-7b78bf72-dee1-4a03-8a83-d3bed782ad34.png)

Steps to reproduce:

1) Clone the `https://github.com/shuding/nextra-docs-template` and set it up for `i18n`.
2) Add below in `themes.config.tsx`
```
i18n: [
    { locale: 'en', text: 'English' },
    { locale: 'es', text: 'Española' },
  ],
```
3) Add i18n code in `next.config.js`

```
module.exports = withNextra({
   i18n: {
    locales: ['en', 'es'],
    defaultLocale: 'en',
  },
})
```

4) Add a new `middleware.ts`
```
export { locales as middleware } from 'nextra/locales'
```

Let me know if you need more details. I think the problem is that we are using the locale extensions for the server v/s the client. Iteally, we shouldn't use file extensions like `my-file.en` even on the server.

**Comment by B2o5T** [comment]
Please provide reproduction repo

**Comment by abhaytalreja** [comment]
@B2o5T Added you to my private repo. I hope it helps.

**Comment by imagineapi** [comment]
I'm seeing this as well.

I'm only getting 404 on server renders for pages that are nested under a fold with the folder having no index page.
