### ISSUE TITLE
how to edit theme??? Feedback for “Docs Theme”

### ISSUE THREAD

**Issue by washirving** [shuding/nextra#1772]
where is docs theme template itself? how to edit theme? not just poor configure but gain full control of output html.
how to change layout, customize css, add custom blocks, remove annoying «Question? Give us feedback 
and «Edit this page» elements etc. ?

**Comment by oyesameed** [comment]
This is how I hide "Edit this page" 😅
<img width="424" alt="Screenshot 2023-04-18 at 2 34 22 PM" src="https://user-images.githubusercontent.com/23375008/232736081-c88bad25-dca7-4ddd-9ab1-ef199ed52cd2.png">

**Comment by oyesameed** [comment]
I wish there was more control over the components and theme, especially in terms of customization options.

**Comment by C-EO** [comment]
@oyesameed and @washirving The prebuilt Nextra themes are for people who don't want to hastle creating a theme. If you want more control, I suggest you create your own theme. Find out more from [here](https://nextra.site/docs/custom-theme).

**Comment by washirving** [comment]
> @oyesameed and @washirving The prebuilt Nextra themes are for people who don't want to hastle creating a theme. If you want more control, I suggest you create your own theme. Find out more from [here](https://nextra.site/docs/custom-theme).

yeah. but docs theme sooo good. so calm and pretty. just need some edits wich are not provided by config

**Comment by C-EO** [comment]
@washirving Like what edits?

**Comment by washirving** [comment]
> @washirving Like what edits?

1. completely get rid of «on this page» (this is just stupud. here is the page, just look at it. totally unnessesary table of contents for small pages), this block must be optional for long pages.
2. remove «Question? Give us feedback →». feedback link should be in the footer. there is alredy «Contact ↗» in header
3. remove «Edit this page». simple user shouldn't see it at all, he cant edit my content, it's just for me as administrator and I know how to edit my site without a link.  maybe it make sence for wikis or comunity sites, but I have just some project documentaton.
4. move  «Last updated on April 18, 2023» below page title or have an option to remove it for specific pages like «About». edit 
 date for domumentation can be reasonable, but «about us» or other pages like it  should be like they where there forever. 
5. make pagination smaller and prettier. have an option to remove it as well or move it to top of the page
6. make page title bigger and in different font. custom font for every h1, h2, h3 etc. 
7. full rich 4-column footer 
8. move «Light/Dark» switch in top right corner in sticky header (where by defailt useless discord link is)
9. custom sidebar and content div width.
10. etc.

all this can be done in minutes if there was a html template or something like that

**Comment by oyesameed** [comment]
> 

Plus there's no option to change colors and fonts for your website specific customisation.

**Comment by washirving** [comment]
so, just played enough with Nextra. my thoughts:
overall expieriecce is not satysfiing. all is too complicated in use. 
we need only three things: menu in sidebar (automatically generated of folders and files structure in «pages» folder), special folder for header links to pages like «about» and existing html/css template which can be easily edited as users like to render all this out.
I see workflow something like that: customise template once and then just adding md files with content to site. would be perfect to use obsidian connected to git for that. thats all. 
simple projects dont need all this not obvious .tsx configs at all but good old html/css for configuring visuals. I  forgot comma or branch in _meta.json and thete is error on deploy. simplicity is a key to future.

**Comment by washirving** [comment]
wow! what an interesting thing Turbo! Thank you! I'll play with it.
yeah, finally read the docks, lol. feedback link can be disabled! nice.  (and «edit this page» should not exist at all)
dont be angry, we just used to old ways of html/css and frustrated, trying to reach something new

**Comment by C-EO** [comment]
@washirving You'll have to remove `sentry` to be able to run the Turbo website

**Comment by C-EO** [comment]
My example is [here](https://github.com/c-eo/dochub-beta).
