### ISSUE TITLE
What are some recommendations of putting an Auth layer?

### ISSUE THREAD

**Issue by hhimanshu** [shuding/nextra#1776]
Hey folks,

Nextra looks great!
I am wondering if there is a way to add user authentication on the site. That ways this can serve as a course hosting site as well. This means that logged-in users only see pages that they have purchased for.

Any ideas?

Thanks

**Comment by washirving** [comment]
good question! It would be great to have special area for logged-in users.

**Comment by abhaytalreja** [comment]
@hhimanshu I will be interested in it. Let me know if you can make it work :)

The Approach:

- Integrate `auth0` just like in a Next.js app.
- Add roles
- Guard the paths / pages.

**Comment by B2o5T** [comment]
https://github.com/shuding/nextra/issues/1121#issuecomment-1374958546
