### ISSUE TITLE
Feature Request: Allow users to parse frontmatter

### ISSUE THREAD

**Issue by thunder-coding** [shuding/nextra#178]
I am just migrating from [`next-mdx-enhanced`](https://github.com/hashicorp/next-mdx-enhanced), in that library I could generate head tags using frontMatter
```mdx
---
title: "Blog Title'
tags: ['blog', 'start']
timePublished: 'TimeStamp'
// And perhaps a lot more tags
---
# My blog
```

In `layouts/index.jsx`:
```jsx
import Head from 'next/head'
export default function MDXPage({children, frontMatter}){
    return (
        <>
            <Head>
                <meta property="og:title" content={frontMatter.title} />
            // All other frontMatter tags here
            </Head>
        </>
    )
}
```

Using Nextra, I am missing this very feature on which my blog is supposed to be made.

**Comment by shuding** [comment]
I believe that all front matter fields are included with the `meta` prop of the layout component, could you please check again?
