### ISSUE TITLE
Website caching works really badly on Vercel

### ISSUE THREAD

**Issue by onrecc** [shuding/nextra#1781]
So I just rebuilt my site on Vercel and added and removed some stuff but the removed stuff are still there with just 404s and the added things are not there. Does anyone know a quick fix for this?

**Comment by abhaytalreja** [comment]
@onrecc I agree. I have had similar issues. I usually end up doing a `redeploy` in vercel to make it work.

**Comment by onrecc** [comment]
Yep I also found that out after playing for a while. I'd expect Vercel to work well since, if I understood correctly, they have funded this project and are promoting it.

**Comment by dsernst** [comment]
Yea, quick solution is to turn off the build cache: https://github.com/shuding/nextra/issues/1564#issuecomment-1447419595
