### ISSUE TITLE
Build error - Unexpected character `3` (U+0033) before name

### ISSUE THREAD

**Issue by jameesy** [shuding/nextra#179]
![Screenshot 2021-06-29 at 16 18 51](https://user-images.githubusercontent.com/32302360/123824439-f392bf80-d8f5-11eb-9710-25adc99381c2.png)

I am getting the following issue when trying to build the blog-theme. 

Repo I am trying to build is here: https://github.com/jameesy/james-blog

Any help massively appreciated!

**Comment by jameesy** [comment]
Managed to solve this, so closed :) 

For whatever reason there were five or so markdown files that were affected. I deleted them and managed to build. 

Still not 100% sure what caused this, because the files seem fine.

**Comment by barnagoz** [comment]
Can I ask you, what how did you do it? I currently have the same problem.

**Comment by jameesy** [comment]
From memory, I couldn't figure it out. The spent a good amount of time trying to figure something out but couldn't. Only way to fix was to delete the files and rebuild.
