### ISSUE TITLE
Error when using inside of Turborepo

### ISSUE THREAD

**Issue by Lermatroid** [shuding/nextra#1793]
Hello!

I am running into the following error when using the docs template with turborepo:

`TypeError: Cannot read properties of undefined (reading 'Compilation')`

I found a similar [issue here](https://github.com/shuding/nextra/issues/1179), but it did not have a solution attached.

Thanks for the help!

**Comment by B2o5T** [comment]
duplicate https://github.com/shuding/nextra/issues/1179
