### ISSUE TITLE
Showcase: Is there a way to add our site in the showcase?

### ISSUE THREAD

**Issue by abhaytalreja** [shuding/nextra#1798]
Hi There,

Might be a silly question, but i actually worked hard on creating a version of nextra as a blog. I will love to add the webste in the showcase tab. Is there a process to do so?

Thanks in Advance!

Abhay

**Comment by officialrajdeepsingh** [comment]
You can add your site on https://github.com/shuding/nextra/blob/main/docs/pages/showcase.mdx file.
