### ISSUE TITLE
i18n with _meta.js

### ISSUE THREAD

**Issue by Prottoy2938** [shuding/nextra#1802]
When using `_meta.js`, I can't specify different page titles for different `i18n` routes or for different langauges. 

I've tried using `_meta.[langCode].js`, but the site breaks on vercel (`showing 500 error`) if I do that.

How can I achieve that?

**Comment by abhaytalreja** [comment]
It should be `_meta.en.json`, `_meta.es.json`

**Comment by B2o5T** [comment]
follow https://github.com/shuding/nextra/tree/main/examples/swr-site i18n working example
