### ISSUE TITLE
Next JS Load JS size is huge

### ISSUE THREAD

**Issue by abhaytalreja** [shuding/nextra#1803]
Hi There,

Is there a setting to optimize the load time for the pages? THe first load JS has an issue that by default the entire app has about 188kb to load. I am using vercel to do the deployment, if there is a setting to gzip or optimize it, that will be great.

Here is an image when I run a build.

![image](https://user-images.githubusercontent.com/1915902/235199311-c82ef8ad-e6a5-4540-9c17-12d55b7be39f.png)

@B2o5T  If you have any feedback on the repo, do let me know.

**Comment by B2o5T** [comment]
which bundle size do you expect to have?

**Comment by B2o5T** [comment]
you can analyze your bundle size with `@next/bundle-analyzer`

where for 188kb
- 11kb css
- 44kb react/react-dom
- 30kb next.js
- nextra-theme-docs 58kb
- _app.mdx 17kb
- rest of dependencies?

**Comment by abhaytalreja** [comment]
@B2o5T So that accounts for 160 KB + rest of dependencies. I see there is no way we can reduce that 160 kb ?

**Comment by B2o5T** [comment]
Feel free to investigate how we can reduce bundle size

**Comment by B2o5T** [comment]
closed by https://github.com/shuding/nextra/pull/2250

https://github.com/shuding/nextra/releases/tag/nextra%403.0.0-alpha.0 

I made some improvements and you can see global bundle decreased https://github.com/shuding/nextra/pull/2245
