### ISSUE TITLE
Is there a way to remove the Nextra text from the tab header?

### ISSUE THREAD

**Issue by FelixWaweru** [shuding/nextra#1805]
I have setup a doc site using the Nextra template and I want to remove the _Nextra_ text from the header.

![Example 1 – Nextra - Google Chrome 29-Apr-23 1_58_23 AM](https://user-images.githubusercontent.com/18608672/235267141-ef734d6b-b63a-4bff-9528-cdf28b5a3eb9.png)

Does anyone have an idea on how to do it?

**Comment by B2o5T** [comment]
https://nextra.site/docs/docs-theme/theme-configuration#seo-options
