### ISSUE TITLE
Server-side Rendering (SSR) support

### ISSUE THREAD

**Issue by lmakarov** [shuding/nextra#181]
This may come in as an odd request, but would Nextra support SSR?
https://nextjs.org/docs/basic-features/pages#server-side-rendering

Our use case is to have public vs private documentation pages and be able to configure access in the page meta data level.
For this to work, private pages would need to be served at runtime, while public pages can be generated as usually, at build time.

**Comment by anguyen110** [comment]
Looking forward to this feature! 👍

**Comment by shuding** [comment]
We have this supported, you can use `getServerSideProps` similar to this: https://nextra.site/docs/guide/ssg

**Comment by timothymiller** [comment]
`import { useSSR } from 'nextra/ssr'`

Module not found error with `"nextra": "2.2.14"`

**Comment by shuding** [comment]
@timothymiller the module is `nextra/ssg` but we are gonna rename it to `nextra/data`.
