### ISSUE TITLE
Is there a way to combine both themes?

### ISSUE THREAD

**Issue by nikgraf** [shuding/nextra#1812]
I was wondering if there is a way to have the docs and blog on one Next installation? Or any recommendations to achieve both e.g. have the blog installation on the `/blog` path?

**Comment by B2o5T** [comment]
take a look of working example https://github.com/shuding/nextra/tree/main/examples/swr-site/pages/blog

**Comment by nikgraf** [comment]
thanks @B2o5T 🙇
