### ISSUE TITLE
Is possible to use two theme in the same istance?

### ISSUE THREAD

**Issue by stephzero1** [shuding/nextra#1820]
Hi everyone,
i need to set up the two theme docs and blog in the same nextra instance.

I know that i can set only one theme per instance, but i was wondering if i can set the theme for a certain path or something.

For now i configured nextra with the docs theme, and created a page which simulates the view of blog posts, but the main feature that i need is the possibility to show date, title and tags inside the single blog post.

Any hint?

**Comment by B2o5T** [comment]
https://github.com/shuding/nextra/issues/1812#issuecomment-1532779994
