### ISSUE TITLE
`staticImage` prevents custom MDX `img` component

### ISSUE THREAD

**Issue by jukrb0x** [shuding/nextra#1821]
## Use case
I am customizing my blog theme, and an Image component comes into play when I am trying to overwrite MDX components like this:
```
const Image = ({ src, alt, ...props }: ComponentProps<'img'>): ReactElement => {
    return (
        // the custom `next/image` wrapped component
    )
}
const useComponents = (): Components => {
    const { config } = useBlogContext();
    return {
        h1: H1,
        h2: (props) => <HeadingLink tag="h2" { ...props } />,
// ...
        img: Image,
        ...config.components
    };
};

```

this doesn't work since `staticImage: true`, the reason is nextra would replace each regular `<img>` to a wrapped static imported next/image component in a mdx plugin: https://github.com/shuding/nextra/blob/main/packages/nextra/src/mdx-plugins/static-image.ts#L45

![image](https://user-images.githubusercontent.com/15688641/236005864-fe1cdee2-960d-450a-94c2-c203aad7cd12.png)

To work around this, I need to set `staticImage: false` and then customize my `Image` component, but the thing is the static imports are broken:

![image](https://user-images.githubusercontent.com/15688641/236010412-37db6580-bd5f-4cb1-a729-27e1530ba527.png)

I am still researching a way to make it work, I wouldn't like to make a modeled nextra for my project.

## Expected behaviour
the best idea is to keep `staticImage: true` but be able to customize the mdx component

### additional 
1. the other way is having the static imports work without the framework `staticImage` logic
2. ability to have to add mdx plugin from user's side

take a deep look into this problem, if I custom an Image MDX component:

`next/image` requires a `width` and `height` for a image for a remote URL, the component will see the URL passed in as a stringy remote source (`fill` property is not desired in my case, width and height are necessary), nextra will replace the source to be locally imported, that's fine as an mdx plugin (framework-wise).

now I am not sure if this problem can be solved from the user-side.

**Comment by B2o5T** [comment]
Please share a reproduction repo and I'll take a look at why it doesn’t work for you

**Comment by jukrb0x** [comment]
> Please share a reproduction repo and I'll take a look at why it doesn’t work for you

Thanks for responding!

Here's the reproduction branch for this issue: https://github.com/jukrb0x/wh0.is/tree/nextra/reprod-static-image

The live codesandbox: https://codesandbox.io/p/github/jukrb0x/wh0.is/nextra/reprod-static-image

The images starting with `/` will be fine since they are put in `/public` directory, the use-case for me is the relative local path like `./some-image.jpg`, and `next/image` will see the stringy URL as a remote source, which will ask for a `width` and `height` (`fill` doesn't apply for my case)... this seems to be an obstacle for constructing an MDX component.

**Comment by B2o5T** [comment]
you can temporarily patch this line https://github.com/shuding/nextra/blob/d23a655581c99a82bf1ece0a80981f20a0c031b1/packages/nextra/src/mdx-plugins/static-image.ts#L74
to `name: 'img'`, so `staticImage: true` and custom `img` component will works and you will receive follow data as `props` 
<img width="510" alt="image" src="https://user-images.githubusercontent.com/7361780/236075136-1693b804-b7f8-4708-ae5e-3d16e6c62b66.png">

Also I will think about how it could be implemented in nextra via a new option or something like this

**Comment by jukrb0x** [comment]
Great! Thanks so much, I am looking forward to a framework-wise solution in future releases.
