### ISSUE TITLE
Build error on Vercel, but not GitHub Actions or on local machine

### ISSUE THREAD

**Issue by jontmy** [shuding/nextra#1827]
### Details
After updating to 13.4.0 (and 13.4.1) it seems that Nextra will fail to deploy on Vercel even though it builds successfully my local machine as well as on GitHub Actions running `next build`.

![image](https://user-images.githubusercontent.com/50949210/236592895-4aebef59-3562-43fd-832a-5107b9ca531f.png)

The Vercel deployment log is at the bottom of this issue.

### Sandbox repo
I've created a fresh repository which can be cloned and added to Vercel, but the deployment will fail at build-time.
[https://github.com/jontmy/nextra-vercel](https://github.com/jontmy/nextra-vercel)

I used Nextra to add a documentation page in the `/pages` directory, but with the `/app` directory alongside with a single dummy page.

### Steps to reproduce

1. Use `create-next-app@latest` to create a fresh Next.js app with version 13.4.1 as of time of writing. Ensure the app router is selected, even though we will be placing the docs in the pages directory. 
```
npx create-next-app@latest
```

2. Follow the steps in [Docs Theme | Get Started](https://nextra.site/docs/docs-theme/start) to get a working documentation page up and running.

3. Move the pre-generated `layout.tsx` and `page.tsx` in `/app` to a new sub-directory in `/app`.

4. Start the dev server and navigate to [localhost:3000](http://localhost:3000/), where you'll see that the documentation page works fine on your machine.
```
npm run dev
```

5. Build the documentation, and this will also work fine on your local machine (and GitHub Actions).
```
npm run build
```

6. Deploy on Vercel. You will get the following error:

![image](https://user-images.githubusercontent.com/50949210/236592710-643ec354-f5fe-4dca-8ef8-c883b629fc7f.png)

**Comment by nnecec** [comment]
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/11435907/236596818-1f117c1e-5ea5-40ee-8710-af57de8d0ec6.png">

Maybe same problem

**Comment by C-EO** [comment]
Nextra doesn't use the new `/app` directory yet.

**Comment by nnecec** [comment]
> Nextra doesn't use the new `/app` directory yet.

I'm not use `/app`, still `/pages`

**Comment by jontmy** [comment]
Closing as it now builds successfully on Vercel with Next.js >=13.4.3.
