### ISSUE TITLE
 If the page is not under the docs, the next link is incorrect.

### ISSUE THREAD

**Issue by sinchang** [shuding/nextra#1829]
please check out the link at https://nextra.site/docs/custom-theme

**Comment by sinchang** [comment]
@Sahil-B07 thanks for following up the issue.

you can visit the page https://nextra.site/docs/custom-theme#, we can't redirect to `About Nextra` page.

![image](https://github.com/shuding/nextra/assets/3297859/c9d1da62-f041-429b-943f-f99c581a2f4e)

**Comment by Sahil-B07** [comment]
ohh, got it !
I'll work on this issue :)

**Comment by dimaMachina** [comment]
this was fixed in Nextra v3 https://nextra.site/docs/custom-theme
