### ISSUE TITLE
Can't load a .ts file that ends with a const assertion.

### ISSUE THREAD

**Issue by salieflewis** [shuding/nextra#1846]
I'm trying to write documentation for a package I'm working on. I've introduced the package to Nextra as a dependency, and both the docs site and package live in the same monorepo, so the package is installed via the workspace protocol.

There is a typescript file in the package that ends with the a const assertion, aka ... `as const`. For some reason I'm getting the error:

You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.

Any ideas? Thank you!

**Comment by B2o5T** [comment]
Please provide a reproduction
