### ISSUE TITLE
Error in starting demo project

### ISSUE THREAD

**Issue by Syed-Ansar** [shuding/nextra#1851]
<img width="1440" alt="Screenshot 2023-05-12 at 11 29 57 AM" src="https://github.com/shuding/nextra/assets/82027712/621c1809-50a9-4678-b3c0-e91294c162a0">

**Comment by Syed-Ansar** [comment]
can anyone help me with this ?

**Comment by B2o5T** [comment]
please provide more information, reproduction repo

**Comment by Syed-Ansar** [comment]
Deployed to github and cloned the repo and started the local server.

Refer: https://nextra.site/docs/custom-theme

**Comment by B2o5T** [comment]
this example is outdated, you need to remove this https://github.com/shuding/nextra-example/blob/c9ca7d2085851ae705977c8150e6cbb82beba457/theme.jsx#L74-L76
