### ISSUE TITLE
Provider to import default components

### ISSUE THREAD

**Issue by abhaytalreja** [shuding/nextra#1852]
Is there an MDXProvider of sorts that we can use to basically define the imports that can be accessed across all MDX files?

I tried the below approach and it didn't work.

`components/MDXComponents.js`

```
import EmailSignUp from './EmailSignUp';

const MDXComponents = {
  EmailSignUp,
  // ... other components
};

export default MDXComponents;
```

In `_app.mdx`

```
import { MDXProvider } from '@mdx-js/react';
import MDXComponents from '../components/MDXComponents';

function MyApp({ Component, pageProps }) {
  return (
    <MDXProvider components={MDXComponents}>
      <Component {...pageProps} />
    </MDXProvider>
  );
}

export default MyApp;
```

My `.msx` file

```
# Title

## H2

## H2

## H2

## H2

<EmailSignUp />

## H2
```

Any help will be appreciated. I don't want to include the component in 100s of files.
@B2o5T

**Comment by B2o5T** [comment]
https://nextra.site/docs/docs-theme/theme-configuration#mdx-components

**Comment by abhaytalreja** [comment]
This is exactly what I was looking for... Thank you so much!
