### ISSUE TITLE
 Is there any way to keep the sidebar closed when the page loads on the docs template?

### ISSUE THREAD

**Issue by Prottoy2938** [shuding/nextra#1854]
As the question says.

Currently, the `sidebar` is always `open` (_on desktop screen size_) when  the page loads and the user has the option to close the sidebar once the page loads by clicking the toggle button. But isi there a way to keep the sidebar `closed` when the page loads, and  later the user can  click on the toggle button to open the sidebar.

How can I achieve it? Is there any options for this?

**Comment by B2o5T** [comment]
There is no way to do it

**Comment by SonMooSans** [comment]
It might be possible by storing the value in localStorage or cookie, then attaching a script that loads the value and display the sidebar if it is enabled

Example: 
```html
<body class="group-sidebar-open">   <!-- Attached by the script -->
    <script></script> <!-- Add "group-sidebar-open" class to body if enabled -->
    <aside class="hidden group-[-sidebar-open]:block">...</aside>
</body>
```
