### ISSUE TITLE
Allow titleComponent metadata

### ISSUE THREAD

**Issue by crutchcorn** [shuding/nextra#1859]
I'm working on a docs page where we'd like the sidebar's root navigational items to have bolder text than subroutes.

However, to do this more reliably it would be nice to have:

```json
{
  "route": {
    "title": "Route Name",
    "metadata": {
        "fontSize": "1.2rem"
    }
  }
}
```

Or something akin to that in `_meta.json` that could then be accessed via:

```jsx
titleComponent: ({title, metadata}) => {
    return (
       <span style={{fontSize: metadata.fontSize ?? "1rem"}}>{title}</span>
    )
}
```

I'm happy to contribute a PR for this behavior.

**Comment by B2o5T** [comment]
titleComponent will be removed in v3 https://github.com/shuding/nextra/pull/2301
