### ISSUE TITLE
About adding new custom theme in nextra 

### ISSUE THREAD

**Issue by officialrajdeepsingh** [shuding/nextra#1860]
I recently build a new blog theme and now I'm thinking of Marge with Nextra. what is Cateria to add a new theme in nextra?
plz, tell me any guidance @B2o5T and @shuding.
Theme GitHub repo [https://github.com/officialrajdeepsingh/nextra-blog](https://github.com/officialrajdeepsingh/nextra-blog)

**Comment by B2o5T** [comment]
Sorry I am not interested in maintaining yet another theme
