### ISSUE TITLE
[Nextra-Blog] A mdx page that is hidden is visible as a post

### ISSUE THREAD

**Issue by md-weber** [shuding/nextra#1878]
I created a _meta.json with the following content:

```json
{
    "impressum": {
        "hidden": true,
        "title": "Impressum",
        "type": "page"
    }
}
```

As expected it gets removed from the sidebar and I cannot directly navigate to it anymore. However we can see it now in the posts page.

<img src="https://github.com/shuding/nextra/assets/8026644/4fc6b5ff-90dc-46cd-aecd-b9da9529a053" height=200/>

I tried already the following: Put the `_meta.json` into the MDX header part then it gets removed from the post part but we it is again visible in the sidebar.

```md
---
hidden: true
title: Impressum
type: page
---
```

And also I tried to use instead of `hidden: true` -> `display: hidden` with the same result.

This could be related to https://github.com/shuding/nextra/issues/1729

**Comment by md-weber** [comment]
I believe I found the issue in the `collect.ts`, here we have the part 
```
const isNav = (page: PageMapItem): page is MdxFile => {
  const type = 'frontMatter' in page && page.frontMatter?.type
  return type && ['page', 'posts'].includes(type)
}
```
Which does not take the `"display": "hidden"` into consideration. I will work further on this issue and hope I can provide next week a PR for it.

**Comment by B2o5T** [comment]
Only docs theme support _meta.json, possible way to hide described here https://github.com/shuding/nextra/issues/351
