### ISSUE TITLE
[ERROR] Getting error Can't resolve module "button.mjs"

### ISSUE THREAD

**Issue by HyperDanisH** [shuding/nextra#1881]
Hi community,
I am trying to build nextra from source code but there is an error each time I do. After I run cd packages/nextra && pnpm build && pnpm dev, cd packages/nextra-theme-docs && pnpm build && pnpm dev. And when I try to run cd examples/blogs && pnpm run dev, This gives the error mentioned below.

![Screenshot 2023-05-17 152722](https://github.com/shuding/nextra/assets/93310647/e244408b-d534-43ba-923e-58d92a13a059)

**Comment by B2o5T** [comment]
Do you use windows? Should be fixed by https://github.com/shuding/nextra/pull/1894

**Comment by HyperDanisH** [comment]
It's fixed by using WSL. Thanks for the help sir! ❤️
