### ISSUE TITLE
Can't use <code> headers in ToC component

### ISSUE THREAD

**Issue by hassankhan** [shuding/nextra#1884]
Hi, I searched existing issues but couldn't find anything related. I have an MDX file that uses backticks in its headings:

```markdown
## `CUBEJS_API_SECRET`
```

When rendering it with Nextra, the content renders the header correctly (`CUBEJS_API_SECRET`, but then in the table of contents, it renders it without the `<code>` element, as you can see from the screenshot below:

<img width="1228" alt="image" src="https://github.com/shuding/nextra/assets/1781985/818c9d8a-49f7-4c25-8e88-c905a327f43d">

I had a go at using a custom component in my `theme.config.tsx`, but the `props.headings` property that it receives only provides headings that have been stripped of the backticks. Is there any possibility of providing the raw(?) content to the ToC component?

**Comment by B2o5T** [comment]
https://github.com/shuding/nextra/issues/126#issuecomment-1205864693
