### ISSUE TITLE
[Nextra-theme-docs] react-hydration-error prop className nav logo

### ISSUE THREAD

**Issue by tuanducdesign** [shuding/nextra#1887]
![Screen Shot 2023-05-20 at 22 11 26](https://github.com/shuding/nextra/assets/69758022/fc823ff9-e484-4ffc-99a8-962a763b791a)

**Comment by B2o5T** [comment]
Please provide more info or reproduction

**Comment by tuanducdesign** [comment]
```
<a href="/" class="nx-flex nx-items-center hover:nx-opacity-75 ltr:nx-mr-auto rtl:nx-ml-auto L-Affiliate-Tagged">...</a>
```

After I deleted the .next folder on the project, the above error no longer appeared

**Comment by tuanducdesign** [comment]
Currently I am using the latest version of Nextra.

**Comment by tuanducdesign** [comment]
> ![Screen Shot 2023-05-20 at 22 11 26](https://github.com/shuding/nextra/assets/69758022/fc823ff9-e484-4ffc-99a8-962a763b791a)
> 
> 

I get this error when using `pnpm dev:website`

**Comment by B2o5T** [comment]
@tuanducdesign I don't have this warning while running `pnpm dev:website`
did you take the latest changes from `main` branch?

**Comment by tuanducdesign** [comment]
I have changed, I deleted nextra folder in packages folder and customized nextra-theme-docs

**Comment by tuanducdesign** [comment]
> I have changed, I deleted nextra folder in packages folder and customized nextra-theme-docs

I mean I replace `"nextra": "workspace:*"` to `"nextra": "latest"`

**Comment by B2o5T** [comment]
This is not the right place for asking general questions or deep diving into your warnings while customization Nextra themes
