### ISSUE TITLE
How can I disable the 'Question?' and 'Edit this page' links

### ISSUE THREAD

**Issue by acoudouy** [shuding/nextra#1901]
Hi, thank you for working on nextra, we love this project.

Our documentation is not public, how can we disable these two settings, please? 

![image](https://github.com/shuding/nextra/assets/57633651/fcc308dc-23d5-480b-a311-28274175bb82)

**Comment by try-to-fly** [comment]
You can configure it in `theme.config.tsx` as follows:

```tsx
editLink: {
  text: null,
},
feedback: {
  content: null,
},

You can refer to my configuration on [here](https://github.com/try-to-fly/wiki/blob/main/theme.config.tsx#L29)

**Comment by acoudouy** [comment]
Thank you!
