### ISSUE TITLE
Hidden folder is still shown in the mobile view

### ISSUE THREAD

**Issue by raproid** [shuding/nextra#1909]
When setting up "display": "hidden" for a folder, the sidebar doesn't show it only in the desktop view. 
If I resize the windows to force on the mobile view, the item is still visible.

For example, Contract Automation is not visible in the sidebar in the desktop view
<img width="822" alt="image" src="https://github.com/shuding/nextra/assets/22454517/d8cd7581-a124-4dbd-83fd-0adf60a6cd20">

but is visible in the mobile view
<img width="500" alt="image" src="https://github.com/shuding/nextra/assets/22454517/2c7ead8f-12fa-493a-8a2c-6701b9e5cd0f">

I tried to set the property diff ways:
1.   "automation": {
    "title": "Contract Automation",
    "type": "folder",
    "display": "hidden"
  },
 2.   "automation": {
    "title": "Contract Automation",
    "display": "hidden"
  },

None worked for me.

**Comment by raproid** [comment]
@B2o5T any idea how to fix or why this happens in the first place?

**Comment by B2o5T** [comment]
No idea, PR welcome
