### ISSUE TITLE
Can't integrate custom components with useContext hook

### ISSUE THREAD

**Issue by giuseppelt** [shuding/nextra#1917]
Hi I'm trying to integrate a custom Component for [Feelback](https://www.feelback.dev), a plugin to integrate _Likes_ button, _Is this page useful_ upvote widget and similar feedback widgets.

I made react components which work fine if used in _plain_ react sites, but I can't seem to make it work on this template.

The error:
```
TypeError: Cannot read properties of null (reading 'useContext')

  209  | var ReactFeelbackContext = createContext(void 0);
  210  | function useFeelbackContext() {
> 211  | return useContext(ReactFeelbackContext);
       |                 ^
  212  | }
```

It errors on the `useContext` hook which finds it as null, but the previous line at  `createContext` on the global scope works. So it cannot be that _React_ is not imported, as some functions are imported and others not.

I don't know if it's something related to the bundler or anything else.
Any advice is appreciated.

**Comment by B2o5T** [comment]
Provide a reproduction repo and maybe somebody will help you

**Comment by giuseppelt** [comment]
Sorry I didn't update the issue.
Yesterday I found a solution, I leave here just if someone face the same.
Basically, it was a bad symlink on the React package. My mono setup has a react-plugin which declares react as peer-dependency. Nextra's react and my package's react, where symlinked to different locations, hence the problem.
