### ISSUE TITLE
bug: markdown link strips .md from link

### ISSUE THREAD

**Issue by d1onys1us** [shuding/nextra#1918]
a link [like this](https://github.com/taikoxyz/taiko-mono/blob/main/CONTRIBUTING.md) is invalid if inside of a `.mdx` document in nextra. the link ends up stripping out the `.md` and navigates to `https://github.com/taikoxyz/taiko-mono/blob/main/CONTRIBUTING` instead of `https://github.com/taikoxyz/taiko-mono/blob/main/CONTRIBUTING.md`

**Comment by B2o5T** [comment]
it was already fixed, update to latest nextra version
