### ISSUE TITLE
Search redirect from template on prod is broken

### ISSUE THREAD

**Issue by UmbrellaCrow612** [shuding/nextra#1920]
**Description:**
I encountered an issue with the search functionality in the Nextra template while developing my website. When using the Nextra template, I created a website at https://what-a-programmer-should-know.vercel.app/. However, the built-in search bar redirects users to a URL with capitalized letters instead of lower case, based on the file name. Strangely, this behavior only occurs in the deployed version of the website, while in local development, it works correctly.

**Steps to Reproduce:**
1. Go to the deployed website: https://what-a-programmer-should-know.vercel.app/.
2. Locate the search bar on the website.
3. Enter a search term in lowercase, for example, "javascript."
4. Press the enter key or click on the search icon.
5. Observe the URL in the address bar.

**Expected Behavior:**
The search functionality should direct the user to a URL with lowercase letters, based on the file name, regardless of whether it is in local development or deployed on a server.

**Actual Behavior:**
The search functionality redirects the user to a URL with capitalized letters, based on the file name, only in the deployed version of the website. In local development, the behavior is as expected, with lowercase URLs.

**Additional Information:**
- I am using the Nextra template for my website development.
- I have not made any modifications to the search functionality or routing code provided by the Nextra template.
- This issue is specific to the deployed version of the website, while local development works correctly.
- It seems to be an inconsistency between the local development environment and the deployed environment in how the URLs are generated by the search functionality.

`repo`: https://github.com/UmbrellaCrow612/what-a-programmer-should-know

**Comment by B2o5T** [comment]
@UmbrellaCrow612 what was the problem?

**Comment by B2o5T** [comment]
@UmbrellaCrow612 yeah, sometimes git has unexpected behavior while changing casing of filenames

**Comment by B2o5T** [comment]
Try follow https://github.com/shuding/nextra/issues/1564#issuecomment-1447419595
