### ISSUE TITLE
horizontal lines low contrast in dark mode

### ISSUE THREAD

**Issue by ShahriarKh** [shuding/nextra#1927]
![image](https://github.com/shuding/nextra/assets/31452340/ca806f0d-7e30-471c-8a8c-0fd0526e241f)
![image](https://github.com/shuding/nextra/assets/31452340/bdc51027-6126-4fbe-a7f3-597d57e07451)

Horizontal lines have low contrast in dark mode and are nearly invisible. I tried with different `primaryHues`, but no luck. (some elements like buttons have poor contrast when using colors like dark blue as primaryHue, but work good with other colors. However, the `hr` color has poor contrast in both)

Maybe switch color system to HSLA (instead of RGBA), so the user (read developer) can set a primary hue (H) and then the elements are colored with various lightness, saturation and alpha.

**Comment by B2o5T** [comment]
pr welcome

**Comment by ShahriarKh** [comment]
Is nextra using tailwind colors under the hood?

**Comment by ShahriarKh** [comment]
I took a look at the source code, and saw that horizontal lines are gray (not changing with primaryHue), so I just changed gray-900 to gray-800 (maybe gray-700 is better?) to make it more visibile.
