### ISSUE TITLE
Step Component without titles

### ISSUE THREAD

**Issue by ShahriarKh** [shuding/nextra#1929]
Is it possible to use steps without the step's title?
Like this:
![image](https://github.com/shuding/nextra/assets/31452340/0b79e352-b477-4007-9e87-423f924e8f03)

Currently, each step is defined by `###`, but I'm looking for a way to use normal text (`p`) for each step.

**Comment by LuciferUchiha** [comment]
I agree on this having to use `###` seems very limiting. Also not great if you don't want the step titles to be in the table of contents. I would suggest adding either a `Step` component with a title attribute and the content as children or just simply a 
`StepSeperator` Component know the range of a step and then leaving the creation of the title to the writer

**Comment by LuciferUchiha** [comment]
This would also solve this "bug": https://github.com/shuding/nextra/issues/2011
