### ISSUE TITLE
Feedback for “Introduction”

### ISSUE THREAD

**Issue by DavidGeismarLtd** [shuding/nextra#1932]
Hello ! I can't figure out how to remove or edit : 
- [(opens in a new tab)](https://github.com/shuding/nextra/issues/new?title=Feedback%20for%20%E2%80%9CIntroduction%E2%80%9D&labels=feedback)
[Edit this page](https://github.com/shuding/nextra/pages/index.mdx)

and 

- [Question? Give us feedback →](https://github.com/shuding/nextra/issues/new?title=Feedback%20for%20%E2%80%9CIntroduction%E2%80%9D&labels=feedback)

in the code.
<img width="317" alt="Screenshot 2023-06-05 at 09 20 18" src="https://github.com/shuding/nextra/assets/68914479/4558c357-e938-415e-a07c-f787ce99d533">
Could you please help me here ?
Thanks

**Comment by B2o5T** [comment]
https://github.com/shuding/nextra/issues/1901
