### ISSUE TITLE
navigation focus is cut off

### ISSUE THREAD

**Issue by n1ru4l** [shuding/nextra#1934]
When navigating with tabs the navigation highlight shadow/outline is a cut-off on the left and right side

<img width="292" alt="image" src="https://github.com/the-guild-org/docs/assets/14338007/27edbaf8-669f-4d9f-b456-d7c27903f236">

https://github.com/the-guild-org/docs/issues/1104

**Comment by B2o5T** [comment]
Duplicate https://github.com/shuding/nextra/issues/1432
