### ISSUE TITLE
Markdown extension isn't support <details> and <summary> tags

### ISSUE THREAD

**Issue by Osmyslitelny** [shuding/nextra#1936]
Looks like *.md file isn't support  `<details> <summary>` and  parse them as code block. 

*.mdx extension supports them and I can collapse/expand it. 

If *.md extension supported it too, it would be amazing.

```md
<details open>
<summary>Shopping list</summary>
      bla-bla
</details> 
```

**Comment by B2o5T** [comment]
pr welcome
