### ISSUE TITLE
Accessing static .html breaks layout and hydration error

### ISSUE THREAD

**Issue by zburk** [shuding/nextra#1941]
When using `next export` and accessing the generated `.html` directly, it creates a React hydration error. If I remove the `.html` everything loads correctly. 

Steps to reproduce:
1. Clone `nextra-docs-template` repo
2. Update `next.config.js` to:
```
module.exports = withNextra({
  images: {
    unoptimized: true
  }
})
```
3. Run `next build` and `next export`
4. Access `/` and `/index.html` to compare results

![Screenshot 2023-06-06 at 9 48 49 PM](https://github.com/shuding/nextra/assets/5782327/5edfa8c5-c9d4-45c1-8384-c8e78c794a4b)
![Screenshot 2023-06-06 at 9 48 53 PM](https://github.com/shuding/nextra/assets/5782327/7dd822d4-deb9-4b79-aadf-2ec0bb6bcac6)

**Comment by zburk** [comment]
After digging around, `__nextra_internal__` is returning different `pageMap` values and missing the `theme` property

**Comment by B2o5T** [comment]
should be fixed by https://github.com/shuding/nextra/pull/1943
