### ISSUE TITLE
Vercel deploy error because of nextra/components

### ISSUE THREAD

**Issue by z4roc** [shuding/nextra#1946]
Hello, I tried out the Built in Callout Component, and it causes an error

Type error: Module '"nextra/components"' has no exported member 'Callout'.

Am I missing something to use the built in components properly?

npm run build and compile was successful. only vercel deploy is failing.

**Comment by Jeffzholy** [comment]
pls refer to this https://github.com/shuding/nextra/issues/1676

**Comment by B2o5T** [comment]
@z4roc you are using not latest version of nextra, update to 2.8.0

**Comment by z4roc** [comment]
Hello, please check your `pnpm-lock.yaml`. In my case an old version of nextra was used in the dependencies section.
Deleting the pnpm-lock.yaml file worked for me.

After that I could build the project and reference the `Callout`

```jsx
import { Callout } from "nextra-theme-docs";

<Callout type="info" emoji="ℹ">
  Die Inhalte der Website werden aktuell konstant gewartet, also sollte ein
  Thema fehlen, dann wird es bestimmt bald hier erscheinen!
</Callout> 
```

Deploy on vercel worked as well
https://pruefungsvorbereitung.aktamirov.de
