### ISSUE TITLE
SEO props are duplicated with Nextra defaults

### ISSUE THREAD

**Issue by steebchen** [shuding/nextra#1957]
When you specify the following config:

```
useNextSeoProps() {
  return {
    titleTemplate: '%s – Prisma Client Go',
    description: 'Prisma Client Go is an auto-generated and fully type-safe database client',
    openGraph: {
      type: 'website',
      locale: 'en_US',
      url: 'https://goprisma.org',
      description: 'Prisma Client Go is an auto-generated and fully type-safe database client',
      site_name: 'Prisma Client Go',
      title: 'Prisma Client Go',
    },
    twitter: {
      handle: '@steebchen',
      site: '@steebchen',
    },
  }
},
```

The generated HTML reflects that, but there's duplicate Nextra meta tags:

<img width="478" alt="image" src="https://github.com/shuding/nextra/assets/5013932/4e936d6e-3a56-4559-935e-f66eff2b256d">

I'm using the docs theme.

See exact config here:

https://github.com/prisma/prisma-client-go/blob/new-docs/docs/theme.config.tsx

**Comment by B2o5T** [comment]
It’s because `nextra-theme-docs` has default value for `head` option
https://github.com/shuding/nextra/blob/5eef7d7ad5aa2ac8a13bcc83ec6f01c5ab73a019/packages/nextra-theme-docs/src/constants.tsx#L243
You should set `head: null`

**Comment by steebchen** [comment]
I see, it worked. Thanks!

**Comment by louielyl** [comment]
Off topic: 
I came to this post because I couldn't remove the default `robots` meta tag generated by `nextra-theme-docs`.
Problem solved by modifying the `noindex` & `nofollow` properties in `useNextSeoProps`.
