### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'flexsearch')

### ISSUE THREAD

**Issue by webdeb** [shuding/nextra#1963]
Just started with **nextra-create-app**. Unfortunately, I could't resolve the flexsearch error, besides some wrong imports:

* `import Bleed from "nextra-theme-docs/bleed";` -> import Bleed from "nextra-theme-docs"`
* `import Callout from "nextra-theme-docs/callout";` -> `import Callout from "nextra-theme-docs";`

However, the flexsearch problem seems to be a wrong config in theme:
theme.config.js

```
search: true
```

The docs says it should be an object. https://nextra.site/docs/docs-theme/theme-configuration#search

The result is an error:
<img width="773" alt="Bildschirm­foto 2023-06-13 um 12 49 42" src="https://github.com/shuding/nextra/assets/14992140/758e1f8d-f837-4147-87e5-a1b59ff5bee4">

But I also tried to change the value to an object for test:

```
  search: {
    component: ({ className, directories }) => <div>Search...</div>,
    emptyResult: "Nothing found",
    loading: "Searching..",
    error: "Search error",
    placeholder: "Type smth..",
  },
```

But got the same error. Whats missing?

**Some info:**

Node: v20.2.0
NPM: 9.6.6

```
 "dependencies": {
    "next": "13.4.5",
    "nextra": "2.7.1",
    "nextra-theme-docs": "2.7.1",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  }
```

**Comment by B2o5T** [comment]
I don’t maintain nextra-create-app. Feel free to take a look at working examples under `examples` folder

**Comment by webdeb** [comment]
Oh, I though it was official.. thank you for the hint 👍

**Comment by burhanshakir** [comment]
@webdeb  @dimaMachina  how did you resolve this ?
