### ISSUE TITLE
Request: option to disable navigation bar?

### ISSUE THREAD

**Issue by jeloi** [shuding/nextra#1969]
Context is I want a fullscreen landing page for my main index.tsx.

It'd be great to have an option to put in "theme" for a page, similar to disabling sidebar:
```
    "theme": {
      "navigation": false,
}
```

I tried hacking it by overriding the Navigation component but this is far from ideal because it relies on checking the url, and hides the nav after it renders:

```
function Navigation(props) {
  // get current url path, minus the host, check if its the root e.g /

  useEffect(() => {
    if (typeof window !== 'undefined' && window.location.pathname == '/') {
      // find css selector .nextra-nav-container and make it display none
      const nav = document.querySelector('.nextra-nav-container');
      if (nav) {
        nav.style.display = 'none';
      }
    }
  }, []);

  return <Navbar {...props} />;
}
```

Thanks for the great project!

**Comment by B2o5T** [comment]
I don't this option will be useful for folks

**Comment by jeloi** [comment]
:/  at least one person will find it useful! This is the only opinionated UI element that's not configurable and preventing a specific given page from being completely customizable, which would be a nice door to have open.

**Comment by mkmuriithi** [comment]
Being able to hide the navbar for specific pages (like the landing page) would be very useful

**Comment by dimaMachina** [comment]
navbar can be already hidden via `theme.navbar?: boolean` in `_meta.json`

**Comment by mkmuriithi** [comment]
thanks, I couldn't find it in the docs, adding it to the docs would be a good first issue to contrib
