### ISSUE TITLE
Can't import static images using next/image

### ISSUE THREAD

**Issue by Laxmanan-Krishnapillai** [shuding/nextra#1970]
In [(Next docs)](https://nextjs.org/docs/pages/building-your-application/optimizing/images#local-images), there is the following example, which is what I am trying to do:
```tsx
import Image from 'next/image'
import profilePic from '../public/me.png'
export default function Page() {
  return (
    <Image
      src={profilePic}
      alt="Picture of the author"
    />
  )
}
```
But I get an error: `Module not found: Can't resolve './screenshot.png'`
I am using the docs theme and made an example in Stackblitz:
https://stackblitz.com/edit/stackblitz-starters-ghzdm6?file=pages%2Fabout.mdx

**Comment by B2o5T** [comment]
your image path path is invalid, and doesn't point to right place

**Comment by Laxmanan-Krishnapillai** [comment]
Ah ok, thanks that makes sense. I thought I could use a relative URL in the import.
