### ISSUE TITLE
Rehype Pretty Code Multiple themes not supported

### ISSUE THREAD

**Issue by jay3332** [shuding/nextra#1974]
https://rehype-pretty-code.netlify.app, scroll down to *Multiple themes (dark/light mode)*

Rehype Pretty Code allows the specification of multiple themes in `rehypePrettyCodeOptions`, which generates multiple code blocks for every theme allowing for multiple custom themes.

It appears inline code-blocks are correctly handled, however multiline codeblocks only show one of the themes:

Dark theme (correct behavior):
![image](https://github.com/shuding/nextra/assets/40323796/7f798fea-6942-4cde-8ff2-d3a94110256b)

Light theme (inline code-blocks display properly, however there no light-theme multiline codeblocks are rendered):
![image](https://github.com/shuding/nextra/assets/40323796/088f839b-dbba-4387-a78b-61a21258beb6)

Nextra config:
```ts
const withNextra = nextra({
  ...
  mdxOptions: {
    rehypePrettyCodeOptions: {
      theme: {
        dark: JSON.parse(readFileSync('./public/syntax/arctis_dark.json', 'utf-8')),
        light: JSON.parse(readFileSync('./public/syntax/arctis_light.json', 'utf-8')),
      },
      getHighlighter: options => getHighlighter({
        ...options,
        langs: [...]
      })
    }
  },
})
```

**Comment by B2o5T** [comment]
pr welcome

**Comment by danielmarinq** [comment]
Is there expected support for multiple themes since marking #1992 as completed?

**Comment by dimaMachina** [comment]
in v2 not, in v3 alpha we need update rehype-pretty-code

**Comment by dimaMachina** [comment]
@danielmarinq available in https://github.com/shuding/nextra/releases/tag/nextra%403.0.0-alpha.17
