### ISSUE TITLE
Change logo color in dark theme

### ISSUE THREAD

**Issue by IlirEdis** [shuding/nextra#1975]
Im using a svg react component logo. I can change its color using props.
Is there something like changing its color conditionally based on the theme, like this: 

<img width="526" alt="Screenshot 2023-06-17 at 16 43 52" src="https://github.com/shuding/nextra/assets/128377763/b3d8465b-17a5-45b4-b736-3ebcaf827f70">

**Comment by B2o5T** [comment]
sure you can you need to import useTheme hook
https://github.com/pacocoursey/next-themes#usetheme-1

that reexported from nextra-theme docs

**Comment by IlirEdis** [comment]
Thanks for the fast reply!

I'm getting `TypeError: Cannot read properties of null (reading 'useContext')`

<img width="495" alt="Screenshot 2023-06-17 at 17 08 22" src="https://github.com/shuding/nextra/assets/128377763/1afb23c4-cd49-4f36-a54c-57670c5aee53">

<img width="979" alt="Screenshot 2023-06-17 at 17 08 47" src="https://github.com/shuding/nextra/assets/128377763/160456a9-d124-4b8c-8f71-ad72db786051">

Btw, i installed Nextra on an existing Nextjs project.

**Comment by B2o5T** [comment]
You can use react hooks only inside components

**Comment by IlirEdis** [comment]
I get the same from inside `Logo.tsx`: 

<img width="971" alt="Screenshot 2023-06-17 at 17 30 10" src="https://github.com/shuding/nextra/assets/128377763/0ec33bb6-4abe-4d56-a230-b19811a51c5b">

**Comment by B2o5T** [comment]
This is not a place of asking general react questions, please read docs on how to use react hooks

**Comment by IlirEdis** [comment]
I understand, but im using countless hooks through my app and this is the only one thats not working. 
I also understand that maybe the issue is the way im implementing Nextra (on an existing project and not as a standalone app), so since this is not a known issue, thanks for the help so far!

**Comment by TheMikeyRoss** [comment]
@IlirEdis did you figure it out? it seems theme is returning undefined 

``` jsx
  logo: () => {
    const { resolvedTheme, theme } = useTheme()
    console.log("theme", theme); // returns undefined
    console.log("resolved theme", resolvedTheme);  // returns undefined
    return (
      <Image
        alt="Sikka Logo"
        height={90}
        width={150}
        src={resolvedTheme ? whiteLogo : blackLogo}
      />
    );
  },
```

**Comment by IlirEdis** [comment]
Hi @TheMikeyRoss. I stopped using Nextra and went with a custom built docs. B2o5T in his comment above was right that i wasn't using the hook the right way. Not that i didnt know how to, but somehow i got confused. His comment could be extracted simply into a "move `const { theme } = useTheme()` line inside the function" instead of telling me what should i learn in general. 
So in your case maybe you should check if your `useTheme` import is right: `import { useTheme } from "nextra-theme-docs";`
My logo is an svg so in my code i did this: 


```
import { useTheme } from "nextra-theme-docs";

export default function Logo(props: SvgProps) {
  const { theme, systemTheme } = useTheme();
  return (
      <svg
        xmlns='http://www.w3.org/2000/svg'
        viewBox='0 0 159.5 49.4'
        fill={theme === "dark" || systemTheme === "dark" ? "#fff" : props.color} // <---- this code
        width={props.width}
        height={props.height}
        role='img'
      >
      ...

```
