### ISSUE TITLE
[Future Request] Compact menu bar option

### ISSUE THREAD

**Issue by tamagoez** [shuding/nextra#199]
Usually menu bar is render with expand.
But some users who made so many pages, menu bar become so long.
That makes hard to find page.

So, I suggest to add option what makes compact menu bar default.
We can set it at theme.config.js.

Thanks.

**Comment by B2o5T** [comment]
I think it was implemented here https://github.com/shuding/nextra/pull/605

**Comment by dimaMachina** [comment]
This was added in mentioned pr
