### ISSUE TITLE
Is there such a component like <Mdx>Hello, **mdx**</Mdx>?

### ISSUE THREAD

**Issue by webdeb** [shuding/nextra#1994]
Lets say we have a custom MathBlock Component to add additional styles like borders etc. to the Math expression:

```
<MathBlock>
$C=\frac{Q}{V}$
</MathBlock>
```

This works so far.

Now we want to include some additional text explaining the expression, we also want to style it relative to it, but we want to use markdown for it.

```
<MathBlock explaination={`wants to add **mdx** string`}>
$C=\frac{Q}{V}$
</MathBlock>
```

This does not work, obviously.

Would be nice to have a component like <Mdx></Mdx>

```
<MathBlock explanation={<Mdx>
  where **C** represents the capacitance in Farads (**F**), **Q** is the charge stored on the capacitor in Coulombs (**C**), and **V** is the voltage across the capacitor in Volts (**V**).
</Mdx>}>
$C=\frac{Q}{V}$
</MathBlock>
```

So which component could we use to render mdx?

**Comment by webdeb** [comment]
Ok, found out how to create such a component, so Mdx can be used as Props.

```jsx
import { evaluateSync } from "@mdx-js/mdx";
import * as provider from "@mdx-js/react";
import { useMDXComponents } from "nextra/mdx";
import * as runtime from "react/jsx-runtime";

export default function Mdx({ children }) {
  const { default: MDXContent, ...rest } = evaluateSync(children, {
    ...runtime,
    ...provider,
    useMDXComponents,
    format: "mdx",
    development: false,
  });

  return <MDXContent />;
}
```
You can use it like

```mdx
export function Counter({ label }) {
  // const [count,..  your counter.. logic..

   return <div>
      {label}: {count}
   </div>
}

# Hello

<Counter label={<Mdx>Some **mdx** counter label</Mdx>}
```

---

Still one question remaining, how to add all the nextra plugins like katex to it, can't get the latex formats rendered inside.. Would be a nice hint.

**Comment by DOROMOLLL** [comment]
> Ok, found out how to create such a component, so Mdx can be used as Props.
> 
> ```js
> import { evaluateSync } from "@mdx-js/mdx";
> import * as provider from "@mdx-js/react";
> import { useMDXComponents } from "nextra/mdx";
> import * as runtime from "react/jsx-runtime";
> 
> export default function Mdx({ children }) {
>   const { default: MDXContent } = evaluateSync(children, {
>     ...runtime,
>     ...provider,
>     useMDXComponents,
>     format: "mdx",
>     development: false,
>   });
> 
>   return <MDXContent />;
> }
> ```
> 
> You can use it like
> 
> ```mdx
> export function Counter({ label }) {
>   // const [count,..  your counter.. logic..
> 
>    return <div>
>       {label}: {count}
>    </div>
> }
> 
> # Hello
> 
> <Counter
>   label={<Mdx>Some **mdx** counter label</Mdx>}
> />
> ```
> 
> Still one question remaining, how to add all the nextra plugins like katex to it, can't get the latex formats rendered inside.. Would be a nice hint.

Seems that some of Nextra's rendering features are not functioning with this, such as superlinks following the title or code linting within code blocks.

**Comment by dimaMachina** [comment]
Nextra has exported Playground component https://nextra.site/docs/guide/advanced/playground
