### ISSUE TITLE
Navbar blur not working when using svg logo

### ISSUE THREAD

**Issue by IlirEdis** [shuding/nextra#2004]
Im importing an svg logo to the navbar but it disables the blur effect when using this logo, however the blur effect works when hovering the logo. Check the video below:

https://github.com/shuding/nextra/assets/128377763/5e3e09e4-df54-4356-bacd-f2e1ecfce49e

If i just use a string instead of the svg logo it works fine.

Heres a [codesandbox](https://codesandbox.io/p/github/IlirEdis/docs-sandbox/draft/fervent-curran?file=%2Fsrc%2Fpages%2Fdocs%2Findex.mdx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clj74vk6h000b3b6mw4bjevyl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clj74vk6h000d3b6mwryfphjs%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B36.27918877427348%252C63.72081122572652%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clj74vk6h000b3b6mw4bjevyl%2522%253A%257B%2522id%2522%253A%2522clj74vk6h000b3b6mw4bjevyl%2522%252C%2522activeTabId%2522%253A%2522clj7525at00wy3b6lcbflakji%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fpages%252Fdocs%252Findex.mdx%2522%252C%2522id%2522%253A%2522clj7525at00wy3b6lcbflakji%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clj74vk6h000d3b6mwryfphjs%2522%253A%257B%2522id%2522%253A%2522clj74vk6h000d3b6mwryfphjs%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clj74vzmi00ev3b6maji0p5kh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fdocs%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clj74vzmi00ev3b6maji0p5kh%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) of the issue

Also how can remove the hover opacity effect on the logo?

_p.s i know i can create a custom css file and override these but i'd like to go the official way first then go with customizations if theres no option_

Thanks!

**Comment by B2o5T** [comment]
can't reproduce, link 404
