### ISSUE TITLE
sidebar.autoCollapse: true is not working

### ISSUE THREAD

**Issue by ansi2u** [shuding/nextra#2007]
I want the sidebar to open only 1 level at a time, followed the documentation & applied the setting via `theme.config.js` file. But I keep getting an error in the console `Unrecognized key(s) in object: 'autoCollapse'. Path: "sidebar`. 

Not sure what is missing or if this functionality has been disabled. My `defaultMenuCollapseLevel` setting is set to `1`

**Comment by B2o5T** [comment]
It was not released, try now to install latest nextra
