### ISSUE TITLE
Sidebar showing all headings from multiple steps in different tabs

### ISSUE THREAD

**Issue by d1onys1us** [shuding/nextra#2011]
## Description of problem
I am using tabs in my nextra site. When using the "steps" feature inside of "tabs", the sidebar shows all the step headings for every tab on the page. Is it possible to dynamically show only the steps for the selected tabs? Or a way to turn off the sidebar showing the step headings in this case but still utilize the steps feature so it looks pretty?

## Screenshots
You can see the issue live here: https://taiko.xyz/docs/guides/deploy-a-contract. Here are screenshots showing the issue:

![image](https://github.com/shuding/nextra/assets/13951458/5add0143-13a2-41c7-8c47-378cfa636980)

![image](https://github.com/shuding/nextra/assets/13951458/7ce022be-0d05-455a-a947-f13992fdcfc3)

**Comment by B2o5T** [comment]
https://github.com/shuding/nextra/issues/1191
