### ISSUE TITLE
How do I remove the next and previous buttons at the bottom of a page?

### ISSUE THREAD

**Issue by james-bowers** [shuding/nextra#2019]
On some pages, I want to be able to remove, or control what pages are linked too next, instead of these being auto-generated. They sometimes push the user onto the next section, which might be completely unrelated.

<img width="867" alt="Screenshot 2023-06-27 at 17 01 55" src="https://github.com/shuding/nextra/assets/17832003/a460ffb8-b0b5-4aac-8221-556113424d92">

**Comment by C-EO** [comment]
In your `_meta.json` file, under the page you want to remove navigation for, use this.

```json
"example": {
     "title": "Example Page",
     "theme": {
        "pagination": false
      }
}
```

Read [HERE](https://nextra.site/docs/docs-theme/page-configuration#theme-components) for more info.

**Comment by james-bowers** [comment]
thanks @C-EO !
