### ISSUE TITLE
How to fix: Module not found: Can't resolve 'nextra/components'

### ISSUE THREAD

**Issue by opendeluxe** [shuding/nextra#2028]
I have a small **nextJS** application using **nextra** for my personal blog. According to the [official examples][1] in nextra, it should be possible to import some more specialized components like the `Callout`-component into a mdx-file:

    import { Callout } from 'nextra/components'

However, it doesn't work this way and gives the following error:

    Module not found: Can't resolve 'nextra/components'

My package.json looks like this:

    {
      "private": true,
      "license": "MIT",
      "scripts": {
        "dev": "next",
        "build": "node ./scripts/gen-rss.js && next build",
        "start": "next start"
      },
      "dependencies": {
        "gray-matter": "^4.0.2",
        "next": "12.0.8",
        "nextra": "^2.0.0-beta.5",
        "nextra-theme-blog": "^2.0.0-beta.5",
        "nextra-theme-docs": "^2.8.0",
        "react": "^17.0.2",
        "react-dom": "^17.0.2",
        "rss": "^1.2.2",
        "sharp": "^0.32.1"
      },
      "dependenciesMeta": {
        "nextra": {
          "injected": true
        },
        "nextra-theme-docs": {
          "injected": true
        }
      },
      "prettier": {
        "arrowParens": "always",
        "singleQuote": true,
        "tabWidth": 2,
        "trailingComma": "none",
        "semi": false
      }
    }

How to fix that?

  [1]: https://github.com/shuding/nextra/blob/main/examples/swr-site/pages/index.es-ES.mdx#L6C1-L7C1

**Comment by B2o5T** [comment]
Update to latest nextra. You use 2.0 beta

**Comment by opendeluxe** [comment]
Works. Thanks!

**Comment by arkitoure** [comment]
> Update to latest nextra. You use 2.0 beta

@B2o5T experiencing the same issue. how is this possible if launched via vercel/docs repo?

**Comment by B2o5T** [comment]
Do not reply in closed issues, update to the latest nextra to fix issue, or create a new issue with reproduction repo
