### ISSUE TITLE
<Image>-Tag is always rendered full width and height with absolute position

### ISSUE THREAD

**Issue by opendeluxe** [shuding/nextra#2029]
When using the <Image>-tag imported from 'next/image', it is always filling up the full window-size and covering all other content. I figured out that the CSS looks like this:

```
element.style {
    position: absolute;
    height: 100%;
    width: 100%;
    left: 0;
    top: 0;
    right: 0;
    bottom: 0;
    object-fit: contain;
    color: transparent;
}

```

The problematic styles are 
- position
- height
- width
- object-fit

resulting in a rendering-style that is hard to adjust for responsive designs.

Can we remove these default-settings globally?
Or how to handle that to use images in a relative position and not covering the full screen?

**Comment by B2o5T** [comment]
Please provide a reproduction

**Comment by B2o5T** [comment]
closed due to missing repro, feel free to share
