### ISSUE TITLE
Error when using search

### ISSUE THREAD

**Issue by MaciejWiatr** [shuding/nextra#203]
![image](https://user-images.githubusercontent.com/44440856/128602624-168b0480-75f5-4fc0-8947-feb73c3e66c7.png)
This error occurs when the searched page wasn't found. How can I fix it?

**Comment by fredliang44** [comment]
same here

**Comment by PabloLION** [comment]
Same here. I think adding a nullity check of `results` here solves the problem. Do you want me to PR this? @shuding 
But I don't know what feedback should be given here. 

The options I'm thinking are:
1. A pop up saying "no searching result"? 
2. A "no result" in dropdown and the <kbd>enter</kbd> key closes the dropdown

**Comment by shuding** [comment]
Should be fixed in #798.
