### ISSUE TITLE
Question: Add ellipses or similar to "shortened" example code blocks?

### ISSUE THREAD

**Issue by crookse** [shuding/nextra#2030]
Firstly, this project is awesome as hell!

I've been using it for a couple of days now and while reading through the Theme Configuration (https://nextra.site/docs/docs-theme/theme-configuration) I noticed the ellipses is shown in the referenced [theme.config.jsx](https://nextra.site/docs/docs-theme/start#create-docs-theme-config) link at the top of the page, and that page shows:

<img width="560" alt="Screen Shot 2023-07-02 at 09 51 28" src="https://github.com/shuding/nextra/assets/12766301/2446a2a2-ae0e-4f41-b1f3-d41356193aaf">

The rest of the Theme Configuration page doesn't show it. Although this is probably trivial and/or personal preference, I think it'd be helpful to add the ellipses to example code blocks that are shortened for brevity. Thoughts?

Also, maybe a description explaining why the ellipses is present could further help? Some practices I've seen are:

```
{
  hello: "world",
  ok: "then",

  // ... rest of config file

}
```
```
{
  //
  // ... config file shortened for brevity
  //

  hello: "world",
  ok: "then",
}
```

Using the above with the Footer's Copyright Information  example (https://nextra.site/docs/docs-theme/theme-configuration#copyright-information), it'd look like:

<img width="746" alt="Screen Shot 2023-07-02 at 10 13 21" src="https://github.com/shuding/nextra/assets/12766301/ab392f38-090c-483f-b8e6-9b73ae5a19f5">

**Comment by C-EO** [comment]
You know that you could do that yourself, right?

It would be your first step toward helping Nextra grow since you love it so much.

**Comment by crookse** [comment]
@C-EO, for sure! I brought up the question because I wanted thoughts from the maintainers first though. (I see your thumbs up. Thanks @B2o5T!)
