### ISSUE TITLE
useConfig docs link is broken 

### ISSUE THREAD

**Issue by kenjinp** [shuding/nextra#2038]
Inside the SEO docs there is a section talking about a `useConfig` function, with a link on the `useConfig` text which leads here: https://nextra.site/docs/docs-theme/api/use-config

However the link appears to be broken, leading to a 404

![image](https://github.com/shuding/nextra/assets/5485824/5973317c-acb6-4c13-a6ac-7240057d9616)

**Comment by B2o5T** [comment]
Duplicate https://github.com/shuding/nextra/issues/1139
