### ISSUE TITLE
[Bug] Prev/Next Links break on pages with exoctic characters

### ISSUE THREAD

**Issue by ChristopherLyon** [shuding/nextra#205]
On a page with a "Æ, Ø or Å" in the URL

![image](https://user-images.githubusercontent.com/31580672/130037120-545be7d2-c589-4df1-b21b-f1aadfdd26da.png)

Without:

![image](https://user-images.githubusercontent.com/31580672/130037274-3461eac8-9666-4dbb-832e-8f78e739e553.png)

**Comment by ChristopherLyon** [comment]
Also spaces

**Comment by B2o5T** [comment]
works fine on the latest beta 2
<img width="988" alt="image" src="https://user-images.githubusercontent.com/7361780/185751874-3f7e3a48-99d2-4a6c-b988-4591a5827232.png">
