### ISSUE TITLE
How to ignore a file from rendering as a page

### ISSUE THREAD

**Issue by mbalex99** [shuding/nextra#2053]
How do I ignore or hide a file from turning into page? I'd like import partial mdx files but not have them turn into a page.

I have a page structure that looks like

```
.
└── pages/
    └── installation/
        ├── javascript.mdx
        ├── _nodejs.mdx
        ├── _browser.mdx
        ├── java.mdx
        ├── _android.mdx
        └── _spring.mdx
```

Anything that begins with `_****.mdx` should not be rendered as a page. However, I'd still like to import them. 

For example, in `javascript.mdx`, I'd like to import `./_nodejs.mdx` and _`./browser.mdx` as a component as an include:

```mdx
import Browser from "_browser.mdx"
import NodeJS from "_nodejs.mdx"

# Installation

Here's how to install our package in the Browser

<Browser />

Here's how to install our package in NodejS

<NodeJS />

```

However, it seems these `_` mdx files still become pages and I am not sure how to disable them:

![image](https://github.com/shuding/nextra/assets/2183729/3e17ae6b-e587-4379-b78f-085a20b14913)

Is it possible to configure Nextra to ignore any files that begin with `_` or some other pattern from rendering into a page?

Thank you community, for an awesome easy-to-use package. 

Here are my package dependencies if it helps:

```
"dependencies": {
    "next": "^13.4.9",
    "nextra": "latest",
    "nextra-theme-docs": "latest",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/node": "18.11.10",
    "typescript": "^4.9.3"
  }
```

**Comment by keaganaut** [comment]
I've achieved the same result by moving the .mdx file to transclude outside of the `pages` directory. e.g. in `components`

**Comment by B2o5T** [comment]
You can do it only by moving outside of pages directory as said @keaganaut

**Comment by wminshew** [comment]
I am currently experiencing this issue with buffer files created by emacs (format `.#page` in the same dir as the file being edited). I can't seem to figure out how to tell next/nextra to ignore these files, which end up breaking the server and its hot loading capabilities any time I edit a page. Unfortunately for these I can't move them out of the directory (afaik).

```
> nextra@1.0.0 dev /Users/x/docs
> next dev

   automatically enabled Fast Refresh for 3 custom loaders
  ▲ Next.js 13.5.3
  - Local:        http://localhost:3000

 ✓ Ready in 2.2s
 ⨯ [Error: ENOENT: no such file or directory, stat '/Users/x/docs/pages/.#page.mdx'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/Users/x/docs/pages/.#page.mdx'
}
```
