### ISSUE TITLE
"nextra/components"' has no exported member 'Card'.ts(2305)

### ISSUE THREAD

**Issue by milonite** [shuding/nextra#2068]
Following docs:
https://nextra.site/docs/guide/built-ins/cards

`import { Cards, Card } from "nextra/components";`

But getting:
`Module "nextra/components"' has no exported member 'Card'.ts(2305)`

It seems there were recent changes on the Cards and I can't see it in the node modules anymore

**Comment by B2o5T** [comment]
update to latest nextra

**Comment by milonite** [comment]
> update to latest nextra

I'm on "nextra": "latest"

**Comment by hedysnike** [comment]
same error, i installed the latest nextra and i'm getting the same error
