### ISSUE TITLE
Separator Issue

### ISSUE THREAD

**Issue by Sam-tech94** [shuding/nextra#2084]
Why in this case i have a bug, when i put separator up, my navmenu router to that page does not work why ?
"---": {
    "type": "separator",
    "title": "Electrolyser Software"
  },
  "ems_toolkit": "Energy Management System Toolkit (EMS Toolkit)",
  "mobile": "Enapter Mobile App",
  "blueprint_marketplace": "Blueprint Marketplace",
  "android_mobile_app": {
    "display": "hidden"
  }

**Comment by zigang93** [comment]
due to separator route always return `#`, I already open up the PR to fix the issue

**Comment by B2o5T** [comment]
please try 2.11.0 seems this pr fixes this issue https://github.com/shuding/nextra/pull/2154
