### ISSUE TITLE
Ifram issue

### ISSUE THREAD

**Issue by Sam-tech94** [shuding/nextra#2086]
why my ifram is not rendered on the browser

<div class=" max-w-3xl" >
  <div class="videoWrapper">
    <iframe width="560" height="315" loading="lazy" src="https://www.youtube.com/embed/JpLiOJgDO4c" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </div>
</div>

**Comment by B2o5T** [comment]
Take a look at a valid example with a blog theme https://github.com/shuding/nextra/tree/main/examples/blog
