### ISSUE TITLE
Cannot find module 'nextra/filter-route-locale' or its corresponding type declarations.

### ISSUE THREAD

**Issue by PSIget** [shuding/nextra#2089]
```ts
import filterRouteLocale from "nextra/filter-route-locale";

return filterRouteLocale(getPagesUnderRoute("/blog"), locale, defaultLocale).map((page: Page) => {
...my code
});
```

Return TS error `Cannot find module 'nextra/filter-route-locale' or its corresponding type declarations.`

**Comment by guilherssousa** [comment]
Maybe you can't import it because its not being directly exported on nextra's package.json: [package.json](https://github.com/shuding/nextra/blob/aa69c7f5dd9b0029e8110ba8f3e311c089ea5dcf/packages/nextra/package.json#L11)

**Comment by PSIget** [comment]
Yes, indeed, this was a mistake. But I decided a little differently, I created a file in the root of the project `nextra.d.ts`:
```ts
declare module "nextra/filter-route-locale"
```
