### ISSUE TITLE
New pages and updated menu not rendering on vercel

### ISSUE THREAD

**Issue by ajthinking** [shuding/nextra#2090]
* got a fresh copy of nextra with the docs theme
* add/edit some pages
* deploy to vercel, all good
* add new pages, deploy - does not see the new pages
* changes to *existing pages* do update properly
* If I manually via url go to /a-newly-created-page I can see it and then it will also show in the menu (briefly)
* when navigting away from it the menu item disapears
* I tried specifiying the new page in meta file but it did not matter

Repo: https://github.com/ajthinking/data-story-docs
Deployment: https://data-story-docs.vercel.app/
New pages example: brand.mdx and customize.mdx
Am I missing some config or build step here?

**Comment by terrymun** [comment]
I'm also experiencing a similar issue here: the sidebar appears to be stale on old pages that were not changed.

**Comment by rbkayz** [comment]
OMG yes! Exactly the same. 

Works fine on local dev environment. Does not seem to update on build

**Comment by earth2travis** [comment]
I am also experiencing this issue

**Comment by earth2travis** [comment]
> I am also experiencing this issue

Seem to be resolved by performing a Redeploy in Vercel

**Comment by oluwatobiss** [comment]
> > I am also experiencing this issue
> 
> Seem to be resolved by performing a Redeploy in Vercel

Thanks, @earth2travis. The redeployment tip in Vercel worked for me!

**Comment by CntrlX** [comment]
after testing, it seems that Vercel is caching the old unchanged files and reusing them, because of this the new routes are not rendered in the old files.

**Comment by B2o5T** [comment]
duplicate https://github.com/shuding/nextra/issues/1564#issuecomment-1447419595
