### ISSUE TITLE
overflow on heading

### ISSUE THREAD

**Issue by d1onys1us** [shuding/nextra#2095]
![image](https://github.com/shuding/nextra/assets/13951458/fa793254-a20f-444e-954a-a928ac20f746)

as you can see in the photo the heading is causing an overflow when it should be word wrapped. I can send the MDX file here if it is helpful, thank you.

**Comment by B2o5T** [comment]
should be fixed in 2.11.0
<img width="364" alt="image" src="https://github.com/shuding/nextra/assets/7361780/d4a20c0a-cc27-4713-9be8-0a60c07dce32">
