### ISSUE TITLE
Moving Search component

### ISSUE THREAD

**Issue by Shawiizz** [shuding/nextra#2098]
Hi, I'm currently developing a Nextjs website, which has pages in .tsx, and Nextra docs in /pages/docs folder.

My website already have a header on all pages in a separated component, so I'm wondering if it's possible to move the Nextra search component to my website header so that I can have it in the whole website. If this is possible, can somebody explain me how to do it please?

If you need more info, please ask me :+1:

**Comment by B2o5T** [comment]
Duplicate https://github.com/shuding/nextra/issues/1435
