### ISSUE TITLE
Search: 404 Appears in Results

### ISSUE THREAD

**Issue by eerikson** [shuding/nextra#2099]
It appears that all pages are indexed, including built-in overrides in Next apps (404, 50x, etc). This means that we see 404 in search results, including in the main Nextra docs site:
<img width="725" alt="image" src="https://github.com/shuding/nextra/assets/1228559/c5c39c43-62de-4b6f-b671-645d1155c1bf">

Perhaps there's a way to either: 
* hook into known overridable Next templates and auto-ignore indexing these pages?
* provide an escape hatch for auto-indexing certain pages?

**Comment by AronBe** [comment]
Also for **Blog Theme**, 404 appears among `posts`. I can change `type` in FrontMatter to `page` but then it appears among pages

<img width="723" alt="image" src="https://github.com/shuding/nextra/assets/32416348/2e35a48b-57e8-4818-947c-0c0c35bbef9a">
<img width="316" alt="image" src="https://github.com/shuding/nextra/assets/32416348/80716d87-f941-4929-ab9f-27995fbda30e">

**Comment by C-EO** [comment]
@B2o5T  I get the same issue
Did the search indexer break? This didn't use to happen before.

**Comment by C-EO** [comment]
![image](https://github.com/shuding/nextra/assets/85847352/27ae21f4-8459-4b88-a140-be97cc1f1301)

**Comment by llllvvuu** [comment]
I propose fix: https://github.com/shuding/nextra/pull/2106

**Comment by eerikson** [comment]
I think this happens with any MD(X) file found inside of `pages`, so it may also happen with `500` or any other reserved Next routes (haven't verified).

**Comment by B2o5T** [comment]
@AronBe use regular 404.jsx or 500.tsx for blog theme
