### ISSUE TITLE
Redirect folder without index page to first occurring child page

### ISSUE THREAD

**Issue by terrymun** [shuding/nextra#2105]
I run into a scenario where I have several folders in my Nextra site, but only some of them have [index pages](https://nextra.site/docs/docs-theme/page-configuration#folders-with-index-page).

```text
pages/
├─ folder-1/
│  └─ subpage-1.mdx
│
├─ folder-2/
│  └─ subpage-2.mdx
│
├─ folder-3/
│  └─ subpage-3.mdx
│
├─ folder-1.mdx
└─ folder-2.mdx
```

I want to link to all these pages with their URL, e.g.: `/folder-1`, `/folder-2` and `/folder-3`. Of course of all the folders, only the first two have a corresponding index page, but `/folder-3` does not. Is it possible for requests pointing to `/folder-3` be redirected to its first child, i.e. `/folder-3/subpage-3.mdx`?

**Comment by guilherssousa** [comment]
You can set redirects on your `next.config.js` file, take a example or look at the docs: https://nextjs.org/docs/pages/api-reference/next-config-js/redirects

```js
module.exports = withNextra({
  redirects: () => {
    return [
      {
        source: "/folder-3",
        destination: "/subpage-3",
        statusCode: 302,
       }
     ];
  }
});
```

**Comment by terrymun** [comment]
@guilherssousa Yes, I could do that, but it becomes impractical when there are multiple folders. Then it comes exhaustive and overly verbose to maintain all these redirection rules.

**Comment by B2o5T** [comment]
Unfortunately, there is no way, @guilherssousa has a point
