### ISSUE TITLE
Failed to load search index

### ISSUE THREAD

**Issue by hoonliu** [shuding/nextra#2109]
I built my project by running the command below:
`next build && next export`

when I put the output on the server and search in the doc, it comes to this error:

![image](https://github.com/shuding/nextra/assets/22422393/6c1f2848-04d6-4460-8613-985e4354fde1)

Here is my next.config.js file
```js
const withNextra = require('nextra')({
  theme: 'nextra-theme-docs',
  themeConfig: './theme.config.jsx',
  defaultShowCopyCode: true,
});

module.exports = {
  ...withNextra(),
  images: {
    unoptimized: true,
  },
  basePath: '/doc',
};

```

and the error on the console:

![image](https://github.com/shuding/nextra/assets/22422393/7749951d-d0f7-48e9-ad2d-7159e96e2bdc)

**Comment by hoonliu** [comment]
my bad, my IIS server does not serve `application/json` type well

**Comment by drewstone** [comment]
@hoonliu what is your web config? I'm having similar issue but unsure how to fix with your provided solution.

**Comment by hoonliu** [comment]
> @hoonliu what is your web config? I'm having similar issue but unsure how to fix with your provided solution.

Sorry it's not a personal project of mine and I no longer have access to that file
