### ISSUE TITLE
[Bug] Sub Doc pattern `Seperator` page type at first sequence of `_meta.json` will cause navigation menu href become `#`

### ISSUE THREAD

**Issue by zigang93** [shuding/nextra#2110]
I found out that this issue only happen on [sub doc](https://nextra.site/docs/docs-theme/page-configuration#sub-docs) pattern.

Navigation menu href link will be come `#`, if using `_meta.json` below: 

```js
// _meta.json at frameworks
  "-- Guide": {
    "type": "separator",
    "title": "Guide"
 },
{
  "react": {
    "title": "React"
  },

}
```

below will work perfectly: 
```js
// _meta.json at frameworks
{
  "react": {
    "title": "React"
  },
  "-- Guide": {
    "type": "separator",
    "title": "Guide"
  }
}

```

**Comment by B2o5T** [comment]
please try 2.11.0 seems this pr fixes this issue https://github.com/shuding/nextra/pull/2154
