### ISSUE TITLE
Using dark mode toggle in anywhere other than footer

### ISSUE THREAD

**Issue by muradtaghiyev05** [shuding/nextra#2117]
Is there any way that I can use the dark mode toggle button in navbar for example? Because I do not know how to reach that component to use it anywhere else.

**Comment by B2o5T** [comment]
yeah, `nextra-theme-docs` exports `ThemeSwitch` component that you can add in navbar via https://nextra.site/docs/docs-theme/theme-configuration#customize-the-navbar `navbar.extraContent`
