### ISSUE TITLE
Use type "menu" in navbar but with separate doc sections in sidebar

### ISSUE THREAD

**Issue by cfranceschi-ledger** [shuding/nextra#2123]
Hello,

Would it be possible to have my sections in a dropdown menu, but that every section is separate on the side bar, as if I used `"type":"page"`?

![nextra-dropdown](https://github.com/shuding/nextra/assets/84771902/ad72a63f-5acb-4b31-83c2-561d8c184d57)

**Comment by C-EO** [comment]
I don't think its possible. @B2o5T please help out here

**Comment by B2o5T** [comment]
I don't understand the question

**Comment by cfranceschi-ledger** [comment]
For exemple if I click on Token in the dropdown menu, I only want the token doc on the left sidebar.

**Comment by C-EO** [comment]
@cfranceschi-ledger I don't think what you're asking for is possible without modifying the codebase itself

**Comment by cfranceschi-ledger** [comment]
Thank you @C-EO
