### ISSUE TITLE
Add doc for adding google analytics to doc theme

### ISSUE THREAD

**Issue by oluwatobiss** [shuding/nextra#2128]
It will be helpful to guide users on adding Google Analytics to their doc site.

I know issue  #1359 already addressed it. But having the steps documented will make it quicker for users to implement. (It took me a lot of searching to find out how).

I'm happy to take on this task if you don't mind.

**Comment by C-EO** [comment]
Go ahead then. The Nextra team is quite busy and like all devs, can't attend to every problem at once. Your help is appreciated

**Comment by oluwatobiss** [comment]
Is there any contributing note you want me to be aware of?

**Comment by 101sam** [comment]
We are using Google Tag Manager to push google analytics. 
I have some docs we prep if it helps to speed the documentation process. however, lately, we are getting cross-site errors when tart use `import Script from "next/script";`
see [ issue #2130](https://github.com/shuding/nextra/issues/2130)

**Comment by oluwatobiss** [comment]
Absolutely. Please do share your docs—every help is most welcome. Thanks.

**Comment by C-EO** [comment]
> Go ahead then. The Nextra team is quite busy and like all devs, can't attend to every problem at once. Your help is appreciated

@shuding and @B2o5T aren't easy to reach. So you'll have to be patient

**Comment by carlgieringer** [comment]
Here's another example of adding to Nexta: https://github.com/Howdju/howdju/pull/714. I only load the tag conditionally based on a consent cookie.

**Comment by dimaMachina** [comment]
https://github.com/shuding/nextra/pull/2137#issuecomment-2439003676
