### ISSUE TITLE
`<HeadingAnchor />` and `<HTML.HeadingTag />`

### ISSUE THREAD

**Issue by shenlong616** [shuding/nextra#2136]
- if i use `Markdown syntax` everything is fine!
- but if using `HTML syntax`, `<HeadingAnchor />` and `<TableOfContents />` don't work 🥲
- tested in `file.mdx`

![image](https://github.com/shuding/nextra/assets/15698245/118db334-ccc7-4b12-b949-a5e99c61a6bf)

- `Markdown syntax`

![image](https://github.com/shuding/nextra/assets/15698245/cea8c4c0-4c53-4733-a5c5-d606a376f62a)

- `HTML syntax`

![image](https://github.com/shuding/nextra/assets/15698245/e128f4d4-219a-43fa-89fe-4f799480d4bb)

**Comment by B2o5T** [comment]
working as expected, see https://nextra.site/docs/guide/advanced/table#why-this-happens

**Comment by B2o5T** [comment]
I replied to you why your headings are styled

Extracting their values to TOC is too tricky and will be not fixed

**Comment by B2o5T** [comment]
Intendent behaviour and will be not fixed
