### ISSUE TITLE
Each tab shows its own representation of table of contents.

### ISSUE THREAD

**Issue by AsynchronousAI** [shuding/nextra#2139]
![Screenshot 2023-08-08 at 2 57 07 PM](https://github.com/shuding/nextra/assets/72946059/b49ae2f8-ff06-4a74-a3b4-6591563f6b91)
![Screenshot 2023-08-08 at 2 57 27 PM](https://github.com/shuding/nextra/assets/72946059/8d995a10-8c99-422b-9a1e-e2d69c5a4087)
Also I deleted a mdx file from the pages folder and __meta.json but it still shows up

**Comment by B2o5T** [comment]
your title is different from your issue

duplicate https://github.com/shuding/nextra/issues/1191
