### ISSUE TITLE
GitLab feedback.labels

### ISSUE THREAD

**Issue by dacevedo12** [shuding/nextra#2169]
labels are only included in the URL for GitHub but not for GitLab

https://github.com/shuding/nextra/blob/main/packages/nextra-theme-docs/src/utils/get-git-issue-url.ts#L18

**Comment by B2o5T** [comment]
Would you want to submit a PR?

**Comment by dacevedo12** [comment]
Sure, I can take a look later. GitLab doesn't support labels via query parameters but a workaround using quick actions in the issue description gets the job done

`issues/new?issue[title]=test&issue[description]=%0A%0A/label%20~label-goes-here`
