### ISSUE TITLE
Javascript code block does not color correctly

### ISSUE THREAD

**Issue by nazmifeeroz** [shuding/nextra#217]
Hi all!
I'm using nextra to write my blog posts. There seem to be an issue when it tries to render JS block code. 
![image](https://user-images.githubusercontent.com/26022852/132093681-455a523f-dd50-4100-b58a-459050021568.png)

The color is off. Is there some configs I've missed?

**Comment by phc5** [comment]
Hey @nazmifeeroz, I noticed @shuding's website has this [css file](https://github.com/shuding/site/blob/master/styles/main.css) added in his [_app.js](https://github.com/shuding/site/blob/master/pages/_app.js) which should make code readability better. 

I'm not sure why the default styling make the js code unreadable... maybe worth fixing.

**Comment by nazmifeeroz** [comment]
Hey @phc5 ! That works! Thank you very much!
