### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by dacevedo12** [shuding/nextra#2174]
I'm trying to build a documentation site with about 3000+ .md files, only 1 .mdx and it runs out of memory.

Tried increasing max-old-space-size to 8192 without success.

```
- info Linting and checking validity of types  
- info Creating an optimized production build .
<--- Last few GCs --->

[79426:0x128008000]   552411 ms: Scavenge 4050.8 (4087.3) -> 4050.4 (4098.3) MB, 2.6 / 0.0 ms  (average mu = 0.275, current mu = 0.246) allocation failure 
[79426:0x128008000]   552418 ms: Scavenge 4057.3 (4098.3) -> 4056.7 (4099.3) MB, 3.0 / 0.0 ms  (average mu = 0.275, current mu = 0.246) allocation failure 
[79426:0x128008000]   552423 ms: Scavenge 4058.2 (4099.3) -> 4057.5 (4120.8) MB, 4.0 / 0.0 ms  (average mu = 0.275, current mu = 0.246) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

Using Node.JS 16x on a M2 Mac with 16GB of RAM

Are there any configs in nextra that can help optimize the build process?

**Comment by B2o5T** [comment]
https://github.com/shuding/nextra/issues/1618#issuecomment-1461217925

**Comment by dacevedo12** [comment]
The project didn't have an _app file, so I created an empty one.

This time it took 2:30 hours, but hey, it didn't run out of memory 😅

**Comment by dacevedo12** [comment]
<img width="955" alt="image" src="https://github.com/shuding/nextra/assets/29694570/b58ae2a9-4155-4296-acdc-e9c9edb8fc93">

I tried disabling flexsearch, swcMinify without success. Still wants over 4GB of RAM and takes 1 hour +

**Comment by B2o5T** [comment]
Please provide reproduction repo

**Comment by dacevedo12** [comment]
At the last moment I figured it out. _app.mdx must not be empty

```
export default function Nextra({ Component, pageProps }) {
  return <Component {...pageProps} />;
}
```

I totally missed that detail. Would be a good improvement for the documentation

**Comment by B2o5T** [comment]
@dacevedo12 feel free to contribute
