### ISSUE TITLE
[Feature Request] Central point to import jsx components

### ISSUE THREAD

**Issue by inezabonte** [shuding/nextra#218]
It would be awesome if Nextra had a central point to import jsx components that may be shared
across all mdx pages so we can use them without importing the components individually in each file.

Here is an example of where this is being used in the [next-mdx-remote](https://github.com/hashicorp/next-mdx-remote#frontmatter--custom-processing) package

**Comment by B2o5T** [comment]
Supported in https://github.com/shuding/nextra/releases/tag/nextra-theme-docs%402.0.0-beta.13
