### ISSUE TITLE
Breadcrumb Initial Entry

### ISSUE THREAD

**Issue by ElementalCrisis** [shuding/nextra#2180]
Hello,

Can we have an option to specify an initial entry, either plain text or custom link for the breadcrumbs?

**Comment by guilherssousa** [comment]
Could you please elaborate more? You mean specify where the breadcrumb path appears or the path content?

**Comment by ElementalCrisis** [comment]
My apologies, I would like to do something like this.

Documentation > Page Name

In the above example, Documentation is not a link or parent of Page Name, in this case it would just be plain text I inputted in say the theme config file.

**Comment by C-EO** [comment]
Why would u do that

**Comment by C-EO** [comment]
and please give examples of where u saw this

**Comment by ElementalCrisis** [comment]
For my use, it's just so I can put "Documentation" as the root, but you could also make the initial breadcrumb a link back to your site if its separate. I don't have any examples to provide of the top of my head.

**Comment by guilherssousa** [comment]
Currently, you can't custom breadcrumb path:
The `activePath` prop on Breadcrumb component only accepts MDX files or Folders, which are normalized and filled at build time

**Comment by C-EO** [comment]
@ElementalCrisis What @guilherssousa is saying is right. But you can also create your own Nextra theme or modify your own Nextra codebase to implement what u want

**Comment by guilherssousa** [comment]
Yeah, you can patch the library to add virtually anything you want. Maybe a core maintainer can say if it makes sense to docs theme to have this feature and a PR will be welcomed

**Comment by ElementalCrisis** [comment]
Thanks for the information, I'll look into creating a custom theme.
