### ISSUE TITLE
How to render filesystem images in markdown

### ISSUE THREAD

**Issue by YikSanChan** [shuding/nextra#22]
In Gatsby, people can put images under a folder and reference the image in markdown.

Demo: https://overreacted.io/preparing-for-tech-talk-part-2-what-why-and-how/
Code: https://github.com/gaearon/overreacted.io/tree/master/src/pages/preparing-for-tech-talk-part-2-what-why-and-how

Is there a way to do so with nextra?

**Comment by shuding** [comment]
You can put your static files in the `/public` directory and they will be hosted under the root path (`/`) by Next.js. 

https://nextjs.org/docs/basic-features/static-file-serving
