### ISSUE TITLE
theme.config.js configure theme files search.emptyResult There is an exception

### ISSUE THREAD

**Issue by beher0** [shuding/nextra#2213]
When configuring search.emptyResult as other content, when searching for documents, it should prompt that "Not result found" is not centered, and the rendering is as follows
![image](https://github.com/shuding/nextra/assets/83959029/a0de5ed4-efce-49ca-889e-a0b407b6428f)

View the elements in the control panel, there are two screenshots as follows
![image](https://github.com/shuding/nextra/assets/83959029/cb64fa21-8e75-4e65-a998-32353ebbf592)
![image](https://github.com/shuding/nextra/assets/83959029/e14aae45-8615-4d3c-9997-ea5f59adea6d)

I suspect that some class names will be lost when configuring search.emptyResult

Please check the code of my configuration theme file, as follows
![image](https://github.com/shuding/nextra/assets/83959029/2fcf8bc2-7898-4de0-b56a-70403257b864)

**Comment by B2o5T** [comment]
Please write in English

**Comment by SimpleLifecst** [comment]
Sorry, I have rewritten it in English

**Comment by SimpleLifecst** [comment]
> Please write in English
Sorry, I have rewritten it in English

**Comment by C-EO** [comment]
@SimpleLifecst  please provide a link to your code repo. This will help us get to the problem root quicker

**Comment by dimaMachina** [comment]
duplicate https://github.com/shuding/nextra/issues/2450
