### ISSUE TITLE
Exclude the headings from ToC for `<Steps />`

### ISSUE THREAD

**Issue by vpavicic** [shuding/nextra#2220]
I have an issue writing the docs using the <steps> component. For the steps to be parsed as steps, they need to be H3 (not H2 or H4). All the steps that have H3 are then visible in the right-side menu, which can make a mess of it because sometimes not all steps are worthy of being a menu item + if the level is not actually H3 it looks extra messy.

All my troubles would be solved if I could somehow mark certain headings so they are not included in the right-side menu but are parsed as steps.

**Comment by B2o5T** [comment]
you can do it by

```diff
<Steps>
-### Install
+{<h3>Install</h3>}
```

more info on why it works https://nextra.site/docs/guide/advanced/table#why-this-happens 

feel free to contribute to `steps` docs

**Comment by vpavicic** [comment]
Thank you so much! Will try and update the docs!

**Comment by smartcontracts** [comment]
> you can do it by
> 
> ```diff
> <Steps>
> -### Install
> +{<h3>Install</h3>}
> ```
> 
> more info on why it works https://nextra.site/docs/guide/advanced/table#why-this-happens
> 
> feel free to contribute to `steps` docs

Main problem with this solution is that it means steps will no longer get anchor tags :-/

**Comment by ikhsangama** [comment]
yeah I also had the same issue, no anchor tags :(
