### ISSUE TITLE
Is it possible to change date language?

### ISSUE THREAD

**Issue by OrigamingWasTaken** [shuding/nextra#2223]
Hello, i'm using nextra to build a blog for my class, which is speaking french. Is there a way to change the language of the displayed dates on the posts?

Thanks in advance

**Comment by B2o5T** [comment]
https://github.com/shuding/nextra/blob/ae45aa16d7c0a7b62e7bf2c912fd80068393f8e1/examples/blog/theme.config.jsx#L24

**Comment by OrigamingWasTaken** [comment]
Sorry, I forgot to mention I used the `npx create-nextra-app` to make my project

**Comment by B2o5T** [comment]
I don't maintain `create-nextra-app`, I replied to your question
