### ISSUE TITLE
Can't set `toc.backToTop` in theme.config.tsx

### ISSUE THREAD

**Issue by davidho0403** [shuding/nextra#2237]
[https://nextra.site/docs/docs-theme/theme-configuration#table-of-contents](https://nextra.site/docs/docs-theme/theme-configuration#table-of-contents)

I'm trying to set `toc.backToTop` to true, but I got this error:

![CleanShot 2023-09-02 at 13 17 00@2x](https://github.com/shuding/nextra/assets/75478661/528796c0-80e9-488f-af1f-653137b49fcd)
![CleanShot 2023-09-02 at 13 17 27@2x](https://github.com/shuding/nextra/assets/75478661/534aaad6-e9e0-4edc-9ea1-62c492c69f12)

**Comment by B2o5T** [comment]
Update nextra-theme-docs

**Comment by davidho0403** [comment]
> Update nextra-theme-docs

Thanks
