### ISSUE TITLE
Clinking on a same origin link does a full page reload.

### ISSUE THREAD

**Issue by heyitsarpit** [shuding/nextra#226]
Given this markdown, it will create two links.
```
[deployments](/deployments)
[wikipedia](https://wikipedia.com)
```

Expected Behavior: 
Clicking on `deployments` should do a client side navigation to the `/deployments` route.
Clicking on `wikipedia` should navigate to `https://wikipedia.com` page.

Current Behavior: 
Clicking on `deployments` does a full page reload at the  `/deployments` route.

**Comment by KinnersleyM** [comment]
Getting the same here, ended up resorting to using `next/link` but would prefer the default markdown syntax to work.

```jsx
import Link from "next/link";

<Link href="/your-url"><a>link here</a></Link>

// This does not work
[link here](/your-url)
```

**Comment by KinnersleyM** [comment]
After testing this with the auto deploy version for Vercel, it appears the issue for me was having the project nested within a monorepo. I'm using turborepo. Other issues include the `id` and `#` linking to specific headers in a page.

**Comment by B2o5T** [comment]
This issue should be gone since in `nextra-theme-blog`/`nextra-theme-docs` we replace all links with NextLink that don’t starts with `https://`
