### ISSUE TITLE
Error TOC Sidebar backToTop type error

### ISSUE THREAD

**Issue by radrianhp** [shuding/nextra#2263]
I have error in TOC, when build my application, I add scroll to top in right side of the page, but have type error issue 

![image](https://github.com/shuding/nextra/assets/15336755/06e661bd-4014-4696-994b-ff26e7730e64)

can u solve this ? 

I use latest package for build my app
![image](https://github.com/shuding/nextra/assets/15336755/677bd819-953e-45b9-bd97-970da9201491)

**Comment by B2o5T** [comment]
https://github.com/shuding/nextra/issues/2237#issuecomment-1703710952

**Comment by radrianhp** [comment]
I try to run with github pages 

![image](https://github.com/shuding/nextra/assets/15336755/c719bed7-1e72-4292-9190-172d2e542a82)

**Comment by B2o5T** [comment]
There is no info about version in your screen
