### ISSUE TITLE
How to set up backgroun color?

### ISSUE THREAD

**Issue by morandalex** [shuding/nextra#2269]
Hello, there is a  way to setup the background color depending on light and dark mode without tailwind?

**Comment by C-EO** [comment]
The only way is using tailwind, or the dark/light/system defaukt mode button. the second option only give white and black backgrounds whose color u could change by altering the codebase of your own Nextra fork

**Comment by dimaMachina** [comment]
https://nextra.site/docs/docs-theme/theme-configuration#theme-color
