### ISSUE TITLE
Potentially duplicated `<meta property="og:title">`

### ISSUE THREAD

**Issue by realfish** [shuding/nextra#2282]
I tried to configure the dynamic `og:title` via the custom [`head`](https://nextra.site/docs/docs-theme/theme-configuration#head-tags) in Theme Configuration. It seems that if I configure the `titleTemplate` via the [`useNextSeoProps`](https://nextra.site/docs/docs-theme/theme-configuration#seo-options)  at the same time, duplicated `<meta property="og:title">` tags will be generated.

(Not quite sure if it is expected.)

For example:

```jsx
// theme.config.jsx
export default {
  head: () => {
    return (
      <>
        <meta property="og:title" content="Some title" />
      </>
    )
  },
  // ...
  useNextSeoProps: () => {
    return {
      titleTemplate: 'Another title'
    }
  }
}
```

```html
<!-- Generated HTML head -->
<meta property="og:title" content="Another title">
<meta property="og:title" content="Some title">
```

**Comment by C-EO** [comment]
please provide a test site url

**Comment by realfish** [comment]
> please provide a test site url

@C-EO You can easily find a reproduction from the Nextra official showcase, e.g., [a random page from the SWR docs](https://swr.vercel.app/docs/getting-started).

![Screenshot 2023-09-13 at 23 23 43@2x](https://github.com/shuding/nextra/assets/3247876/8ebe0ce6-175c-40ad-9742-84213b541e90)

* * *

See also the [`theme.config.js`](https://github.com/vercel/swr-site/blob/main/theme.config.js) of the docs site:

- L24–L27: https://github.com/vercel/swr-site/blob/main/theme.config.js#L24-L27
- L107: https://github.com/vercel/swr-site/blob/main/theme.config.js#L107

**Comment by chapmanio** [comment]
I can also replicate this following the demo site example https://nextra.site/docs/docs-theme/theme-configuration#dynamic-tags-based-on-page

**Comment by B2o5T** [comment]
will be fixed in v3

**Comment by jamesmoss** [comment]
Any suggestions for those of us on v2 right now? This is affecting us badly.

**Comment by jamesmoss** [comment]
A workaround I found today, don't put a `og:title` in your `head` component, instead use this:

```
useNextSeoProps: () => {
    const { title } = useConfig();

    return {
      openGraph: {
        title: title === 'Index' ? 'Introduction' : title,
      },
    };
  },
```

There's also another bug where the `title` from the `useConfig` is also wrong for the homepage, we have this set to "Introduction" in our `_meta.json` but its always passed as "Index" hence the ternary.
