### ISSUE TITLE
[nextra-theme-docs] add the ability to add extra content to each page

### ISSUE THREAD

**Issue by thomasgouveia** [shuding/nextra#2283]
Hi folks,

I'm using Nextra (v2.12.3) with the `nextra-theme-docs` to build documentation. I would like to know if it is currently possible to add extra content to any of the generated pages? (to add custom components above the pagination for instance). I saw some reference about a `main.extraContent`, but this seems to be deprecated or removed from the code. 

My workaround at the moment is to pass my custom components on each page, but it is not ideal because if I change some props I need to edit all my files.

Thanks!

**Comment by B2o5T** [comment]
https://nextra.site/docs/docs-theme/theme-configuration#main-content

**Comment by thomasgouveia** [comment]
Thank you @B2o5T, It is exactly what I was looking for!
