### ISSUE TITLE
Separator Docs is not correct

### ISSUE THREAD

**Issue by gfazioli** [shuding/nextra#2289]
Hi all, in the [separator docs](https://nextra.site/docs/docs-theme/page-configuration#separators) I can see

```
{
  "index": "My Homepage",
  "---": {
    "type": "separator"
  },
  "contact": "Contact Us"
}
```
Looks like that the `title` is missing. it seems mandatory

```
{
  "index": "My Homepage",
  "---": {
    "type": "separator",
    "title" : "Anything",
  },
  "contact": "Contact Us"
}
```

A part of that, this means that is not possible create a simple separator...

Any feedback or clue is welcome, thx 🙏

**Comment by C-EO** [comment]
please provide a repo link, plus i think that u could just fill "---" for the title and it might work

**Comment by gfazioli** [comment]
@C-EO the repo link is https://github.com/shuding/nextra/blob/main/docs/pages/docs/docs-theme/page-configuration.mdx#L317

with `title: "---" `you will see `"---"` so it won't work 🤔

**Comment by wanjas** [comment]
Following code from the documentation leads to errors in build console but actually works.

```json
{
 "index": "Intro",
  "---": {
    "type": "separator"
  }
}
```

```
[nextra-theme-docs] Error validating _meta.json file for "---" property.
Invalid input
Invalid input
Invalid input
Expected string, received object
Required. Path: "items"
Required. Path: "title"
Invalid literal value, expected "menu". Path: "type"
Required. Path: "title"
Invalid enum value. Expected 'page' | 'doc', received 'separator'. Path: "type"
```

Simply adding an empty `title` does exactly as I would expect it to do, draw a separator line. 

```json
{
 "index": "Intro",
  "---": {
    "type": "separator",
    "title": ""
  }
}
```

**Comment by Mikescops** [comment]
I supplement what @wanjas just said.

```
[nextra-theme-docs] Error validating _meta.json file for "---1" property.

Invalid input
Invalid input
Invalid input
Expected string, received object
Required. Path: "items"
Required. Path: "title"
Invalid literal value, expected "menu". Path: "type"
Required. Path: "title"
Invalid enum value. Expected 'page' | 'doc', received 'separator'. Path: "type"
```

Versions:
```
        "next": "^13.5.6",
        "nextra": "^2.13.2",
        "nextra-theme-docs": "^2.13.2",
```
