### ISSUE TITLE
How to render table of contents

### ISSUE THREAD

**Issue by YikSanChan** [shuding/nextra#23]
Example: see https://using-remark.gatsbyjs.org/hello-world-kitchen-sink/

Thank you!

**Comment by suica** [comment]
I found a way to render the toc using `remark-toc@5.0.0` (7.0.0 should also work. But 8.x.x uses esm, so you will deal with it by yourself if you choose 8.x.x)

Run `yarn add remark-toc@5.0.0`, then add `remark-toc` to the remarkPlugin list in `next.config.js`:

```js
const toc = require('remark-toc')
const withNextra = require('nextra')({
  theme: 'nextra-theme-blog',
  themeConfig: './theme.config.js',
  mdxOptions: {
    remarkPlugins: [toc],
  },
})
```

Then you could put
```
## toc
```
in your mdx file for a test. If every works fine, you will see a toc in your page. In fact, any heading matched by a regex pattern `'toc|table[ -]of[ -]contents?'` will be replaced by a toc.

PS. If you find out your links toc cannot jump correctly, please try [this](https://github.com/vercel/next.js/issues/11109#issuecomment-1133904021).

**Comment by B2o5T** [comment]
Closing since nextra-theme-docs v2 has toc out of box
