### ISSUE TITLE
Add a banner to a subset of pages.

### ISSUE THREAD

**Issue by RobertCorey** [shuding/nextra#2305]
Instead of adding a global banner to the site, I would like to be able to add a banner to a subset of pages. For example all of the pages in a single folder.

**Comment by B2o5T** [comment]
duplicate https://github.com/shuding/nextra/issues/852

support of `_meta.json` will be removed in v3 in favour of `_meta.{js,jsx,ts,tsx}` with jsx elements support

**Comment by dimaMachina** [comment]
try below in v3
```js
theme: {
  topContent?: FC | ReactNode
  bottomContent?: FC | ReactNode
}
