### ISSUE TITLE
i18n support for `Scroll to top`

### ISSUE THREAD

**Issue by zwaittt** [shuding/nextra#2308]
expecting i18n config for this line

https://github.com/shuding/nextra/blob/093336858a23245fa47f8fe07f33f2d425a80416/packages/nextra-theme-docs/src/components/back-to-top.tsx#L34

**Comment by xijinping0** [comment]
I created #2895 to address this issue.

**Comment by dimaMachina** [comment]
will be available in next v3 alpha https://github.com/shuding/nextra/pull/3258
