### ISSUE TITLE
How to extend a custom theme?

### ISSUE THREAD

**Issue by alansiq** [shuding/nextra#231]
I couldn't find where to begin and how to start. Is it possible to make my own navbar (example for the blog theme), footer, etc?

Where could I go to find good examples or a direction to begin with?

**Comment by siddharthborderwala** [comment]
Hey @alansiq here is a link to an example - https://github.com/jaredpalmer/nextra-blank-custom-theme.

Example by [Jared Palmer ](https://twitter.com/jaredpalmer)

**Comment by harrybawsac** [comment]
> Hey @alansiq here is a link to an example - https://github.com/jaredpalmer/nextra-blank-custom-theme.
> 
> Example by [Jared Palmer ](https://twitter.com/jaredpalmer)

That's not really extending, that's something completely new. How does one add custom components to the docs theme for example? So, "extending the docs theme", so to say?

**Comment by B2o5T** [comment]
I guess previous answers responded to this

**Comment by gigamesh** [comment]
I agree that Jared Palmer's example is not helpful. 

For example, I'm currently trying to remove the `underline` class from `<a>` tags. It's not clear how to do simple overrides like that.

**Comment by harrybawsac** [comment]
> I guess previous answers responded to this

Well, no answer was given that addresses the question.

Obviously this issue should not be closed, since it's not been answered yet.

**Comment by franswan** [comment]
Bump. 

👀

I'll let you know if I find anything. It's a requirement on a project I have to extend the docs theme, so hopefully I'll figure it out.

**Comment by TheMikeyRoss** [comment]
Any update on this?
I'm trying to have the index page an entirely different design (to use as landing page) and the other pages to work as part of the nextra-theme-docs template. But when I update `next.config.js` to this:

```js
const withNextra = require("nextra")({
  theme: "./theme.tsx", //attempting to extend 'nextra-theme-docs', but it replaces it
  themeConfig: "./theme.config.tsx",
});

```

**Comment by ddomdel** [comment]
Me too. Anybody found a solution to this?

**Comment by marcchehab** [comment]
The way I did that is clone this repo (except "examples" dir): https://github.com/shuding/nextra

The repo is already setup with turbo, and nextra and nextra-themed-docs as packages inside the repo. So you can add custom components there in packages/nextra-theme-docs/src/components

On a side note: When you clone, make sure to do it properly from the beginning excluding /examples but with nextra repo still in upstream. that way you can pull updates easily.

**Comment by niklasp** [comment]
whats the nextra4 way to extend the docs theme?
