### ISSUE TITLE
Request: re-add automatic `id` / anchor for headings within tabs

### ISSUE THREAD

**Issue by imchairmanm** [shuding/nextra#2314]
The [fix for removing headings from the table of contents within tab sections](https://github.com/shuding/nextra/pull/2199) removes automatic `id` from all headings used within tabs.

While this simplifies the table of contents by removing those tab-specific elements from the page navigation, it also disables functionality like easily adding a mini tab-specific TOC to link to headers within the tab.  It would be useful to still include the anchors for the headings, even if they aren't automatically added to the side table of contents.

For example, what I'd like to be able to do is this:

```mdx
<Tabs items={['First tab', 'Second tab']}>

<Tabs.Tab>
You can do two things here:

* [First thing specific to tab 1](#first-thing-specific-to-tab-1)
* [Second thing specific to tab 1](#second-thing-specific-to-tab-1)

### First thing specific to tab 1

Content 

### Second thing specific to tab 1

Content

</Tabs.Tab>
<Tabs.Tab>
You can do two other things here:

* [First thing specific to tab 2](#first-thing-specific-to-tab-2)
* [Second thing specific to tab 2](#second-thing-specific-to-tab-2)

### First thing specific to tab 2

Content 

### Second thing specific to tab 2

Content

</Tabs.Tab>
</Tabs
```

Currently, I'm able to work around this by manually adding the same types of anchors that it generates for non-tab headings:

```mdx
### First thing specific to tab 1 <a href="#first-thing-specific-to-tab-1" id="first-thing-specific-to-tab-1" className="subheading-anchor" aria-label="Permalink for this section"></a>
```

However, this is less than ideal and feels very fragile.  It'd be great if the anchors could be automatically generated for headers within tabs, even if they aren't going to be used within the generated table of contents.

Hope that makes sense.

**Comment by B2o5T** [comment]
See https://github.com/shuding/nextra/issues/1191#issuecomment-1373077810

There’s no reason to add headings for dynamic content such as tabs, since if you copy the heading inside second tab, on first load you’ll not jump to it

**Comment by imchairmanm** [comment]
To me, there's value in having the anchor even if it doesn't function across reloads.  It helps the reader quickly find the information they're looking for without having to scroll down too far.

If that's not a use case you want to support, I understand, but I don't think it's accurate to say that there's no reason to have them.
