### ISSUE TITLE
Unable to hide root folder in monorepo setup

### ISSUE THREAD

**Issue by sanchezfdezjavier** [shuding/nextra#2319]
Hello, I'm using Nextra for hosting my documentation with a **Nextjs + Nextra monorepo** setup. I have all my **docs under `pages/docs`**, however, I **don't** want the root **`docs`** folder **showing up** in the **sidebar** as the main container for all the documentation. Is there a way to hide it?

<img width="226" alt="Screenshot 2023-09-20 at 17 59 42" src="https://github.com/shuding/nextra/assets/32944505/e65f2ac0-73ee-4e28-918d-e7c95f5299cd">

**Comment by baceituno** [comment]
This is critical for many organizations...

**Comment by houmland** [comment]
Same here, please fix it

**Comment by ToniRV** [comment]
+1!

**Comment by ManuelAngel99** [comment]
+1

**Comment by fparejam** [comment]
Any updates on this? I need to incorporate my custom naming from _meta.json...
I don't see a direct solve in the [docs](https://nextra.site/docs/guide/organize-files)

**Comment by B2o5T** [comment]
use `"display": "children"` in _meta.json
```diff
  "docs": {
    "title": "Documentation",
+    "display": "children"
  },
```

**Comment by smartcontracts** [comment]
Any reason why this isn't in the docs? I'd be happy to add it if this just needs someone to make a PR

**Comment by mbeaudru** [comment]
> use `"display": "children"` in _meta.json
> 
> ```diff
>   "docs": {
>     "title": "Documentation",
> +   "display": "children"
>   },
> ```

It definitely helps with the sidebar, though the root node still appears in the breadcrumb

<img width="559" alt="image" src="https://github.com/shuding/nextra/assets/8942633/46022b34-98cb-41af-96b1-fd204f481bfe">

Any solution for this?
