### ISSUE TITLE
TypeError in `next.config.mjs`: rule.test?.test is not a function

### ISSUE THREAD

**Issue by realfish** [shuding/nextra#2322]
After updating to Next.js v13.5.2, I encounter a TypeError `rule.test?.test is not a function` on these lines:

https://github.com/shuding/nextra/blob/093336858a23245fa47f8fe07f33f2d425a80416/docs/next.config.mjs#L34-L36

* * *

Here is the [SVGR documentation](https://react-svgr.com/docs/next/#usage) for reference: 

```js
// Grab the existing rule that handles SVG imports
const fileLoaderRule = config.module.rules.find((rule) =>
  rule.test?.test?.('.svg'),
)
```

**Comment by B2o5T** [comment]
Next.js has some issues starting from 13.4.9

https://github.com/shuding/nextra/blob/093336858a23245fa47f8fe07f33f2d425a80416/package.json#L53

fast refresh is no longer working for packages in `node_modules`
e.g. while editing `nextra-theme-docs` you’ll not get hmr working.

For this reason, I locked the version of Next.js, and didn’t have time to deep dive to it.
Maybe it was due this pr https://github.com/vercel/next.js/pull/52270

**Comment by B2o5T** [comment]
ok I bumped next to 13.5.2 and reported about issue in https://github.com/vercel/next.js/issues/55872
