### ISSUE TITLE
Title are not recognized.

### ISSUE THREAD

**Issue by anudit** [shuding/nextra#235]
While using Nextra, titles are not recognized, this also leads to TOC being empty.

![image](https://user-images.githubusercontent.com/12015553/139623110-73ddf31c-9c50-4f33-92d5-3579b065073c.png)

Docs Source code: https://github.com/anudit/convodocs
Live demo: https://docs.theconvo.space/integrate/Convo-API/api-docs

**Comment by siddharthborderwala** [comment]
I am having the same issue :(

**Comment by siddharthborderwala** [comment]
@shuding Any idea why this is happening?

**Comment by siddharthborderwala** [comment]
@anudit You will have to give individual titles in the mdx files like this -
![image](https://user-images.githubusercontent.com/54456279/141430444-5a1e28a8-f073-4807-93e0-7eebccd80a86.png)

**Comment by anudit** [comment]
@siddharthborderwala  Thanks a lot!

**Comment by siddharthborderwala** [comment]
> @siddharthborderwala  Thanks a lot! 

Happy to help! @anudit

**Comment by ChinW** [comment]
checked the `nextra-theme-docs/index`

```
  const titles = React.Children.toArray(children).filter(
    child => child.props && titleType.includes(child.props.mdxType)
  )
  const titleEl = titles.find(
    child => child.props && child.props.mdxType === 'h1'
  )
  const title =
    meta.title || (titleEl ? innerText(titleEl.props.children) : 'Untitled')
  const anchors = titles
    .filter(child => child.props && (config.floatTOC || child.props.mdxType === 'h2'))
    .map(child => child.props.children)

```

the child.props is empty here, the floatTOC also doesnt work now
does this also reflect the same in your end @siddharthborderwala @anudit

**Comment by ChinW** [comment]
i feel like it is because one of `mdx-js` plugin upgraded into 2.0 version, the schema changed 

![image](https://user-images.githubusercontent.com/8458838/142588773-b718769a-9183-4724-a651-ecbcc7b62cf1.png)

**Comment by anudit** [comment]
@ChinW checkout the codebase [anudit/convodocs](https://github.com/anudit/convodocs), Got the titles and `floatTOC` to work correctly with the latest versions of the dependencies. 
Still couldn't get Stork Search to completely work correctly so switched to Docsearch.

**Comment by ChinW** [comment]
![image](https://user-images.githubusercontent.com/8458838/142590223-23bfcc5f-d8b0-46fd-847f-c488263cba6c.png)

I cloned the master branch just now and tried to run locally, but the h2 headline doesnt have the "#" effect

thanks @anudit , let me check yours

**Comment by ChinW** [comment]
local server
![image](https://user-images.githubusercontent.com/8458838/142590510-5719b542-eaeb-4d79-8516-368192a0e9a9.png)


the website 

![image](https://user-images.githubusercontent.com/8458838/142590626-5b492705-d096-4dad-848e-9da79525471d.png)


I feel it is because the `MdxProvider` doesnt work anymore

**Comment by ChinW** [comment]
![image](https://user-images.githubusercontent.com/8458838/142591115-77262f9f-c8d1-48c2-aea3-3b81064f7014.png)


same in your repo, well... let me dig more to see if there is a quick patch

**Comment by siddharthborderwala** [comment]
> @ChinW checkout the codebase [anudit/convodocs](https://github.com/anudit/convodocs), Got the titles and `floatTOC` to work correctly with the latest versions of the dependencies. 
> 
> Still couldn't get Stork Search to completely work correctly so switched to Docsearch.

I suggest you use algolia if your work is open-source

**Comment by anudit** [comment]
> same in your repo, well... let me dig more to see if there is a quick patch
It won't show up on local dev environment, you'll have to deploy it to see it in action. see the same page here https://docs.theconvo.space/docs/Convo-Extensions/brightid

**Comment by anudit** [comment]
> I suggest you use algolia if your work is open-source

@siddharthborderwala [DocSearch](https://docsearch.algolia.com/docs/docsearch-v3/) is by Algolia.

**Comment by siddharthborderwala** [comment]
Aah, I see. Thanks for letting me know 😅

**Comment by korn101** [comment]
Still not working when using .md files instead of .mdx on 2.0.0-beta.5
