### ISSUE TITLE
Feedback for “Index”

### ISSUE THREAD

**Issue by IamtheMa** [shuding/nextra#2366]
ok firstly, the feedback button on the main site says 'this typeform is now closed', i think the link expired or something. so this is the only way i can find to contact you through the site. i really love this ai it's amazing but the web design is lacking. i just bought the first maker tier and it's showing me video tutorials on the video to model ai but at no point can i find the URL for the page to upload videos or the name of the app it keeps mentioning or where to get it. is this feature actually available yet? otherwise well done, amazing work.

**Comment by B2o5T** [comment]
Wrong repo
