### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'mathFlowInside')

### ISSUE THREAD

**Issue by albertilagan** [shuding/nextra#2368]
Broke on the latest release.

![image](https://github.com/shuding/nextra/assets/22500561/827d2772-886a-4a55-94eb-76452b7b54ba)

<img width="875" alt="image" src="https://github.com/shuding/nextra/assets/22500561/e063a6a8-e64a-4cc2-819a-d87a81b60039">

<img width="679" alt="image" src="https://github.com/shuding/nextra/assets/22500561/9e15f160-6f06-466c-b3ab-08ed6d6cd630">

**Comment by B2o5T** [comment]
upstream issue for latex/katex

**Comment by dsernst** [comment]
Hmm, seeing this too all of a sudden, and it's breaking and blocking builds.

Not seeing any references to `mathFlowInside` in https://github.com/KaTeX/KaTeX. Unclear how to proceed.

**Comment by B2o5T** [comment]
Please share code snippet, I’ll debug

**Comment by B2o5T** [comment]
@acdibble thx for repro

this issue was made after `remark-math` update to v6, seems like in the new version `$$` syntax isn't supported and `math` code block language should be used instead aka:

````md
```math
````

I downgraded `remark-math` to v5 to fix breaking changes, and will do an update of `remark-math`  only for Nextra v3.

so you'll need to do following refactor for Nextra v3 or right now
````diff
- $$
+ ```math
  x^2
- $$
+ ```
````
