### ISSUE TITLE
Enable toggle for sidebar expansion

### ISSUE THREAD

**Issue by minskim0327** [shuding/nextra#2370]
Is there an option to change sidebar menus?

Currently, all sidebars are expanded unless it is a folder structure, as shown below. Is there an option to change default to collapse?
![Screenshot 2023-10-02 at 11 18 02 AM](https://github.com/shuding/nextra/assets/51442256/3d427aba-d8c9-4a8a-b1d7-79db652a863d)

**Comment by B2o5T** [comment]
https://nextra.site/docs/docs-theme/theme-configuration#menu-collapse-level
