### ISSUE TITLE
`distDir` not respected in `nextraConfig`

### ISSUE THREAD

**Issue by siefkenj** [shuding/nextra#2377]
Making a project and setting the configuration to
```javascript
export default nextraConfig({distDir: "build"})()
```
then running `npm run build` results in the pages being built to `.next` instead of `build/`. It appears that this option is not being forwarded to the NextJS config.

If I do
```javascript
const config = nextraConfig({distDir: "build"})();
config.distDir = "build";
export default config;
```
then it works as expected.

**Comment by siefkenj** [comment]
I understand now that I am supposed to do

```
export default nextraConfig({})({distDir: "build"})
```

**Comment by B2o5T** [comment]
@siefkenj nextra config arguments will be validated with zod in v3!

**Comment by B2o5T** [comment]
In November
