### ISSUE TITLE
Feature: MathJax Support

### ISSUE THREAD

**Issue by siefkenj** [shuding/nextra#2389]
It would be great if MathJax were supported for math rendering. MathJax has an accessibility menu and has done work to integrate with screenreaders that KaTeX has not, so it would be nice to have it available as an option.

**Comment by B2o5T** [comment]
Support MathJax can be done via https://github.com/remarkjs/remark-math/tree/main/packages/rehype-mathjax plugin?

Currently, we use `rehype-katex` and `remark-math`

**Comment by siefkenj** [comment]
Yes, `rehype-mathjax` with mode set to `browser` should work, but it's a little more complicated than just that, since the MathJax JS needs to be loaded into the page.

I don't know how people feel about their generated pages loading stuff from the MathJax CDN. Hosting MathJax locally is possible but would take a little more work.

**Comment by B2o5T** [comment]
Would you want to contribute and send a PR ? (prefer to set base branch to v3)
I am new in mathjax but could help with blocking questions.

**Comment by siefkenj** [comment]
Yes. I'd be happy to give it a try.

Can you let me know where should code go that should be injected into the header of every page?

**Comment by B2o5T** [comment]
I guess it will require importing next head (as ast node) in your custom remark or rehype plugin. You can skip it for the moment and I’ll do it for you

**Comment by B2o5T** [comment]
closed by https://github.com/shuding/nextra/pull/2440
