### ISSUE TITLE
feature request: custom head according to meta or frontMatter of post

### ISSUE THREAD

**Issue by geekplux** [shuding/nextra#239]
Proposal: pass in config.head as a function and pass all meta or frontmatter in then. https://github.com/shuding/nextra/blob/core/packages/nextra-theme-blog/src/index.js#L43

The flexibility of the blog theme does not seem to be very high. For instance, there is no easy way for me to expand <Meta /> .

**Comment by AronBe** [comment]
agreed, SEO for blog is quite important
