### ISSUE TITLE
use without server

### ISSUE THREAD

**Issue by Samrose-Ahmed** [shuding/nextra#2390]
Can we use Nextra without a server, as a static export (e.g. https://nextjs.org/docs/pages/building-your-application/deploying/static-exports) and deploy it straight on S3?

**Comment by Samrose-Ahmed** [comment]
It seems to work with `next export`, the docs there don't seem to be correct, you cant set "output": to "export".

**Comment by reyemtm** [comment]
Also - if you have any images it will fail as well. Next JS will allow you to set `images: { unoptimized: true }` in the config but it seems this is ignored in nextra, causing the export to fail when using `next export`.

```
    - Configure `images.unoptimized = true` in `next.config.js` to disable the Image Optimization API.
 ```
Setting this in the next.config.js does not change anything.

**Comment by dimaMachina** [comment]
Doc was added https://nextra.site/docs/guide/static-exports
