### ISSUE TITLE
Suppressing display of pages marked as "display": "hidden" in mobile design hamburger menu

### ISSUE THREAD

**Issue by NPJigaK** [shuding/nextra#2408]
In my Nextra project, I have specified a "display": "hidden" property for certain pages in the `_meta.json` file to suppress their display in the navbar in PC design. This works as expected; the pages are hidden from the navbar. However, when the screen size is narrowed and the mobile design takes effect, revealing the hamburger menu, all pages, including those marked as "display": "hidden", are shown in the menu. I would like the behavior to remain consistent between PC and mobile designs, where pages marked as "display": "hidden" are suppressed from the hamburger menu as well.

Is there a way to ensure that the pages marked as "display": "hidden" are not displayed in the hamburger menu in mobile design, similar to how they are suppressed in the navbar in PC design?

Supplemental Information:
Here's how I specify the "display" property in the `_meta.json` file:

```json
{
  "page": {
    "title": "Page Title",
    "display": "hidden"
  }
}
```

In PC design, this successfully hides the page from the navbar, but in mobile design, the page still appears in the hamburger menu. Looking for a way to have consistent behavior across both designs.

**Comment by NPJigaK** [comment]
Will v2 fix it or will v2 no longer be updated?
Is it possible to update from v2 to v3? (Compatibility)

**Comment by B2o5T** [comment]
I do not plan to maintain both versions, v3 is currently unstable alpha prerelease mode, release ~November
