### ISSUE TITLE
Math not rendered in the auto-generated TOC

### ISSUE THREAD

**Issue by siefkenj** [shuding/nextra#2411]
With `latex: true`, math is correctly rendered in headings, but not in the auto-generated TOC.

See the screenshot below where

```
# $\arcsin$
```
is rendered correctly, but in the TOC on the right, it is not.

![image](https://github.com/shuding/nextra/assets/839083/4fd13988-db44-417d-8b8d-b767383261cc)

**Comment by B2o5T** [comment]
Will be fixed in v3 https://x.com/b2o5t/status/1707502267107311667?s=46&t=vfE4sELND26J46km7DSPmw
