### ISSUE TITLE
Module build failed: UnhandledSchemeError: Reading from "D:testapp.nextstaticchunks extra-page-map-.mjs" is not handled by plugins (Unhandled scheme).

### ISSUE THREAD

**Issue by NPJigaK** [shuding/nextra#2422]
```
D:testapp.nextstaticchunks
extra-page-map-.mjs
Module build failed: UnhandledSchemeError: Reading from "D:testapp.nextstaticchunks
extra-page-map-.mjs" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "d:" URIs.
```

I get an error when I try to update nextra from v2 to v3.
I have made the changes while following the PR, but would appreciate support to resolve this error.

**Comment by NPJigaK** [comment]
Checking the contents of nextra-page-map-.mjs, it imports "D:\~~~~~\_meta.ts". This may be the cause.
Did you change this part of the process in nextra v3?

**Comment by NPJigaK** [comment]
The cause may be that you are importing the full path when creating nextra-page-map-.mjs. Maybe This should be a relative path.

**Comment by NPJigaK** [comment]
https://github.com/shuding/nextra/pull/2070/files#diff-54928ad3c1f65b91db395cd176dd7e4ef585f4e31a412274382663a3abfa5731

**Comment by B2o5T** [comment]
thank you, I haven't tested yet v3 on windows, will be fixed soon

**Comment by B2o5T** [comment]
this is strange, because we have tests that are run on windows

https://github.com/shuding/nextra/blob/a3b67aea7eec331202a6fef6d335b70a5bce0e22/.github/workflows/test.yml#L14

so technically it should fails, because we build all `examples`

https://github.com/shuding/nextra/blob/a3b67aea7eec331202a6fef6d335b70a5bce0e22/.github/workflows/test.yml#L36-L37

**Comment by NPJigaK** [comment]
Can you actually debug the value of nextra-page-map-.mjs that is output by windows os? (github action to output the contents of a specific file)
I would like to know if `import foo from "D\\barpiyo\_meta.js".`

Checking the diff, the _app.mdx (to be _app.tsx) file is missing in the v3 examples. Perhaps this has something to do with it. (I don't think it has anything to do with me)

**Comment by B2o5T** [comment]
in v3 there is no longer `_app.mdx`, use regular `_app.jsx/tsx`

**Comment by NPJigaK** [comment]
yes, but not existing tsx or jsx file in v3 examples

**Comment by B2o5T** [comment]
`_app` file is not required, he exists only in swr example https://github.com/shuding/nextra/blob/v3/examples/swr-site/pages/_app.jsx since there is style import

**Comment by NPJigaK** [comment]
I see. I understand. But I have a feeling that it has nothing to do with this case.
I think it is a Windows path issue.

**Comment by B2o5T** [comment]
Sure, but it's super strange that tests are false negative

**Comment by B2o5T** [comment]
could you try to modify locally this line https://github.com/shuding/nextra/blob/e2f45057239316a6b3c4bd9db17a7dc4227b52ca/packages/nextra/src/server/loader.ts#L71

by
```diff
+  const mdxPath = slash(this._module?.resourceResolveData
    ? // to make it work with symlinks, resolve the mdx path based on the relative path
      /*
       * `context.rootContext` could include path chunk of
       * `context._module.resourceResolveData.relativePath` use
       * `context._module.resourceResolveData.descriptionFileRoot` instead
       */
      path.join(
        this._module.resourceResolveData.descriptionFileRoot,
        this._module.resourceResolveData.relativePath
      )
+    : this.resourcePath)
```

I guess this should fix https://github.com/shuding/nextra/issues/2424 too

**Comment by NPJigaK** [comment]
@B2o5T 
The error was not resolved.However, the slash in the mdxPath was changed.

Before the change
`D:\foo\pages\en\piyo.mdx`
After change
`D:/foo/pages/en/piyo.mdx`

**Comment by NPJigaK** [comment]
If I can make the path to the imported meta file relative when building nextra-page-map-.mjs, I think it will work on any OS.

**Comment by NPJigaK** [comment]
https://github.com/shuding/nextra/blob/v3/packages/nextra/src/server/page-map.ts
I thought it might be necessary to make some corrections in this area.

**Comment by NPJigaK** [comment]
I attempted to modify the file path for nextra-page-map-.mjs to a relative path and also tried prefixing it with file:/// for webpack interpretation, however, the same error persisted. It's possible that webpack is interpreting this file's value in a different manner and attempting to read from the absolute path starting with D:, which is causing the error.

**Comment by NPJigaK** [comment]
https://github.com/shuding/nextra/blob/main/packages/nextra/src/webpack-plugins/nextra.ts


There is an error in `compiled\webpack\bundle5.js`
The webpack settings around here are no longer available in v3, so upgrading to v3 may cause an error.
I would like to know the changes around webpack in v3.

**Comment by B2o5T** [comment]
> There is an error in compiled\webpack\bundle5.js

which error?

> The webpack settings around here are no longer available in v3

which settings?

> I would like to know the changes around webpack in v3.

https://github.com/shuding/nextra/blob/v3/packages/nextra/src/server/webpack-plugins/nextra.ts

**Comment by NPJigaK** [comment]
```
Module build failed: UnhandledSchemeError: Reading from "D:[redacted]\[redacted].next.static.chunks
nextra-page-map-.mjs" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "d:" URIs.
    at D:\[redacted]\[redacted]\node_modules\next\dist\compiled\webpack\bundle5.js:28:399825
    at Hook.eval [as callAsync] (eval at create (D:\[redacted]\[redacted]\node_modules\next\dist\compiled\webpack\bundle5.js:13:28867), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\[redacted]\[redacted]\node_modules\next\dist\compiled\webpack\bundle5.js:13:26021)
    at Object.processResource (D:\[redacted]\[redacted]\node_modules\next\dist\compiled\webpack\bundle5.js:28:399750)
    at processResource (D:\[redacted]\[redacted]\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:5308)
    at iteratePitchingLoaders (D:\[redacted]\[redacted]\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:4667)     
    at runLoaders (D:\[redacted]\[redacted]\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:8590)
    at NormalModule._doBuild (D:\[redacted]\[redacted]\node_modules\next\dist\compiled\webpack\bundle5.js:28:399612)
    at NormalModule.build (D:\[redacted]\[redacted]\node_modules\next\dist\compiled\webpack\bundle5.js:28:401640)
    at D:\[redacted]\[redacted]\node_modules\next\dist\compiled\webpack\bundle5.js:28:82059
```

**Comment by NPJigaK** [comment]
This issue's UnhandledSchemeError was originating from webpack.

**Comment by B2o5T** [comment]
try to wrap `filePath` with `slash` here https://github.com/shuding/nextra/blob/917e17e49131c990d090aa9ceab1d1c362c34036/packages/nextra/src/server/page-map.ts#L195

**Comment by NPJigaK** [comment]
> source: { type: "Literal", value: slash(filePath) },


I made the modifications as suggested, but the error remains unchanged.

**Comment by B2o5T** [comment]
try to fix false negative tests on Windows, and I'll fix Windows compatibility https://github.com/shuding/nextra/issues/2422#issuecomment-1758145381

your tests should be run in PRs on your fork

**Comment by NPJigaK** [comment]
Should I try all the pnpm commands written in the GitHub action locally?

**Comment by B2o5T** [comment]
You don't need to fix windows compatibility locally, I am asking to make CI fail when `os` is specified as `windows`

https://github.com/shuding/nextra/blob/a3b67aea7eec331202a6fef6d335b70a5bce0e22/.github/workflows/test.yml#L14

Follow command should fail on windows
https://github.com/shuding/nextra/blob/a3b67aea7eec331202a6fef6d335b70a5bce0e22/.github/workflows/test.yml#L36-L37

once tests fail, I can fix it

**Comment by NPJigaK** [comment]
@B2o5T 
Discovered a bug in test.yml. Requesting for verification.
https://github.com/shuding/nextra/pull/2437

**Comment by B2o5T** [comment]
@NPJigaK thank you! I will work tomorrow to make Nextra 3 compatible with windows

**Comment by NPJigaK** [comment]
@B2o5T 
Thank you for the prompt response! I appreciate your commitment to making Nextra 3 compatible with Windows. Looking forward to the updates. Have a great day ahead!

**Comment by B2o5T** [comment]
Have a great day too! Thanks for your contributions!

**Comment by B2o5T** [comment]
@NPJigaK try `3.0.0-alpha.7`

**Comment by NPJigaK** [comment]
It worked on the Windows environment too! I am glad that Nextra has become a better application!! Really great job! Please take a rest!

**Comment by B2o5T** [comment]
Thank you ☺️
