### ISSUE TITLE
Is there a way for sidebar headings to link to the index instead of collapsing the section?

### ISSUE THREAD

**Issue by pbassham** [shuding/nextra#243]

**Comment by h0n24** [comment]
+1

**Comment by B2o5T** [comment]
Duplicate of https://github.com/shuding/nextra/issues/85 (will work on fixing it soon)

**Comment by WooodHead** [comment]
Just create a file with same name as folder:

- features.mdx
- features
  - readfile.mdx
  - writefile.mdx

https://turbo.build/pack/docs/features

![image](https://github.com/shuding/nextra/assets/5668806/2ba460d2-308e-4f96-bf46-a4159b3b1479)
