### ISSUE TITLE
page scrolls towards top when typing in the flexsearch box 

### ISSUE THREAD

**Issue by zwaittt** [shuding/nextra#2441]
It's happening exactly on https://nextra.site, but not seen on https://swc.rs which built with nextra@2.0.1 as shown 
https://github.com/swc-project/website/blob/e494c92223b6832e95391ed1ff98b6498a291168/package.json#L15
It confused me cause it seems there is't an issue target this yet.

**Comment by B2o5T** [comment]
saw this bug too, needs find after which version it occurs

**Comment by MatejZelenka** [comment]
Hello. I just wanted to report this issue too so just asking, if there is any update to this? Thanks

**Comment by dimaMachina** [comment]
Was fixed in v3 alpha

**Comment by MatejZelenka** [comment]
Okay, thanks for feedback!
