### ISSUE TITLE
Feedback for “Tailwind CSS”

### ISSUE THREAD

**Issue by ajthinking** [shuding/nextra#2449]
Regarding this page: https://nextra.site/docs/guide/advanced/tailwind-css

My install does not have an `_app.js` or `globals.css` so I can't simply "follow the official Tailwind CSS documentation for Next.js to set up Tailwind CSS". I figure I need to add an `_app.js` but not sure how it should look if the only purpose is adding tailwindcss via globals.css.

**Comment by ajthinking** [comment]
I got it to work by adding this `_app.ts` in pages dir:

```ts
import '../globals.css'

export default function Nextra({ Component, pageProps }) {
  return (
    <>
      <Component {...pageProps} />
    </>
  )
}
```

**Comment by DatoKhojava** [comment]
@ajthinking solution worked for me !!
