### ISSUE TITLE
support different documents for different version of our product

### ISSUE THREAD

**Issue by Crayon-ShinChan** [shuding/nextra#2459]
Is there any way to support different documents for different version of our product.

For example, Pandas has multiple documents for different versions:
<img width="1295" alt="image" src="https://github.com/shuding/nextra/assets/38809606/f07d49ca-e627-4cec-a61f-7337e617cfae">

**Comment by abenhamdine** [comment]
see discussion in https://github.com/shuding/nextra/issues/20
