### ISSUE TITLE
remove "-nextra" from page title

### ISSUE THREAD

**Issue by SamIxCode** [shuding/nextra#2461]
I am trying to remove the "-nextra" from page title **but** i do not want to overwrite the Title which gets automaticaly generated from the page i am viewing. Only the suffix.

**Comment by DerTimonius** [comment]
It's pretty simple to change the tab title with the `useNextSeoProps` function in the `theme.config.jsx` file:

```ts
useNextSeoProps() {
    return {
      titleTemplate: '%s – SamIxCode',
    };
  },
```

If you want to remove it completely, just write `titleTemplate: '%s'`

**Comment by Elegant-Bird** [comment]
Is this in the docs somewhere that I missed? It took ages to find this and fix the issue

**Comment by DerTimonius** [comment]
@Elegant-Bird it is, but not really intuitive to find imo 
https://nextra.site/docs/docs-theme/theme-configuration#seo-options

**Comment by Elegant-Bird** [comment]
Oh wow. Yeah I totally missed that. Thank you for the link!

**Comment by alamenai** [comment]
Thank you @DerTimonius.

**Comment by dimaMachina** [comment]
`useNextSeoProps` was removed in Nextra v3, so this issue should not occur
