### ISSUE TITLE
Feedback for 'page switch buttons'

### ISSUE THREAD

**Issue by steadily-worked** [shuding/nextra#2469]
<img width="1624" alt="스크린샷 2023-10-20 오전 11 34 05" src="https://github.com/shuding/nextra/assets/61453718/7e5b5446-b962-4719-825b-a0ada4f1474e">

Hi, when i use this page switch buttons, i want to open page with new tab like `<a href=".." target="_blank>...</a>` does.
but i think that there are no features to support it. it would be good if there is a feature about it(of course, this feature should be optional).

**Comment by B2o5T** [comment]
Why do you think it will be good? I don't think is useful

**Comment by steadily-worked** [comment]
![스크린샷 2023-10-20 오후 2 38 06](https://github.com/shuding/nextra/assets/61453718/05b1be13-dd6d-48c0-bc37-cb3c6aa8d3ae)

in this page(`next/turbo` docs), `Changelog` button doesn't work. and i think that this happens becuase when i click `Changelog` button on the left side menu, new page(releases of turbo) is opened. so, after i saw this, i think it would be better if there is a option to open link with new tab.

**Comment by dimaMachina** [comment]
Sorry I don't see a big value in this option, the turbo repo contains the below bug https://github.com/shuding/nextra/issues/2360 that should be fixed
