### ISSUE TITLE
Styling breaks when importing nextra stylesheet in an existing tailwind project

### ISSUE THREAD

**Issue by iamnottheway** [shuding/nextra#247]
Hello,

I'm trying to integrate nextra docs into an existing nextjs tailwind project but importing the nextra stylesheet breaks/override some of the styles throughout the project. Removing the stylesheet seems to fix the issue but that's not really going to work for the docs.

I've tried copying all the styles from [here](https://github.com/shuding/nextra/blob/core/packages/nextra-theme-docs/src/styles.css) into a new stylesheet but importing that doesn't seem to work as well. 

This is what I see when I copy all the styles from the above link and import it 

<img width="1440" alt="Screenshot 2021-11-15 at 10 11 20 PM" src="https://user-images.githubusercontent.com/16266156/141820018-6de991cb-e494-436d-b583-d9553b60c366.png">

These styles get overridden when importing `nextra-theme-docs/style.css`

<img width="821" alt="Screenshot 2021-11-15 at 10 15 16 PM" src="https://user-images.githubusercontent.com/16266156/141820627-d01a49bb-c608-488d-90ae-5f26615726ea.png">

Is there anyway to fix this? Appreciate any help! Thanks!

**Comment by dashcraft** [comment]
Yeah there's some unscoped styles in the docs theme, ideally all docs theme work should be scoped to the specific docs work so that if you use this in an existing app it doesn't wreck all the other styles.

**Comment by bhatvikrant** [comment]
I am facing the same

**Comment by dashcraft** [comment]
@bhatvikrant you can use my pr and fix the issue then copy paste the generated styles instead of the modules CSS export

**Comment by B2o5T** [comment]
https://github.com/shuding/nextra/issues/492#issuecomment-1205884261
