### ISSUE TITLE
Feedback for “Docs Theme”

### ISSUE THREAD

**Issue by RichardJECooke** [shuding/nextra#2476]
I followed everything under "Start as New Project" but my package.json had no `next` command. Is there another tutorial before this one?  Your Introduction Quick Start just points to the docs page

**Comment by abenhamdine** [comment]
You can take example from the official template https://github.com/shuding/nextra-docs-template
The package.json file has the appropriate scripts  

it's basically 3 lines to add : 
```
    "scripts": {
        "dev": "next dev",
        "build": "next build",
        "start": "next start"
    },
```

**Comment by RichardJECooke** [comment]
Thanks. But why isn't this in the docs? It's not going to help people if they have to search for this issue

**Comment by dimaMachina** [comment]
feel free to contribute

**Comment by abenhamdine** [comment]
I sent a PR : https://github.com/shuding/nextra/pull/2490
please maintainers feel free to reword, I'm not a native english speaker

**Comment by dimaMachina** [comment]
huge thanks @abenhamdine I am too 🙈

**Comment by abenhamdine** [comment]
> huge thanks @abenhamdine I am too 🙈

ohh just realized that 😄
