### ISSUE TITLE
Default Dark Mode

### ISSUE THREAD

**Issue by rajanwastaken** [shuding/nextra#250]
tried using next-themes and ThemeProvider to make add default dark mode, but it wouldn't work. what i noticed is that i can only customize the body with css/scss (the stuff within the page and on the mdx files), rather than the entire page.

could someone please guide me on how to implement this?

**Comment by geekplux** [comment]
hi @itsrajan , which theme, doc or blog

**Comment by itsrajan** [comment]
> hi @itsrajan , which theme, doc or blog

Docs theme :)

**Comment by hmmhmmhm** [comment]
You can temporarily set the default theme by inserting the code below into the head element of theme.config.js.

```html
<script
  lang="javascript"
  dangerouslySetInnerHTML={{
    __html: `if (!window.localStorage.getItem("theme_default")) {
      window.localStorage.setItem("theme", "dark");
      window.localStorage.setItem("theme_default", "dark");
      document.documentElement.classList.add("dark");
      document.documentElement.classList.remove("light");
    }`,
  }}
/>;

```

**Comment by wottpal** [comment]
would be cool to have this as a config option though! @shuding

**Comment by shuding** [comment]
https://nextra.site/docs/docs-theme/theme-configuration#dark-mode-and-themes

You can pass

```js
nextThemes: {
  defaultTheme: 'dark'
}
```

**Comment by updwnheadlights** [comment]
where can I pass this?
for reference I'm trying to do it to this template 
[](https://vercel.com/templates/next.js/portfolio-starter-kit)

**Comment by Pathsis** [comment]
> ```js
> documentElement
> ```

This is a disaster, since I ran this code, all my next.js app for local debugging, are in dark mode! Can you tell me how to clear this effect? Much appreciated.

**Comment by Pathsis** [comment]
> You can temporarily set the default theme by inserting the code below into the head element of theme.config.js.
> 
> ```js
> <script
>   lang="javascript"
>   dangerouslySetInnerHTML={{
>     __html: `if (!window.localStorage.getItem("theme_default")) {
>       window.localStorage.setItem("theme", "dark");
>       window.localStorage.setItem("theme_default", "dark");
>       document.documentElement.classList.add("dark");
>       document.documentElement.classList.remove("light");
>     }`,
>   }}
> />;
> ```

This is a disaster, since I ran this code, all my next.js programs for local debugging, are in dark mode! Can you tell me how to clear this effect? Much appreciated.

**Comment by nurwah1d** [comment]
> https://nextra.site/docs/docs-theme/theme-configuration#dark-mode-and-themes
> 
> You can pass
> 
> ```js
> nextThemes: {
>   defaultTheme: 'dark'
> }
> ```

This exactly work!

**Comment by imonish8** [comment]
### This is theme.config.js | Where to put it ?
```js
const YEAR = new Date().getFullYear()

export default {

  footer: (
    <small style={{ display: 'block', marginTop: '8rem' }}>
      <time>{YEAR}</time> © Monish Nule 
      <a href="#"_blank">Source</a>
      <style jsx>{`
        a {
          float: right;
        }
        @media screen and (max-width: 480px) {
          article {
            padding-top: 2rem;
            padding-bottom: 4rem;
          }
        }
      `}</style>
       
    </small>
  )
```

**Comment by Pathsis** [comment]
It's just a crappy program, what's there to waste time on it?

> ### This is theme.config.js | Where to put it ?
> ```js
> const YEAR = new Date().getFullYear()
> 
> export default {
> 
>   footer: (
>     <small style={{ display: 'block', marginTop: '8rem' }}>
>       <time>{YEAR}</time> © Monish Nule 
>       <a href="#"_blank">Source</a>
>       <style jsx>{`
>         a {
>           float: right;
>         }
>         @media screen and (max-width: 480px) {
>           article {
>             padding-top: 2rem;
>             padding-bottom: 4rem;
>           }
>         }
>       `}</style>
>        
>     </small>
>   )
> ```

It's just a crappy program, what's there to waste time on it?

**Comment by imonish8** [comment]
> It's just a crappy program, what's there to waste time on it?
> 
> > ### This is theme.config.js | Where to put it ?
> > ```js
> > const YEAR = new Date().getFullYear()
> > 
> > export default {
> > 
> >   footer: (
> >     <small style={{ display: 'block', marginTop: '8rem' }}>
> >       <time>{YEAR}</time> © Monish Nule 
> >       <a href="#"_blank">Source</a>
> >       <style jsx>{`
> >         a {
> >           float: right;
> >         }
> >         @media screen and (max-width: 480px) {
> >           article {
> >             padding-top: 2rem;
> >             padding-bottom: 4rem;
> >           }
> >         }
> >       `}</style>
> >        
> >     </small>
> >   )
> > ```
> 
> It's just a crappy program, what's there to waste time on it?

where should I place the dark mode code from Nextra?
I want to add a toggle in there for dark mode.

**Comment by Coderamrin** [comment]
> > https://nextra.site/docs/docs-theme/theme-configuration#dark-mode-and-themes
> > You can pass
> > ```js
> > nextThemes: {
> >   defaultTheme: 'dark'
> > }
> > ```
> 
> This exactly work!

It doesn't work, don't why.

**Comment by gitagogaming** [comment]
> > > https://nextra.site/docs/docs-theme/theme-configuration#dark-mode-and-themes
> > > You can pass
> > > nextThemes: {
> > >   defaultTheme: 'dark'
> > > }
> > 
> > 
> > This exactly work!
> 
> It doesn't work, don't why.


I was able to get this to work by passing this into the `Layout` inside of `layout.tsx`
one important note is you will have to go into your local browser storage and delete the theme key there otherwise its just gonna stay to what you had it set to previously.

```js
            nextThemes={{
              defaultTheme: 'dark'
          }}
```

**Comment by huykon** [comment]
How can I customize or set the text color for dark mode to be easy to read? It's very difficult to read on my site now

<img width="1215" height="604" alt="Image" src="https://github.com/user-attachments/assets/3c8b2abb-8748-441b-9ee9-b8ba31d971c6" />
