### ISSUE TITLE
how  to use <table></table> in .md

### ISSUE THREAD

**Issue by xxx920** [shuding/nextra#2517]
I want to use html table in the md file, just like this, but it doesn't display my table.
![image](https://github.com/shuding/nextra/assets/145538209/b2ff938c-57a5-4860-8207-0ff7d98ef8e4)
![image](https://github.com/shuding/nextra/assets/145538209/86da74bd-b924-45d9-8899-2fc1e71ae527)

**Comment by dimaMachina** [comment]
https://nextra.site/docs/guide/advanced/table
