### ISSUE TITLE
Can't access to your webpage https://nextra.site/

### ISSUE THREAD

**Issue by lawweiliang** [shuding/nextra#2520]
Hi Team, 

Seems like something wrong with the site. 

![image](https://github.com/shuding/nextra/assets/34936929/7e70ec80-72b4-456d-806a-1c5a44351187)

**Comment by abenhamdine** [comment]
it works now, you can close this issue

**Comment by lawweiliang** [comment]
@abenhamdine 
I don't think so,

![image](https://github.com/shuding/nextra/assets/34936929/7d09418f-9fa2-4fa8-a6fb-8a222666e7db)

**Comment by abenhamdine** [comment]
It looks like Avast block the site on your computer, can you please paste details (under "see details") ?

**Comment by lawweiliang** [comment]
![image](https://github.com/shuding/nextra/assets/34936929/cca147a5-ba6d-432f-8622-ef26023623d4)

**Comment by abenhamdine** [comment]
Looks like a false positive on the Avast side, the website seems safe  

Tested with :  
- https://hetrixtools.com/blacklist-check/nextra.site
- https://domsignal.com/test/eu0i5nnrcp1icctydbbo6lrnt1s23daf
- https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fnextra.site%2F
- https://www.websitepulse.com/tools/results.php

**Comment by lawweiliang** [comment]
Previously, I faced the same problem on another website. I informed the owner.  
Eventually, owner of the project email AWAST and ask them to whitelist the website.
Then, problem solved.

**Comment by dimaMachina** [comment]
Closing due age
