### ISSUE TITLE
Are nextra code highlight suport grammar `// ^?` and `// ^|`

### ISSUE THREAD

**Issue by tianyingchun** [shuding/nextra#2525]
Hope nextra code hilight can support grammar `// ^?`, please see below case

```ts
.query((opts) => {
      const name = opts.input.name;
      //    ^?
      return {
        greeting: `Hello ${opts.input.name}`,
      };
    }),
 ```
 
 the output should be
 
 
<img width="477" alt="image" src="https://github.com/shuding/nextra/assets/2833251/6e241de0-9c55-4dc8-baa5-b87ce9ecac7f">

second case

```ts
 .query((opts) => {
      return {
        gre,
        // ^|
      };
    })
```

<img width="464" alt="image" src="https://github.com/shuding/nextra/assets/2833251/14ab93ea-b2fa-46e3-9d08-7b015a4b39c5">

please see: https://github.com/trpc/trpc/blob/main/www/docs/server/validators.md

**Comment by dimaMachina** [comment]
This feature looks nice, and I am +1 to add it to Nextra, would you want to make an attempt to contribute? preferable to set `v3` as base branch to avoid fixing conflicts with future release

I think there is some remark/rehype plugin to do it

**Comment by imranbarbhuiya** [comment]
I can work on this after #2658 (after https://github.com/rehype-pretty/rehype-pretty-code/pull/172) gets merged

**Comment by dimaMachina** [comment]
will be added in next alpha release
