### ISSUE TITLE
Callout component causes weird errors

### ISSUE THREAD

**Issue by gunayanil** [shuding/nextra#2529]
If I use `<Callout>` built-in component I get this error:

```
Element type is invalid: expected a string (for built-in components) or a class/function 
(for composite components) but  got: undefined. You likely forgot to export your component   
from the file it's defined in, or you might have mixed up default  and named imports.

Check the render method of `MDXContent`.
```
If I use Next 13.0.5 I can see this error in my dev enviroment locally but for 13.0.6 it only happens after I deployed the site to Vercel.

I use Callout like this, also tried `import Callout from 'nextra/components', same.

```js
import { Callout } from 'nextra/components'
 
<Callout type="info" emoji="ℹ️">
  Weird
</Callout>
```

**Comment by MedX101** [comment]
Did you find solutions about around this, also have same issues with Steps built in function

**Comment by louis-md** [comment]
Same issue

**Comment by dimaMachina** [comment]
Use latest Nextra
