### ISSUE TITLE
Code highlighting doesn't work

### ISSUE THREAD

**Issue by aidenybai** [shuding/nextra#253]
I'm having issues getting code highlighting to work for https://million.js.org (repo: https://github.com/millionjs/docs) on both dev and prod.

I've tried switching package managers (npm/yarn/pnpm), hard installing `prismjs` and `prism-react-renderer` as hard dependencies.

I've also tried to manually add support for the languages I use for codeblock highlighting via [this doc](https://nextra.vercel.app/advanced/code-highlighting), but it doesn't seem to work

Versions:
```
"next": "^12.0.4",
"nextra": "^1.1.0",
"nextra-theme-docs": "^1.2.6",
"react": "^17.0.2",
"react-dom": "^17.0.2"
```

Wondering if anyone can repro this issue? If so, anybody know a fix?

**Comment by spaceinvadev** [comment]
I'm having the same issue with the same set of dependencies and versions. No syntax highlighting at all.

**Comment by aidenybai** [comment]
@spaceinvadev do you currently have any workarounds?

**Comment by spaceinvadev** [comment]
Well, I decided to use another package for syntax highlighting: https://www.npmjs.com/package/react-syntax-highlighter

<img width="885" alt="Screen Shot 2021-11-27 at 3 10 43 PM" src="https://user-images.githubusercontent.com/49292621/143720942-5825a70a-6bc6-45f1-8332-c409c93a221c.png">

**Comment by kanadgupta** [comment]
I thought this was due to the mismatching MDX versions (which was addressed in #251), but I just tried this on `v2.0.0-beta.3` (released a few hours ago) and can confirm it's still broken. Maybe https://github.com/shuding/nextra/issues/262 will address this?

**Comment by shuding** [comment]
Unfortunately Prism is a bit hard to use with React, I'm wondering if we should switch to https://github.com/react-syntax-highlighter/react-syntax-highlighter or https://github.com/shikijs/shiki. Shiki seems pretty well designed for today's ecosystem. And with #262 I'm trying to make all major languages supported with ease.

**Comment by spaceinvadev** [comment]
Shiki seems way much stronger and a better option to me.

**Comment by aidenybai** [comment]
Looks like #312 has fixed this issue! Install the alpha to fix

**Comment by shuding** [comment]
Friendly note: the new alpha version currently requires pnpm (yarn doesn't work, it's a bug that I'll look into :)) but feel free to try and give us feedback!

**Comment by dsousa12** [comment]
Guys I can't put my code with colors.
Already follow the steps on documentation, but I have errors because I'm using TypeScript.
Anyone can help me?
