### ISSUE TITLE
how to enable these cards?

### ISSUE THREAD

**Issue by ArnavK-09** [shuding/nextra#2530]
![image](https://github.com/shuding/nextra/assets/69188140/97c03735-1b3b-4fe9-8c11-cd926beda124)

**Comment by MedX101** [comment]
Did you find solution for this ? I am also can't enable them even thou  am usng import from { **** } from nextra/components

**Comment by maulik-NeoXL** [comment]
To enable these cards, follow the steps:

1. Import cards from nextra

```
import { Cards, Card } from 'nextra/components'
```

2. Import the icons from your preferred library or locally.
``` copy
import { CardsIcon, OneIcon, WarningIcon } from '../../icons'
```

3. Call <Cards/> component and import the icons from your preferred library or locally.

```js copy
<Cards>
  <Card icon={<WarningIcon />} title="Callout" href="/docs/guide/built-ins/callout" />
  <Card icon={<CardsIcon />} title="Tabs" href="/docs/guide/built-ins/tabs" />
  <Card icon={<OneIcon />} title="Steps" href="/docs/guide/built-ins/steps" />
</Cards>
```

**Comment by ArnavK-09** [comment]
> To enable these cards, follow the steps:
> 
> 1. Import cards from nextra
> 
> ```
> import { Cards, Card } from 'nextra/components'
> ```
> 
> 2. Import the icons from your preferred library or locally.
> ``` copy
> import { CardsIcon, OneIcon, WarningIcon } from '../../icons'
> ```
> 
> 3. Call <Cards/> component and import the icons from your preferred library or locally.
> 
> ```js copy
> <Cards>
>   <Card icon={<WarningIcon />} title="Callout" href="/docs/guide/built-ins/callout" />
>   <Card icon={<CardsIcon />} title="Tabs" href="/docs/guide/built-ins/tabs" />
>   <Card icon={<OneIcon />} title="Steps" href="/docs/guide/built-ins/steps" />
> </Cards>
> ```

### I mean can't they be automatically like gitbolk?

**Comment by ArnavK-09** [comment]
+ Im unable to find the file in official docs where they have done like this ^

**Comment by maulik-NeoXL** [comment]
Here is the exact link: 

https://nextra.site/docs/guide/built-ins/cards

**Comment by ArnavK-09** [comment]
> Here is the exact link: 
> 
> https://nextra.site/docs/guide/built-ins/cards

I mean, in nextra official docs src

https://github.com/shuding/nextra/tree/main/docs

**Comment by dimaMachina** [comment]
@ArnavK-09 These cards aren't autogenerated like in gitbook, to see the source code just click edit on github or see here https://github.com/shuding/nextra/blob/main/docs/pages/docs/guide/advanced.mdx

but maybe in future, they can be autogenerated, and in theory icon can be specified in newly `_meta.js/ts` which has jsx support in Nextra 3

**Comment by ArnavK-09** [comment]
> @ArnavK-09 These cards aren't autogenerated like in gitbook, to see the source code just click edit on github or see here https://github.com/shuding/nextra/blob/main/docs/pages/docs/guide/advanced.mdx
> 
> but maybe in future, they can be autogenerated, and in theory icon can be specified in newly `_meta.js/ts` which has jsx support in Nextra 3

Oh soo sorry, I was seeking these cards in index.mdx in advanced folder

## Thanks 🐐
