### ISSUE TITLE
`projectLink` not working: Redirects to default value

### ISSUE THREAD

**Issue by spaceinvadev** [shuding/nextra#254]
The `projectLink` setting (the URL that the button in the top right will point to) does not work as expected. I've added a custom value in the `theme.config.js` file yet it keeps redirecting to the default value instead (https://github.com/shuding/nextra).

<img width="1247" alt="Screen Shot 2021-11-27 at 8 43 55 AM" src="https://user-images.githubusercontent.com/49292621/143684253-104309c0-82f9-49e0-ab45-603961ae20b2.png">

<img width="998" alt="Screen Shot 2021-11-27 at 8 46 38 AM" src="https://user-images.githubusercontent.com/49292621/143684259-10c990fc-0229-405b-83b0-804e9e9dd88e.png">

These are the dependencies on my `package.json` file:
```json
"dependencies": {
    "next": "12.0.4",
    "nextra": "^1.1.0",
    "nextra-theme-docs": "^1.2.6",
    "prism-react-renderer": "^1.2.1",
    "prismjs": "^1.25.0",
    "react": "17.0.2",
    "react-dom": "17.0.2"
  },
```

**Comment by ranajahanzaib** [comment]
You are right @spaceinvadev. The `projectLink` isn't working.

**Comment by C-EO** [comment]
Is there any fix for this?

**Comment by shuding** [comment]
Could you try it with the latest beta release? I tested locally and it worked: https://github.com/shuding/nextra/releases/tag/v2.0.0-beta.2

**Comment by branhillsdesign** [comment]
@shuding with the latest beta release, this is still broken. Both `projectLink` and `projectLinkIcon` revert to their default values.

**Comment by spaceinvadev** [comment]
Hi, @branhillsdesign. I'm using the following versions and it works just fine for me.

```json
"nextra": "^2.0.0-beta.5",
"nextra-theme-docs": "^2.0.0-beta.5",
```
