### ISSUE TITLE
feature request: Configure navigation buttons

### ISSUE THREAD

**Issue by arno-fukuda** [shuding/nextra#2545]
It would be nice if we could customize the `prev` and `next` navigation buttons for each page using the _meta.json

Example structure of a Sidebar:

```
-Folder_A
    - Item1
    - Item2
    - Item3
-Item_B
```

When I am on the page for Item2, it will automatically give me navigation to prev: Item1 and next:Item3.
Instead I want to be able to configure in _meta.json what the next button should be eg:

```
{
  "item2": {
    "title": "Item 2",
    "theme": {
      next: "/Item_B". <<<<<
    }
  }
}
```

**Comment by dimaMachina** [comment]
Have you already seen something similar? in docusaurus for example

**Comment by arno-fukuda** [comment]
Fair point.

Just to highlight the use case I had a mind:

Lets say you have something like this:

* **Configuration**
** MacOS
** Windows
** Linux
* **Next Step**


In this case the user will only need to navigate to one of the OS options and the 'next' option should go to the next category that's a folder above.

**Comment by dimaMachina** [comment]
this case makes sense, but it's too narrow case to make them configurable, sorry for it
