### ISSUE TITLE
Nextjs config won't export when using Nextra - next.config.js

### ISSUE THREAD

**Issue by SamIxCode** [shuding/nextra#2550]
Hi,

I am getting issue that i can not wrap my head around.

I am trying to **export** nextra nextJs with docs theme. But as from version 13.3 is the next export deprecated I am using the next config.

Here i am encountering an issuse where i either export:
```
const withNextra = require('nextra')({
  //Nextra
  theme: 'nextra-theme-docs',
  themeConfig: './theme.config.tsx',
  unstable_staticImage: false,
  output:"export"
});


module.exports = withNextra()
;

```

or:
```
/**
 * @type {import('next').NextConfig}
 */
const nextConfig = {
  output: 'export',

}
 
module.exports = nextConfig

```

I have tried to export both:

```
module.exports ={
  
  
  ...withNextra(),
  ...nextConfig


}

```

which gives me a rewrites error.

# Steps to Reproduce

* 1. https://nextra.site/docs/docs-theme/start - follow this example, and try to export it 
* 2. https://nextjs.org/docs/pages/building-your-application/deploying/static-exports

#Expected Behavior

Expected HTML , CSS  and JS outut

# Real Behavior

Either when using the nextra config - it is exported to be used with `next start`
Either if switching to the nextJS export config - the output is missing all static pages and only _app and 404.html gets generated.

Thanks for help

**Comment by TheMikeyRoss** [comment]
how did you solve that?
