### ISSUE TITLE
Use Holocron as default editor for the `Edit this page` link

### ISSUE THREAD

**Issue by remorses** [shuding/nextra#2552]
Hey, i am working on [Holocron](https://holocron.so/markdown-editor), a WYSIWYG Markdown editor that can edit any markdown file on Github (automatically creates a fork, branch and PR with 1 click)

For example you can use this link to make changes to the Nextra markdown files: https://holocron.so/github/pr/shuding/nextra/main/editor/README.md

Can i open a PR to use Holocron as default editor for the Nextra `edit this page` link?

This workflow is much faster compared to manually using Github to fork, create a branch and create a PR. It also allows people that don't know MDX or Markdown to make changes very easily.

**Comment by dimaMachina** [comment]
Your work looks incredible 👏, but I would like to stay with the default way

particular users still could override it in favour of Holocron with `editLink.component` option https://github.com/shuding/nextra/blob/66798f8e7f92cca80f2d62d19f9db5667bcc62ef/packages/nextra-theme-docs/src/constants.tsx#L203-L212

**Comment by remorses** [comment]
Ok, what do you think about adding 2 links like the following image? 

Or maybe a commented out example code in the create-next-app template?

![Screenshot 2023-12-02 at 11 07 04](https://github.com/shuding/nextra/assets/31321188/142bacd3-50fa-49fb-b442-3aecf91feee8)

I think an WYSIWYG editor would help a lot of less technical people to contribute to docs

**Comment by arvinxx** [comment]
@remorses [Holocron](https://holocron.so/markdown-editor) are great! 😋 We have use it in LobeChat 's [docs](https://chat-docs.lobehub.com/en/usage/features/vision)

<img width="1910" alt="image" src="https://github.com/shuding/nextra/assets/28616219/a4021cbb-dc1e-4303-be73-6f6b63929eeb">

**Comment by dimaMachina** [comment]
Closing, if you want improve docs with holocron mention feel free to send pr
