### ISSUE TITLE
How to add vercel analytics to the Nextra Docs Project

### ISSUE THREAD

**Issue by thatbeautifuldream** [shuding/nextra#2558]
[Vercel Analytics](https://vercel.com/docs/analytics/quickstart#:~:text=Add%20the%20Analytics%20component%20to%20your%20app)

```js
import type { AppProps } from 'next/app';
import { Analytics } from '@vercel/analytics/react';
 
function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Component {...pageProps} />
      <Analytics />
    </>
  );
}
 
export default MyApp;
```

Since there seems to be no app.tsx file in the /pages route how do we implement analytics?

If I try to add the app.tsx the build fails.

If there is a workaround that I am missing please help me.

**Comment by abenhamdine** [comment]
try to add page/_app.mdx file 

see https://github.com/shuding/nextra/pull/1448 for reference

**Comment by dimaMachina** [comment]
Anything that works with next.js works with nextra, follow next.js examples
