### ISSUE TITLE
Can't get in-line images to work

### ISSUE THREAD

**Issue by Reddybrekkers** [shuding/nextra#2559]
I'm trying to get images to appear inside a sentence in Nextra - such as: 'To close the window, click the Close [ICON].

I achieve this result inside my IDE's preview window, but not inside my app.

Can anyone advise on how this is done? 

P.S. I'm a tech author, not a dev!

**Comment by dimaMachina** [comment]
can you share an example of what you mean? maybe in some existing website

**Comment by dimaMachina** [comment]
nextra-theme-blog/docs uses `tailwindcss`' `preflight.css` that set `display: block` for `img` element

https://github.com/tailwindlabs/tailwindcss/blob/f667746d797264a59f1fd97003deedaad34b1a3f/src/css/preflight.css#L358-L368
