### ISSUE TITLE
Can clicking on a sidebar item redirect?

### ISSUE THREAD

**Issue by YikSanChan** [shuding/nextra#256]
## What do I want to do?

Let's use https://nextra.vercel.app/ as an example.

The side bar has an item "Introduction", this is because there is an index.md in the directory, and it is named "Introduction" in meta.json.

I wonder, is there a way to redirect to an external link when I click on "Introduction"?

## Why is it useful?

Because sometimes I want to link to external API docs directly. For example, in this [docs site](https://docs.feast.dev/), when I click "Changelog" on the sidebar, it redirects to the GitHub changelog directly, which is handy.

**Comment by shuding** [comment]
This is something nice to have! In the docs theme, you can already add some more meta info such as `type` and `hidden` in meta.json: https://github.com/shuding/nextra/blob/0cdf467a9485ad4f831298d5da441a64a1075846/examples/docs/pages/meta.en.json

Can definitely add an `external` field too.

**Comment by shuding** [comment]
#258.
