### ISSUE TITLE
Component with getStaticProps imported into mdx page

### ISSUE THREAD

**Issue by bngarren** [shuding/nextra#2564]
## Problem

I can get the sample code from Nextra to work (https://nextra.site/docs/guide/ssg) as is.

However, if I put this code in a separate file and then import into the mdx page I get empty 'stars' prop.

```js
// components/stars.js

import { useData } from 'nextra/data';

export const getStaticProps = ({ params }) => {
	return fetch(`https://api.github.com/repos/shuding/nextra`)
		.then((res) => res.json())
		.then((repo) => ({
			props: {
				// We add an `ssg` field to the page props,
				// which will be provided to the Nextra `useData` hook.
				ssg: {
					stars: repo.stargazers_count
				}
			},
			// The page will be considered as stale and regenerated every 60 seconds.
			revalidate: 60
		}));
};

const Stars = () => {
	// Get the data from SSG, and render it as a component.
	const data = useData();

	if (data?.stars) return <strong>{data.stars}</strong>;
};

export default Stars;
```

```js
// pages/index.mdx

import Stars from "../components/stars"

Nextra has <Stars /> stars on GitHub!

```

I then simplified it to just pass a prop from getStaticProps and it still won't work (the page renders the Stars component but no prop passed):
```js
// components/stars2.js

export const getStaticProps = ({ params }) => {
	return {
    props: {
      stars: 1
    }
  }
};

const Stars = ({stars}) => {
	return <strong>{stars}</strong>;
};

export default Stars;
```

<img width="418" alt="image" src="https://github.com/shuding/nextra/assets/10670702/83407ead-94f2-4b86-b7fe-6aeb43a75c82">

## Version
```json
  "dependencies": {
    "next": "^14.0.3",
    "nextra": "^2.13.2",
    "nextra-theme-docs": "^2.13.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  }
```

Apologies if I'm grossly missing an obvious problem

**Comment by dimaMachina** [comment]
`getStaticProps` should be exported in mdx page, not in partial mdx

**Comment by bngarren** [comment]
Great, thank you. Any documentation to point to this requirement?

**Comment by dimaMachina** [comment]
https://nextjs.org/docs/pages/building-your-application/data-fetching/get-static-props
<img width="658" alt="image" src="https://github.com/shuding/nextra/assets/7361780/ae77336d-0081-4014-8436-f632eb554139">
