### ISSUE TITLE
i18n: redirected you too many times.

### ISSUE THREAD

**Issue by suhaotian** [shuding/nextra#2566]
next 13.5.6 with i18n when switch language in the home page, will occur this error:

<hr />
<img width="614" alt="image" src="https://github.com/shuding/nextra/assets/6512574/c1ef5752-de4c-479a-afbc-943537a5fbf2">
<hr />

downgrade to next@13.0.6 is ok.

Maybe someone will met this issue too.. so post here.

**Comment by tarjelavik** [comment]
Hi, i can confirm this. Downgrading to 13.0.6 worked for me as well.

**Comment by dimaMachina** [comment]
there will be no fixes for current i18n, try new i18n from Nextra 3 https://github.com/shuding/nextra/issues/1421#issuecomment-1852012364
