### ISSUE TITLE
Problem with deploy via Remix

### ISSUE THREAD

**Issue by venomy420** [shuding/nextra#2567]
I can't make a smart contract deploy via Remix. It always gives an error for different contracts.
https://explorer.rarichain.org/tx/0xcbe49ea83673a6c09fb72044b9d2003e0b637bf945d23adfab6393762b74bb3c
https://explorer.rarichain.org/tx/0xcc016aa637ca470521e7dd244a2f4164d5d32d09732d432828cd2bc30f51a0a0
https://explorer.rarichain.org/tx/0xe712ffb5ed0d8d6941cf2dbff6ae583627503bc3a733d8fd8340e370298b505f
What could be the problem?

**Comment by dimaMachina** [comment]
wrong issue, unrelated to nextra
