### ISSUE TITLE
Setup Docs and Blog theme in the same monorepo

### ISSUE THREAD

**Issue by sanchezfdezjavier** [shuding/nextra#2571]
Is it possible to setup both the [Docs](https://nextra.site/docs/docs-theme/start) and [Blog](https://nextra.site/docs/blog-theme/start) theme in the same monorepo?

I currently have the Docs theme working, however I'm not sure how to configure both of them, I don't know if this is even possible.

Thanks!

**Comment by nicholasoxford** [comment]
Do you have a repo you can share?

**Comment by sanchezfdezjavier** [comment]
I've switched to Mintlify. Love nextra anyways! 💙

**Comment by dimaMachina** [comment]
Duplicate https://github.com/shuding/nextra/issues/361 Will be possible in v4
