### ISSUE TITLE
CSS file not included anymore when switching _app.js to _app.mdx

### ISSUE THREAD

**Issue by leruaa** [shuding/nextra#2573]
I have the following code in `pages/_app.mdx`
```mdx
// These styles apply to every route in the application
import '../styles/globals.css'

export default function App({ Component, pageProps }) {
  return <Component {...pageProps} />
}
```
the following in `styles/globals.css`:
```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```
and this in `pages/index.mdx`:
```mdx
<div className="content-container">
  <h1 className="text-red-400">Hello</h1>
</div>
```

Doing `next dev`, the text "Hello" is not red. When I rename `pages/_app.mdx` to `pages/_app.js`, it works correctly.

What am I doing wrong? Thanks.

You can find the full repo there: https://github.com/leruaa/stapifaction-website

**Comment by dimaMachina** [comment]
seems https://github.com/leruaa/stapifaction-website/blob/62bdedd56f18e6eadb4dd4f4a902cf8538ae2198/pages/_app.mdx#L1 is illegal comment in mdx files (use `{/* some-comment */}` syntax), also `_app.mdx` will be removed in v3

**Comment by leruaa** [comment]
Oh thanks I'll try.

By what will it be replaced?

**Comment by leruaa** [comment]
It's working now, thanks!

**Comment by leruaa** [comment]
@archform-eng-wjsong just remove the comment in `_app.mdx`

**Comment by archform-eng-wjsong** [comment]
i clone your repo, and remove _app.mdx, text "Hello" is not red, it not works. @leruaa
