### ISSUE TITLE
Fix page reload when navigating to sub-level menu

### ISSUE THREAD

**Issue by 0xARK** [shuding/nextra#2576]
Your website is a SPA, so when we want to navigate there is no page reload.

However, after setting up nextra, I found that the page was reloading in some case. Here is an example :

![image](https://github.com/shuding/nextra/assets/108460887/9d89965b-88ba-4efa-ad8a-28220c55ffe2)

When I navigate in top-level documentation (from Introduction to Test page), the page is not reloaded.

However when I navigate to sub-level documentation (from Introduction to Example > Installation page), the page is reloaded.

**Comment by dimaMachina** [comment]
please share reproduction

**Comment by dimaMachina** [comment]
closing due lack of repro
