### ISSUE TITLE
Support `href` for external links in navigation

### ISSUE THREAD

**Issue by jaredpalmer** [shuding/nextra#258]
Need to be able to do: 

```json
{
  "index": {
    "title": "Introduction",
    "type": "nav",
    "hidden": true
  },
  "docs": {
    "title": "Docs",
    "type": "nav"
  },
  "enterprise": {
    "title": "Enterprise",
    "type": "nav",
    "href": "https://my-contact-form.com"
  }
}
```

**Comment by YikSanChan** [comment]
Hi @shuding I am looking to build this feature since I need this soon.

Can you plz quickly show me where should I start with? Thanks

**Comment by mpaler** [comment]
As a temporary workaround you can put the following at the top of your .mdx page:

```
import {useEffect} from 'react'
export default function redirect() {
    useEffect(() => {
        window.location.assign('https://google.com')
    })
    return(
        <>
        </>
    )
}
```

**Comment by B2o5T** [comment]
Closing since it possible, take a look of swr example https://github.com/shuding/nextra/blob/2c59ffc2af03b0f3f48a97e0c419d8d4c106c2cc/examples/swr-site/pages/meta.en-US.json#L55

**Comment by mptorz** [comment]
@B2o5T how should we go about it in the blog theme? We cannot use meta.json there.

**Comment by B2o5T** [comment]
Do not reply on closed issue, create a new one
