### ISSUE TITLE
page is missing in sidebar

### ISSUE THREAD

**Issue by futantan** [shuding/nextra#2583]
Website: https://tokenscript-doc.vercel.app/
Github: https://github.com/SmartTokenLabs/TokenScript-Doc

The pages looks great in local, but when I deploy it to Vercel, the page is missing. But I can visit that url directly https://tokenscript-doc.vercel.app/integrate-wallet
But if you visit https://tokenscript-doc.vercel.app/ 
![CleanShot 2023-12-18 at 12 13 06@2x](https://github.com/shuding/nextra/assets/6268441/ee1f8cc6-ca47-42a5-a260-a7b9746c81a2)
the page is missing.

**Comment by nicholasoxford** [comment]
I've found when deploying to vercel often times you need to redeploy without build cache to get rid of these problems

**Comment by futantan** [comment]
thank you @nicholasoxford , I deployed serval times, and it finally works!
