### ISSUE TITLE
Theme Switch Support for DocsThemeConfig

### ISSUE THREAD

**Issue by stasnocap** [shuding/nextra#2584]
Hi! I want be able to change option names like desribed in https://nextra.site/docs/docs-theme/theme-configuration#theme-switch while using docs theme

**Comment by jellli** [comment]
make sure you done correctly

1. make sure your `next.config.js` configures the `themeConfig` path correctly
```js
const withNextra = nextra({
  theme: 'the name of the doc',
  themeConfig: './src/theme.config.js',  // this line
})
```
2. configure theme
```jsx
// ./src/theme.config.js
export default {
  themeSwitch:{
    useOptions() {
      return {
        dark: 'night mode',
        light: 'day mode',
        system: 'auto mode'
      }
    }
  }
}
```

preview:
<img width="263" alt="image" src="https://github.com/shuding/nextra/assets/22422393/37ff5f36-d5a3-4642-a134-7e5864d9e734">

**Comment by stasnocap** [comment]
I'm literally generetad project with template (https://github.com/shuding/nextra-docs-template) and have no intellisense for themeSwitch whatsoever. My project: https://github.com/stasnocap/sb-bsu-perepodgotovka-pois-docs
Then I look into nextra-theme-docs library files and saw that theme options were hardcoded or maybe I don't understand something

**Comment by jellli** [comment]
The theme options have their default setup, it will be covered by your custom config.

**Comment by jellli** [comment]
Maybe your dependencies are out of date, I upgraded the doc theme version and the problem goes away

<img width="345" alt="image" src="https://github.com/shuding/nextra/assets/22422393/1978e04b-e982-4f50-8f57-492d8cdf749d">

<img width="264" alt="image" src="https://github.com/shuding/nextra/assets/22422393/f66a36fe-07ea-4ca2-a687-fa64431c5cc8">

**Comment by stasnocap** [comment]
Thank you! But why 
{
    "nextra": "latest",
    "nextra-theme-docs": "latest",
}
don't actually set it to latest? I'm confused

**Comment by jellli** [comment]
the `pnpm-lock.yaml` told the package management program that older version is good enough unless you tell it you want the newer version when you install the dependence on the command line

**Comment by stasnocap** [comment]
Now I'm understand, thank you again! Happy new year!
