### ISSUE TITLE
Doc theme: built in component `Bleed` is too wide

### ISSUE THREAD

**Issue by jellli** [shuding/nextra#2591]
it's too wide and it will block the `Toc`, maybe `mx-[4rem]` will be better 

<img width="1428" alt="image" src="https://github.com/shuding/nextra/assets/22422393/fbc463eb-547a-431c-847a-638675189dfb">

**Comment by dimaMachina** [comment]
What I remember from Nextra v1 that this behaviour intended

**Comment by mengxi-ream** [comment]
You can customize your Bleed use `-mx-6` like
```tsx
      <div className="relative mt-6 -mx-6 sm:mx-0 rounded-none sm:rounded-xl border-y sm:border border-zinc-200 dark:border-zinc-800 overflow-hidden">
        {children}
      </div>
```

**Comment by dimaMachina** [comment]
Closing since it’s per design
