### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by Shubham-EV** [shuding/nextra#2598]
how to add favicon using svg or ico?
And also please add option to turn off search bar for some pages

**Comment by jellli** [comment]
Which theme are you currently using?

And why do you want to hide the search bar for some pages?

**Comment by Shubham-EV** [comment]
I am using docs theme and I want to hide the search bar on main page where I showcase all my project. I want to show search bar only when someone clicks on any of the project

And moreover how to add favicon using ico or svg?

**Comment by jellli** [comment]
I don't think the search bar is customizable for each single page for now.

To add a favicon, check out [this](https://nextra.site/docs/docs-theme/theme-configuration#static-head-tags).
```html
<link rel="icon" href="/favicon.ico" sizes="any" />
```

**Comment by Shubham-EV** [comment]
I have tried using it in head : () in theme.config.jsx but it ain't working.  faviconglmph is working but it is only taking an emoji or string as its parameter not ico or svg

**Comment by jellli** [comment]
do you have a repo or example?

**Comment by Shubham-EV** [comment]
![githubeg](https://github.com/shuding/nextra/assets/64977436/c4037e8f-ac85-45f2-a539-336e49fd7a20)
This is my code

**Comment by jellli** [comment]
I think you should create a `public` folder in the root directory and put the favicon in it

**Comment by Shubham-EV** [comment]
![githubeg](https://github.com/shuding/nextra/assets/64977436/7454f509-ecf2-4b03-8c67-4367e742022c)

Doing that still doesn't solve the issue :( 
favicon only changes using   faviconGlyph: "👨🏻‍💻", but it only supports character or emoji

**Comment by jellli** [comment]
You don't need to change the `link` tag, `/favicon.ico` is good. I suggest you comment out the `faviconGlyph` for now.

**Comment by Shubham-EV** [comment]
I am uncommenting faviconGlyph everytime I am using link tag and doing that "/favicon.ico" still don't solve the issue

**Comment by jellli** [comment]
Maybe this [example](https://github.com/shuding/nextra/tree/main/examples/docs) can help.

**Comment by Shubham-EV** [comment]
Using  additionalLinkTags component is working fine to change favicon thank you so much :)
 useNextSeoProps() {
    return {
      titleTemplate: "%s – Eniv Docs",
      additionalLinkTags: [
        {
          href: "/square-code.png",
          rel: "icon",
          sizes: "32x32",
          type: "image/png",
        },
      ],
    };
  },
