### ISSUE TITLE
MDX Pages under folders do not render properly.

### ISSUE THREAD

**Issue by sarthaktexas** [shuding/nextra#26]
![image](https://user-images.githubusercontent.com/28282096/100558046-31513c00-3272-11eb-8cb9-1ddac609cd93.png)
I'm selecting only the second page.

**Comment by sarthaktexas** [comment]
Looks like it's only selecting the `index.md` page.

**Comment by shuding** [comment]
Mind sharing your repository / folder structure?

**Comment by sarthaktexas** [comment]
https://srtk.me/gh/notes

**Comment by shuding** [comment]
Should be good in 2.0.
