### ISSUE TITLE
Dark and Light mode

### ISSUE THREAD

**Issue by Shubham-EV** [shuding/nextra#2608]
I am using React.jsx code for the home page. Is it possible to change the text color for dark and light modes? If so, how?

**Comment by jakubgrygiel** [comment]
Hi, have you tried using useConfig provided by Nextra?
```tsx
import { useConfig } from "nextra-theme-docs/dist/index.mjs";

export default function HomePage() {
  const { darkMode } = useConfig();

  return (
    <div>
      <span style={{ color: darkMode ? "white" : "black" }}>Hello World!</span>
    </div>
  );
}

```

**Comment by Shubham-EV** [comment]
In my case useConfig is here import { useConfig } from "nextra-theme-docs"; 
and its not working the way  you showed

**Comment by Shubham-EV** [comment]
I figured it out :)

I need to use 

```
import { useTheme } from "nextra-theme-docs";

export default function HomePage() {
    const { theme } = useTheme();

  return (
    <div>
       <span style={{ color: theme === "dark" ? "green" : "red" }}>
          Hello World!
        </span>
    </div>
  );
}
```

**Comment by adamhake** [comment]
@Shubham-EV  The `theme` property gives the current selection in the theme switcher, not the active theme.  For instance, if the user selected "system", then `theme` will be "system".  Alternatively, the `resolvedTheme` property gives the true active theme (either "light" or "dark").
