### ISSUE TITLE
Feedback for “Next.js I18n”: ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by namnguyenthanhwork** [shuding/nextra#2611]
I can't switch languages, when I switch `vi -> en -> vi` or `en -> vi -> en`. The error is below

<img width="751" alt="image" src="https://github.com/shuding/nextra/assets/78526193/6384facb-b9d1-4b08-87fc-3b6523cd4f43">

Steps to reproduce:

Clone the https://github.com/shuding/nextra-docs-template and set it up for `i18n`.

Add below in `themes.config.tsx`

```
 i18n: [
    { locale: 'en', text: 'English' },
    { locale: 'vi', text: 'Tiếng Việt' },
  ],
```

Add `i18n` code in `next.config.js`

```
module.exports = withNextra({
  i18n: {
    locales: ['vi', 'en'],
    defaultLocale: 'en',
  },
})
```

Add a new `middleware.js`

```
export { locales as middleware } from 'nextra/locales'
```

[Link repo](https://github.com/namnguyenthanhwork/nextra-docs-template)

**Comment by dimaMachina** [comment]
https://github.com/shuding/nextra/issues/2566#issuecomment-1865486480

**Comment by namnguyenthanhwork** [comment]
I am trying to use Nextra 3, and I have a few questions. Can you help me?

1. Can I change `<html lang={locale}></html>` when I switch languages? If yes, how?

<img width="305" alt="image" src="https://github.com/shuding/nextra/assets/78526193/fcaba9e0-f503-429e-a777-3336fa707e63">

2. If I configure 'i18n: undefined,' the select language does not appear and the switch does not change.

<img width="186" alt="image" src="https://github.com/shuding/nextra/assets/78526193/2e1950df-86ec-4940-895d-d950d24b5758">

If I configure

```
 i18n: {
    locales: ['en', 'vi'],
    defaultLocale: 'vi',
  },
```

The switch changes and the select language appears.

<img width="586" alt="image" src="https://github.com/shuding/nextra/assets/78526193/561f417f-f5c7-422a-b000-b83697e9befc">

I need to see the title in the current language. But I read your blog, and you recommend setting `i18n: undefined`. Can you give me an example using `useRouter` instead of `locale` or `defaultLocale` values?

<img width="906" alt="image" src="https://github.com/shuding/nextra/assets/78526193/7d7fcb5d-1254-4b00-9ba3-b7c26c770325">

Thank for your help. @dimaMachina
