### ISSUE TITLE
Adding support for cascade layers

### ISSUE THREAD

**Issue by terrymun** [shuding/nextra#2613]
Is it possible to provide an option in the build step (could be a theme config) in nextra, so that it wraps all nextra-related styles in a cascade layer, e.g. `@layer nextra { ... }`?

The reason I'm asking is because we are working with component libraries in our organization and some are considering using cascade layers in their component styles. However, the styles from nextra (unlayered ones) will always override the layered styles, making it difficult to consume these component libraries with nextra.

**Comment by dimaMachina** [comment]
pr welcome

**Comment by samcxps** [comment]
I have opened a PR for this issue.

See [2740](https://github.com/shuding/nextra/pull/2740)

**Comment by dimaMachina** [comment]
closed by https://github.com/shuding/nextra/pull/3220 and https://github.com/shuding/nextra/pull/3248, use https://github.com/shuding/nextra/releases/tag/nextra-theme-docs%403.0.0-alpha.39
