### ISSUE TITLE
primarySaturation is not an option anymore

### ISSUE THREAD

**Issue by ritmillio** [shuding/nextra#2616]
I wanted to change the colors for the theme and was following nextra docs : https://nextra.site/docs/docs-theme/theme-configuration#theme-color

inside the theme.config.tsx there is no primarySaturation option anymore.

**Comment by dimaMachina** [comment]
I don't understand your question, `primarySaturation` option exist in v2, and was renamed in v3 https://github.com/search?q=repo%3Ashuding%2Fnextra%20primarySaturation&type=code

**Comment by dimaMachina** [comment]
closing due no reply
