### ISSUE TITLE
It is not possible to mark more than one identical footnote.

### ISSUE THREAD

**Issue by bulhakovolexii** [shuding/nextra#2620]
I found the following problem.

With a clean installation and configuration according to the [documentation](https://nextra.site/docs/docs-theme/start) and the latex module is enabled...

```next.config.js
const withNextra = require("nextra")({
  theme: "nextra-theme-docs",
  themeConfig: "./theme.config.jsx",
  latex: true,
});

module.exports = withNextra();
```
...if i mark a footnote to the same reference more than once, compiling is impossible.

![image](https://github.com/shuding/nextra/assets/110279020/13c56425-81c3-4751-b687-9b10e3543372)

![image](https://github.com/shuding/nextra/assets/110279020/6eab2127-0e7d-41b4-8997-3f66220f483a)

But if there is no more than one footnote, or the latex module is disabled, then everything is fine.

The problem also does not occur if i change the file extension from .mdx to .md.

![image](https://github.com/shuding/nextra/assets/110279020/7fb41906-4989-4f39-96fa-c062d8f43cb4)

![image](https://github.com/shuding/nextra/assets/110279020/9e68d275-8989-4442-9ab7-f8ce743d350d)

Please help me fix this problem. :heart:

**Comment by dimaMachina** [comment]
stake trace says that error goes from `rehype-katex`

```
TypeError: Cannot read properties of undefined (reading 'className')
 ❯ ../../node_modules/.pnpm/rehype-katex@7.0.0/node_modules/rehype-katex/lib/index.js:48:56
 ❯ node element<sup> file:/Users/dmytro/Desktop/nextra/node_modules/.pnpm/unist-util-visit-parents@6.0.1/node_modules/unist-util-visit-parents/lib/index.js:346:27
 ❯ node element<a> file:/Users/dmytro/Desktop/nextra/node_modules/.pnpm/unist-util-visit-parents@6.0.1/node_modules/unist-util-visit-parents/lib/index.js:363:61
 ❯ node element<p> file:/Users/dmytro/Desktop/nextra/node_modules/.pnpm/unist-util-visit-parents@6.0.1/node_modules/unist-util-visit-parents/lib/index.js:363:61
 ❯ node element<li> file:/Users/dmytro/Desktop/nextra/node_modules/.pnpm/unist-util-visit-parents@6.0.1/node_modules/unist-util-visit-parents/lib/index.js:363:61
 ❯ node element<ol> file:/Users/dmytro/Desktop/nextra/node_modules/.pnpm/unist-util-visit-parents@6.0.1/node_modules/unist-util-visit-parents/lib/index.js:363:61
 ❯ node element<section> file:/Users/dmytro/Desktop/nextra/node_modules/.pnpm/unist-util-visit-parents@6.0.1/node_modules/unist-util-visit-parents/lib/index.js:363:61
 ❯ node root file:/Users/dmytro/Desktop/nextra/node_modules/.pnpm/unist-util-visit-parents@6.0.1/node_modules/unist-util-visit-parents/lib/index.js:363:61
 ❯ visitParents ../../node_modules/.pnpm/unist-util-visit-parents@6.0.1/node_modules/unist-util-visit-parents/lib/index.js:304:31
 ❯ ../../node_modules/.pnpm/rehype-katex@7.0.0/node_modules/rehype-katex/lib/index.js:47:5
```

**Comment by dimaMachina** [comment]
after more deep dive into this problem, I figured out that updating `@mdx-js/mdx` from 2.3.0 to 3.0.0 fixes this issue (Nextra 3 already uses mdx v3)

Use Nextra 3 alpha and refactor `$$` style to https://the-guild.dev/blog/nextra-3#-syntax-no-longer-works-for-latex

**Comment by bulhakovolexii** [comment]
I tried the alpha version, indeed, it does not contain such a bug. Big thanks!

**Comment by bulhakovolexii** [comment]
I tried the alpha version, indeed, it does not contain such a bug. Big thanks!
