### ISSUE TITLE
Importing components from nextra/components does not work as expected

### ISSUE THREAD

**Issue by Xiexe** [shuding/nextra#2621]
Steps to reproduce:

1. Follow quick start to get a git repo for docs page.
2. create test.mdx
3. add `import { Callout } from 'nextra/components'` to the file
4. commit and watch deploy logs

Build will fail with the error:
`Attempted import error: 'Callout' is not exported from 'nextra/components' (imported as 'Callout').`

Either I'm doing something incredibly wrong, or the docs don't mention a few steps on how to get built-in components to work.

**Comment by Xiexe** [comment]
I've confirmed that this happens with all components, not just Callout.

**Comment by Xiexe** [comment]
Upon further investigation it seems that a bunch of things are not up to date within the template repository, meaning that components just straight up don't work.

Given that this is front and center in the docs on how to set things up, it would probably be a good idea to update that.

**Comment by fawltya** [comment]
Hi @Xiexe, I've been scratching my head on this for a while. Do you know how to correctly implement the components?

They work ok despite error log but fails when pushing to Vercel. Cheers.

**Comment by Xiexe** [comment]
Hi @fawltya, so from my testing it was just that the dependencies included with the template repository just weren't up to date.
After updating everything and deploying to vercel again, things worked, it really was as simple as that.

Here's a screenshots of which dependencies were not up to date.
![image](https://github.com/shuding/nextra/assets/5119787/b01c3a04-d999-4ac0-a580-4ee9ee73d2d1)

**Comment by fawltya** [comment]
@Xiexe thanks for your detailed reply. Updating those dependencies worked a treat. Cheers
