### ISSUE TITLE
Faulty/incomplete documentation for a feature

### ISSUE THREAD

**Issue by Genesis3800** [shuding/nextra#2648]
The [Cards](https://nextra.site/docs/guide/built-ins/cards) feature is a neat one in Nextra. There is a hitch, however:

- The documentation implies you can use those pretty icon-augmented cards simply like this:
![image](https://github.com/shuding/nextra/assets/56264430/e9fd2cb9-c48a-4892-977f-9734dbf92e3d)

- This is incorrect, however. Attempting to use the icons like in the docs results in the localhost crashing with errors. You can only use cards without emojis by default.
- Tracing through the repo's PRs I was able to recreate the icon-augmented cards like this:

1. Copy the actual `icons` folder into the `components` folder of your nextra repo.
2. Add the following to your `next.config.mjs` file inside the `export default withNextra` object :

```
 webpack(config) {
    const allowedSvgRegex = /components\/icons\/.+\.svg$/

    const fileLoaderRule = config.module.rules.find(rule =>
      rule.test?.test?.('.svg')
    )
    fileLoaderRule.exclude = allowedSvgRegex

    config.module.rules.push({
      test: allowedSvgRegex,
      use: ['@svgr/webpack']
    })
    return config
  }
```

3. Install the actual `svgr/Webpack` package like this:
`pnpm install @svgr/webpack --save-dev`

> Or any other package manager of your choice.

Only after this can you correctly import and use the emojis from the `icons` folder.
IMO as a technical writer, these steps should **DEFINITELY** be included in the docs.

**Comment by dimaMachina** [comment]
Docs doesn't mention your icons should be `svg` files, but it shows that icons are React components

**Comment by Genesis3800** [comment]
Still I feel this should be documented as a step-by-step mini tutorial, so that folks who want to, can follow the examples from the docs all the way through. What do you think?

**Comment by dimaMachina** [comment]
Docs was updated https://nextra.site/docs/guide/built-ins/cards#usage
