### ISSUE TITLE
Better built-in search

### ISSUE THREAD

**Issue by shuding** [shuding/nextra#265]
Generate https://github.com/nextapps-de/flexsearch indexes at build time as webpack assets for each language.

**Comment by YikSanChan** [comment]
This would be great, stork is not working too great with CJK from my own experience

**Comment by shuding** [comment]
Yep I felt the same, but this feature requires tons of time to work so...

**Comment by ankit-gaur** [comment]
@shuding is it done? I am happy to pick it up, let me know if you have already done something for it. I see swr-site uses flexsearch in theme.config.js but same config doesn't work for me so I am assuming flexsearch is not implemented yet. Thanks

**Comment by shuding** [comment]
@ankit-gaur It is basically done (released under `@alpha` currently), you can check how https://github.com/vercel/swr-site uses it.
