### ISSUE TITLE
Support image in cards

### ISSUE THREAD

**Issue by tpalaz** [shuding/nextra#2678]
nextra.site shows images being passed as props to the <Card> component, yet they don't work. Example (NEXTRA3):
`
<Cards>
    <Cards.Card
        title="Getting Started"
        href={"#"}
        image={"../../../public/images/preview.jpg"}
    />
</Cards>
`

Nextra2:
`
<Cards>
    <Card
        image={"/relativepath"}
        title="Getting Started"
        href={"#"}
    />
</Cards>
`
passing the NextJS image as a child:
`
image={<Image src={../../../public/images/preview.jpg} alt="Hello" width={500} height={500} />}
`
importing the image:
import PREVIEW from "../../../public/images/preview.jpg"
and passing:
`image={PREVIEW} `
aslo does not work. 

Even looking at the compiled package it clearly shows the image prop is being checked.

**Comment by imranbarbhuiya** [comment]
`image` prop is a boolean option, u need to pass the image as child and use `true` for `image`

```jsx
<Cards>
	<Cards.Card title="Getting Started" href={"#"} image>
		<Image src={"../../../public/images/preview.jpg"} />
	</Cards.Card>
</Cards>
```

**Comment by dimaMachina** [comment]
closing since @imranbarbhuiya is right, thank you!
