### ISSUE TITLE
Regarding the issue of automatic conversion of DOM tags.

### ISSUE THREAD

**Issue by binghuis** [shuding/nextra#2686]
Here is my code.

<img width="779" alt="image" src="https://github.com/shuding/nextra/assets/20395726/6c7a23d9-9e53-4c61-90af-f9beac25d42e">

I noticed that multiline p tags have been converted into this kind of dom structure.

<img width="359" alt="image" src="https://github.com/shuding/nextra/assets/20395726/dae39301-1ab3-4ab1-95fc-ce11746d6990">

At the same time, it prompts this error.

<img width="865" alt="image" src="https://github.com/shuding/nextra/assets/20395726/b8d80f2e-b71e-4a81-9446-2c6b09238bd6">

I noticed that nextra has done element conversion for mdx pages that are not in raw layout.

<img width="605" alt="image" src="https://github.com/shuding/nextra/assets/20395726/34c0218c-15bb-4901-b185-ae833fe2e72f">

Is this intentionally designed by nextra? I'm very puzzled. The automatic wrapping of DOM elements will cause errors in nextjs, but how to implement page layout without writing DOM? And it seems that a single line p tag did not automatically add a layer of p tags.

**Comment by dimaMachina** [comment]
this behaviour goes not from Nextra but from `@mdx/js` and is intentional since MDX wraps your content with a `p` element only for 2nd case (see screen).
this happens when your content is placed on a new line and does not follows JSX elements in the current line https://mdxjs.com/playground/

<img width="1614" alt="image" src="https://github.com/shuding/nextra/assets/7361780/05986200-4152-4323-b4f9-b447f0a5384e">

**Comment by binghuis** [comment]
<img width="1233" alt="image" src="https://github.com/shuding/nextra/assets/20395726/ca54494f-fa43-4291-a50e-d296ea5c8af8">

I understand, I see the solution from nextra is not to set automatic line wrapping, is this currently the recommended method?

**Comment by dimaMachina** [comment]
there is no other method, it was designed to work as in your issue, you get line wrapping after running prettier, right?
this happens because he doesn't support MDX2/3 and still formats according to MDX1
