### ISSUE TITLE
Nesting nextra within an existing App router application

### ISSUE THREAD

**Issue by ukcw** [shuding/nextra#2688]
Hi.

I'd like to nest my nextra documention within a page (in terms of the App router). In particular, I want to reuse the same headers and footers from my current Next.js 13 application, not use the navbar from Nextra.

Something like:

```
app/
  docs/
    layout.tsx
    page.tsx
```

where `page.tsx` will render whichever `.mdx` page the user is on.

As well, `layout.tsx` will wrap the `page.tsx` with the necessary headers and footers.

Is this even possible?

**Comment by caffeine-addictt** [comment]
Nextra only supports the pages router. https://github.com/shuding/nextra/issues/1421#issuecomment-1858999853

According the NextJS docs [here](https://nextjs.org/docs/app/building-your-application/routing#the-app-router), you can have the pages and app router at the same time.

Although I haven't tested this myself, you could have nextra handle only the `docs/` route.
Perhaps a file structure like this is what you're looking for?
```
app/
    other_page/
        page.tsx
        layout.tsx
pages/
    _meta.json
    docs/
        _meta.json
        index.mdx
```

If you do not like this 2 router approach, app router will be supported in Nextra4, you can track it here #2600.
