### ISSUE TITLE
Index page isn’t redirecting properly with i18n non-default locale on Firefox

### ISSUE THREAD

**Issue by GitXenon** [shuding/nextra#2689]
## Problem
While using the non-default locale `de-DE` for the root page `index.de-DE.mdx`, `localhost:3000/` redirects to`http://localhost:3000/de-DE`, which causes the app to throw  a `The page isn’t redirecting properly` error.  I don't get this error if I'm on another page that links to this root page.

All the other pages works properly translated and in their `en-US` version.

## Files 
`next.config.js`
```jsx
module.exports = withNextra({
    i18n: {
        locales: ['en-US', 'de-DE'],
        defaultLocale: 'en-US'
    }
});
```

`_meta.de-DE.json`
```
{
    "index": {
        "title": "Home",
        "type": "page"
    },
    "docs": {
        "title": "API",
        "type": "page"
    }
}
```

My folder structure:
```
pages/
├─ docs/
│  ├─ welcome.de-DE.mdx
│  ├─ welcome.en-US.mdx
├─ _meta.de-DE.json
├─ _meta.en-US.json
├─ index.de-DE.mdx
├─ index.en-US.mdx
```

## Reproducibility of the bug
This is only an issue with Firefox and might have to do with how this browser deals with cookies. On Chrome, it's working as expected.

Firefox is blocking cross-site cookies in all windows.

**Comment by dimaMachina** [comment]
Try to update to Nextra 3 with new i18n introduced
