### ISSUE TITLE
weird random italicized words not reflected in the markdown 

### ISSUE THREAD

**Issue by xentoshi** [shuding/nextra#2696]
<img width="391" alt="Screenshot 2024-02-09 at 15 39 47" src="https://github.com/shuding/nextra/assets/37624021/ad01fb9f-b226-4b37-bd0f-bbfce682ae88">

these are coming out of nowhere and showing like this in my docs.

**Comment by dimaMachina** [comment]
Please provide reproduction or link to your repo/file

**Comment by xentoshi** [comment]
i found the solution, the $ sign is formatting to math formula therefore needs to be escaped like this \$ 

reference: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions
