### ISSUE TITLE
Compiling error on latest 0.3.1 & React 17

### ISSUE THREAD

**Issue by benoror** [shuding/nextra#27]
```
SyntaxError: /Users/benoror/code/baseql-docs/pages/index.md: pragma and pragmaFrag cannot be set when runtime is automatic
```

<img width="1003" alt="Screen Shot 2020-11-29 at 18 58 15" src="https://user-images.githubusercontent.com/119117/100558638-db31c800-3274-11eb-8ab9-6b99abd78947.png">

Dependencies versions:

```json
  {
    "next": "^10.0.3",
    "nextra": "^0.3.1",
    "nextra-theme-docs": "^0.3.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  }
```

**Comment by sarthaktexas** [comment]
that's weird, works for me

**Comment by benoror** [comment]
This is the commit where I was facing the issue, maybe you can reproduce it: https://github.com/BaseQL/baseql-docs/tree/910b1c86b37e5247251dda2a837e6d0bf88a82c7

**Comment by sarthaktexas** [comment]
Ohhh I see. Looks like your `main` branch has the same version dependencies as mine but the commit you sent doesn't.

**Comment by benoror** [comment]
This is the filing combo afaict: https://github.com/BaseQL/baseql-docs/blob/910b1c86b37e5247251dda2a837e6d0bf88a82c7/package.json

**Comment by shuding** [comment]
@benoror Looks like something with React 17, I'll be taking a look. Thanks for reporting!

Related: https://github.com/vercel/next.js/issues/18461

**Comment by plongoria** [comment]
Any update on this? I also have the same issue

**Comment by shuding** [comment]
@plongoria FYI currently the only work around I have is to use `react@16`.

**Comment by smakosh** [comment]
This might help @shuding https://github.com/system-ui/theme-ui/issues/1160

**Comment by shuding** [comment]
You can add this `.babelrc` configuration to your project root:

```
{
  "presets": [
    [
      "next/babel",
      {
        "preset-react": {
          "runtime": "classic"
        }
      }
    ]
  ]
}
```

Tested and it would solve the problem for now. 👍
