### ISSUE TITLE
dev:website unhandled runtime error

### ISSUE THREAD

**Issue by tilefishpoele** [shuding/nextra#2707]
When I try to rebuild the website using pnpm dev:website I get the following runtime error:

> Unhandled Runtime Error
> Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
> 
> Check the render method of `MDXContent`.

I think it might be related to how the sidebar accordion works? As I can direct route to /docs and /docs-custom-theme without hitting the error however when i route to anything with the accordions expanded it throws the error.

**Comment by tilefishpoele** [comment]
The full call stack:

> Call Stack
> createFiberFromTypeAndProps
> ..\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom.development.js (28439:0)
> createFiberFromElement
> ..\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom.development.js (28465:0)
> createChild
> ..\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom.development.js (15109:0)
> reconcileChildrenArray
> ..\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom.development.js (15404:0)
> reconcileChildFibers
> ..\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom.development.js (15821:0)
> reconcileChildren
> ..\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom.development.js (19167:0)
> updateHostComponent
> ..\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom.development.js (19924:0)
> beginWork
> ..\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom.development.js (21618:0)
> HTMLUnknownElement.callCallback
> ..\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom.development.js (4164:0)
> Object.invokeGuardedCallbackDev
> ..\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom.development.js (4213:0)
> invokeGuardedCallback
> ..\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom.development.js (4277:0)
> beginWork$1
> ..\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom.development.js (27451:0)
> performUnitOfWork
> ..\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom.development.js (26557:0)
> workLoopSync
> ..\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom.development.js (26466:0)
> renderRootSync
> ..\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom.development.js (26434:0)
> performConcurrentWorkOnRoot
> ..\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom.development.js (25738:0)
> workLoop
> ..\node_modules\.pnpm\scheduler@0.23.0\node_modules\scheduler\cjs\scheduler.development.js (266:0)
> flushWork
> ..\node_modules\.pnpm\scheduler@0.23.0\node_modules\scheduler\cjs\scheduler.development.js (239:0)
> MessagePort.performWorkUntilDeadline
> ..\node_modules\.pnpm\scheduler@0.23.0\node_modules\scheduler\cjs\scheduler.development.js (533:0)

**Comment by dimaMachina** [comment]
Do you still have this issue? Closing for now, feel free to reply and i’ll reopen
