### ISSUE TITLE
can't download image from link

### ISSUE THREAD

**Issue by artem3332** [shuding/nextra#2708]
Good afternoon dear friends!
I’m trying to create a session, but using an open link on Yandex or Google Drive, your service does not download the image, how can I solve this problem?
400 Bad Request: "{"statusCode":400,"message":"Invalid status: current status is upload_failed","data":{}}"

![bag](https://github.com/shuding/nextra/assets/62416433/e2aff335-26e7-433f-af14-d0746dad0311)

**Comment by artem3332** [comment]
https://docs.csm.ai/Image-to-3d/1_Create_Session

**Comment by dimaMachina** [comment]
issue unrelated to nextra
