### ISSUE TITLE
Feedback for “Settings Menu”

### ISSUE THREAD

**Issue by lmccook** [shuding/nextra#2710]
Hi I am unable to add an image.  It asks for an image URL which I don't have.  It says on the settings menu that I can add a jpeg, png, svg, etc, but I am not able to.  Is there a way I can add this somehow?

Thanks

**Comment by mutasim77** [comment]
Next time when asking, please provide what you TRIED and what the ISSUE is.

**Comment by dimaMachina** [comment]
closing since it seems you issue is unrelated to Nextra
