### ISSUE TITLE
Head Tags are not working. Tried both static and dynamic tags as explained in the doc. Still no luck. 

### ISSUE THREAD

**Issue by rohitspujari** [shuding/nextra#2712]
I'm trying customize the annotation 'Index - Nextra' to 'Index - Company', I'm unable to do with the instructions below. 

https://nextra.site/docs/docs-theme/theme-configuration#dynamic-tags-based-on-page

**Comment by Esh07** [comment]
Try this if it work for you 

```js
export default {
  head: () => {
      ... 
    }, 
    useNextSeoProps() {
        const { frontMatter } = useConfig();
    
        const { asPath } = useRouter()
    
        if (asPath !== '/') {
            return {
                titleTemplate: '%s - Company name',
            }
        }
    },
    ... // other configs
}

}
```

Here is Doc
https://nextra.site/docs/docs-theme/theme-configuration#seo-options

**Comment by rohitspujari** [comment]
Beautiful. That solved it.

**Comment by rohitspujari** [comment]
Thank you

**Comment by bdthombre** [comment]
Saved. Thank you.
