### ISSUE TITLE
Hidden Routes doesn't work

### ISSUE THREAD

**Issue by rickkdev** [shuding/nextra#2719]
I'm using [Contentlayer ](https://contentlayer.dev/) for my blog configuration, and I aim to prevent the /blog route from adopting any Nextra styling. Initially, I sought to exclude it from the Submenu. According to the documentation, the snippet below should remove it from the Submenu.

```jss
{
  "blog": {
    "display": "hidden"
  },
  "help": "Help"
}
```

However, this approach didn't remove the Submenu link as expected. Additionally, I'm looking for a method to entirely bypass Nextra styling on the /blog route. I'm open to suggestions before considering the development of a custom solution.

**Comment by dimaMachina** [comment]
try nextra 3 https://github.com/shuding/nextra/issues/1421#issuecomment-1852012364, seems I fixed it in latest alpha

**Comment by dimaMachina** [comment]
Do you still have this problem with Nextra 3? Closing for now
