### ISSUE TITLE
yarn lint doesn't lint .mdx files

### ISSUE THREAD

**Issue by Nilegfx** [shuding/nextra#2722]
I feel that I am missing the big elephant in the room, but this is my first time to use nextra. I was under assumption that following the getting started docs should also enable linting `.mdx` files but this is not the case. 

to reproduce the is, you can follow the [getting started docs](https://nextra.site/docs/docs-theme/start) and create two files

`index.mdx`
```mdx
# Welcome to Nextra
<image> {/*noteice the error we are introducing here*/}
Hello, world!
```

and another file `second.tsx`
```tsx
import Image from 'next/image'
export default function Test() {
   return <Image /> //notice the error we are introducing here
}
```

you only get the error

```
3:12  Warning: Image elements must have an alt prop, either with meaningful text, or an empty string for decorative images.  jsx-a11y/alt-text
```
try to fix the `second.tsx` file

```tsx
import Image from 'next/image'
export default function Ahmed() {
    return <Image src="" alt="some alt"/> //notice the error we are introducing here
}
```

and rerun `yarn lint` again, you will get 
`✔ No ESLint warnings or errors`

**Comment by caffeine-addictt** [comment]
Are you including `.md` and `.mdx` files in your linter configuration?

**Comment by dimaMachina** [comment]
Use this eslint plugin / parser to lint md/mdx https://github.com/mdx-js/eslint-mdx
