### ISSUE TITLE
[v3] SubDocs are not working as expected with type: "page" and display: "hidden"

### ISSUE THREAD

**Issue by davitp** [shuding/nextra#2723]
Hello.

My setup looks like this.
Index page
- Subdocs1 (page1, page2) 
- Subdocs2 (page1, page2)

In _meta.js, subdoc1 and subdoc2 are marked with display: 'hidden' and type: 'page', because I don't want two separate pages to be shown on the top navbar, rather having a Menu with Subdoc1 and Subdoc2 inside.

Actual behaviour:
When entering Subdoc1 or Subdoc2 pages, sidebar is missing.

Expected behaviour: 
The Subdoc1 page has its own sidebar with its children only.

**Comment by dimaMachina** [comment]
Please share a reproduction repo

**Comment by davitp** [comment]
Here is the repo with reproduction: https://github.com/davitp/nextra-repro-v3
Please look at file [pages/_meta.ts](https://github.com/davitp/nextra-repro-v3/blob/main/pages/_meta.ts)

**Without** display: 'hidden', the behaviour is as expected, which is, the sidebars are properly shown on every subdoc folder (and the pages are shown in the navbar).

![image](https://github.com/shuding/nextra/assets/7922751/48275ef3-013f-4144-88de-d2406eb89c78)

**With** display: 'hidden', pages are hidden from navbar, but when accessing the pages directly (or via navbar sub-menu) the sidebars are missing.

![image](https://github.com/shuding/nextra/assets/7922751/23e0d98f-36d4-43ee-83f5-bbb93a8bba41)

**Comment by dimaMachina** [comment]
> With display: 'hidden', pages are hidden from navbar, but when accessing the pages directly (or via navbar sub-menu) the sidebars are missing.

this is expected behaviour

**Comment by davitp** [comment]
But if I want to hide a page, but keep its sub-pages, isn't that possible?

**Comment by dimaMachina** [comment]
hidden pages and their subpages doesn't add to the page map, so they will always be missing in the sidebar

**Comment by davitp** [comment]
The ultimate goal is to have all the "subdoc" pages grouped under a menu. 
So, it's enforcing the navbar link when the type is page. 

IMHO, it would be natural to group links the way It works best (via menu), so is it possible to hide it from Navbar only?

**Comment by KaiVolume** [comment]
This used to work with .json

The behaviour is as @davitp described in the issue description with .json.

If you change to .js/.ts then the sidebars do not show for sub docs accessed through menu

**Comment by marcklingen** [comment]
Running into this issue as well when upgrading to v3. Is this the new desired behavior? Has someone figured out a workaround? We have a number of subsections of our docs that should have sidebars but need to be excluded from our main menu.

Related #2909

**Comment by marcklingen** [comment]
Fixed this for us via css override (desktop menu only)

Global `overrides.css` ([source](https://github.com/langfuse/langfuse-docs/blob/main/src/overrides.css#L16-L23))
```css
/* Hide guides and faq from main menu */
.nextra-nav-container>nav>a[href="/guides"] {
    display: none;
}
```

_meta.tsx
```ts
export default {
  ...
  guides: {
    type: "page",
    title: "Guides",
  },
  ...
}

**Comment by dimaMachina** [comment]
this was fixed by https://github.com/shuding/nextra/issues/3331 in stable v3
