### ISSUE TITLE
How to Deploy to Local Machine (My Private Server)

### ISSUE THREAD

**Issue by indarjoko** [shuding/nextra#2724]
Hi, I want to build nextra on local machine only (my server). Can you share about build mode and run into local server? and it is possible to use pm2 for automatically run? thanks.

**Comment by aidanm1999** [comment]
Hi @indarjoko, building and deploying a Nextra site should be the same as a Next.js site if I am not mistaken. Check out the detailed instructions the Next.js team have written [here](https://nextjs.org/docs/pages/building-your-application/deploying#self-hosting). Depending on your preferences, you could:

1. Set up a Node.js server (essentially building and serving it). I believe this would be the best option if you are using `pm2` as you can define the start-up/restart by just running `npm/yarn/pnpm run start`. 
2. If you just want to access it locally, you can build it statically and there are plenty of great tools that spin up a static HTTP service locally when you start up your machine
3. You could set it up in a Docker instance, but as my Docker exposure is limited, I cannot recommend using it

**Comment by Match-Yang** [comment]
Hi, if you're asking this question, am I right in assuming that you may not be familiar with NextJS or its deployment processes? If you're not familiar with the process or would like to skip them, I would suggest going with some SaaS service that works similar to Nextra so you don't have to think about how to do this. For example [Docuo](https://www.spreading.ai/?via=github)

**Comment by indarjoko** [comment]
Thank you for all of your suggestion  @Match-Yang and @aidanm1999 . I tried alone with reading the documentation and articles and then it work very well. Thanks.
