### ISSUE TITLE
Static Image don't work with remote images

### ISSUE THREAD

**Issue by arvinxx** [shuding/nextra#2729]
I'm using Nextra alpha.18.

image like this:

```md
![](https://github.com/xxxx/assets/30863296/1b405347-f4c3-4c55-82f6-47116f2210d0)
````

won't work as document says:

<img width="886" alt="image" src="https://github.com/shuding/nextra/assets/28616219/1e750ad7-f69c-41bf-88b6-114a0f1a7e29">

**Comment by dimaMachina** [comment]
duplicate https://github.com/shuding/nextra/issues/2024
