### ISSUE TITLE
Search is not updating on Vercel

### ISSUE THREAD

**Issue by Reddybrekkers** [shuding/nextra#2730]
When I run my help center locally, the search is up to date. However, in my Vercel app the search shows values that have since been deleted:
- If I search the deleted term, it appears multiple times in search despite having been deleted when running on Vercel.
- If I search the term that replaced the deleted term, it does not show up in search when running on Vercel.

Does anyone know what might cause this?

**Comment by dimaMachina** [comment]
maybe this can help you https://github.com/shuding/nextra/issues/1564#issuecomment-1447419595

**Comment by dimaMachina** [comment]
This should be fixed in nextra 3 since there is no more _meta.json, try to update
