### ISSUE TITLE
[Built-ins] In docs-theme some Built-ins not loading

### ISSUE THREAD

**Issue by whymancreates** [shuding/nextra#2736]
Im trying to work with built-ins in my docs theme, the Callout and Bleed component work and load just fine but the Tabs, Steps, Card and Filetree do not load for some weird reason.

I tried to import from both `nextra/components` and `nextra-theme-docs`

<img width="1595" alt="Screenshot 2024-02-23 at 10 12 34" src="https://github.com/shuding/nextra/assets/129885898/f2639110-8200-4c88-8013-ba5dc40de3c0">
<img width="1012" alt="Screenshot 2024-02-23 at 10 12 41" src="https://github.com/shuding/nextra/assets/129885898/cf295c17-7237-48c0-8142-fed6285ce6e8">

and when I try steps I get a different error
<img width="992" alt="Screenshot 2024-02-23 at 10 17 53" src="https://github.com/shuding/nextra/assets/129885898/df1fc5af-9d4b-4b64-b1b8-5182fef76cd8">

**Comment by whymancreates** [comment]
To add more to this, seems like `Tabs.Tab `might not be defined. This code works 

```
import { Bleed, Callout, Tabs } from "nextra-theme-docs";
 
<Tabs items={['pnpm', 'npm', 'yarn']}>


</Tabs>
```

but this code fails to load

```
import { Bleed, Callout, Tabs } from "nextra-theme-docs";
 
<Tabs items={['pnpm', 'npm', 'yarn']}>
  <Tabs.Tab>**pnpm**: Fast, disk space efficient package manager.</Tabs.Tab>
  <Tabs.Tab>**npm** is a package manager for the JavaScript programming language.</Tabs.Tab>
  <Tabs.Tab>**Yarn** is a software packaging system.</Tabs.Tab>
</Tabs>
```
<img width="1441" alt="Screenshot 2024-02-23 at 14 53 47" src="https://github.com/shuding/nextra/assets/129885898/3847f800-ca43-4ce2-8df4-a83cdc5fec9c">

<img width="988" alt="Screenshot 2024-02-23 at 14 53 37" src="https://github.com/shuding/nextra/assets/129885898/49127f69-cbc5-414e-b5b8-656343803d70">

**Comment by marshallgeorge44** [comment]
I had the same issue, running `pnpm update`  fixed the issue for me. 

I noticed when looking in `node_modules\nextra\dist\components` that the components where not defined, but after the update they are now present and it is working as expected.

**Comment by whymancreates** [comment]
@marshallgeorge44 thanks a bunch that worked and your comment was super helpful. Appreciate it
