### ISSUE TITLE
How do I remove dropdown from top level folder 

### ISSUE THREAD

**Issue by rickkdev** [shuding/nextra#2737]
How do I remove the dropdown menu here from Reference. It shouldn't be a collapsable menu. 

My folder structure is /pages/help (renamed to Reference)/all other categories

I tried to also hide help instead but I can only rename it.

![change nextra](https://github.com/shuding/nextra/assets/28826387/f85966d2-b0ad-452e-aba5-02f5d6e5def7)

**Comment by dimaMachina** [comment]
https://github.com/shuding/nextra/issues/2319#issuecomment-1734547874

**Comment by rickkdev** [comment]
@dimaMachina is there also a way so it doesnt highlight on hover?
