### ISSUE TITLE
h2 headline doesnt have the "#" effect

### ISSUE THREAD

**Issue by samuelgoff** [shuding/nextra#274]
Hey @shuding, thanks so much for creating this amazing project 🙏🏼 It's been a tremendous help. I have only one issue that's preventing me from delivering a no-brainer replacement for Hugo:

> ![image](https://user-images.githubusercontent.com/8458838/142590223-23bfcc5f-d8b0-46fd-847f-c488263cba6c.png)
> 
> I cloned the master branch just now and tried to run locally, but the h2 headline doesnt have the "#" effect
> 
> thanks @anudit , let me check yours
> 
> _Originally posted by @ChinW in https://github.com/shuding/nextra/issues/235#issuecomment-973861043_

After reading this thread, I was able to solve one of my issues (missing titles on individual pages), however I'm still having the exact same issue as a couple others are/were having: **`h2` headlines (`##`) don't have the "#" effect that automatically populates these links into the navbar on the left.**

I replicated all of the changes described below and it's still not working:

> @ChinW checkout the codebase [anudit/convodocs](https://github.com/anudit/convodocs), Got the titles and `floatTOC` to work correctly with the latest versions of the dependencies. 
> 
> _Originally posted by @anudit in https://github.com/shuding/nextra/issues/235#issuecomment-973859193_

Note the format of the `meta.json` documented by Nextra is different from what is used in the above. I tried it using the different structure (object vs key/value + `"type": "nav"`), but this ends up adding them to the header rather than a side navbar, so I walked this change back.

Separate but lesser concerns that don't currently impact me:
- `floatTOC` doesn't work, no matter how I format the `meta.json`
- `.md` files don't render properly, with React imports & navbar JSON showing up in the browser window; I have to change the file extensions to `.mdx` in order for them to work properly

Aside from the issues mentioned above, Nextra has been absolutely awesome, and I'd love to be able to solve this one remaining dealbreaker. Anyone else seeing this issue? Anyone else figure out a solution?

**Comment by shuding** [comment]
Thanks for writing this! I think it's because I'm using a raw `<h2>` here instead of `##` to avoid it in the sidebar: https://raw.githubusercontent.com/shuding/nextra/master/pages/features/mdx.mdx

**Comment by samuelgoff** [comment]
> Thanks for writing this! I think it's because I'm using a raw `<h2>` here instead of `##` to avoid it in the sidebar: https://raw.githubusercontent.com/shuding/nextra/master/pages/features/mdx.mdx
> 
> I did it intentionally to make the sidebar cleaner.

Hey @shuding, thanks for getting back to me. I'm genuinely confused. Perhaps you're referencing a different version than the one I'm seeing, but in the one I'm looking at both in the repo & the live deployed website, I see your linked file is using `##`, **_not_** `<h2>`. I also see the `##` showing up in the menu, as is my goal (& the goal of others). See attached image, which illustrates my confusion :)

![markup-01](https://user-images.githubusercontent.com/2007084/144681681-0d32b409-3e27-4e36-b13c-4e1171b8f4d8.png)

Sounds like you're describing exactly the opposite: trying to prevent them from showing up in the menus. It would be great if the `meta.json` or other mechanism could easily allow us to customize whether `h2`/`##` headers are included or excluded from the nav menus.

Of course, when I looked at the example repo by @anudit, I saw an example of converting the `meta.json` from key/value to objects, which allows the inclusion of a `"hidden": true` property -- however, I also discovered this was incompatible with the vertical menu, only with displaying them along the top menubar horizontally.

**Comment by samuelgoff** [comment]
@shuding by the way, I thought perhaps I misunderstood you, so I tried replacing own own `##` headlines (which match how your documentation site works) with `<h2>` headlines, but it produces no change. I'm still unable to get them to show up in the menu, regardless of which option I use.

**Comment by faisalsayed10** [comment]
facing the same issue here

**Comment by anudit** [comment]
Hey @samuelgoff @faisalsayed10 are you on version `2.0.0-beta.5` for `nextra` and `nextra-theme-docs` ?

**Comment by faisalsayed10** [comment]
nope. this is in my package.js
```
    "nextra": "^1.1.0",
    "nextra-theme-docs": "^1.2.6",
```

**Comment by anudit** [comment]
@faisalsayed10 Try switching to `2.0.0-beta.5`

**Comment by faisalsayed10** [comment]
ohh yeah, it started working now

**Comment by shuding** [comment]
Fixed in both `@beta` and `@alpha` releases, working on making it stable in 2.0 soon 🙏
