### ISSUE TITLE
Feedback for “Tailwind CSS”

### ISSUE THREAD

**Issue by Sciphr** [shuding/nextra#2741]
Good evening!

I'm trying out Nextra's documentation template for the first time; Followed all the instructions to install and deploy it. It works great, however using TailwindCSS seems to not work for me. I followed all of Nextra documentation, NextJS and TailwindCSS's docs to install it correctly, but it still won't work. I have posted all details here: 

https://stackoverflow.com/questions/78051080/tailwindcss-not-working-in-new-nextra-web-app

next.config.js

```
const withNextra = require("nextra")({
  theme: "nextra-theme-docs",
  themeConfig: "./theme.config.tsx",
});

module.exports = withNextra();
```

package.json
```

{
  "name": "documenation",
  "version": "0.0.1",
  "description": "Documentation",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Sciphr/KICSDocumentation.git"
  },
  "author": "Jacob",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/Sciphr/KICSDocumentation/issues"
  },
  "homepage": "https://github.com/Sciphr/KICSDocumentation/#readme",
  "dependencies": {
    "eslint": "^8.57.0",
    "next": "^14.1.0",
    "nextra": "latest",
    "nextra-theme-docs": "latest",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/node": "18.11.10",
    "autoprefixer": "^10.4.17",
    "postcss": "^8.4.35",
    "tailwindcss": "^3.4.1",
    "typescript": "^4.9.3"
  }
}
```

tailwind.config.js

```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,md,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,md,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,md,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
```

And the MDX file I'm using for testing (index.mdx):

```
##
import Tester from "../components/tester";

<Tester />

##

import React from "react";

export const Tester2 = () => {
  return (
    <div>
      <h1 className="text-blue-700">Tester 2</h1>
    </div>
  );
};

<Tester2 />

```

Any help would be greatly appreciated! I've used TailwindCSS on numerous sites but this is the only time I have been unsuccessful in using it. Thank you!

**Comment by Sciphr** [comment]
Update: So I seemed to have 'potentially' fixed it. Currently it is working but I am not 100% confident in the fix. Here is what I did:

Created an "_app.js" file in the Pages folder (Nextra defaults to using pages for their template), and adding an import for your globals.css file; Just like you would in your layout.js file in Next.js 14 App router

```
import "../styles/globals.css";
export default function MyApp({ Component, pageProps }) {
return <Component {...pageProps} />;}
```

That worked in my localhost, however deploying to Vercel, it failed. So I added 'standalone: true' to my next.config.js file, and that seemed to have fixed the problem, so officially it is running. I will keep this up for the next week just to see if anyone else has any better ideas/can correct me on my potentially lackluster fix.

```
const withNextra = require("nextra")({
theme: "nextra-theme-docs",
themeConfig: "./theme.config.tsx",
standalone: true,
});

module.exports = withNextra();
```

**Comment by samcxps** [comment]
A custom app file (`_app.js`) is the correct way to include global styles in the pages router, as per [the docs](https://nextjs.org/docs/pages/building-your-application/styling/tailwind-css#importing-styles-1). It seems as though it was misconfigured in the first place, so nothing to change there.

Not sure why you would need the output to be set to standalone though, especially when deploying on Vercel. Did you create this next app with the `create-next-app` utility? Were there any errors?

**Comment by Sciphr** [comment]
> A custom app file (`_app.js`) is the correct way to include global styles in the pages router, as per [the docs](https://nextjs.org/docs/pages/building-your-application/styling/tailwind-css#importing-styles-1). It seems as though it was misconfigured in the first place, so nothing to change there.
> 
> Not sure why you would need the output to be set to standalone though, especially when deploying on Vercel. Did you create this next app with the `create-next-app` utility? Were there any errors?

Honestly it was 3am after looking at this for hours, that I absolutely most likely didn't need to add 'standalone', so you're absolutely probably right. But I appreciate the validation for the _app.js file as I figured later that was really all I needed. I absolutely didn't look at the docs on the Next.JS site, but on the Nextra site + the TailwindCSS site which (I believe) didn't state that I needed the _app.js, so that's totally on me for not looking at Next.JS documentation too. 

I'll test again tonight without the 'standalone' which I'm sure won't change anything and confirm it was not needed. Thanks mate!

**Comment by amcdnl** [comment]
I'm also running into this, however, the `standalone` prop did not solve my problem. Any updates on a actual fix?
