### ISSUE TITLE
Theme switcher UI glitch

### ISSUE THREAD

**Issue by RakeshUP** [shuding/nextra#2745]
Hi, 

I'm having a small UI glitch in the next-theme swither on the sidebar. The UI is messed up during the first load always and goes away when I refresh the page. The issue exists while both sidebar toggleButton is `true` or `false`.

<img width="268" alt="Screenshot 2024-02-27 at 4 35 09 PM" src="https://github.com/shuding/nextra/assets/20946466/177cefe2-b6f6-4b05-a892-de514a2e73d4">

**Comment by dimaMachina** [comment]
please provide a reproduction

**Comment by dimaMachina** [comment]
Closing due silence
