### ISSUE TITLE
sidebar.autoCollapse not working

### ISSUE THREAD

**Issue by Funmi7** [shuding/nextra#2756]
<img width="294" alt="Screenshot 2024-03-01 at 4 00 50 PM" src="https://github.com/shuding/nextra/assets/34395743/54ef7331-1e49-4f2b-b3b7-06f86bec2a75">
<img width="292" alt="Screenshot 2024-03-01 at 4 08 33 PM" src="https://github.com/shuding/nextra/assets/34395743/c1631d3b-1704-4f82-bb85-c23504c3115d">

sidebar.autoCollapse does not work for me, it shows the object property does not exist, and I am on the latest version

**Comment by dimaMachina** [comment]
update `nextra` and `nextra-theme-docs`, replace `latest` with pinned version
