### ISSUE TITLE
How to move root pages to a non-directory in sidebar?

### ISSUE THREAD

**Issue by 0xbid** [shuding/nextra#2762]
# Overview

I am using app router + pages router, where app router contains my app content and pages router contains my Nextra docs content.

```
./
├──   docs/
│   ├──   advanced/
│   │   └──   satori.mdx
│   ├──   _meta.json
│   ├──   about.mdx
│   ├──   advanced.mdx
│   ├──   index.mdx
│   └──   overview.mdx
├──   _meta.json
└──   globals.css
```

Now when I visit example.com/docs, everything works. However, what I don't like is that it treats the docs directory as a directory in the docs itself: **on the sidebar, there is a directory-style tab that says "docs" with a dropdown arrow**, and all content is in it.

This is undesirable, since it's clear the user is already visiting docs.

## Things I've tried:

* Root _meta.json:
```
{
	"docs": "Some Other Title",
}
```
This successfully changes the word "docs" to "Some Other Title", but it's still not as good as removing the directory entirely

* theme.config.tsx :
```
import NamesLogoSVG from '@/app/_components/svg/NamesLogoSVG';
import { useRouter } from 'next/router';
import { useConfig } from 'nextra-theme-docs';

// eslint-disable-next-line import/no-anonymous-default-export
export default {
    sidebar: {
        titleComponent({ title, type }) {
            if (title === 'docs') {
                return null;
            }
            return <>{title}</>;
        }
    },
};
```
This changes "docs" to be blank, but an empty directory-style row still exists:
![image](https://github.com/shuding/nextra/assets/145181252/87388822-77b2-4719-91ce-76d70146b35c)

Neither of these solutions achieve what I want: removing the dropdown entirely and moving all of it's content (e.g. Introduction, Overview) to the root such that it is not nested in anything.

**Comment by ronneldavis** [comment]
Hey had the same issue and this helped: https://github.com/shuding/nextra/issues/2319#issuecomment-1734547874

**Comment by 0xbid** [comment]
thank you so much! closing as duplicate of #2319
