### ISSUE TITLE
[v3] Search is broken - undefined is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by hariria** [shuding/nextra#2763]
## Description

Search seems to be completely broken in the `swr-site` example on the latest v3 branch. I believe it's because Nextra is not creating the correct i18n file for flexsearch to use. Specifically in my case, this is `nextra-data-en.json`.

## Root Problem

I receive this error when typing something in the search filed

```sh
Uncaught (in promise) TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at doSearch (index.js:955:39)
    at eval (index.js:1050:5)
    at Generator.throw (<anonymous>)
    at rejected (index.js:90:29)
```

Digging into it further, it seems like the problem is coming from the `doSearch` function in `packages > nextra-theme-docs > src > components > flexSearch.tsx`. Specifically this line. Based on the error above, it seems as though the `indexes` object is undefined.

```js
    const doSearch = (search2)=>{
        ...
        const [pageIndex,sectionIndex] = indexes[locale]; // ⚠️ Unexpected error
        ...
    }
```

Additionally I see a `404` error on the client, like so:

```sh
GET http://localhost:3002/_next/static/chunks/nextra-data-en.json 404 (Not Found)
```

due to a missing `_next/static/chunks/nextra-data-en.json` in `examples > aptos-swr` example, also stemming from `flexSearch.tsx`.

```js
const loadIndexesImpl = async (
  basePath: string,
  locale: string
): Promise<void> => {
  const [searchData, Document] = await Promise.all([
    fetch(`${basePath}/_next/static/chunks/nextra-data-${locale}.json`).then(
      response => response.json() as Promise<SearchData>
    ),
    import('flexsearch').then(mod => mod.default.Document)
  ]) // ⚠️ Unexpected 404 error -> json not found 
```

## Repro

Running `pnpm dev` in the latest v3 branch for `examples > aptos-swr`. Go to `localhost:3000` and try to search for anything.

https://github.com/shuding/nextra/assets/31301117/187bad95-ae68-47cc-ae57-fe83df1f3f8c

cc @dimaMachina

**Comment by hariria** [comment]
## Partial Resolution

I figured out what was causing the issue. 

In `nextra > src > server > loader.ts` there's a line like so:

```ts
  if (searchIndexKey && frontMatter.searchable !== false) {
    // Store all the things in buildInfo.
    const { buildInfo } = this._module as any
    buildInfo.nextraSearch = {
      indexKey: searchIndexKey,
      title,
      data: structurizedData,
      route
    }
```

The `swr-site` example had 

```mdx
---
title: React Hooks for Data Fetching
searchable: false
---
```

as the frontmatter. It seems like the `nextraSearch` attribute in `buildInfo` was then referenced in `packages > nextra > src > server > webpack-plugins > nextra-search.ts`. Specifically here


```ts
            const nextraSearch = entryModule?.buildInfo?.nextraSearch
            if (nextraSearch) {
              const { title, data, indexKey, route } = nextraSearch
              const indexFilename = `nextra-data-${indexKey}.json`
              indexFiles[indexFilename] ??= {}
              indexFiles[indexFilename][route] = { title, data }
            }
```

Thus, setting `searchable: false` in the frontmatter was making `nextraSearch` to be `false`, and so the indexFiles were not assigned, causing the error above. 

I guess my question is, is this supposed to be like this? I was under the impression that `searchable` in the frontmatter was supposed to indicate whether or not you want the content on that page to be indexed, not that it would break search for Nextra?

**Comment by hariria** [comment]
New update: seems like issues with search arise when one of two scenarios occur:

1. frontmatter has `searchable` marked as `false` and running `pnpm dev`
2. `nextra-data-en.json` not found, also due to `pnpm dev`

When running `pnpm build && pnpm start` it builds the nextra-data-en.json file correctly

**Comment by dimaMachina** [comment]
This confusing error which happens only in dev environment will be fixed in next alpha release

Why this happens only in dev - because search is collected only for the current route, or visited routed
You were right, `index` page of swr example contained `searchable: false` and this provoked some bug happened only on dev env

**Comment by hariria** [comment]
Thanks @dimaMachina! Rockstar!
