### ISSUE TITLE
How to set actual color for dark/white mode?

### ISSUE THREAD

**Issue by itsmaty** [shuding/nextra#2772]
So you can chnage between dark & white mode, great.
But how to actually set the color for the background/text for certain mode.

So for drakmode the background is HEX #111111
Ho to chnage it to #00000 or any other color?

**Comment by dimaMachina** [comment]
Available in v3, use `backgroundColor` theme option

**Comment by itsmaty** [comment]
took some time to figure this out but it works thanks

whats a bit confusing and not "expected behaviour" that you have to set the rgb code in a string and cant use the hex code
but as i looked into how this was actually implemented here: https://github.com/shuding/nextra/pull/2732
and how the css variable is used in the css is probably a tailwind thing and so wont be able to support hex codes.

**Comment by mmkal** [comment]
@dimaMachina exciting to hear! Are there instructions for migrating to v3 (or v4?) - I tried manually installing one of the alpha packages but got peer dependency warnings and some errors when running.

**Comment by dimaMachina** [comment]
@mmkal https://the-guild.dev/blog/nextra-3
