### ISSUE TITLE
Feedback for “Theme Configuration”

### ISSUE THREAD

**Issue by reynold-zhang** [shuding/nextra#2776]
q: Why does head configured not take effect? i need help ~
<img width="1021" alt="image" src="https://github.com/shuding/nextra/assets/118344237/28b55c13-70c2-4f33-a935-9ef438733f3d">
<img width="574" alt="image" src="https://github.com/shuding/nextra/assets/118344237/3bd7e17f-d0d6-4d3d-b2b0-2b9328fb2129">

**Comment by dimaMachina** [comment]
put favicon.ico in `public` folder

**Comment by reynold-zhang** [comment]
> put favicon.ico in `public` folder

oops.. I was careless. thank you so much, pro.
