### ISSUE TITLE
Sidebar toggle button with custom Navbar in mobile

### ISSUE THREAD

**Issue by bpoulaindev** [shuding/nextra#2781]
When working with Nextra Docs and using a custom Navbar component, it isn't possible to **toggle the sidebar in mobile** view as the toggle is rendered outside of the page.
Even somehow pressing the toggle doesn't display the sidebar.
How can i retrieve the original mobile behaviour while still using a **custom navbar** ?
<img width="481" alt="image" src="https://github.com/shuding/nextra/assets/64689165/f9490644-3725-4126-b93f-aceafb19aaaf">

**Comment by dimaMachina** [comment]
I think this can be done by exporting `useMenu` hook, PR welcome (use v3 as base branch) https://github.com/shuding/nextra/blob/217f7082aca416d0d16bce83cd63143d9f7f302f/packages/nextra-theme-docs/src/contexts/menu.ts#L14
