### ISSUE TITLE
White color as primary color

### ISSUE THREAD

**Issue by radim10** [shuding/nextra#2786]
How to use white color as primary color?  When using hue there is no meaningful representation because white is achromatic, meaning it doesn't contain hue information.

**Comment by dimaMachina** [comment]
Currently it doesn't possible PR welcome

**Comment by SwarajBaral** [comment]
I would love to fix this. Could you maybe point me in the right direction ? From what I understand from this ticket, the primary color list must be extended to include white ?

**Comment by dimaMachina** [comment]
> I would love to fix this. Could you maybe point me in the right direction ? From what I understand from this ticket, the primary color list must be extended to include white ?

I am not sure how to support white color, currently in this place we generate primary variants https://github.com/shuding/nextra/blob/b47880d504a4961ba3229419abdd9e62d327d6e3/packages/nextra-theme-docs/tailwind.config.ts#L4-L11

and in this place we inject CSS variables https://github.com/shuding/nextra/blob/b47880d504a4961ba3229419abdd9e62d327d6e3/packages/nextra-theme-docs/src/components/head.tsx#L59
