### ISSUE TITLE
Compile error after i18n

### ISSUE THREAD

**Issue by arange** [shuding/nextra#279]
Error message
```
TypeError: (0 , _pages_en_md_nextra_raw__WEBPACK_IMPORTED_MODULE_3__.getStaticProps) is not a function
  11 |   const locale = context.locale;
  12 |   if (locale === 'en' && true) {
> 13 |     return page_data_0(context);
     |                       ^
  14 |   } else {
  15 |     return {
  16 |       props: {}
```

Reproduce procedure:
Follow the [steps](https://nextra.vercel.app/features/i18n).
This only happens after I changed `/pages/posts/pages.md` to `/pages/posts/pages.en.md`, and only for this particular file. If I delete this md file, the error disappears.

Not sure what's causing it at the moment, but looks like in the `loader.js` at `line 205`, when trying to import `getStaticProps` from `'./${file.name}?nextra-raw'` it returns undefined.

**Comment by B2o5T** [comment]
Hi @arange, do you still have this problem?
