### ISSUE TITLE
Can the <Tabs> component be crawlable and indexable?

### ISSUE THREAD

**Issue by zachtil** [shuding/nextra#2798]
Hi all,

Lots of support for this project!

Currently, it seems that the content of hidden `<Tabs.Tab>` components remain uncrawlable by Google, AI Assistants, and Algolia. The content of the non-selected tabs never seems to be rendered by automated crawlers.

Can the component be changed to make each tab contents always available for crawling but hide unselected and only show the contents of the deselected tabs?

**Comment by dimaMachina** [comment]
ref https://github.com/tailwindlabs/headlessui/discussions/740, will be indexable by default in v3

**Comment by zachtil** [comment]
Thank you, that was helpful. Why not make it available already in one of the next 2.x versions?

**Comment by dimaMachina** [comment]
> Thank you, that was helpful 🙏 Why not make it available already in one of the next 2.x versions?

https://github.com/shuding/nextra/pull/2765#issuecomment-1985960730
