### ISSUE TITLE
Tables do not render correctly

### ISSUE THREAD

**Issue by sarthaktexas** [shuding/nextra#28]
![image](https://user-images.githubusercontent.com/28282096/100563248-96f9f400-3283-11eb-9a96-cc063010f85c.png)

**Comment by sarthaktexas** [comment]
Looks like I can add this:
```html
<link rel="stylesheet" href="/style.css" />
```
to my `theme.config.json` and create a `style.css` file in my `/public` directory and apply my own styles.

**Comment by shuding** [comment]
Added better table support in the latest theme: https://nextra.vercel.app/docs/mdx#table :)
