### ISSUE TITLE
Tags page not rendered when i18n is enabled

### ISSUE THREAD

**Issue by arange** [shuding/nextra#280]
If we enable i18n for posts, the default `[tag].md` will throw an 404 error because all md file now should have a prefix of '.en' or '.zh' for it to be recognised by MDX.
However, if we add that -> `[tag].en.md`, the page is simply blank, and we get the following error message in console: 
`Component 'Page_0' was not imported, exported, or provided by MDXProvider as global scope`

Please help me, I've been trying to debug for hours but couldn't figure out how the tags dynamic routes are parsed as I'm new to Next.js

Thanks!

**Comment by B2o5T** [comment]
Currently blog don’t support i18n. Main issue https://github.com/shuding/nextra/issues/182
