### ISSUE TITLE
Feedback for “Page Configuration”

### ISSUE THREAD

**Issue by EmericZh** [shuding/nextra#2802]
I added this configuration, but the folder still shows in the sidebar. it didn't work.
<img width="864" alt="image" src="https://github.com/shuding/nextra/assets/118344237/5295e254-cf07-4e17-b4dc-8ecf67a51ac9">

**Comment by dimaMachina** [comment]
Fixed in v3

**Comment by reynold-zhang** [comment]
> Fixed in v3

okay, thanks~
