### ISSUE TITLE
Hidden Routes still show on Mobile Browser - Feedback for “Page Configuration” 

### ISSUE THREAD

**Issue by thanksgaga** [shuding/nextra#2813]
Hi, 
Hidden Routes still show on Mobile Browser, even after I set it up as "display": "hidden".
Anything I can do to fix it? Thanks! 

pages/_meta.json
{
  "index": "My Homepage",
  "contact": {
    "display": "hidden"
  },
  "about": "About Us"
}

**Comment by dimaMachina** [comment]
Try nextra v3

**Comment by dimaMachina** [comment]
Fixed in Nextra 3
