### ISSUE TITLE
In Dark mode, how to use a light gray color as --primary-color?

### ISSUE THREAD

**Issue by sykp241095** [shuding/nextra#2815]
I have read the docs https://nextra.site/docs/docs-theme/theme-configuration#theme-color, and know that we are using HSL color format, and I also know hsl(0, 0%, 50%) is a gray color, but where should I set the  HSL Lightness value?

<img width="834" alt="image" src="https://github.com/shuding/nextra/assets/1237528/a092a52c-0054-42ea-a348-23b7ee0e1b0b">

**Comment by arno-fukuda** [comment]
If we'd want to add it, here is a good reference, where saturation was added.
https://github.com/shuding/nextra/pull/2281/files
