### ISSUE TITLE
Bleed overflows incorrectly in firefox

### ISSUE THREAD

**Issue by domin-mnd** [shuding/nextra#2824]
## Chrome:

![image](https://github.com/shuding/nextra/assets/69919939/fe2c6519-5d33-45d4-87ae-ab465e5b1ad6)

## Firefox:

![image](https://github.com/shuding/nextra/assets/69919939/00e91991-5765-465a-be1c-17cc51b7dbff)

[Example used](https://nextra.site/docs/docs-theme/built-ins/bleed#example)

**Comment by dimaMachina** [comment]
ty for the catch, will be fixed in v3
