### ISSUE TITLE
On Firefox, search box can't input and match Chinese files

### ISSUE THREAD

**Issue by CaryiWong** [shuding/nextra#2833]
Windows Firefox 121.0.1 (64 x)
Input Method: Sogou or Microsoft Input Method

When entering Chinese, the search box will display the corresponding pinyin. When I press "space" or "number" to select words, the input box does not respond and matches with pinyin, resulting in matching failure。
I’ve already used the latest nextjs and nextra. Please help fix it out ~~

![error1](https://github.com/shuding/nextra/assets/10609679/05aeedf7-bddb-4a28-a366-c984c5393111)

**Comment by CaryiWong** [comment]
It also appeared at https://nextra.site/ while visiting by Firefox

**Comment by yyrc** [comment]
我测试过自己的nextra，估计是firefox的问题。而且我测试过在firefox使用vitepress用中文搜索，也有问题，估计不会修复了。毕竟现在用chrome的人多太多。

**Comment by gitforziio** [comment]
I have encountered this situation as well.

Perhaps modifying [this function](https://github.com/shuding/nextra/blob/e1574f06b5d8c0377c2e6f74bd30deb4d5198521/packages/nextra-theme-docs/src/components/flexsearch.tsx#L261) can resolve the issue.

**Comment by dimaMachina** [comment]
I don't know Chinese, PR is welcome, some work with the Chinese language was done at https://github.com/shuding/nextra/pull/2124

**Comment by dimaMachina** [comment]
fixed in https://github.com/shuding/nextra/releases/tag/nextra-theme-docs%403.0.0-alpha.34
