### ISSUE TITLE
Hiding folder directory from sidebar whilst keeping subfolders

### ISSUE THREAD

**Issue by jobiewong** [shuding/nextra#2834]
Is it possible to hide a parent directory from the sidebar without also hiding its children?

Currently, setting `"display": "hidden"` to the parent directory hides all sub-files/directories. It is possible to re-add them manually, but I want to avoid having to do this.

The purpose of this behaviour would be to reduce the number of unnecessary indentation levels in the sidebar in favour of separating our sections with titles and separators.

**Comment by keaganaut** [comment]
@jobiewong, set `"display" : "children"`

**Comment by jobiewong** [comment]
Thanks! That achieves the desired effect. However, if sub-folders/files share the same names as sibling folders duplicate entries in the sidebar appear and the console displays key errors. Is there a way to define IDs in the _meta.json explicitly rather than directly using the file name?

**Comment by keaganaut** [comment]
There's a workaround here: https://github.com/shuding/nextra/issues/2557#issue-2013595171, granted it's not a long-term solution.
