### ISSUE TITLE
Hiding breadcrumbs through theme.config.tsx

### ISSUE THREAD

**Issue by kyrylolvov** [shuding/nextra#2838]
Is there a way to hide breadcrumbs? E.g my documentation links are on the same level and I just use sidebar separators, so dont want to have breadcrumbs displayed as they just display same as page title above it in a smaller font.

<img width="739" alt="Screenshot 2024-04-15 at 7 08 27 AM" src="https://github.com/shuding/nextra/assets/70720713/fa96dcad-f851-4834-8641-35c93c26ff2b">

**Comment by arno-fukuda** [comment]
https://nextra.site/docs/docs-theme/page-configuration#advanced

inside your `_meta.json`, try adding the following for every page entry
```
{
  "getting-started": {
    "title": "Getting Started",
    "theme": {
      "breadcrumb": false
     }
  }
}
```
