### ISSUE TITLE
When entering anything in search bar, page scrolls

### ISSUE THREAD

**Issue by kyrylolvov** [shuding/nextra#2840]
https://github.com/shuding/nextra/assets/70720713/facd04f0-391b-47c7-9957-55787a418f2e

**Comment by dimaMachina** [comment]
caused by https://github.com/shuding/nextra/pull/2104

https://github.com/llllvvuu/nextra/blob/e26ee4173bd690cf346f4e7fed333bf819c4e13e/packages/nextra-theme-docs/css/styles.css#L14
