### ISSUE TITLE
Navigation Bar is Unstable

### ISSUE THREAD

**Issue by Yijia-Chen** [shuding/nextra#2847]
When I click on some part of the Navigation Bar (determined by `_meta.json`), the other part of the bar changes to an older version. I suspect this is a cache problem of Nextra. Has anyone else had this issue?

See below for details. For example, the "Flow" page becomes "Progression", which is from an older version, when one clicks on "Fundamentals".

![Screenshot 2024-04-21 at 14 35 22](https://github.com/shuding/nextra/assets/38818142/8868fb2c-50c3-4603-b69b-b80223d942bc)

![Screenshot 2024-04-21 at 14 35 29](https://github.com/shuding/nextra/assets/38818142/a7dcb421-0d1b-4aa8-b942-f99919ab8dd2)

**Comment by Mangesh636** [comment]
look at [https://nextra.site/docs/docs-theme/theme-configuration#sidebar](https://nextra.site/docs/docs-theme/theme-configuration#sidebar)

**Comment by Yijia-Chen** [comment]
> look at https://nextra.site/docs/docs-theme/theme-configuration#sidebar

I mean the side bar on the left. All the `_meta.json` files are configured correctly and the localhost version is flawless. However, when it's pushed to GitHub and deployed by Vercel, the linking becomes incorrect. It's a really weird issue, and don't think the link you sent is helpful on this.

**Comment by Mangesh636** [comment]
If your repo is public drop the link of repo and deployment link of the website

**Comment by Yijia-Chen** [comment]
> If your repo is public drop the link of repo and deployment link of the website

Here you go:

- Repo: https://github.com/curio-research/duper-docs
- Deployment link: https://docs.duper.gg

**Comment by arno-fukuda** [comment]
<img width="472" alt="Screenshot 2024-04-29 at 9 53 33" src="https://github.com/shuding/nextra/assets/133849024/642ee6c5-453a-4ef6-9cde-7cd76672377a">

Does redeploying from within vercel without using existing build cache correct the behavior?

**Comment by Yijia-Chen** [comment]
> <img alt="Screenshot 2024-04-29 at 9 53 33" width="472" src="https://private-user-images.githubusercontent.com/133849024/326309848-642ee6c5-453a-4ef6-9cde-7cd76672377a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNTUyNjIsIm5iZiI6MTcxNDM1NDk2MiwicGF0aCI6Ii8xMzM4NDkwMjQvMzI2MzA5ODQ4LTY0MmVlNmM1LTQ1M2EtNGVmNi05Y2RlLTdjZDc2NjcyMzc3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQwMTQyNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNzM5YjVmY2U5ZDIzZDc3ODI3YWYwMzJmM2E5MzQ5MjI3Nzg4MmFhODg0ZmU3MDU1OTlkOTUzZGZmMTQxNGJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qKvlsfffWuNQIx3w1pft4I3I3OrAge8Sf7864UMFYCQ">
> Does redeploying from within vercel without using existing build cache correct the behavior?

Fixed! Thank you.
