### ISSUE TITLE
Navigation Buttons not highlighting on Hover | Darkmode

### ISSUE THREAD

**Issue by arno-fukuda** [shuding/nextra#2860]
<img width="1282" alt="Screenshot 2024-05-01 at 14 23 13" src="https://github.com/shuding/nextra/assets/133849024/3fabdc00-60bd-4166-bf87-7d58537e6e40">

On dark-mode, the navigation <a> elements don't change color upon hover due to the darkmode css having higher specificity:
```
:is(html[class~=dark] .dark\:nx-text-gray-300)
```

Can potentially workaround by using !important here:
```
.hover\:nx-text-primary-600:hover {
    --tw-text-opacity: 1;
    color: hsl(var(--nextra-primary-hue) var(--nextra-primary-saturation) 45% / var(--tw-text-opacity)) !important;
}
```

**Comment by jpcodes2022** [comment]
This workaround resolved the issue, thank you!
