### ISSUE TITLE
Steps Component | Text/Heading not aligned when using empty h3

### ISSUE THREAD

**Issue by arno-fukuda** [shuding/nextra#2862]
```
<Steps>

###

First, hello world

###

then, hello world

###

finally, hello world

</Steps>
```

<img width="451" alt="Screenshot 2024-05-02 at 13 26 23" src="https://github.com/shuding/nextra/assets/133849024/9337279b-ecbf-4c39-9c22-1cee6200711c">

Ideally, alignment should be consistent across all steps.

**Comment by dimaMachina** [comment]
Closing due to lack of interest in adding this feature
