### ISSUE TITLE
How to prevent documents from being searched？

### ISSUE THREAD

**Issue by yyrc** [shuding/nextra#2874]
How to prevent documents from being searched？~

**Comment by Fun117** [comment]
It's possible to prevent documents from being searched by removing the search box in the [navigation bar](https://nextra.site/docs/docs-theme/theme-configuration#navbar). Below is an example code for achieving this. In this code, we are passing an empty element to the [option to replace the search box](https://nextra.site/docs/docs-theme/theme-configuration#search) in `theme.config` from the [Docs Theme Configuration](https://nextra.site/docs/docs-theme/theme-configuration), effectively disabling the search functionality.

```tsx
import type { DocsThemeConfig } from "nextra-theme-docs";

const config: DocsThemeConfig = {
  search: {
    component: <></>,
  }
};

export default config;
```

I hope this helps! Let me know if you need any further assistance.

**Comment by yyrc** [comment]
Thank you, what should I do if I just want a document not to be searched?

**Comment by yyrc** [comment]
Specify a document.~
