### ISSUE TITLE
How to use PNG, IMG file as background image? and can I add some css to animate effect on page?

### ISSUE THREAD

**Issue by AppleBoiy** [shuding/nextra#2886]
Is there any way to use png as background? and is it possible to add some effect at background by using css

### This is my current page
![Screenshot 2567-05-13 at 17 16 36](https://github.com/shuding/nextra/assets/115919485/5eefa343-f22b-4dd3-8a11-1e60bb6a5069)

### This is my expectation 
![Screenshot 2567-05-13 at 17 16 36 png-1](https://github.com/shuding/nextra/assets/115919485/b43edae1-6494-42bc-9e8d-bd75bd459b3b)

from my expected image I have a background image (.PNG) and I want to add smoke effect by using css. is it possible?

**Comment by arno-fukuda** [comment]
You could wrap your mdx page in a Background component.

1) add png or svg to `/public/`

2) Create component
```javascript
// Background.js
import React, { useState, useEffect } from "react"
import { useTheme } from "nextra-theme-docs"

const Background = ({ children }) => {
  const { resolvedTheme } = useTheme()
  const [backgroundImage, setBackgroundImage] = useState("")

  useEffect(() => {
    setBackgroundImage(
      resolvedTheme === "dark"
        ? "background/background_dark.svg"
        : "background/background_light.svg",
    )
  }, [resolvedTheme])

  return (
    <>
      <div
        style={{
          position: "fixed",
          top: 0,
          left: 0,
          width: "100%",
          height: "100%",
          zIndex: -1,
          backgroundImage: `url('${backgroundImage}')`,
          backgroundSize: "cover",
          backgroundRepeat: "no-repeat",
          backgroundPosition: "center",
          filter: "blur(6px)",
        }}
      />
      {children}
    </>
  )
}

export default Background
```

3) Wrap your mdx page in it:

```javascript
// index.mdx
import Background from 'components/Background'

<Background>

# Documents
...

</Background>
```

For animation, you can use an APNG or an svg from [here](https://loading.io/background/) as an example.

**Comment by AppleBoiy** [comment]
Thanks a lot!
