### ISSUE TITLE
Problems with the `projectChatLink`

### ISSUE THREAD

**Issue by C-EO** [shuding/nextra#289]
I have updated my project's deps in the `package.json`, but when I retry the `projectChatLink` config in the `theme.config.js` it doesn't display on the vercel deployment.
Should I do anything else for it to work or?

**Comment by B2o5T** [comment]
Hi @C-EO , do you still have this problem?

**Comment by C-EO** [comment]
yes

**Comment by B2o5T** [comment]
Do you use v1 I think? Have you tried v2 beta?

**Comment by C-EO** [comment]
how do u access v2 beta
