### ISSUE TITLE
the way I make it is like this

### ISSUE THREAD

**Issue by Azda45** [shuding/nextra#2894]
the way I make it is like this
![Screenshot 2024-05-20 235846](https://github.com/shuding/nextra/assets/72027480/48b739e3-22a4-4b18-a96d-c4d76433a5bd)

**Comment by Benceszalaiii** [comment]
in the `_meta.json` file, include

```
"--":  {
"type": "separator",
"title": "Name displayed"
}
```

for additional customization, check out the [customization guide](https://nextra.site/docs/docs-theme/theme-configuration#customize-sidebar-content) provided by the official documentation
