### ISSUE TITLE
[BUG?] Every reload i get this error 

### ISSUE THREAD

**Issue by yan-pi** [shuding/nextra#2899]
![Captura de tela de 2024-05-22 19-13-18](https://github.com/shuding/nextra/assets/102800044/c7a62eca-ce41-4483-8576-a5d145078f5c)

**Comment by arno-fukuda** [comment]
This has not to do with nextra, but nextjs.

Are you mapping through items to create the list?

You can try using 'use client' / useEffect to make it a client component or try giving the `<li>`  tags distinct key values:
```
  <ul>
    {items.map((item, index) => (
      <li key={index}>{item}</li>
    ))}
  </ul>
```

**Comment by dimaMachina** [comment]
Please provide a reproduction
