### ISSUE TITLE
core branch: remark/rehypeKatex options not processed

### ISSUE THREAD

**Issue by robbear** [shuding/nextra#290]
This impacts the support of math output in markdown files.

`remarkMath`/`rehypeKatex` options specified by the app via `mdxOptions` are being ignored.

`packages/nextra/src/compile.js` might handle the app's `mdxOptions.rehypePlugins` specification this way:

```
export async function compileMdx(source, mdxOptions = {}, nextraOptions = {}) {
  return String(
    await compile(source, {
      jsx: true,
      providerImportSource: '@mdx-js/react',
      remarkPlugins: [
        ...(mdxOptions.remarkPlugins || []),
        remarkGfm,
        remarkMdxCodeMeta,
        nextraOptions.unstable_staticImage && remarkStaticImage
      ].filter(Boolean),
      rehypePlugins: [
        ...(mdxOptions.rehypePlugins || []),
      ].filter(Boolean)
    })
  )
}
```

Note that this solution makes the decision to expose the `rehypePlugins` option specifically, similar to `remarkPlugins`.

In `packages/nextra/src/loader.js`, `mdxOptions` appears to be handled incorrectly. Should it look like the following, instead?

```
const options = getOptions(this)
  const {
    theme,
    themeConfig,
    locales,
    mdxOptions,
    defaultLocale,
    unstable_stork,
    unstable_staticImage
  } = options
  const { resourcePath, resourceQuery/*, mdxOptions*/ } = this
```

**Comment by robbear** [comment]
@rbox-risk Here is what I'm doing that is successful against the current `core` branch.

In `next.config.js`
```
const remarkMath = require('remark-math');
const rehypeKatex = require('rehype-katex');

const withNextra = require('nextra')({
  theme: 'nextra-theme-docs',
  themeConfig: './theme.config.js',
  // ...
  mdxOptions: {
    remarkPlugins: [ remarkMath ],
    rehypePlugins: [ rehypeKatex ],
  },
});

module.exports = withNextra();
```

In the site's `package.json` dependencies:
```
    "rehype-katex": "5.0.0",
    "remark-math": "4.0.0",
```

**Comment by rbox-risk** [comment]
@robbear Ah perfect. Not using rehype-katex: 5.0.0 was the issue. Thanks
