### ISSUE TITLE
How to highlight a new item added in the right sidebar ?

### ISSUE THREAD

**Issue by alamenai** [shuding/nextra#2905]
Hi,

I have added a new item called `useAbortController` to my documentation, and I would highlight it by adding a colored text on the right ( Ex: New ).

How can I do that?

![image](https://github.com/shuding/nextra/assets/20143684/d9d3cc1e-315e-4a2e-8905-a983773b000f)

This my `_meta.json`:

```json

{
  "use-local-storage": "useLocalStorage",
  "use-abort-controller": "useAbortController"
}


```

**Comment by arno-fukuda** [comment]
Per [documentation](https://nextra.site/docs/docs-theme/theme-configuration#customize-sidebar-content), in your theme.config

```html
export default {
  sidebar: {
    titleComponent({ title, type }) {
     // your condition
      if (title=== 'useAbortController') {
        return (
          //  customize it here
          <div style={{ display: 'flex' }}>
              <div style={{ marginRight: '5px' }}>{title}</div>
              <div style={{ backgroundColor: 'yellow' }}>(New)</div>
          </div>
        )
      }
     return <>{title}</>
    }
  }
}
```

**Comment by alamenai** [comment]
Thank you @arno-fukuda , I'll try it this evening.

**Comment by alamenai** [comment]
Hi @arno-fukuda , yes it works as expected, thank you.

![image](https://github.com/shuding/nextra/assets/20143684/7054100f-61eb-4f78-a508-cd8e7135ae29)

**Comment by alamenai** [comment]
Hi @arno-fukuda , I reopened the issue because I could not find a way to change the `width` of the siebar. See the sidebar item behavior below:

[d6beb1a7-dd42-45f9-97b9-696fd04feb31.webm](https://github.com/shuding/nextra/assets/20143684/c914141c-5a44-40f1-adde-97982b9d53ee)

**Comment by alamenai** [comment]
Thank you @arno-fukuda , I solved the issue:

```tsx

  titleComponent({ title, type }) {
      return (
        <div className="flex items-center justify-between relative w-full">
          <div >{title}</div>
          {title === "useAbortController" && (
            <Badge className=" absolute -right-[0.5em] bg-transparent border-lime-500 text-lime-500 px-[0.5em]">
              New
            </Badge>
          )}
        </div>
      );
    },
```

![image](https://github.com/shuding/nextra/assets/20143684/c5c9b9b5-6d9e-4d01-9fc0-3653672d1c37)

**Comment by arno-fukuda** [comment]
looking great!
