### ISSUE TITLE
[v3] applying `display: "hidden"` breaks _meta in the subdir

### ISSUE THREAD

**Issue by hezean** [shuding/nextra#2909]
When using nextra and the docs theme of version `3.0.0-alpha.24`, setting the display mode of a subdir to "hidden" seems to make the _meta file in that folder not work.

Say I set all pages in the `sample` dir to be with the article typesetting, as shown like:

<img width="312" alt="Screenshot 2024-05-30 at 02 03 48" src="https://github.com/shuding/nextra/assets/49837965/ecca27d3-4d1f-483e-9db8-d23992663db5">

After setting the _meta file of its parent dir to:

```typescript
export default {
  sample: {
    display: "hidden",
  }
}
```

the page comes like:

<img width="312" alt="Screenshot 2024-05-30 at 02 04 09" src="https://github.com/shuding/nextra/assets/49837965/02947ba7-8c3a-4714-b0bc-355a8a0de1ac">

Here's the code for a minimal reproducible example: [nextra3-meta-not-applied.zip](https://github.com/shuding/nextra/files/15489277/nextra3-meta-not-applied.zip)

**Comment by marcklingen** [comment]
Same applies to us. This route is hidden but linked to via our customer switcher on top of the sidebar. The sidebar is not rendered at all as the parent meta hides this page.

https://langfuse.com/guides

**Comment by dimaMachina** [comment]
this was fixed by https://github.com/shuding/nextra/issues/3331 in stable v3
