### ISSUE TITLE
Tabs are not shown in Sidebar even after mentioning in `_meta.json`

### ISSUE THREAD

**Issue by TheNoumanDev** [shuding/nextra#2914]
Hey Like when i am trying to access the website from the starting point, like main page, it doesn't load that "Firebase" tab or its child as you can see other is not Firebase tab in sidebar.

![image](https://github.com/shuding/nextra/assets/76642732/2392ecd5-aa33-4bb9-a9b3-c1fbff6d5c95)

But as you can see in belive image, when I search it or just go straight from URL, it appears, idk wot is that issue can u give some guidance on it.

![image](https://github.com/shuding/nextra/assets/76642732/d5b843d8-9292-4e66-aabf-816ef559efdd)

And below is the _meta.json where you can see everything else is also mentioned and other stuff is being shown but firebase is being skipped but when we access it like I show in above picture, it appears in the same spot I declared it. idk is it cache issue or something else.

![image](https://github.com/shuding/nextra/assets/76642732/bcc92a18-d954-4667-9b85-bf2421eca81f)

**Comment by arno-fukuda** [comment]
It's most likely a cache issue.

If you have sidebar or _meta.json changes, try to redeploy your latest build on Vercel.

https://vercel.com/docs/deployments/managing-deployments#redeploy-a-project

Make sure to leave `Redeploy with existing Build Cache` unchecked.

**Comment by dimaMachina** [comment]
Should be fixed in Nextra 3, lmk if you have still issue with cache
