### ISSUE TITLE
Recma plugins order

### ISSUE THREAD

**Issue by pomber** [shuding/nextra#2915]
#2866 added support for recma plugins, but they are being applied after nextra custom plugins: https://github.com/shuding/nextra/pull/2866/files#diff-529083ef03cb653fd91399220a1a136114d36a4b6fed51cef498562c26a1ac7fR349

User's remark and rehype plugins are applied before any nextra plugin, maybe it will be more consistent if the same applies to recma.

(not a nitpick, this is breaking the [integration with Code Hike](https://github.com/code-hike/examples/pull/6#issuecomment-2135140882))

**Comment by pomber** [comment]
I can send a PR if needed

**Comment by dimaMachina** [comment]
hey, do you still need this feature?

**Comment by pomber** [comment]
Yes!

(In the meanwhile, I've been using [patch-package](https://github.com/code-hike/examples/pull/6/commits/dc5438d122d3cd08ad481af5405cdc2a686c5d0a) to change the order so it works with codehike, but it's far from ideal)

**Comment by dimaMachina** [comment]
feel free to send PR!
