### ISSUE TITLE
Feedback for “Page Configuration”

### ISSUE THREAD

**Issue by jpcodes2022** [shuding/nextra#2916]
Beautiful docs theme! The only question I have so far is why, in Dark mode, do the previous and next page links not change to the primary color on hover as in Light mode. Was this intentional?

< Get Started
Theme Configuration>

**Comment by jpcodes2022** [comment]
I think you're correct. This workaround did the trick, thank you!

**Comment by arno-fukuda** [comment]
feel free to close
