### ISSUE TITLE
v3 back-to-top button does not scroll all the way to top

### ISSUE THREAD

**Issue by ZYJLiu** [shuding/nextra#2917]
Clicking "scroll to top" will scroll up until the button toggles to hidden, which causes scrolling to stop. 
Solution may be to keep "scroll to top" button visible until scrolling is complete.

For example, you can test on the graphql docs pages: https://graphql.org/learn/queries/

![CleanShot 2024-06-05 at 21 43 41](https://github.com/shuding/nextra/assets/75003086/49f77d2b-8142-406b-abf5-ec464ad9f39f)

**Comment by dimaMachina** [comment]
upstream https://github.com/facebook/react/issues/20770
