### ISSUE TITLE
.mdx works fine, but .md breaks the layout.

### ISSUE THREAD

**Issue by softmarshmallow** [shuding/nextra#292]
<img width="303" alt="Screen Shot 2021-12-17 at 9 38 39 PM" src="https://user-images.githubusercontent.com/16307013/146545850-0faf04b2-d7fd-4c7d-a222-5b848f19559a.png">

This is mdx document
<img width="903" alt="Screen Shot 2021-12-17 at 9 39 01 PM" src="https://user-images.githubusercontent.com/16307013/146545916-e23986d0-2b91-4004-8693-71c2186cbbf9.png">

This is md document
<img width="1221" alt="Screen Shot 2021-12-17 at 9 39 14 PM" src="https://user-images.githubusercontent.com/16307013/146545905-8eeeab8d-0fe3-43a7-a9fc-0bdc44c1aa8e.png">

Repo: https://github.com/gridaco/grida.co - (Now using docusaurus)

**Comment by loonfly** [comment]
same. found any workaround? or am I missing any important settings?

**Comment by ddiu8081** [comment]
solved after upgrading to version 2.0.0

**Comment by B2o5T** [comment]
Closing since related to v1
