### ISSUE TITLE
changing the name of files or updating order of files in _meta.json is not reflected in production build

### ISSUE THREAD

**Issue by lililud** [shuding/nextra#2928]
- when changing the ordering of files with the _meta.json or changing the name of a file (and route), this all works fine locally. However doing a build and start does not show the change and/or inconsistently shows the right ordering.
- Deleting .next folder locally fixes this 
- on a deploy preview, redeploying fixes this

**Comment by dimaMachina** [comment]
This should be fixed in Nextra 3, feel free to reply if you still have an issue
