### ISSUE TITLE
Feedback for “Importing Video / Audio into TimeBolt”

### ISSUE THREAD

**Issue by renaudderepentigny** [shuding/nextra#2931]
Hello,

I have paid for your lifetime version. I am using it with a 2020 Mac M1 running Big Sur. I am trying to import an MXF video file from a Canon C300 Mark II, but nothing happens. According to all the tutorial videos, the conversion is supposed to start automatically upon importing the file into your software. Can you help me quickly, please? Otherwise, I will have to use another software.

Thank you.

**Comment by RonaldTorrez** [comment]
@renaudderepentigny Are you talking about Nextra?
