### ISSUE TITLE
How to change the color of banner component

### ISSUE THREAD

**Issue by alamenai** [shuding/nextra#2933]
Hi guys,

I have create a custom configuration for the Banner component like this :

```ts
 banner: {
    key: "2.0-release",
    text: (
      <a href="https://github.com/alamenai/rehook" target="_blank">
        Rehook 1.0.0 beta is out changes 
      </a>
    ),
  },
```

It looks like this :
  
![image](https://github.com/shuding/nextra/assets/20143684/6e271be8-6dc2-4c45-b24d-84f5d599b2dc)

However, I would change the background color but I did not how to do it in the documentation.

Thank you.

**Comment by annalhq** [comment]
I think you should fork and create your own theme:
https://github.com/shuding/nextra/tree/main/packages

Styles overwrites get quite tricky as some components so it's better you do all these customization in your custom theme.

**Comment by alamenai** [comment]
I made it like this:

```ts


  banner: {
    key: "2.0-release",
    dismissible: false,
    text: (
      <div className="bg-rose-600 absolute right-0 left-0 top-0 bottom-0 flex justify-center items-center">
        <a href="https://github.com/alamenai/rehook" target="_blank">
          <span className="mr-4">🎉</span> Rehook 1.0.0 beta is out with 16
          custom hooks. Read more
        </a>
        <ChevronRight className="ml-4" />
      </div>
    ),
  },
```

Output:

![image](https://github.com/shuding/nextra/assets/20143684/10908c1e-d72d-4389-936f-0d3744bd4ab8)
