### ISSUE TITLE
How to switch the theme from the header?

### ISSUE THREAD

**Issue by alamenai** [shuding/nextra#2934]
Hi,

I would ask if there is  way to add the theme component in the header to allow the users change the mode from the header instead of the footer.

Something like this:

![image](https://github.com/shuding/nextra/assets/20143684/15239157-98ed-4b9d-bbd5-0dcb356c027d)

**Comment by annalhq** [comment]
@alamenai 
You can achieve this by adding this to your _theme.config.jsx_ configguration.
```
import { ThemeSwitch, LocaleSwitch } from "nextra-theme-docs";
navbar: {
      extraContent: (
        <>
          <LocaleSwitch />
          <ThemeSwitch />
        </>
      ),
    },
```
