### ISSUE TITLE
[v3] Not working sidebar and toc

### ISSUE THREAD

**Issue by Gellipapa** [shuding/nextra#2935]
Hi! I am trying to use nextra docs v3.

```js

//theme.config.tsx

  sidebar: {
    autoCollapse: true,
    defaultMenuCollapseLevel: 1,
    toggleButton: true
  },
  toc: {
    backToTop: true,
    float: true
  }

```

I have entered the new settings and for some reason neither the sidebar nor the toc appear.

What I also noticed is that in mobile view the toggle appears and the "menu" comes up but on the main page itself, not in mobile view, none of the sidebars appear.

```js
  //_meta.ts
  
  export default {
  test: 'Test',
  'test-2': {
    type: 'page'
  }
}
```
I use plain _meta.ts, which you can see how it is built above.

What I also noticed is that I get two types of error. I don't know how much this affects it, because maybe it has to do with the hot reload and the build will eliminate these errors, but maybe I'm wrong.

![image](https://github.com/shuding/nextra/assets/22717950/5ad89aa9-cc76-4450-a279-6aac5709383b)

![image](https://github.com/shuding/nextra/assets/22717950/3d5ee69a-f511-4d1c-ba7e-4468db78290c)

Could you please help me with this and tell me what the problem might be?

Thank you in advance for your answers.

**Comment by amcdnl** [comment]
I think this is related to my issue as well - https://github.com/shuding/nextra/issues/2920

**Comment by Gellipapa** [comment]
@amcdnl Hi! Thanks for your answer. 

It's quite strange because in mobile view when I open the page there is sidebar, but there are some pages where I click and the sidebar doesn't appear and the main page itself doesn't have the sidebar. 

I have tried the ones described in the issue, but I could not solve the problem. 

I also turned off javascript in devtools and the HTML content that renders the sidebar doesn't appear anyway. 

My guess is that I have 6 hydration errors and that's why it doesn't appear.

Do you think this could be a problem?

Thanks for answers. 

Bye,

Gellipapa

**Comment by Gellipapa** [comment]
Hi! I was able to solve the problem, the problem was that in _meta.ts type: 'page' was set so the sidebar and the toc don't appear, if it's not there it works fine.

```js

//_meta.ts
export default {
  index: {
    title: 'Introduction',
    type: 'page' //you should remove this line if you want show sidebar and toc
  },
  test: {
    title: 'Test',
  },
```
