### ISSUE TITLE
[v3] Details now requires a specific div for the content

### ISSUE THREAD

**Issue by chriswiggins** [shuding/nextra#2941]
We have run into a bug in the v3 alpha which now doesn't render details correctly if the content isn't in a div.

Previously we could do the following:

```mdx
<details>
    <summary>Title</summary>
    content line 1
    some more content
</details>
```

Whereas now we have to do this:
```mdx
<details>
    <summary>Title</summary>
    <div>
      content line 1
      some more content
    </div>
</details>
```

Not sure if this is desired behaviour or not, but I did note in #2307 this changed the way details were rendered, so this I would say is a regression.

**Comment by dimaMachina** [comment]
thank you for your report, this was not desired, this is a regression from v2 when I refactored details/summary to avoid using context and providers, will be fixed in next alpha
