### ISSUE TITLE
ERROR WHEN DEPLOY

### ISSUE THREAD

**Issue by Finsiii** [shuding/nextra#2944]
Error: No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings.

When i deploy it to vercel, Error: No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings.

How to fix this error?

**Comment by EstebanDalelR** [comment]
Build locally, check if it happened to be "dist" and change the settings.

**Comment by dimaMachina** [comment]
closing due lack of activity, feel free to reply if you still need help
