### ISSUE TITLE
Feedback for “Cypress to Playwright”

### ISSUE THREAD

**Issue by pavelfeldman** [shuding/nextra#2947]
You should delete the link to https://ray.run/tools/cypress-to-playwright - it is a copy of https://github.com/playwright-community/cy2pw (https://demo.playwright.dev/cy2pw/) w/o attribution. That's typical for the user: https://www.reddit.com/r/programming/comments/17w3toy/comment/k9etf1x/?utm_source=reddit&utm_medium=web2x&context=3. I'm bringing it up because your page shows up relatively high on "cypress to playwright" search.

**Comment by dimaMachina** [comment]
your issue is created in wrong repo
