### ISSUE TITLE
Mobile - INP score on hamburger menu

### ISSUE THREAD

**Issue by arno-fukuda** [shuding/nextra#2952]
Earlier this year, Google introduced a new Core Web Vital, [INP](https://developers.google.com/search/blog/2023/05/introducing-inp#:~:text=Update%20on%20January%2031%2C%202024,Vitals%20on%20March%2012%2C%202024.)

The hamburger menu has a long transition time, which could be shortened to get an overall better score.

<img width="1278" alt="INP" src="https://github.com/shuding/nextra/assets/133849024/a296701b-d4cf-4615-9aed-805350bd17b5">

**Comment by dimaMachina** [comment]
Are you still interested in this fix? Would you want to send a pr?

**Comment by dimaMachina** [comment]
fixed, translate3d will be removed in v4 https://github.com/shuding/nextra/issues/3659
