### ISSUE TITLE
i18n help

### ISSUE THREAD

**Issue by kilianbalaguer** [shuding/nextra#2962]
Hey im using Nextra 2 docs but when i use i18n i delete the index and make a index.en-US.mdx and the meta json of it but it says 404 page not found and i dont know how to use i18n in nextra.

**Comment by LuchoTurtle** [comment]
I'm having the same issue. 

I've made all the modifications according to the [`Nextra`'s documentation](https://nextra.site/docs/guide/i18n).

```js
// next.config.js
const withNextra = require("nextra")({
  theme: "./theme/src/index.tsx",
  themeConfig: "./theme.config.tsx",
  defaultShowCopyCode: true
});

module.exports = withNextra({
  i18n: {
    locales: ['en-US', 'ar-SA'],
    defaultLocale: 'en-US'
  }
});
```

```ts
// middleware.ts

"server only";

import { auth } from "@/src/auth";
import { NextResponse } from "next/server";
import { withLocales } from 'nextra/locales'

export default withLocales(auth(async (req, ctx) => {
  return NextResponse.next()
}));

export const config = {
  matcher: [
    '/((?!api|_next/static|_next/image|favicon.ico).*)',
  ],
}
```

```tsx
// theme.config.tsx
import { DocsThemeConfig } from "nextra-theme-docs";

const config: DocsThemeConfig = {
    logo: <span>My Nextra Documentation</span>,
    project: {
      link: 'https://github.com/shuding/nextra'
    },
    i18n: [
      { locale: 'en-US', text: 'English' },
      { locale: 'ar-SA', text: 'العربية', direction: 'rtl' }
    ]
  }

  export default config
```

And my page returns `404` on `localhost:3000`.

![image](https://github.com/shuding/nextra/assets/17494745/23b5d9a3-4cae-4ce1-8663-07a1e6b16f9b)

This wasn't the case before (`index.mdx` was rendered properly).
Here's how my file structure looks like now:

![image](https://github.com/shuding/nextra/assets/17494745/71c22094-6ee5-47b9-a631-21af6170aa71)

Weird stuff 🤔 . Any insights?

**Comment by kilianbalaguer** [comment]
Yeah bc for me it does work if i do localhost:3000/filename exaple
```
localhost:3000/index.en-US.mdx
```
but for the rest i dont know what to do.

**Comment by kilianbalaguer** [comment]
and when i use middleware.ts it gives me the error ERR_TOO_MANY_REDIRECTS but when i delete it it stops giving me the error

**Comment by arno-fukuda** [comment]
try this matcher:

```
export const config = {
  matcher: [
    '/',
    '/((?!api|_next/static|_next/image|favicon.ico).*)',
  ],
}
```

**Comment by LuchoTurtle** [comment]
@arno-fukuda thank you! That fixed it! :)

**Comment by arno-fukuda** [comment]
Does it also reproduce if you remove the matcher completely?

**Comment by LuchoTurtle** [comment]
If I remove the matcher completely, the `middleware.ts` executes normally and the `i18n` seems to work as intended. 

Which is weird, I thought the `withLocales` hook would be able to help in these cases? 🤔

**Comment by kilianbalaguer** [comment]
> If I remove the matcher completely, the `middleware.ts` executes normally and the `i18n` seems to work as intended.
> 
> Which is weird, what's the point of `withLocales` hook, then? 🤔

So how is your code now?

**Comment by LuchoTurtle** [comment]
@kilianbalaguer you just remove the `matcher` you exported inside your `middleware.ts `file.

```ts
// middleware.ts

"server only";

import { auth } from "@/src/auth";
import { NextResponse } from "next/server";
import { withLocales } from 'nextra/locales'

export default withLocales(auth(async (req, ctx) => {
  return NextResponse.next()
}));

export const config = {} // don't match anything
```

**Comment by kilianbalaguer** [comment]
and your next config?

**Comment by kilianbalaguer** [comment]
@LuchoTurtle and what is your next config code and how is your pages look like for the i18n

**Comment by LuchoTurtle** [comment]
My `next.config.js` code is written above in my original reply. The pages are the same as following the guide (meaning you've `_meta.en-US.json and index.en-US.mdx` files and such).

**Comment by kilianbalaguer** [comment]
bc me it does not work when i do url/en i need to specifie my file

**Comment by kilianbalaguer** [comment]
but can you delete the index file bc if i do that its not found

**Comment by kilianbalaguer** [comment]
btw do you have the repo of you?

**Comment by LuchoTurtle** [comment]
I don't have a repo, it's stashed. If anything, you should share yours so people can help you :)

**Comment by kilianbalaguer** [comment]
@LuchoTurtle  
https://github.com/WinUI-Blog/site
what do i need to do to use i18n?

**Comment by kilianbalaguer** [comment]
Nvm i used the swr docs that uses nextra 3 ig and now it works here check it out 
```
https://winuiblog.vercel.app/
```
```
https://github.com/WinUI-Blog/site
```
