### ISSUE TITLE
WordPress style site 

### ISSUE THREAD

**Issue by The-Code-Monkey** [shuding/nextra#304]
Hey guys,

Loving the project so far, really useful.

So the thing I'm looking to achieve is by having the markdown be built by the end user on a backend CMS using a markdown editor, for them to be able to add blocks similar to how wordpress does it, but what will happen is a list of markdown syntaxes will be created instead.

E.g. 

```
--- 
block_type: image
alt: "an image"
url: "image url"
---

---
block_type: text
align: right
---

This is normal content like how the app currently works
```

Is there plans to support this. Or is there a quick way that I could get this supported via pointing me to the correct part of the code where the changes would be needed. I'm guessing a new component or something would be needed.

The blocks could come down as an array of objects too and converted to the correct format on the server side render. Which can then be parsed using the same parser currently used.

This would be a great help if you reply. If I can work it out I will put up a pr for a new package along with an example. Hopefully the day after I get a reply I can get something sort of working in an example.

Project starred 👍

**Comment by shuding** [comment]
Thanks for the feature request! I don't think this is something we have bandwidth or plan to support in the near future, so I'm going to close this. We've been working hard to make Nextra feature complete first in the past year.
