### ISSUE TITLE
Integrate Plausible Analytics with nextra

### ISSUE THREAD

**Issue by shankiflang** [shuding/nextra#3047]
### Discussed in https://github.com/shuding/nextra/discussions/2938

<div type='discussions-op-text'>

<sup>Originally posted by **shankiflang** June 18, 2024</sup>
Hi guys,

I'm using Plausible (https://plausible.io/) as my main analytics manager and I wanted to know how can I add my nextra doc in it ?

Thanks for the help</div>

**Comment by shankiflang** [comment]
I'll take the liberty of asking you again! Does anyone have any idea how I can do this?

**Comment by dimaMachina** [comment]
closing since what works with Next.js - works with Nextra, so just follow Next.js examples for Pages router for your analytics
