### ISSUE TITLE
Integer rounding behaves strange

### ISSUE THREAD

**Issue by sfrezza** [shuding/nextra#3055]
I had to do odd work-arounds to get integer division to behave normally. See the following code snippet:

When $totalValue is 1, these two formulations do not compute the same result (I think they should both be zero)

\<number name=$totalValue> 1 \</number>
\<integer name="quo0"> ($totalValue)/2 \</integer>
vs.
\<integer name="quo1"> ($totalValue-0.1)/2 \</integer>

In the first case, $quo0 is set to 1; in the second $quo1 is set to 0. Shouldn't they both compute zero?

In normal rounding or truncation, if the dividend from 1/2 = 0.50 or less, then the integer conversion of this result should be zero.  Why in the first case is it 1?

**Comment by dimaMachina** [comment]
unrelated issue to nextra

**Comment by sfrezza** [comment]
'Sorry.  'Thought I was in the https://github.com/Doenet
/
[DoenetML](https://github.com/Doenet/DoenetML) repo.
