### ISSUE TITLE
Disable sidebar open / close toggle

### ISSUE THREAD

**Issue by lukecd** [shuding/nextra#3059]
Is there any way to hide the open / close toggle on the sidebar and just leave everything open? I have a pretty minimal sidebar and would just rather leave them all open all the time. 

Thanks

**Comment by lukecd** [comment]
Thanks for the reply. That helps me set all menus to open, but what I want to do is remove the option to collapse all together. Remove this little arrow that I'm highlighting in the screenshot.

Thanks

<img width="224" alt="Screenshot 2024-07-29 at 12 25 30" src="https://github.com/user-attachments/assets/522f86b5-0c18-4e5b-ae8a-12d1cbe9c805">

**Comment by dimaMachina** [comment]
I'm not sure if I want to add this feature because I never saw this in some docs framework, did you see already something similar?

**Comment by lukecd** [comment]
No, never seen it anywhere else. We just have a very small nav section now, so thought I'd force them all open. I got it working with custom CSS though.  Thanks!

**Comment by dimaMachina** [comment]
closing due lack of interest of this feature
