### ISSUE TITLE
Feedback for “Working with the Timeline”

### ISSUE THREAD

**Issue by KathleenSpracklen** [shuding/nextra#3072]
I purchased TimeBolt yesterday, so I'm a brand-new user. 

The starter video: Quickly Edit Long Video Timelines with Shortcuts in TimeBolt
mentions using Command-B to split the timeline. (I tried Ctrl-B and it appeared to do just that.)

In the ap, the keyboard shortcut button shows "S" to split the timeline. (That appears to work, too.)

Question: is there any difference between Ctrl-B and "S"?

**Comment by arno-fukuda** [comment]
@KathleenSpracklen , the `Question? Give us feedback →` link from their documentation uses a placeholder to their documentations Framework, which is Nextra.

It has nothing to do with their product.

You probably want to reach out here:
https://help.timebolt.io/submit-ticket

**Comment by KathleenSpracklen** [comment]
Thank you!
