### ISSUE TITLE
[nextra] Init git repository failed. deploy in docker container, build image error.

### ISSUE THREAD

**Issue by aurora-lch** [shuding/nextra#3086]
Build docker image, with error

<img width="1220" alt="image" src="https://github.com/user-attachments/assets/42c0ad48-eaa0-42de-b693-61c7b4275144">

dockerfile

`FROM node:alpine

RUN mkdir -p /docs
WORKDIR /docs

COPY . .

RUN npm i
RUN npx next telemetry disable
RUN npm run build

CMD npm run start

EXPOSE 3000`

**Comment by aurora-lch** [comment]
I can only build local

**Comment by vickydk** [comment]
@aurora-lch what is the solution for this issue? I faced the same issue

**Comment by aurora-lch** [comment]
> @aurora-lch what is the solution for this issue? I faced the same issue

Recommend you to use nextjs examples with docker's dockerfile
[https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile](https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile)
I remember that's how I solved the problem
