### ISSUE TITLE
Support a callback function to capture search results.

### ISSUE THREAD

**Issue by Mike-Logit** [shuding/nextra#3103]
I can't find a way to add a callback function that gets called with the search results (from flexsearch) so that I can add some analytics/logs etc... about what the user searched for.

I checked the code but the theme config options are very limited, and the search function isn't accessible or open to extension.

I don't think it's supported but it would be great to have if possible. I don't think it would be too difficult to add.

**Comment by dimaMachina** [comment]
Hi, do you still need it? Is there an alternative in other search engine like algolia, or am a with these callbacks functions?

**Comment by dimaMachina** [comment]
closing due no reply
