### ISSUE TITLE
[Blog Feature Request] Is it Possible adding some scripts to generate markdown files?

### ISSUE THREAD

**Issue by yuetong3yu** [shuding/nextra#311]
Greeting!✋🏼

I was wondering if we could add some simple scripts that could generating `title`, `author`, `date` even `h1` tag...

Create file manually each time is troubling.

**Comment by shuding** [comment]
Hey! I think you can manually create a script file and execute it before building the Next.js project. Here's a similar example (how I generate these RSS feeds): https://github.com/shuding/site/blob/master/package.json#L9
