### ISSUE TITLE
`pageMap` is undefined after refreshing the page (only with `_app.mdx`)

### ISSUE THREAD

**Issue by hubertbodek** [shuding/nextra#3118]
Hey, recently I encountered Out Of Memory issues while building the project - what has helped was changing `_app.tsx` to `_app.mdx`.

But that introduced another issue - `pageMap` is undefined after refreshing the page which wasn't happening with `_app.tsx`. (NOTE: with client-side navigation the `pageMap` has correct value)

![image](https://github.com/user-attachments/assets/7a15e0c3-d628-4cad-bbac-e6c1f5e72bc3)

I noticed whenever I use imported components in the theme config the above error occurs.

![image](https://github.com/user-attachments/assets/dcaafb31-76b0-4a5b-a2dc-9fcc98334cfd)
![image](https://github.com/user-attachments/assets/4e7c0a55-1817-4847-8d71-c157301f3172)

Here is a sample repo so you can reproduce the bug: https://github.com/hubertbodek/nextra-sample-repo

**Comment by ndimares** [comment]
@dimaMachina hey Dimitri, I sent you a slack message. But I doubt that you're in the habit of checking our connect channel :) Just wanted to let you know that this issue is related to https://www.speakeasy.com/

We're stuck on site development at the moment, and would love love your help!

**Comment by dimaMachina** [comment]
Closed since I received feedback that you fixed your issue
