### ISSUE TITLE
Broken demo image (Documentation>Docs Theme>Built-ins>Bleed)

### ISSUE THREAD

**Issue by benceruleanlu** [shuding/nextra#3124]
Currently showing a missing image with the caption "Landscape" at [https://nextra.site/docs/docs-theme/built-ins/bleed](https://nextra.site/docs/docs-theme/built-ins/bleed).

Link specified is [https://source.unsplash.com/eaxwP9J_V6s/1600x398](https://source.unsplash.com/eaxwP9J_V6s/1600x398).

Using [source.unsplash.com](source.unsplash.com) has been deprecated in favor for their API.

[GitHub File](https://github.com/shuding/nextra/blob/main/docs/pages/docs/docs-theme/built-ins/bleed.mdx?plain=1)

**Comment by dimaMachina** [comment]
Thank you, would you want to submit a PR?

**Comment by benceruleanlu** [comment]
> Thank you, would you want to submit a PR?

I would if I could!

Still new to everything, so I struggle even following the development setup instructions.

But I wouldn't have the artistic taste to find a suitable image anyway.
