### ISSUE TITLE
Using Shiki transformers with Nextra

### ISSUE THREAD

**Issue by arvinpoddar** [shuding/nextra#3138]
Hey all, I'm curious if it's possible to use Shiki transformers with Nextra. I'm attempting to use the `transformerNotationDiff` for my code blocks on my Nextra site. See https://shiki.matsu.io/packages/transformers#transformernotationdiff. 

From https://rehype-pretty.pages.dev/, it appears that we should be able to pass a `transformers` option to `rehypePrettyCodeOptions` in the `next.config.js` file:

```ts
const withNextra = require('nextra')({
  theme: "nextra-theme-docs",
  mdxOptions: {
    rehypePrettyCodeOptions: {
      theme: "one-dark-pro",
      transformers: [transformerNotationDiff()]

    },
  },

});

module.exports = withNextra()
```

The site is able to build and run with this config. However, this has no effect on the code blocks using the transformer notation. Are transformers currently supported?

**Comment by 87xie** [comment]
Shiki transformers require rehype-pretty-code version 0.12 or higher. Nextra v2 doesn't support it, but v3 alpha does.

**Comment by arvinpoddar** [comment]
> Shiki transformers require `rehype-pretty-code` version 0.12 or higher. Nextra v2 doesn't support it, but v3 alpha does.

This worked perfectly, I had to update my `nextra` and `nextra-theme-docs`dependencies. For anyone in the future, here's what I used: https://the-guild.dev/blog/nextra-3

After that, just had to add a CSS rule targeting the diff line classes added by Shiki!
