### ISSUE TITLE
Feedback for “Presentations”

### ISSUE THREAD

**Issue by himanshu-videoremix** [shuding/nextra#3153]
when i call at on presentationgpt. I am getting error "Something went wrong". How can i resolve that error

**Comment by himanshu-videoremix** [comment]
![Screenshot from 2024-08-29 18-27-02](https://github.com/user-attachments/assets/5426eb5f-dca4-4148-81c3-a4833b499935)

**Comment by dimaMachina** [comment]
https://github.com/shuding/nextra/issues/3072#issuecomment-2254345423

**Comment by deangilmoreremix** [comment]
You closed this issue without commenting or giving a solution and instead added a comment from someone else's question and not ours

**Comment by deangilmoreremix** [comment]
@dimaMachina could you please answer our request of why we are getting the following error 

getting error "something went wrong"
![image (12)](https://github.com/user-attachments/assets/adb2ebb7-24cc-4168-a102-0b7afec5c2c4)

**Comment by dimaMachina** [comment]
Your issue is unrelated to Nextra library, in attached comment there is explanation why

**Comment by deangilmoreremix** [comment]
this is the help that we see for presentationsgpt? is this the wrong channel

**Comment by dimaMachina** [comment]
This is wrong channel

**Comment by deangilmoreremix** [comment]
what is the right channel because this is the channel they give on their website

**Comment by dimaMachina** [comment]
I don’t know and can’t help you

**Comment by deangilmoreremix** [comment]
maybe you should tell presentationsgpt to not have this link for support on their site. it would help all of us

**Comment by dimaMachina** [comment]
You can tell them
