### ISSUE TITLE
Chinese title anchor support ?

### ISSUE THREAD

**Issue by JesseEisen** [shuding/nextra#32]
**Actually, this is slugify not support chinese.** 

Hi shu.
Is there any good choice that can elegant support chinese anchor?

--- 
Can add a check before use slugify to generate a slug? 

-  If this is a chinese title, just use it as raw. otherwise use slugify.  Also use a random hexstring instead of it.

Hope you can reply. ^_^

**Comment by shuding** [comment]
Yeah thanks for reporting! I'll add the support for this soon.

**Comment by shuding** [comment]
Please upgrade the `nextra-theme-docs` package and this is now supported!
