### ISSUE TITLE
Support `_.json` as an alias of `meta.json`

### ISSUE THREAD

**Issue by shuding** [shuding/nextra#320]
When a directory grows, `meta.json` might get lost in the giant list of document pages... but `meta.json` has a special meaning and functionality in a Nextra project, it would be nice to simplify the name, and always make it the first file in the list. This change will improve the experience tremendously.

It might be not performant to read both meta files. So if possible, we can also deprecate the `meta.json` support.

**Comment by alii** [comment]
Perhaps `_meta.json` would be more apt being more descriptive of what we're looking at. Similar to `_app` & `_document` etc

**Comment by B2o5T** [comment]
@shuding it can be done easily with new theme option - `unstable_underscoreMeta` 😅

**Comment by AmiteyeEmmanuel** [comment]
How can I add an icon to my _meta.json Nextra document page, like for example, 

{
  “Index” : { 
     “title” : “Introduction” 
     “Icon”: “fa fas Introduction” // Not recognized by Nextra
} 

please help out.
