### ISSUE TITLE
[v3] Navbar dropdown not working in 3.0.0-alpha.36

### ISSUE THREAD

**Issue by hariria** [shuding/nextra#3215]
## Description

Just an fyi, I'm noticing that the navbar dropdowns are not working in the latest alpha release. Also search is not working properly anymore after bumping from `3.0.0-alpha.24` to `3.0.0-alpha.36`. 

Note: It does work on `3.0.0-alpha.35`. I believe the error is likely due to the Headless UI upgrade to 2.0

## Error

Pasted the error I'm noticing in the console from alpha.36

```
[Deprecation] Custom state pseudo classes have been changed from ":--scroll-timeline" to ":state(scroll-timeline)". See more here: https://github.com/w3c/csswg-drafts/issues/4805
```

## Context

Using

```
    "nextra": "3.0.0-alpha.36",
    "nextra-theme-docs": "3.0.0-alpha.36",
```

**Comment by dimaMachina** [comment]
Please share your code or reproduction repo

**Comment by hariria** [comment]
Sorry @dimaMachina I posted a bad PR and preview link. Just edited the above, should be good now.

**Comment by dimaMachina** [comment]
I have locally working menu and search 
<img width="1651" alt="image" src="https://github.com/user-attachments/assets/ea3df764-7f24-4b6c-a4d7-d43e8311c2ac">


maybe you need to remove

```
  "dependenciesMeta": {
    "nextra": {
      "injected": true
    },
    "nextra-theme-docs": {
      "injected": true
    }
  },
```

it's needed only for our examples

**Comment by hariria** [comment]
@dimaMachina yes I observed that too, but if you run `pnpm build && pnpm start`, the behavior is different than `pnpm dev` for some reason. 

I noticed that when I click on the `build` section, the div with `id="headlessui-portal-root"` appears, but shows nothing.

Tested on Chrome 128 Incognito. Safari has same behavior.

https://github.com/user-attachments/assets/b2798cd7-4d0c-498c-a04e-5bad6971a8ae

**Comment by 87xie** [comment]
It looks like the `@scalar`-related package modified the styles of `#headlessui-portal-root`, which affected Nextra's headless portal.

https://github.com/user-attachments/assets/40f3fcde-2b2b-489a-a34a-1e32163cb89e

The error message might also be related to scalar's JavaScript.

**4a7b0aab-de96bf42fd08e753.js:288**

![image](https://github.com/user-attachments/assets/a114720a-63f8-44bc-80a7-53269b989972)

**Comment by dimaMachina** [comment]
Thank @87xie for the investigation, since nobody more reported a similar issue, I think the problem is with conflicting your internal packages who uses headless ui as well

**Comment by hariria** [comment]
You both are amazing! Thank you for the help @87xie and @dimaMachina . Upgrading scalar fixed it.
