### ISSUE TITLE
Mermaid breaks after v3.0.0-alpha.35

### ISSUE THREAD

**Issue by 87xie** [shuding/nextra#3236]
## Description

I tried migrating my blog to `v4.0.0-app-router` and found that the Mermaid diagrams were not displaying. After comparing versions, I discovered that the issue could also be reproduced in v3 alpha:

The error started appearing in `v3.0.0-alpha.35`. I checked the lock file, and 

- in `v3.0.0-alpha.35` version of `@theguild/remark-mermaid` was `v0.1.2`.
- In `v3.0.0-alpha.34`, the diagrams are displayed correctly, and the version of `@theguild/remark-mermaid` was `v0.0.7`.

I’m not sure about the actual cause of the error, I hope the information provided above is helpful.

Additionally, I’d like to ask, what is the preferred method for providing feedback on v4? Should I open a discussion or leave a comment on a specific issue?

**Comment by dimaMachina** [comment]
About Mermaid, can you try to patch this line 

https://github.com/the-guild-org/docs/blob/0362d4f5f262b8e9e210ec9102f66aeffeb17245/packages/remark-mermaid/src/index.ts#L21

to change import path to `nextra/components` (I think we need enhance this remark plugin to pass importPath as remark plugin option)

and about v4 feedback whatever works for you, maybe in [original GitHub issue](https://github.com/shuding/nextra/issues/2600), so people who subscribed will see it as well

**Comment by 87xie** [comment]
I patched the mermaid element ast back to the version before [this pull request](https://github.com/the-guild-org/docs/pull/1642/files), and it is rendering correctly. It seems the difference is that the chart prop of `<Mermaid />` retains the `\n`

**Comment by dimaMachina** [comment]
fixed in [`@theguild/remark-mermaid@0.1.3`](https://github.com/the-guild-org/docs/releases/tag/release-1727376017280)
