### ISSUE TITLE
Details Tag does not work as expected

### ISSUE THREAD

**Issue by The-Code-Monkey** [shuding/nextra#326]
When using the details tag it doesn't work as expected both the summary and content get put within the details tag with the title just saying details.

**Comment by aruniverse** [comment]
Not sure why this issue was closed, but this is definetly a bug with nextra, as collapsible blocks do work properly with mdx 

I expect:
  <details>
    <summary>Overview</summary>
	<p>
		"blah blah"
	</p>
  </details>

But this is actually what shows up: 

  <details>
    <summary>details</summary>
    - Overview
		  <p>
			  "blah blah"
		  </p>
  </details>

**Comment by aruniverse** [comment]
Fixed by @shuding and will be apart of the 2.0 release.

**Comment by B2o5T** [comment]
Closed as completed https://github.com/shuding/nextra/pull/407
