### ISSUE TITLE
hey, sorry, i just want to ask what's this plugin?

### ISSUE THREAD

**Issue by TONY-STARK-TECH** [shuding/nextra#3262]
<img width="864" alt="image" src="https://github.com/user-attachments/assets/27a6ae47-4046-4169-9b41-f2406059e7ea">

**Comment by luis-cruzt** [comment]
That's from https://arc.net

**Comment by TONY-STARK-TECH** [comment]
🦐🦐🦐🦐
 very thanks!!! @luis-cruzt
