### ISSUE TITLE
Mermaid in Tabs

### ISSUE THREAD

**Issue by 87xie** [shuding/nextra#3291]
## Description

Mermaid diagram displays correctly in the default active tab, but if it's in a non-default active tab, its size doesn't display properly when switching to that tab, It seems that calling `mermaid.initialize` within elements that have `display: none` results in incorrect SVG dimensions. as shown in the image below.

![image](https://github.com/user-attachments/assets/04af8e93-334e-4f7d-a6d6-523d7951e941)

There is a similar usage example in [Docusaurus](https://docusaurus.io/tests/pages/diagrams#mermaid-in-tabs). It would be great if Nextra could support this as well.

## Reproduction URL

https://codesandbox.io/p/devbox/affectionate-leftpad-vyqdks

The reproduction is using `nextra@3.0.0-alpha.34`, and it can also be reproduced in `v3.0.0-alpha.41` (after patching the `MermaidElementAST` to the implementation of `@theguild/remark-mermaid@0.1.0`).

**Comment by dimaMachina** [comment]
fixed in [`@theguild/remark-mermaid@0.1.3`](https://github.com/the-guild-org/docs/releases/tag/release-1727376017280)
