### ISSUE TITLE
cant's use docsRepositoryBase with github enterprise

### ISSUE THREAD

**Issue by maticrivo** [shuding/nextra#330]
Hi, when setting `docsRepositoryBase` with a self-hosted github enterprise version its throwing the error:
```
Invalid `docsRepositoryBase` URL!
```

After some investigation its coming from the `parse-git-url` package that does not handle self-hosted git server urls..

is there a way to add a workaround for that?

Thanks

**Comment by johnbellone** [comment]
I am running into same issue here.

**Comment by always-maap** [comment]
This is just a questionable design

**Comment by B2o5T** [comment]
will be available in next release

**Comment by maticrivo** [comment]
@B2o5T   Thanks for resolving this but honestly it has been 9 months since i opened the issue and as there was no response i have switched to use docusaurus 🙃

**Comment by nkechr1s** [comment]
Is there any way to remove it ?
