### ISSUE TITLE
SSR className bug with anchor links on 2.0.0-beta.5

### ISSUE THREAD

**Issue by tyrw** [shuding/nextra#331]
When hard-reloading a page with an anchor, the console logs the following error:

`Warning: Prop 'className' did not match. Server: "active" Client: ""`

Steps to reproduce:

1. Plain vanilla install as described [here](https://nextra.vercel.app/get-started)
2. Update to 2.0.0-beta.5 `yarn add nextra@2.0.0-beta.5`
3. Add a file to `/pages/page.mdx`:

```
# Page

Some text

## A subheading
```

4. Hard load the page `http://localhost:3000/page#a-subheading`

Following these steps, the browser throws the error listed above.

![Screen Shot 2022-01-19 at 8 33 29 AM](https://user-images.githubusercontent.com/819876/150173883-972bdf92-3d24-402a-bc9a-2540113bec73.png)

package.json

```
{
  "dependencies": {
    "next": "^12.0.8",
    "nextra": "2.0.0-beta.5",
    "nextra-theme-docs": "^1.2.6",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  }
}
```

**Comment by B2o5T** [comment]
do you have still an issue in the latest beta?
