### ISSUE TITLE
Sidebar don't update with Nextra 3

### ISSUE THREAD

**Issue by torn4dom4n** [shuding/nextra#3320]
**Describe the bug** I updated [my site](https://fancy-notes.vercel.app/) to Nextra 3 from Nextra 2 and the sidebar seems to not be corrected.

**To Reproduce** Steps to reproduce the behavior:

1. Go to: https://fancy-notes.vercel.app/
2. See the sidebar and click on pages with titles, nothing happens. Only pages with 'codes' are enabled to open.

**Expected behavior** Get correct titles instead of code names.

**Additional context**: I'm not sure this helps but I get this warning on Vercel:

![image](https://github.com/user-attachments/assets/1cdc3a7d-327c-426e-8c02-503aa12598f1)

**Comment by tirednemo** [comment]
facing the same issue
