### ISSUE TITLE
Build fails on vercel when docs exceed 800 files

### ISSUE THREAD

**Issue by badboyilprimo** [shuding/nextra#3321]
I have been trying to make a doc website for 1900 md files using vercel template and been failing for quite some time, doing the build few by few shows that it failed around 800 with

`Error: Command "pnpm run build" exited with SIGKILL `
I have tried

NODE_OPTIONS
VERCEL_FORCE_NO_BUILD_CACHE
VERCEL_DEEP_CLONE

this is the log when trying 1000 doc

- • Folder sizes on disk:
- ‣ Input source code: 8 MB
- ‣ Build cache: <1 MB
- ‣ Output files: 4 MB
- ‣ Node modules: 337 MB
- • 2 files larger than 100 MB detected on disk:
- ‣ 2705 MB : .next/cache/webpack/server-production/1.pack
- ‣ 450 MB : .next/cache/webpack/server-production/0.pack

**Comment by dimaMachina** [comment]
Please create a reproduction

**Comment by baraich** [comment]
Maybe, you could try building the application on your system using `vercel-cli` and push the built to production using `vercel deploy --prod --prebuilt`.

> You can build a production ready build on local machine using `vercel build --prod`

**Comment by badboyilprimo** [comment]
@baraich 
Thank for the suggestion it seems to have worked now in the build process (over 16gb of memory used) but issues on vercel are still a thing even if I'm deploying prebuilt, will try again later.

Thanks for the help.
