### ISSUE TITLE
`head` is not working  on 2.0.0-beta.5

### ISSUE THREAD

**Issue by cakecatz** [shuding/nextra#333]
I use `head` option for my application, but is throw an error like this:

```
error - node_modules/nextra-theme-blog/dist/index.js (354:230) @ Layout
ReferenceError: title is not defined
```

Here is the code that is causing the error.

```js
// node_modules/nextra-theme-blog/dist/index.js 
config.head ? config.head({ title, meta }) : null),
```

The `title` is used there, but it is not passed by args.

I tried to build it from source, but the output results were different.

```js
// nextra/packages/nextra-theme-blog/dist/index.js
config.head ? config.head({ title: `${pageTitle} ${config.titleSuffix}`, meta }) : null)
```

**Comment by AronBe** [comment]
facing the same issue 👋

**Comment by rgoomar** [comment]
It's definitely broken in the beta, I was able to get it working by switching to the latest alpha version
```
    "nextra": "2.0.0-alpha.48",
    "nextra-theme-blog": "2.0.0-alpha.48",
```

**Comment by B2o5T** [comment]
try the latest 2 beta
