### ISSUE TITLE
i18n problem

### ISSUE THREAD

**Issue by promer94** [shuding/nextra#336]
Nextra's i18n currently has some problems

1. When user's ```NEXT_LOCALE``` cookie conflicts with url, the render result is confusing.
![url-cookie-conflict](https://user-images.githubusercontent.com/15878786/150504350-0e524b9c-b972-48d8-8600-82633dfad0f9.png)

2. Since the nextjs i18n only handles the GET request, When ```NEXT_LOCALE``` cookie is missing, the ```prefilght request``` fired from ```next/link``` will not work as expected. It will prefetch unnecessary resources.
![i18-not-handle-head-request](https://user-images.githubusercontent.com/15878786/150504385-b0188abe-600b-4002-81fd-d06a45d338a1.png)

3. When users navigate to the site without ```NEXT_LOCALE``` and their language setting is different from the default locale. If users try to switch to the default locale, the corresponding resources will not be loaded

https://user-images.githubusercontent.com/15878786/150504431-2a0c536b-b669-4acb-a2ac-9059b6e65bf3.mov

**Comment by shuding** [comment]
Thanks for opening this!

**Comment by shuding** [comment]
(this should be fixed, forgot to close)
