### ISSUE TITLE
Improve Twoslash Popover Display in Nextra

### ISSUE THREAD

**Issue by Zih0** [shuding/nextra#3361]
Hello,

I would like to propose an enhancement regarding the display of the Twoslash popovers in Nextra. In the official Twoslash documentation, the popovers are displayed above the code blocks, which makes it easy to view the content. However, in Nextra, the popovers seem to be cut off inside the code blocks, making it difficult to read the content, especially when the popover is longer.

Would it be possible to implement a custom popover component in Nextra to address this issue? I noticed that the official Shiki/Twoslash documentation provides a renderer for Vue users (as seen here: https://shiki.matsu.io/packages/twoslash#rendererfloatingvue), and it seems feasible to create a similar implementation for React.

Additionally, another Next.js documentation library, Fumadocs, has already implemented this feature (you can find it here: https://github.com/fuma-nama/fumadocs/blob/1e715c93e53051fd699981e5c05c98750af7d6e6/packages/twoslash/src/index.ts#L38).

I believe this improvement would significantly enhance the user experience for those working with code blocks in Nextra. I would greatly appreciate your consideration of this request.

Thank you for your time and effort!

| shiki/twoslash docs | nextra docs |
| ------------- | ------------- |
| <img width="1274" alt="SCR-20241005-bwfc" src="https://github.com/user-attachments/assets/5b29b292-5f00-433f-93ac-aa0c4db6105c"> | <img width="1172" alt="SCR-20241005-buuf" src="https://github.com/user-attachments/assets/d1dd3e95-6199-43f0-b39d-be32b417cc53"> |

**Comment by dimaMachina** [comment]
Definitely good improvement 👍

**Comment by dimaMachina** [comment]
Hi, would you like to submit the PR? Since you already investigated how to fix it 😁
