### ISSUE TITLE
useNextSeoProps replacement?

### ISSUE THREAD

**Issue by tiffanyqi** [shuding/nextra#3363]
I'm currently migrating from Nextra 2 to Nextra 3, and I noticed that useNextSeo is deprecated in favor of the head field, but I don't know how toi add the page title name as the title anymore.

```
  useNextSeoProps: () => ({
     titleTemplate: "%s - Docs",
   }),
```

Is there a nice replacement to add the title name to the title tag in html? Thanks!

**Comment by tiffanyqi** [comment]
Found the replacement by doing this: https://nextra.site/docs/docs-theme/theme-configuration#dynamic-tags-based-on-page , I don't have `frontMatter` configured, but using `const { title } = useConfig()` worked!

**Comment by suprunchuk** [comment]
@tiffanyqi you can show me a complete example. I don't understand how to get it back

```jsx
useNextSeoProps() {
        return {
            titleTemplate: "%s",
        };
    },
```
