### ISSUE TITLE
<p> tag wrapping text content of <button>

### ISSUE THREAD

**Issue by jonasms** [shuding/nextra#3381]
**Describe the bug** A clear and concise description of what the bug is.
A `<p class="[&amp;:not(:first-child)]:_mt-6 _leading-7">` node is getting injected into some buttons and wrapping the text content. This is causing styling issues.

I'm rendering `<Button disabled outline>Outlined component</Button>` component whose return fxn looks like
```
return (
...

   <HButton
         {...props}
         {...dataProps}
         className={classes}
         disabled={disabled}
         ref={ref}
       >
         {children}
       </HButton>
)
```

(`HButton` is from `import {  Button as HButton } from "@headlessui/react";`.)

In the DOM, I'm seeing this <p> tag w/ a this class that's coming from `styles.css` which afaict is the Nextra stylesheet.
```
<button className="..."
    <p class="[&amp;:not(:first-child)]:_mt-6 _leading-7">Outline disabled button</p>
</button>
```

**Expected behavior** A clear and concise description of what you expected to
happen.

Should render to the DOM:
```
<button className="..."
    Outline disabled button
</button>
```

**Screenshots** If applicable, add screenshots to help explain your problem.
<img width="896" alt="image" src="https://github.com/user-attachments/assets/1d392c3d-8b7a-4498-8b66-2e4e7b4a896a">

**Desktop (please complete the following information):**

- OS: OSX 15.0.1
- Browser chrome v129.0.6668.90
- Version `"nextra-theme-docs": "3.0.0-alpha.39",`

**Comment by dimaMachina** [comment]
This not issue with nextra but as mdx 2/3 works

![IMG_2727](https://github.com/user-attachments/assets/45eadd19-4f6c-41eb-8ad5-ccaa759e3414)
![IMG_2728](https://github.com/user-attachments/assets/fb0625f4-79c8-456e-ab1e-cbedd5cf5988)
