### ISSUE TITLE
Add Smooth Scrolling to article.nextra-content

### ISSUE THREAD

**Issue by oobg** [shuding/nextra#3387]
**Is your feature request related to a problem? Please describe.** A clear and
concise description of what the problem is. Ex. I'm always frustrated when [...]

- Stiff page scrolling...?

**Describe the solution you'd like** A clear and concise description of what you
want to happen.

- It would be great to have smooth scrolling when clicking the TOC to navigate to a specific section.

**Describe alternatives you've considered** A clear and concise description of
any alternative solutions or features you've considered.

- You can achieve this by adding `scroll-behavior: smooth;` to the `article.nextra-content` class.
```css
article.nextra-content {
    scroll-behavior: smooth;
}
```
- I would like this feature to be included as a default option.

**Additional context** Add any other context or screenshots about the feature
request here.

- I’ve implemented this on [my personal website](https://blog.osb.im/posts/nodejs/01), and personally, I believe it has a positive impact on user experience.

**Comment by dimaMachina** [comment]
IMO I would like to reduce these animations (similar as in Next.js docs), people who need it can simply add with 3 lines CSS, wdyt @87xie cc

**Comment by 87xie** [comment]
> IMO I would like to reduce these animations (similar as in Next.js docs), people who need it can simply add with 3 lines CSS, wdyt @87xie cc

I prefer reducing these animations too.
