### ISSUE TITLE
Markdown file iframe not rendering

### ISSUE THREAD

**Issue by JacobHuang91** [shuding/nextra#3397]
**Describe the bug**

if you have a <iframe> in a markdown file, it will not display on the web page. 

**To Reproduce** Steps to reproduce the behavior:

1. add <iframe> to a .md file

**Expected behavior** 
iframe should display

**Screenshots** If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context** Add any other context about the problem here.

**Comment by arno-fukuda** [comment]
iframes render for me in v2 as well as v3.

Can you share a repro?

**Comment by dimaMachina** [comment]
I integrated totally fine iframe copied from YouTube in Nextra 3

<img width="844" alt="image" src="https://github.com/user-attachments/assets/d0a60687-2cfb-4094-a632-a70be40d8a4d">

Share minimal reproduction, closing for now
