### ISSUE TITLE
[v3] No built-in solution exists for detecting and redirecting to the user-selected language

### ISSUE THREAD

**Issue by pan93412** [shuding/nextra#3398]
**Is your feature request related to a problem? Please describe.**

In Nextra v2, the built-in `nextra/locale` can redirect a page to the user-selected language based on the `NEXT_LOCALE`.

```mermaid
graph TB
  docs["/docs/networking/public"] --> determine(Determine NEXT_LOCALE or by defaultLocale)
  determine -- en-US --> docs_en["/docs/en-US/networking/public"]
  determine -- zh-CN --> docs_zhcn["/docs/zh-CN/networking/public"]
  determine -- zh-TW --> docs_zhtw["/docs/zh-TW/networking/public"]
```

Additionally, it can redirect to the locale defined as `defaultLocale` in `next.config.js`. When users select a language on the documentation site, the subsequent `/docs` redirects to their preferred option:

```mermaid
graph TB
  docs["/docs"] -- by defaultLocale --> docs_en["/docs/en-US"]
  docs -- by cookie (NEXT_LOCALE) --> docs_zhtw["/docs/zh-TW"]
```

However, in Nextra v3, there is no official solution to re-implement this behavior. The [`swr-site`](https://github.com/shuding/nextra/tree/main/examples/swr-site) example does not support root subpage redirection:

```mermaid
graph LR
  docs["/docs/networking/public"] --> notfound(**404** 😢)
```

Although `swr-site` supports root redirection (via `redirects`), it does not take user preferences into account:

```mermaid
graph LR
  docs["/docs"] -- always --> docs_en["/docs/en-US"]
  docs["/docs"] -.->|if users prefer this, we should redirect to| docs_zh["/docs/zh-TW"]
```

**Describe the solution you'd like**

I’m wondering if we can restore `nextra/locale` or at least provide a solution for it. Otherwise, this would result in significant breaking changes, and I would need to write custom middleware to achieve what Nextra v2 could do.

**Describe alternatives you've considered**

I write a middleware for my case? 🫠

**Additional context**

N/A

**Comment by dimaMachina** [comment]
Can you try to use this middleware from v4? https://github.com/shuding/nextra/blob/v4-v2/examples/swr-site/middleware.ts

If it works in v3 I’ll include it

**Comment by arno-fukuda** [comment]
> If it works in v3 I’ll include it

@dimaMachina, using the v4 middleware in v3 indeed worked.
Note however that we also have to copy over the './app/_dictionaries/i18n-config' part.

One bug I noticed (which is also reproducible in v4):
* create /en and /zh folders within /pages directory.
* edit your NEXT_LOCALE value to `en-US` or `en1'
* run app
* access http://localhost:3000/
* observe ERR_TOO_MANY_REDIRECTS with Browser URL becoming http://localhost:3000/en-US/en-US/en-US/...

This could break the experience for existing users after a potential migration if you were to rename your locale prefixes.

I can file it separately if needed.

**Comment by pan93412** [comment]
> Can you try to use this middleware from v4? [`v4-v2`/examples/swr-site/middleware.ts](https://github.com/shuding/nextra/blob/v4-v2/examples/swr-site/middleware.ts?rgh-link-date=2024-10-09T10%3A31%3A15Z)
> 
> If it works in v3 I’ll include it

It works. I also add some modifications to make it aligned to the Nextra v2 behavior (root `/docs` redirection): https://github.com/zeabur/zeabur/pull/522/commits/a5442c5880b0cb6f6b6928741b16dc31c2ee715c

**Comment by dimaMachina** [comment]
will be exported in nextra 3.0.11, updated docs https://nextra.site/docs/guide/i18n#automatically-detect-and-redirect-to-user-selected-language-optional

@pan93412 you did an amazing job with mermaid diagrams, would you like to improve i18n docs to describe how redirecting works? Please contribute at https://nextra.site/docs/guide/i18n#automatically-detect-and-redirect-to-user-selected-language-optional 🙏❤️
