### ISSUE TITLE
Nested list margin bug

### ISSUE THREAD

**Issue by dasemai** [shuding/nextra#3399]
In a nested list (be it `ul` or `ol`, if the `li` into which is the list nested contains an inline element (`em`, `strong`, `a`, ...), the nested list get wrong `margin-top` due to apparently broken style precedence.

An example list in MD:

```markdown
This is a list:

- Lorem ipsum no formatting
	- No _problem_ here
	- Nested list
	- Another point
- This is top lvl _with_ formatting
	- This had wrong top margin 1.5rem
	- Lorem something ipsum
		- Deeper nested list
		- Something _formatted_ ipsum
			- And even deeper list with another wrong margin
```

This list renders as follows (marked the formatting and wrong margins with red rectangles):
![image](https://github.com/user-attachments/assets/cf7ea214-9baa-4932-9241-cc53b8ec52cb)

I'm using Nextra docs theme, these are relevant `package.json` lines:
```json
    "next": "^14.2.13",
    "nextra": "^2.13.4",
    "nextra-theme-docs": "^2.13.4",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
```

**Comment by dimaMachina** [comment]
Use Nextra v3 where it was fixed
