### ISSUE TITLE
(nextra=3.0.8) i18n: defaultLocale is not working

### ISSUE THREAD

**Issue by batchor** [shuding/nextra#3406]
I have a simple nextra site with following configurations:

```
import nextra from 'nextra'

const withNextra = nextra({
    theme: 'nextra-theme-docs',
    themeConfig: './theme.config.tsx'
})

export default withNextra({
    i18n: {
        locales: ['en', 'zh'],
        defaultLocale: 'en'
    },
    basePath: "/docs"
})
```

I couldn't visit `example.com/` and it returns 404 error. I have to visit `example.com/en` to get the default locale.
Seems like the `defaultLocale` configuration is not working. 

Code is here: <https://github.com/batchor/docs>

**Comment by arno-fukuda** [comment]
Removing `basePath` returns the index page on http://localhost:3000/en or http://localhost:3000/zh
```
import nextra from 'nextra'

const withNextra = nextra({
    theme: 'nextra-theme-docs',
    themeConfig: './theme.config.tsx'
})

export default withNextra({
    i18n: {
        locales: ['en', 'zh'],
        defaultLocale: 'en'
    },
    // basePath: '/docs'
})
```

**Comment by batchor** [comment]
@arno-fukuda Thanks for your response! I have two follow-up questions:

1. What does defaultLocale: 'en' do exactly? I was under the impression that setting this would serve the English version when visiting example.com or example.com/en. How can I access the default locale without using a sub-path?
2. I plan to deploy the website at example.com/docs. How can I configure this correctly?

**Comment by arno-fukuda** [comment]
In believe that in current v3, `defaultLocale` unfortunately doesn't do anything since out of the box [nextjs i18n](https://nextjs.org/docs/pages/building-your-application/routing/internationalization) is not being used.

There is some chatter in https://github.com/shuding/nextra/issues/3398 with potential workarounds being explored at the moment.

**Comment by batchor** [comment]
@arno-fukuda Thank you for your prompt response. Is there any plan for a fix to i18n in the future?
I can stay with what it is right now, but hopefully there will be a fix.

**Comment by arno-fukuda** [comment]
Hopefully 🤞.
The maintainer mentioned they might bring the middleware solution from v4 into v3.

I'm currently also blocked on migrating from v2 to v3 because of mentioned i18n discrepancies.

**Comment by dimaMachina** [comment]
[nextra.site/docs/guide/i18n#automatically-detect-and-redirect-to-user-selected-language-optional](https://nextra.site/docs/guide/i18n#automatically-detect-and-redirect-to-user-selected-language-optional)
