### ISSUE TITLE
[v3/v4] Feature Request:  Custom 404 page

### ISSUE THREAD

**Issue by arno-fukuda** [shuding/nextra#3409]
In v3 & v4, `theme.config.tsx` allows us to customize the `notFound` object to change the Issue hyperlink, but it doesn't give us full flexibility over a custom 404 page similarly to how v2 handles it.

Example of what we would like to keep when migrating:
https://docs.imgix.com/doesntexist

This was done by adding a 404.mdx page under `/pages` in combination with _meta file:
```
  "404": {
    "type": "page",
    "display": "hidden",
    "theme": { "layout": "raw" }
  }
```

**Comment by dimaMachina** [comment]
Hi, what do you want to configure exactly for 404 page via `theme` option? I think layout raw is by default now? example https://nextra.site/foo

**Comment by arno-fukuda** [comment]
> what do you want to configure exactly for 404 page via `theme` option?

A custom component to be rendered instead.
In our case we want to have our buttons to navigate back to Home or contact help.

Speakeasy example for reference:
https://www.speakeasy.com/doesntexist

**Comment by dimaMachina** [comment]
you can put anything you want in 404.mdx
```mdx
# 404: Page Not Found

<button onClick={() => {}}>Go Back</button>
```

<img width="1650" alt="image" src="https://github.com/user-attachments/assets/6f032e39-849a-4870-9de1-9b05c83623ff">

**Comment by arno-fukuda** [comment]
Gotcha, I don't see it working with i18n in that case.

I have a 404.mdx in each loc folder:
`/pages/en-US/404.mdx`
`/pages/ja-JP/404.mdx`

They are being treated as normal pages and an actual 404 gets the default nextjs boilerplate:
<img width="487" alt="Screenshot 2024-10-12 at 23 02 03" src="https://github.com/user-attachments/assets/cc4e90fe-34bc-4b9e-aa14-946df514f59e">

When we add a 404.mdx directly under `pages/`, it seems output this error:
```
 ✓ Starting...
   automatically enabled Fast Refresh for 4 custom loaders
 ✓ Ready in 1412ms
 ✓ Compiled /middleware in 67ms (65 modules)
 ○ Compiling /404 ...
 ⨯ ./pages/404.mdx:2:1
Module not found: Can't resolve '/Users/arno/Desktop/docs/.next/static/chunks/nextra-page-map-404.mdx.mjs'
  1 | import { HOC_MDXWrapper } from 'nextra/setup-page'
> 2 | import { pageMap } from '/Users/arno/Desktop/docs/.next/static/chunks/nextra-page-map-404.mdx.mjs'
    | ^
  3 |
  4 | /*@jsxRuntime automatic*/
  5 | /*@jsxImportSource react*/

https://nextjs.org/docs/messages/module-not-found
```

**Comment by dimaMachina** [comment]
https://nextra.site/docs/guide/i18n#custom-404-page
