### ISSUE TITLE
[V3] What happened to SEO?

### ISSUE THREAD

**Issue by LuchoTurtle** [shuding/nextra#3430]
Thank you for the **amazing effort** done with `Nextra` so far and creating version `v3` and `v4`!

The previous version of Nextra `v2` allowed us to customize the SEO (including the icon and title of each page) through [`useNextSeoProps`](https://nextra-v2-oe0zrpzjp-shud.vercel.app/docs/docs-theme/theme-configuration#seo-options) in the `theme-config.tsx` file.

Perusing the new documentation at https://nextra.site/docs/, I can't find any mention of `useNextSeoProps` (it has been removed). How can I customize the tab title and the site icon now? I want to reuse my previous SEO configuration but I don't know where I can do so 🤔 

Thank you!

**Comment by dimaMachina** [comment]
removed, setup your `<head>` tags via head option now or install `next-seo` manually

**Comment by mnahkies** [comment]
@LuchoTurtle In case it helps, I just updated mine, like so: https://github.com/mnahkies/openapi-code-generator/blob/2068ae20201bbcc1353aee9c5babfa0170adfbef/packages/documentation/src/theme.config.tsx#L14-L50

**Comment by LuchoTurtle** [comment]
Thank you @mnahkies and @dimaMachina for the feedback, it is SUPER appreciated <3!
