### ISSUE TITLE
Support GitHub alert syntax

### ISSUE THREAD

**Issue by 87xie** [shuding/nextra#3447]
**Is your feature request related to a problem? Please describe.**

Currently, the usage of Nextra's `<Callout />` is somewhat similar to [GitHub alert syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts). If `<Callout>` could support these alert types and perform a similar transformation during the compilation phase:

```mdx
> [!NOTE]
> Useful information that users should know, even when skimming content.
```

to

```mdx
<Callout type="info">
  Useful information that users should know, even when skimming content.
</Callout>
```

This might useful when a user clicks on `Edit this page on GitHub →` on doc page, as they should be able to see a similar style on GitHub like:

![image](https://github.com/user-attachments/assets/c180d77c-8e25-4a14-bad7-02726d5389fc)

Not sure if I have missed something obvious; feel free to close this or move it to a discussion if it is not suitable.

**Describe the solution you'd like** 

- Support GitHub alert syntax.
- When using GitHub alert syntax, there should be no need to import the `<Callout>` component.

**Describe alternatives you've considered** 

N/A

**Additional context** 

N/A

**Comment by dimaMachina** [comment]
we can even make it's as agnostic `<Callout>` component, so users can use own
```js
    blockquote: withGitHubAlert(
// component for blockquote
      props => (
        <blockquote
          className={cn(
            '[&:not(:first-child)]:_mt-6 _border-gray-300 _italic _text-gray-700 dark:_border-gray-700 dark:_text-gray-400',
            '_border-s-2 _ps-6'
          )}
          {...props}
        />
      ),
      (type: 'note' | 'tip' | 'important' | 'warning' | 'caution', content) => {
        return (
          <Callout
            type={
              {
                note: 'info',
                tip: 'default',
                important: '...',
                warning: 'warning',
                caution: 'error'
              }[type]
            }
          >
            {content}
          </Callout>
        )
      }
    ),
```
