### ISSUE TITLE
Support Twoslash code organization features

### ISSUE THREAD

**Issue by aniravi24** [shuding/nextra#3448]
**Is your feature request related to a problem? Please describe.**

When using [twoslash](https://shikijs.github.io/twoslash/) code organization features like `@include` or `---cut---`, nothing happens in the rendered Nextra page.

**Describe the solution you'd like**

I want to be able to use features such as `@include` and `---cut---` from twoslash in my Nextra pages. Right now, it just prints the directive directly into the output without actually applying it to the twoslash markdown.

**Describe alternatives you've considered**

Prior to Nextra adding support for twoslash, I tried to add it myself with [remark-shiki-twoslash](https://www.npmjs.com/package/remark-shiki-twoslash). However, the Nextra twoslash integration looks better than trying to add twoslash and the corresponding styling manually. I would prefer to use twoslash through nextra with no additional configuration.

**Additional context** Add any other context or screenshots about the feature
request here.

**Comment by dimaMachina** [comment]
PR welcome

**Comment by sgmustafi** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by jellli** [comment]
The features you mentioned don’t seem to have any issues.
Here's my input and render result:
<img width="380" alt="image" src="https://github.com/user-attachments/assets/2b1ec5e9-7c51-4a3b-9631-cc56da881792" />
<img width="810" alt="image" src="https://github.com/user-attachments/assets/68dd737a-9461-49cb-9cd1-b3e281f76bb2" />

The difference between my example and the official website is that I explicitly specified the language. It didn’t display correctly before I did this step.
<img width="269" alt="image" src="https://github.com/user-attachments/assets/cb69bac6-7ca9-4600-a3b7-2234bccbbd56" />
<img width="316" alt="image" src="https://github.com/user-attachments/assets/d6cf84fa-413d-4e77-9a33-c86484f1d6ed" />

**Comment by aniravi24** [comment]
Ah that was the issue, thank you!
