### ISSUE TITLE
[Feedback] sidebar.titleComponent replacement

### ISSUE THREAD

**Issue by arno-fukuda** [shuding/nextra#3475]
`sidebar.titleComponent` was removed in favor or `_meta.js`

We used `sidebar.titleComponent` to replace all occurrences of "and" with "&" in the sidebar for better readability.

```
sidebar: {
    defaultMenuCollapseLevel: 1,
    toggleButton: true,
    autoCollapse: true,
    titleComponent({ title }) {
      if (title.includes(" and")) {
        title = title.replace("and", "&")
      }
      return <>{title}</>
    },
  }
```

Now, when having to do it through `_meta.js`, we would need to list every nested mdx page (imagine having 100), otherwise it would be bumped to the top of the sidebar.

Example:
pages/one.mdx
pages/two.mdx
pages/three.mdx
pages/foo-and-bar.mdx
pages/four.mdx
pages/five.mdx

`_meta.js` :
```
export default {
	'foo-and-bar': 'foo & bar'	
```

^ Would push the file to the top unless we listed all nested mdx files in `_meta.js`

**Comment by dimaMachina** [comment]
> we would need to list every nested mdx page (imagine having 100), otherwise it would be bumped to the top of the sidebar.

In nextra 3 we have new frontmatter property sidebarTitle

```md
---
sidebarTitle: foo & bar
---
```

Would you want to help document it?

Is it solution is still not enough for you and you want alternative to `titleComponent`?

**Comment by arno-fukuda** [comment]
`sidebarTitle` would be great. Happy to document it once below is cleared ↓

https://github.com/shuding/nextra/blob/5d37b3d8396551f9b30d855fd694e9a7f53cbba0/packages/nextra/src/server/page-map.ts#L124

It only seem to work when the page also includes a frontMatter.title

Is it possible to make it work just like that without a title?
```
---
description: this is a  description
sidebarTitle: custom side bar title
---

# Heading 1
```

**Comment by dimaMachina** [comment]
fix on way
