### ISSUE TITLE
Nextra3: _meta.ts config not applied

### ISSUE THREAD

**Issue by moklick** [shuding/nextra#3481]
After migrating to nextra 3 there are some pages where we can't display a TOC or change the layout.

**To Reproduce** Steps to reproduce the behavior:

1. Go to a [React Flow what's new article](https://reactflow.dev/whats-new/2024-10-16)
2. No TOC, even if specified in related [_meta.ts](https://github.com/xyflow/web/blob/main/sites/reactflow.dev/src/pages/whats-new/_meta.ts#L5-L6)

**Expected behavior**: Display a TOC

**Comment by dimaMachina** [comment]
this line can be removed as well https://github.com/xyflow/web/blob/80dd366f2922748af38bfa8f4f4a81039da28083/sites/reactflow.dev/src/pages/whats-new/_meta.ts#L6

**Comment by moklick** [comment]
Thanks @dimaMachina! Removing `type: 'page'` fixed the issue. It was working with nextra 2, so I thought this was a bug.
