### ISSUE TITLE
[v3] Separator not respecting order in sidebar

### ISSUE THREAD

**Issue by arno-fukuda** [shuding/nextra#3485]
**Describe the bug** 

Regression, used to work in v2.

Following file structure:
```
pages/overview.mdx
pages/getting-started.mdx
pages/about.mdx
```
Create the following `_meta.js`, where separator follows the top item with no item after that:
```
export default {
  "overview": "Overview",
  "---": {
    "type": "separator"
  },
}
```

**Expected** 
Sidebar should be:
```
Overview
---separator---
- rest ordered alphabetically
```

**Actual** 
Sidebar becomes:
```
Overview
- rest ordered alphabetically
---separator---
```

**Comment by dimaMachina** [comment]
can confirm, need to fixed here somewhere https://github.com/shuding/nextra/blob/a742821f3c125a6bd2e300ba1b5411be6c2320c8/packages/nextra/src/client/normalize-pages.ts#L166-L202

**Comment by dimaMachina** [comment]
@arno-fukuda Ok, seems I fixed it after big refactoring in https://github.com/shuding/nextra/pull/3512, I will release `canary` instead of stable first, please definitely try it if I didn't miss something and share your feedback

Also I found a way to fix another issue to validate `_meta` keys https://github.com/shuding/nextra/issues/2664

**Comment by dimaMachina** [comment]
try `nextra-theme-docs/nextra` `3.1.0-canary.0`

**Comment by arno-fukuda** [comment]
Thank you for the quick turnaround 🙇

Tested the canary.

1) Separator location is now correct for sidebar.

2) had a redundant object in _meta.js that was ignored previously but failed dev this time.
This is in combination with a 404.js file. Deleting the below line corrected it.
```
// _meta.js
export default {
   ...
  "404": {
    "type": "page",
    "display": "hidden",
    "theme": { "layout": "raw" }
  }
}
```

3) [breaking] `_meta.js` menu items are missing.
```
// _meta.js
export default {
  "getting-started": {
    "title": "Getting Started",
    "type": "menu",
    "items": {
      "setup": {
        "title": "Setup"
      },
      "best-practices": {
        "title": "Best Practices"
      },
      "tutorials": {
        "title": "Tutorials"
      }
    }
  }
}

<img width="134" alt="Screenshot 2024-10-20 at 11 35 14" src="https://github.com/user-attachments/assets/a9285f8e-a75f-4e72-831d-39fff39719aa">
You should be able to repro with docs template on the version menu:
https://github.com/shuding/nextra/blob/6511ed4cf45ffe68c08b1446941dd5a6543e28d4/docs/pages/_meta.ts#L20

**Comment by dimaMachina** [comment]
> You should be able to repro with docs template on the version menu:

hm I can't repro this in https://nextra.site/

Can you help me repro it, so i will found how to fix it :)

**Comment by arno-fukuda** [comment]
@dimaMachina  

https://github.com/arno-fukuda/nextra/tree/ISSUE-3485

<img width="534" alt="Screenshot 2024-10-20 at 21 13 31" src="https://github.com/user-attachments/assets/844228a6-2566-4017-b63b-b7d9d9caaefe">

**Comment by dimaMachina** [comment]
Hi @arno-fukuda try `nextra/nextra-theme-docs` `3.1.0-canary.1`, should be good now, thanks for reporting!

**Comment by arno-fukuda** [comment]
works now 👍 Thanks as always
Will update our app when its out of canary

**Comment by dimaMachina** [comment]
did a stable release 👍
