### ISSUE TITLE
Feedback for “License Upgrade”

### ISSUE THREAD

**Issue by 8string** [shuding/nextra#3496]
Hi. I just paid you $20 through PayPal (and it shows I did on my PayPal activity). However it did not drop me back to your purchase page and show the purchase completing. Can you fix this? 

Al Bergstein
Mountainstone Consulting

![image](https://github.com/user-attachments/assets/101a056e-091a-42fa-964c-b4c239069351)

**Comment by dimaMachina** [comment]
your issue is unrelated to Nextra https://github.com/shuding/nextra/issues/3072#issuecomment-2254345423

**Comment by 8string** [comment]
What are you talking about? This has nothing to do with Nextra's 3072. I just tried buying an update to your product. It didn't work. Why did you close this?

**Comment by dimaMachina** [comment]
This website has nothing to do with [Nextra](nextra.site) right, it was just built with Nextra framework

Contact owner of your website in another way
