### ISSUE TITLE
[I18n] `direction: rtl` in RTL languages

### ISSUE THREAD

**Issue by ezzak** [shuding/nextra#35]
Is it possible to get the main paragraphs on the page with the correct applied direction when in RTL.

![image](https://user-images.githubusercontent.com/20268283/101299989-05016680-3802-11eb-90bb-544609c53e77.png)

https://developer.mozilla.org/en-US/docs/Web/CSS/direction

**Comment by shuding** [comment]
Thanks for reporting! I'll make sure it gets supported.

**Comment by shuding** [comment]
Just added a `direction: 'rtl'` option for i18n: https://nextra.vercel.app/docs/i18n 🎉

**Comment by ezzak** [comment]
Fix is great thank you, a small request if possible, can we hide the language menu if there is only one item in it? Before it was okay to exclude it to hide the menu but now I need to set the language there to get RTL. Thanks!

**Comment by shuding** [comment]
@ezzak I see, what do you think about adding a global RTL option? Because if I understand correctly, you have only 1 locale but it's RTL.

**Comment by ezzak** [comment]
Yup that's the case 👍

**Comment by shuding** [comment]
Root-level `direction: "rtl"` is supported now, please upgrade 👍
