### ISSUE TITLE
Layout keeps breaking since updating to Nextra 3.0

### ISSUE THREAD

**Issue by timohuennebeck** [shuding/nextra#3506]
After updating to Nextra 3.0 this morning, I'm experiencing intermittent layout issues. The styling occasionally disappears completely, as shown in the attached screenshot.

I've tried the following:
- Reinstalling Nextra 3.0
- Deleting node_modules and reinstalling
- Deleting existing npm cache
- Checking package.json for conflicts (no other packages installed)

This issue occurs randomly and is not consistently reproducible, and most of the time I can just restart the local server and it will disappear again.

Has anyone else encountered similar issues with Nextra 3.0?

<img width="522" alt="Screenshot 2024-10-19 at 15 42 57" src="https://github.com/user-attachments/assets/820715da-a206-4e85-9d73-ea2501ee5945">

Here's my package.json:

```
{
  "type": "module",
  "name": "nextra-docs-template",
  "version": "0.0.1",
  "description": "Nextra docs template",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/shuding/nextra-docs-template.git"
  },
  "author": "Shu Ding <g@shud.in>",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/shuding/nextra-docs-template/issues"
  },
  "homepage": "https://github.com/shuding/nextra-docs-template#readme",
  "dependencies": {
    "next": "^13.0.6",
    "nextra": "^3.0.15",
    "nextra-theme-docs": "^3.0.15",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/node": "18.11.10",
    "typescript": "^4.9.3"
  }
}
```

**Comment by dimaMachina** [comment]
Please provide reproduction

**Comment by timohuennebeck** [comment]
Thanks! Adding the _app.tsx in the pages folder solved it for me, as it had been stated in the linked issue 👍 

```
function App({ Component, pageProps }) {
  return <Component {...pageProps} />
}

export default App
```
