### ISSUE TITLE
Ability to add a custom icon against an item in side menu bar

### ISSUE THREAD

**Issue by norbert-fivestars** [shuding/nextra#3507]
In Nextra 3, is there an ability to add a custom svg/webp icon (stored in public, for example) to be rendered to the left of the text representing the page in the side menu bar?

**Comment by dimaMachina** [comment]
you can add any jsx content in sidebar title via `_meta` files https://github.com/shuding/nextra/blob/a1bd1599e1ac0f9d12078263ed19937d6c113f54/examples/swr-site/pages/en/docs/_meta.tsx#L18-L24

**Comment by norbert-fivestars** [comment]
Got it. Thank you!
