### ISSUE TITLE
[nextra-theme-blog] Allow for a draft post

### ISSUE THREAD

**Issue by rgoomar** [shuding/nextra#351]
Currently, you can get around this by putting a `_` as part of the `.mdx` file although, I think it would be helpful to have a metadata field like:
```
---
type: post
draft: true
---
```
That way, it won't display in the posts list although still have a link that you can send out to people to review that will remain the same after publishing.

**Comment by YikSanChan** [comment]
@rgoomar 

> you can get around this by putting a _ as part of the .mdx file although

Do you mind sharing more details on how to make it work? Thx!

**Comment by rgoomar** [comment]
@YikSanChan Basically, if you have an `_`, it ignores it based on this line https://github.com/shuding/nextra/blob/core/packages/nextra-theme-blog/src/index.tsx#L126

So you can link to it as a post, but doesn't appear in the list.
