### ISSUE TITLE
Support `npx` commands through `npm2yarn`

### ISSUE THREAD

**Issue by peterkogo** [shuding/nextra#3528]
**Is your feature request related to a problem? Please describe.**
Currently using `npm2yarn` on code blocks which start with `npx` is not possible because there is an error built into `@theguild/remark-npm2yarn` that only allows for command conversions that start with `npm`.

**Describe the solution you'd like**
`npm-to-yarn`, the actual library performing the conversions, already supports this in the currently used version 3.0.0. I have created [a pull request](https://github.com/the-guild-org/docs/pull/1749#issuecomment-2428909818) for the `@theguild/remark-npm2yarn` package that also allows `npx` conversions. Pulling in the upstream changes once it's merged should be enough.

**Comment by dimaMachina** [comment]
I cut a release, update your `lock` file

**Comment by peterkogo** [comment]
Thanks so much for the swift action!

**Comment by dimaMachina** [comment]
You are welcome
