### ISSUE TITLE
Rendering a component inside head does not rerender

### ISSUE THREAD

**Issue by peterkogo** [shuding/nextra#3529]
**Describe the bug**
Since updating [our site ](https://reactflow.dev/)to Nextra 3 we are having issues displaying the correct title inside `<head />`.
I was able to pin it down to the reason being that we render a component inside `head` in `theme.config.tsx`. 

Simplified version:

```tsx
const config: DocsThemeConfig = {
  head(): {
    const { frontMatter } = useConfig();

    const title = frontMatter.title ?? 'Title;

    return(<Head title={title} />);
  }
};

const Head = ({ title }) => <title>{title}</title>;
```

The problem is that `head()` actually re-renders, but `<Head />`  is just being rendered once on the server and then stays the same.

**To Reproduce** Steps to reproduce the behavior:

I [created a fork](https://github.com/peterkogo/nextra-docs-template) of the nextra-docs-template. I updated the dependencies to the latest and migrated the project.[ I hope did everything right.](https://github.com/shuding/nextra-docs-template/compare/main...peterkogo:nextra-docs-template:main)

1. clone the project
2. `pnpm install && pnpm dev`
3. Open inspector and navigate inside `<head>` tag
4. See the first title (rendered directly inside `config.head`) rerender, and the second (rendered inside a component) does not.

**Expected behavior** We should be able to pass a component that handles the head inside `theme.config.tsx`

**Comment by dimaMachina** [comment]
Don't use react components in `head` option

**Comment by dimaMachina** [comment]
See example of from nextra.site https://github.com/shuding/nextra/blob/d3d9508bb3bae0a1526f97512fcbe3ad96ca5585/docs/theme.config.tsx#L63

**Comment by peterkogo** [comment]
Alright! Does this also effect other options inside `theme.config.tsx`?

**Comment by dimaMachina** [comment]
Nope, only `head`
