### ISSUE TITLE
`<table>` elements no longer styled by default in v3 when used in expression

### ISSUE THREAD

**Issue by terrymun** [shuding/nextra#3530]
**Describe the bug** In `nextra@2`, the native `<table>` elements and its associated nodes, e.g. `<tbody>`, `<tr>`, `<td>`, `<th>` have opinionated styles, which allows us to use the actual `<table>` tags in MDX and still get the same appearance as the markdown table.

However, in `nextra@3`, the `<table>` element is no longer styled if and only if it is generated as a JSX expression:

```tsx
// This works
<table>
  <thead>
    <tr>
      <th />
      <th>Column 1</th>
      <th>Column 2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Row 1</td>
      <td>Lorem</td>
      <td>ipsum</td>
    </tr>
    <tr>
      <td>Row 2</td>
      <td>Dolor</td>
      <td>sit</td>
    </tr>
  </tbody>
</table>

// This doesn't
{<table>
  <thead>
    <tr>
      <th />
      <th>Column 1</th>
      <th>Column 2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Row 1</td>
      <td>Lorem</td>
      <td>ipsum</td>
    </tr>
    <tr>
      <td>Row 2</td>
      <td>Dolor</td>
      <td>sit</td>
    </tr>
  </tbody>
</table>}
```

This is potentially problematic as we have dynamically generated tables in our documentation, which appear unstyled after the upgrade to v3.

**To Reproduce** Steps to reproduce the behavior:

Create a HTML table using JSX expression:

```tsx
{<table>
  // Rest of the table content here
</table>}
```

**Expected behavior** A `<table>` inside curly brackets should render just like a regular `<table>` in the MDX file.

**Screenshots**

![Screenshot 2024-10-24 at 13 53 17](https://github.com/user-attachments/assets/0a28bfa8-e87c-4541-a2e4-a0d453628cc0)

**Desktop (please complete the following information):**

- OS: macO
- Browser Google Chrome
- Version 130.0.6723.70

**Comment by dimaMachina** [comment]
this is a new MDX3.1 behaviour, a place to complain https://github.com/mdx-js/mdx/issues/2549

**Comment by terrymun** [comment]
Thanks for the reply @dimaMachina :)

**Comment by dimaMachina** [comment]
Feel free to send a PR
