### ISSUE TITLE
Document alternative to "raw" in v4

### ISSUE THREAD

**Issue by Firgrep** [shuding/nextra#3541]
**Is your feature request related to a problem? Please describe.** 
I would like the flexibility of fully controlling a page when needed. Certain pages, such as landing pages, need to have full width for fancy backgrounds, etc. Currently, "full" layout has a div with a max width high up and then an article that further adds padding. 

![Screenshot from 2024-10-25 18-47-07](https://github.com/user-attachments/assets/7c0fb646-51af-4029-bb08-1ed21899df9a)

![image](https://github.com/user-attachments/assets/157adca6-dbb4-4a03-be62-d2596b52ebe7)

**Describe the solution you'd like**
Put back "raw" as a layout option as it was before.

Or at least put the CSS into classes that I can then select and override for the particular page. 

**Describe alternatives you've considered**
Creating pages apart from Nextra routes, but then I have to duplicate the navbar, footer etc, which doesn't seem like a good idea.

**Comment by dimaMachina** [comment]
[you can use `page.tsx` for it](https://github.com/shuding/nextra/blob/v4-v2/docs/app/page.tsx), an example from migrated nextra.site

**Comment by Firgrep** [comment]
Thanks for super quick reply! I was trying to use a page.tsx, but I'm also trying out the catch-all [[...mdxPath]] route, since it's so much nicer to deal with docs using the content folder, and that caused a route collision.

I've nested the catch-all route one level down. `/test-path/[...mdxPath]]` which seems to have done the trick, but it seems it's not obeying the `_meta.ts` file properly anymore, `type: "page",` is not being respected 🤔 do I need to make any changes in the content folder?

**Comment by dimaMachina** [comment]
I will take a look at how to use `page` files with `catch-all` once I will have some free time, thanks for the feedback!

**Comment by dimaMachina** [comment]
closed by https://github.com/shuding/nextra/pull/3595
