### ISSUE TITLE
_Meta file not finding files when nesting catch-all route in v4

### ISSUE THREAD

**Issue by Firgrep** [shuding/nextra#3567]
**Describe the bug** A clear and concise description of what the bug is.

Nesting the catch-all route one level down. /nested-path/[...mdxPath]] seems it's not obeying the _meta.ts file properly anymore, type: "page", is not being respected. 

Additionally, any nested paths inside of `content` are "not found". Without the nested path everythig seems to work fine.

![Screenshot from 2024-10-27 21-31-12](https://github.com/user-attachments/assets/7180f786-59bf-45f7-80f9-05712ecf23aa)

![image](https://github.com/user-attachments/assets/d6afa161-5a9a-4c27-b4ad-03daa476f1c8)

**To Reproduce** Steps to reproduce the behavior:

1. Go to 'a nextra project that uses v4 catch-all route'
2. Nest the catch-all route one level down
3. Run the app

**Expected behavior** A clear and concise description of what you expected to
happen.

Expected that it would be able to maintain the content folder integrity and its meta config.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

Ubuntu 24.04.1 LTS
Chrome
Chrome 130 on Linux

**Comment by sgmustafi** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by dimaMachina** [comment]
Made some progress:

<img width="253" alt="image" src="https://github.com/user-attachments/assets/f32636b4-32e6-4bd0-a289-2509ed0d35f4">

<img width="696" alt="image" src="https://github.com/user-attachments/assets/57177aca-0d16-44df-976b-5a65fe845763">

**Comment by Firgrep** [comment]
Wuuhuu! Nice! 🥳👌
