### ISSUE TITLE
Routing/Refresh behavior

### ISSUE THREAD

**Issue by dashcraft** [shuding/nextra#357]
On latest (2.0.0 beta 5), if you have a site deployed (not locally) and refresh on a nested markdown file/route, it will return back the index/base path.

The work around is to add all the paths for your md files into exportPath object, this somehow forces it to send the correct client side, compiled md route.

Cursory review seems to indicate that the pagemap inside of the nextjs implementation doesn't respect different base routes when creating paths. This may not be true, that's what it seems.

**Comment by B2o5T** [comment]
Hi @dashcraft do you still have this problem?

**Comment by dashcraft** [comment]
@B2o5T i haven't updated to the latest version, but as of the version listed above, i was still experiencing the issue.

I'll double check if we still have that issue now.

**Comment by dimaMachina** [comment]
closing due time, feel free to reply if you still need help
