### ISSUE TITLE
Files not added to navigation

### ISSUE THREAD

**Issue by pearcircuitmike** [shuding/nextra#358]
In the most recent version, adding a new .mdx file does not result in it being added to the site navigation sidebar when the file is added to a subfolder.

**Comment by B2o5T** [comment]
Hi @pearcircuitmike, do you still have this problem?

**Comment by B2o5T** [comment]
closing due inactivity

**Comment by bryandandan** [comment]
I have the same issue. Locally the navigation is fine, on vercel, it does not work
