### ISSUE TITLE
Can I ignore the hidden files while searching ?

### ISSUE THREAD

**Issue by CaryiWong** [shuding/nextra#3580]
When I make a document hidden, I don't want users to be able to search for it（like show in search result list）. 
Hoping this feature can be supported in future versions~~~

**Comment by sgmustafi** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by CaryiWong** [comment]
Is it already supported？I tried but didn't work in V3~

**Comment by dimaMachina** [comment]
please create a reproduction
