### ISSUE TITLE
Page Configuration issue when two pages share same folder with index namespace on Nextra 3

### ISSUE THREAD

**Issue by Morgan-jarry** [shuding/nextra#3581]
## Description

From nextra 3.0.0 to latest 3 version, using the following name configuation for folders with index Page:

**`pages/_meta.ts`**
```tsx
export default {
  text: "Text",
  "text-input": "TextInput",
}
```

**`pages/Text.mdx`**
```mdx
# Text page
```

will duplicate `text` link in navigation.

| Folder Structure | Result in main sidebar navigation |
| :--: | :--: |
| ![Capture d’écran 2024-10-28 à 16 24 27](https://github.com/user-attachments/assets/913ed67c-c855-4ffc-9e5d-435781589d0c) | ![Capture d’écran 2024-10-28 à 16 26 04](https://github.com/user-attachments/assets/f40f4841-02c6-489f-96c1-dc4bdcd639c2) |

**Screenshot**
![image](https://github.com/user-attachments/assets/0b3ae26c-86ca-4828-bd18-ef63c8a26c46)

## How to Reproduce?

In `pages/` folder, create a file with a namespace like `foobar.mdx` and use the same namespace to create another file separate with a dash and another string like `foobar-test.mdx`.
Then, create a `pages/foobar/` folder with another mdx file inside.
This results in a duplicate `foobar` link.

## Expected behavior

Using folders with index page should not duplicate the folder name in the main navigation.

## Configuration

**Desktop computer**:
- **OS**: macOS 13.7
- **Browser**: Chrome 129.0.6668.101 (Build officiel) (arm64)
- **Nextra** Version from 3.0.0 to 3.1.2

**Comment by dimaMachina** [comment]
Hi, I never encountered this problem, seems something related to your project configuration, `index` pages works without any issues for nextra.site

Try to provide runnable reproduction or create a PR which demonstrate this issue based on [nextra.site](https://github.com/shuding/nextra/tree/main/docs) app or our [examples](https://github.com/shuding/nextra/tree/main/examples)

Also, I saw your like in https://github.com/shuding/nextra/issues/3576, can you provide this repro as well?

**Comment by Morgan-jarry** [comment]
Hi @dimaMachina,
I do [reproduce the bug](https://github.com/Morgan-jarry/nextra-issue/commit/924d6189ce98b0a9dc3278ba2d30108c64a85e43) using `docs/` examples.

![Capture d’écran 2024-10-28 à 18 09 26](https://github.com/user-attachments/assets/3ac761b8-154f-4b12-af3b-2910188f159d).

About https://github.com/shuding/nextra/issues/3576, I will remove the like because I thought it was the same bug as the one explained here.

**Comment by dimaMachina** [comment]
Thank you, I will take a look ❤️

**Comment by Morgan-jarry** [comment]
Thank you very much for your responsiveness @dimaMachina!
