### ISSUE TITLE
[v4] still add `page.{tsx,mdx,jsx}` and `_meta` files from `app` dir to `pageMap` when `contentDirBasePath` is set

### ISSUE THREAD

**Issue by dimaMachina** [shuding/nextra#3594]
I found one issue for `docs` folder:

So now, this `_meta` is ignored from adding to `pageMap`

<img width="548" alt="image" src="https://github.com/user-attachments/assets/5f956bfa-df49-40bb-a972-4e04458663ee">

<img width="611" alt="image" src="https://github.com/user-attachments/assets/9973754e-1897-4218-8c1a-c86f57909219">

- we cannot rename `docs` folder here
- we cannot also use `display: 'children'` (to hide the folder and show only children).

This will be not fixed in this PR, and more likely be fixed after 4 RC.0.

When you set `contentDirBasePath: '/docs'` - pages `page.{tsx,mdx,jsx}` and `_meta` files  in `app` dir  are not added to `pageMap`, to fix it I have an idea: when `contentDirBasePath` is set - still add all `page.{tsx,mdx,jsx}` and `_meta` files from `app` dir to `pageMap`

_Originally posted by @dimaMachina in https://github.com/shuding/nextra/issues/3593#issuecomment-2445207923_

**Comment by manfromanotherland** [comment]
Is there a way to hide `docs` from the sidebar when using `contentDirBasePath: '/docs'`? I tried the method above by using `_meta.ts` but it doesn’t work. And if I tried to add `docs` on my `/content/_meta.ts` file it throws an error saying:

```
The field key "docs" in `_meta` file refers to a page that cannot be found, remove this key from "_meta" file.
```

## Update

For anyone that has the same issue, add the following under `/app/_meta.ts` directory with this content:

```ts filename="_meta.ts"
import type { MetaRecord } from 'nextra';

export default {
  docs: {
    display: 'children',
  },
} satisfies MetaRecord;

```

I was trying to put it under `app/docs/_meta.ts` but that was wrong.

Thanks!
