### ISSUE TITLE
v4: Changing checkbox state in MDX throws React error about un/controlled input

### ISSUE THREAD

**Issue by eliot-akira** [shuding/nextra#3597]
**Describe the bug**

When writing a task list with MDX using `- [ ]` and `[x]`, changing the checkbox state results in React error.

> A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://react.dev/link/controlled-components

**To Reproduce**

1. Open an MDX file
2. Start a task list
   ```md
   - [ ] Example
   ``` 
3. Save file
4. Change checkbox to `[x]` and save again
5. See error

**Expected behavior**

Change task list checkbox without error

**Additional context**

- Using `nextra` version `4.0.0-app-router.17`

**Comment by dimaMachina** [comment]
this issue is nothing related to Nextra, just a hydration mismatch due to fast refresh, when you reload a page you don't receive any errors
