### ISSUE TITLE
pnpm cache is always not found for `windows`

### ISSUE THREAD

**Issue by dimaMachina** [shuding/nextra#3609]
<img width="979" alt="image" src="https://github.com/user-attachments/assets/acec4285-0aab-42eb-a126-8a38c8eaceec">

It would be nice if somebody fix this workflow

https://github.com/shuding/nextra/blob/0da9c11a554059c5baea89d3392cb7c700b7c0f1/.github/workflows/test.yml#L13

**Comment by jdpoccorie** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by jellli** [comment]
hey @dimaMachina , i would like to give it a try, but how can i test it?

**Comment by dimaMachina** [comment]
@jellli Thank you, I think it was somehow fixed maybe by `action` internally
<img width="1084" alt="image" src="https://github.com/user-attachments/assets/f1b5aaa1-c37a-4440-b1c0-75a34f05ec51">
