### ISSUE TITLE
Question about max files/folders

### ISSUE THREAD

**Issue by dennyrgood** [shuding/nextra#3617]
Greetings,

I am working with a hard drive that has approximately 700,000 files and 12,000 folders. (4TB)

Should DeltaWalker be able to handle those quanities without freezing up? Are there settings I need to check on my Windows 11 machine?

Kind regards,
Dennis

**Comment by dimaMachina** [comment]
your issue is unrelated to Nextra

**Comment by dennyrgood** [comment]
Just so you know, their website:

https://www.deltawalker.com/documentation

has a link to this:

https://github.com/shuding/nextra/issues/new?title=Feedback%20for%20%E2%80%9CWelcome!%E2%80%9D&labels=feedback

**Comment by dimaMachina** [comment]
Contact them via other way
