### ISSUE TITLE
3.1. introduced a breaking change

### ISSUE THREAD

**Issue by russellmcc** [shuding/nextra#3635]
Thanks for nextra!

https://github.com/shuding/nextra/pull/3585 seemed to introduce some breaking changes, making my 3.0-compatible site no longer build.  According to [semver](https://semver.org), breaking change must be reserved for major versions, is there a way to wait until 4.0 to introduce this requirement?

**Comment by dimaMachina** [comment]
Hi, [Nextra 3 had some problems in Next.js 15](https://github.com/shuding/nextra/issues/3357#issuecomment-2419750310) without a custom `_app` file. Did you have some issues with adding a custom `_app` file?

Can you add this file with the following content? https://github.com/shuding/nextra/blob/c09fd957094a3c42f16977fa55b358d7d7a4105a/examples/docs/src/pages/_app.jsx

**Comment by russellmcc** [comment]
Ah, adding the `_app` file did work fine.  I still failed to build, but this was fixed by also removing any `index.tsx` files referred to in `_meta.ts`, and replacing these with `index.mdx` files - I'm not sure why I had to do this, but everything is working now!  Thanks for maintaining this library.

**Comment by dimaMachina** [comment]
You are welcome 👋
