### ISSUE TITLE
Feedback for “Comparing Image Files”

### ISSUE THREAD

**Issue by said-son** [shuding/nextra#3644]
As a photographer managing an image archive across multiple JBOD hard drives, it sure would be handy if DeltaWalker could help distinguish changes in metadata (IPTC, EXIF, XMP, for example) for image files JPEG, TIFF, PSD, PSB, and DNG across replicas. I've been using DW for years as a folder management tool but have been stymied when it comes to identifying photo files that have had fresh metadata input vs those that have not. File size can often differ based solely upon the size of the hard drive to which a file has been copied, so size differences are not a reliable indicator for me.

If I take a single TIFF file, duplicate it, then add a few keywords to the metadata of one copy in Photoshop and save the file... comparing the two files in DW recognizes a difference in Date and Size with no further detail. It is therefore impossible for me to disambiguate image files in the archive that have updated metadata from those otherwise identical photographs.

https://iptc.org/standards/photo-metadata/photo-metadata/

Am I missing something from DW's functionality which would help in this task?

Thanks for listening and for the great program !

-Said

**Comment by dimaMachina** [comment]
Unrelated issue to Nextra

**Comment by said-son** [comment]
Understood Dmitri,

I clicked a link on the DeltaWalker site: "Question? Give us feedback” and failed to realize that I was taken to a different service.


Sorry for the bother,
Said

**Comment by dimaMachina** [comment]
Contact them via another way, and you can also ask to remove this feedback link which by default points to Nextra (removed this default in Nextra v4)
