### ISSUE TITLE
[v4] `::selection` background invalid property value prevents text selection

### ISSUE THREAD

**Issue by eliot-akira** [shuding/nextra#3645]
**Describe the bug**

This is a weird one, the symptom is that text selection doesn't work on Firefox and Chromium. Article text cannot be selected by click and dragging the mouse - nor by keyboard as far as I can tell.

It took some digging to find the cause, it's this [inline style in the Head component](https://github.com/shuding/nextra/blob/4616cf08674d9c5fd4f61cc96051b783b804fc73/packages/nextra/src/client/components/head.tsx#L85-L91) that applies background color to the `::selection` pseudo-element.

```css
::selection {
  background: ${makePrimaryColor(41)};
}

.dark ::selection {
  background: ${makePrimaryColor(-11)};
}
```

On Firefox, inspecting this CSS shows "invalid property value".

![image](https://github.com/user-attachments/assets/b748a67d-8cf6-49ee-9c01-bf1f61d7da17)

Same error on Chromium:

![image](https://github.com/user-attachments/assets/60399326-aa62-4d99-b673-22bf0835bef0)

It looks like a parser bug. The value includes the closing bracket `}` and the next selector `.dark ::selection { ... }`.

```
hsl(var(--nextra-primary-hue) var(--nextra-primary-saturation) calc(var(--nextra-primary-lightness) + 41%); } .dark ::selection { background: hsl(var(--nextra-primary-hue) var(--nextra-primary-saturation) calc(var(--nextra-primary-lightness) + -11%); }
```

Mysteriously this error prevents text selection from working. When I remove the `::selection` styles, it works.

It seems the JSX `style` element is being incorrectly parsed. Hard to imagine but in that case the root cause is somewhere upstream, I guess in the Webpack/Babel build pipeline.

**To Reproduce**

1. On Firefox or Chromium, try to select any text in an article (MDX) using the mouse.

**Expected behavior** 

Able to select text on Firefox and Chromium.

**Additional context**

- Next `15.0.2`
- Nextra `4.0.0-app-router.21`
- Firefox version: `132.0` (64-bit Linux)
- Chromium version: Version `113.0.5672.126` (Official Build) (64-bit Linux)

**Comment by eliot-akira** [comment]
I see, you solved it by moving the string interpolation outside of the `style` element. Sweet!

**Comment by dimaMachina** [comment]
@eliot-akira I think the problem was due to missing closed bracket at the end of the line here

https://github.com/shuding/nextra/blob/53c86ca95e02740f71f9e26e7f8c1b7c90ae9799/packages/nextra/src/client/components/head.tsx#L104

**Comment by eliot-akira** [comment]
Ooh right, `calc()` was closed but the outer `hsl()` was not. And solved by

https://github.com/shuding/nextra/pull/3655/files#diff-702a7a239ca5189f9ea2bb6b092f8ecba0918a5fbfb2cde3fdc242f2a8c84d75R107-R108

**Comment by dimaMachina** [comment]
exactly 👌
