### ISSUE TITLE
Supports Embedded Video from other sources

### ISSUE THREAD

**Issue by dharanigowthamsampath** [shuding/nextra#3647]
Here's a detailed feature request for adding embedded video support in Nextra:

---

**Feature Request: Embedded Video Support in Nextra Documentation**

**Summary**  
I would like to request the addition of a feature in Nextra that allows users to embed videos directly within Markdown (`.md`) files. This enhancement would improve the user experience by enabling visual content integration within documentation, making it especially helpful for educational and instructional materials.

**Description**  
Nextra’s current setup primarily focuses on text and static content, which works well for many use cases. However, there are scenarios where video content can significantly enhance understanding, especially when explaining complex concepts or showcasing tutorials. Adding embedded video support within Markdown files would allow users to incorporate YouTube, Vimeo, or self-hosted videos without needing to link out to external pages.

**Expected Behavior**  
Users should be able to embed videos within a Markdown file by including a video URL or iframe code directly in the `.md` file, and Nextra should render the embedded video in the generated HTML without additional configuration.

**Suggested Implementation**  
1. **Support for Video Links**:  
   Allow a simple syntax for video URLs from platforms like YouTube and Vimeo, such as:
   ```markdown
   ![Video title](https://www.youtube.com/watch?v=example)
   ```
   The Markdown processor should recognize the URL as a video link and embed it accordingly.

2. **Iframe Embed Support**:  
   Provide support for iframes directly within Markdown, which could look like:
   ```markdown
   <iframe width="560" height="315" src="https://www.youtube.com/embed/example" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
   ```
   Nextra could sanitize and securely display these iframes within the documentation page.

3. **Nextra-Specific Component for Videos**:  
   Optionally, add a Nextra-specific component, like `<Video src="URL" />`, to support consistent embedding across all pages, allowing for additional configuration options (e.g., width, height, autoplay, etc.).

4. **Styling and Responsiveness**:  
   Ensure that embedded videos are responsive and match the theme’s styling so they adapt to various screen sizes and look cohesive with the rest of the content.

**Benefits**  
- **Enhanced User Experience**: Videos embedded in context with text can make complex information easier to digest.
- **Improved Engagement**: Users are more likely to engage with documentation that includes multimedia content.
- **Educational Utility**: For users creating learning materials, embedded videos can be crucial for visual explanations.

**Example Use Cases**  
- **Technical Documentation**: Embedding short video tutorials or code walkthroughs to complement written explanations.
- **Product Guides**: Including demo videos directly within feature descriptions.
- **Educational Content**: Providing learners with instructional videos on specific topics within educational documentation.

**Conclusion**  
Adding embedded video support to Nextra would greatly benefit content creators who rely on a combination of text and multimedia to communicate effectively. This feature aligns with Nextra's goal of delivering a rich and interactive documentation experience.

Thank you for considering this feature request!

**Comment by Firgrep** [comment]
I use a component for youtube videos. Maybe it can be helpful in this context.

<details>

```typescript
// usage
import { EmbedYT } from "lib/components/ui/EmbedYT";

<EmbedYT src="https://www.youtube.com/embed/embed-id-stuff">
    Some text
</EmbedYT>
```

```typescript
export const EmbedYT = (props: any) => {
    const {
        children,
        src,
        minWidth = "400px",
        maxWidth = "800px",
        ...otherProps
    } = props;

    return (
        <section
            style={{ width: "100%", minWidth: minWidth, maxWidth: maxWidth }}
            aria-label="YouTube video"
        >
            <div
                style={{
                    position: "relative",
                    width: "100%",
                    overflow: "hidden",
                    paddingTop: "56.25%",
                }}
            >
                <div>
                    <iframe
                        style={{
                            position: "absolute",
                            top: "0",
                            left: "0",
                            right: "0",
                            width: "100%",
                            height: "100%",
                            border: "none",
                        }}
                        width="560"
                        height="315"
                        src={src}
                        title="Video player"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                        {...otherProps}
                    >
                        {children}
                    </iframe>
                </div>
            </div>
        </section>
    );
};
```

</details>

**Comment by dharanigowthamsampath** [comment]
im completely beginner to this, and i dont know how to import this component into the md file, can you help me with some example?

**Comment by Firgrep** [comment]
You can import it in a `.mdx` file :) as you can with many other javascript components as long as they don't require anything back from the server.
