### ISSUE TITLE
Improve search ranking

### ISSUE THREAD

**Issue by shuding** [shuding/nextra#366]
Would love to have some explicit rules here. For example if searching for "middleware" on swr.vercel.app the first match will be the blog post. However there is a page in the docs that titled with just "Middleware". So I think that we should use the following strategy with flex search:
- Do two indexes, one for `title` and one for `title + content`.
- We search with both indexes, and always put the results from `title` first.
- Join the results by page / sections.

**Comment by buccalon** [comment]
@shuding Have you considered [minisearch](https://github.com/lucaong/minisearch)? Detailed explanation [here](https://lucaongaro.eu/blog/2019/01/30/minisearch-client-side-fulltext-search-engine.html).
