### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by wayne-shih** [shuding/nextra#3667]
writing a issue here in case it helps others while searching for the issue 

## issue 

upgrading 3.0.x to ^3.1.0 caused this issue for us

![image](https://github.com/user-attachments/assets/7466ddee-d9bc-4e7e-8d61-73d9966083a6)

we were using type:menu and display:hidden it as a hacky solution to hide nested items on the sidebar, ie. -- 
```tsx 
// /pages/**/_meta.tsx

export default {
  'hide-this-folder-and-child-items': {
    display: 'hidden',
    type: 'menu'
  }
}
```

## solution 

[Menu](https://nextra.site/docs/docs-theme/page-configuration#menus) only work for top navbar 

So outside of your top navigation meta file `/pages/_meta.[jsx,tsx]` make sure you don't have any `type: 'menu'` and/or items 

```diff 
// /pages/**/_meta.tsx

  export default {
    'hide-this-folder-and-child-items': {
      display: 'hidden',
-    type: 'menu'
    }
  }
```

removing it fixes issue and builds correctly 

it also hides the folder and child items now

**Comment by dimaMachina** [comment]
this was improved in v4, `_meta` files are parsed with zod now
