### ISSUE TITLE
[v4] Nextra adds all static sites to navigation while using useContentDirPath

### ISSUE THREAD

**Issue by ArikSquad** [shuding/nextra#3672]
**Describe the bug**
Nextra adds all static sites to navigation while using useContentDirPath. Also the /docs could be cut from there but it's not the main point of this issue.

**To Reproduce** Steps to reproduce the behavior:

1. Have static sites on your website
2. use v4
3. useContentDirPath

**Expected behavior**
I expected src/app and all the static pages not to show up. _Also I expected the /docs in the top to not show up._

**Screenshots**
![image](https://github.com/user-attachments/assets/98cdc1c5-5034-4ae3-a743-3802f40bf059)

Talking about the src/app showing there

**Desktop:**

- OS: Windows 11
- Browser: Chrome
- Version 130?

**Additional context** 
Using [nextra@4.0.0-app-router.22](https://github.com/shuding/nextra/releases/tag/nextra%404.0.0-app-router.22)

**Comment by dimaMachina** [comment]
Files which you don't want to show you can always hide with `display: hidden`

> I expected src/app and all the static pages not to show up. Also I expected the /docs in the top to not show up.

the whole point of `content` dir is:

- use `content` dir as an alternative to Next.js `pages` dir to avoid `page.{md,mdx}` convention
- **`to include`** in `pageMap` mdx pages from `content` dir and `page.{mdx,jsx,tsx}` from `app` dir 
- remove `layout: raw` and replace it with `page.{jsx,tsx}` files

> Also the /docs could be cut from there but it's not the main point of this issue.

you can use `type: page` or `display: children` in `_meta` file

**Comment by ArikSquad** [comment]
If I'm gonna use the content dir, I expect it not tho use the jsx routes from app. Also I don't know where to put the `type: page` or `display: children`, I tried the children display but I wasn't sure how. Also I can't display hide the src things cuz they aren't in the content dir

**Comment by dimaMachina** [comment]
> Also I don't know where to put the type: page or display: children,

in `_meta` file in `app` dir, look at docs example https://github.com/shuding/nextra/blob/v4-v2/examples/docs/app/_meta.js

> Also I can't display hide the src things cuz they aren't in the content dir

this is strange, can you share your project?

**Comment by ArikSquad** [comment]
When I'm home I'll invite you to my repo

**Comment by ArikSquad** [comment]
I invited you to my repo, it's in the `feature/nextra4` branch

**Comment by ArikSquad** [comment]
![image](https://github.com/user-attachments/assets/0a276901-cfef-4f57-b66e-f3b56eb87ec3)
oh... this didnt happen when I tested using dev mode

**Comment by dimaMachina** [comment]
Yeah, move app and content in root directory, will be fixed after rc.0 release

**Comment by dimaMachina** [comment]
I think you using windows locally?

**Comment by ArikSquad** [comment]
Yes I use windows locally, but I might not be able to move to root directory as I really like the src folder and I can wait :) good work tho, nextra is awesome

**Comment by dimaMachina** [comment]
try https://github.com/shuding/nextra/releases/tag/nextra%404.0.0-app-router.23

**Comment by ArikSquad** [comment]
Thanks, works perfectly!
