### ISSUE TITLE
[v4] Compilation failed with a mermaid block

### ISSUE THREAD

**Issue by 87xie** [shuding/nextra#3687]
**Describe the bug** A clear and concise description of what the bug is.

Compile error in `page/**/page.mdx` or `content/**/*.mdx` with a mermaid block. (using`nextra@4.0.0-app-router.24`)

**To Reproduce** Steps to reproduce the behavior:

[Here](https://github.com/87xie/nextra/tree/compilation-failed-with-a-mermaid-block) is a runnable reproduction. I added a [mermaid page](https://github.com/87xie/nextra/commit/23a4fb9651be3d67b4b4923ab806b0a14c10c4e6) in the docs example

1. `pnpm dev:theme-docs`
1. Go to `/mermaid`
1. You may see the following error: `Module not found: Can't resolve '@theguild/remark-mermaid/mermaid'`

**Expected behavior** A clear and concise description of what you expected to
happen.

No errors occur, and the page and Mermaid diagram display as expected.

**Screenshots** If applicable, add screenshots to help explain your problem.

![image](https://github.com/user-attachments/assets/284a3022-385e-4d4b-9095-7ef14ca58479)

**Desktop (please complete the following information):**

N/A

**Smartphone (please complete the following information):**

N/A

**Additional context** Add any other context about the problem here.

N/A

**Comment by shunueda** [comment]
Temporary solution: add `@theguild/remark-mermaid` to your `dependencies`.

**Comment by TOLK-kz** [comment]
I also had this error with React 19.0 (nextra-theme-docs - version 4.2.16). When I downgraded to React 18.2, the problems were solved.
