### ISSUE TITLE
DeltaWalker hang

### ISSUE THREAD

**Issue by qvtac** [shuding/nextra#3711]
fist test of DW on mac mini M4Pro 64GB
testing comparison apps   on internal SSD cf external Acacias TB4/Crucial Gen5 NVMe  T700 pro 

not responding  286.31GB
novel

![Screenshot 2024-11-16 at 6 57 52 pm](https://github.com/user-attachments/assets/e87c47fe-d816-4070-bfb0-f657fcea5520)

**Comment by dimaMachina** [comment]
Unrelated issue to nextra
