### ISSUE TITLE
2.0.0-alpha.28 doesn't work

### ISSUE THREAD

**Issue by MinJieLiu** [shuding/nextra#373]
clone swr-site

![image](https://user-images.githubusercontent.com/6167727/154842670-413341cb-f6cb-4a4d-be85-a64ba6f03d48.png)

```
pnpm i

pnpm dev
```

![image](https://user-images.githubusercontent.com/6167727/154842665-0950f1b4-61fb-468a-8cf6-3cc223656bdb.png)

**Comment by shuding** [comment]
Fixed in `2.0.0-alpha.29`.
