### ISSUE TITLE
bugfix: theme: {layout: 'full', typesetting: 'article'}

### ISSUE THREAD

**Issue by pnrf** [shuding/nextra#3730]
These parameters do not work together. Or.. or...
For example, if I make a fullpage then the header is left. 'Typesetting' can't align it to the center.

```
export default {
  index: {
    title: 'Home',
    theme: {
             layout: 'full',
	     typesetting: 'article'
    }
  }
}
```

Docs:
https://nextra.site/docs/docs-theme/page-configuration#full-layout

#Full Layout
#Typesetting

**Comment by pnrf** [comment]
Nextra 3.x

**Comment by dimaMachina** [comment]
can cofirm this issue https://github.com/shuding/nextra/blob/a94c7e2a477d94e7b5e9b4956ca76a880f03b9ee/packages/nextra-theme-docs/src/mdx-components.tsx#L303-L304

PR welcome, already fixed in v4 with https://github.com/shuding/nextra/issues/2016 feature

**Comment by pnrf** [comment]
Thank you.
