### ISSUE TITLE
Question using Nextra 3/4 for Dynamic Routes and ISR

### ISSUE THREAD

**Issue by mcnojo** [shuding/nextra#3768]
Hello!  I'm trying to use Nextra for hosting multiple docs sites that are generated in a dynamic route for multiple subdomains, then use ISR for each of them:

Question: is it possible to host multiple dynamically generated Nextra sites in the same application route? let say we have a primary application that that will route subdomains apple and orange (or others outside of "www".site.com) to a dynamic catch all route [[...subdomain_docs]].

Is this a reasonable (or possible) strategy to present static docs that also use ISR?

Would we be able to use and apply dynamic theme as well? Many thanks, I'm new to Nextra :)

**Comment by mcnojo** [comment]
You're the goat thank you, also: should I only be installing one of nextra-theme-docs and/or nextra?

I imagine I'm supposed to install at: 4.0.0-app-router.34

But with both nextra and nextra-theme-docs using this package I keep running into this issue:


`Failed to compile

Next.js (14.2.6) is outdated [(learn more)](https://nextjs.org/docs/messages/version-staleness) (turbo)
./node_modules/.pnpm/nextra@4.0.0-app-router.34_acorn@8.12.1_next@14.2.6_@opentelemetry+api@1.9.0_@playwright+test_khefrv2awh4q6u44w5mrhmsi54/node_modules/nextra/dist/client/components/search.js:13:27
Module not found
  11 | import { InformationCircleIcon, SpinnerIcon } from "../icons/index.js";
  12 | async function importPagefind() {
> 13 |   window.pagefind = await import(
     |                           ^^^^^^^
> 14 |     /* webpackIgnore: true */
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 15 |     addBasePath("/_pagefind/pagefind.js")
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 16 |   );
     | ^^^^
  17 |   await window.pagefind.options({
  18 |     baseUrl: "/"
  19 |     // ... more search options

https://nextjs.org/docs/messages/module-not-found`

**Comment by dimaMachina** [comment]
use next.js 15 or remove `--turbo` flag from next.js 14
