### ISSUE TITLE
One page documentation

### ISSUE THREAD

**Issue by alexandrutasica** [shuding/nextra#377]
Hello, Nextra community,
The company I collaborate with wants to use the documentation as one-pager documentation.

My thoughts about this were to:
- either implement it using an API endpoint that crawls all the markdown from `/pages` folder and then gets it using a fetch call on the UI, and renders the MDX
- have one MDX file that contains  all the documentation, instead of having multiple files

Is there any built-in function for having one-pager documentation on Nextra? Or a planned feature for the future?

**Comment by leerob** [comment]
Hey! You could definitely have a single page using Nextra, if you want. You could be a custom theme (similar to docs theme, blog theme) for the single page 😄

**Comment by B2o5T** [comment]
I thought @leerob answered for it
