### ISSUE TITLE
docs: add warning about _meta.js allowed extensions

### ISSUE THREAD

**Issue by pnrf** [shuding/nextra#3782]
Nextra 3.x
Is it possible to add to the documentation?

**Where:** https://nextra.site/docs/guide/organize-files#allowed-extensions
**What:**

_meta.js does not allow naming long files with dashes, you have to use camelcase. Therefore, it is better to use .jsx. 

1. For example:

```jsx
export default {
  index: '',
  'docs-theme': '',
  'blog-theme': ''
}
```
It doesn't work in _meta.js
But it works in _meta.jsx

2. For example: 

```js
export default {
  index: '',
  docsTheme: '',
  blogTheme: ''
}
```
It works in _meta.js
But it's not convenient

**Comment by dimaMachina** [comment]
I don't think you are right, please provide reproduction repo, `_meta` behaviour is the same for `js`/`jsx`/`ts`/`tsx` extensions

**Comment by pnrf** [comment]
Thanks, I'll try to double-check everything again.

**Comment by suprunchuk** [comment]
@dimaMachina @pnrf 

I confirm that this does not work in `.tsx`

![изображение](https://github.com/user-attachments/assets/94c9525b-1ee5-4e78-852f-b29a502346a0)


```json
  "dependencies": {
    "next": "^15.1.4",
    "nextra": "^3.0.0",
    "nextra-theme-docs": "^3.3.1",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
```

**Comment by suprunchuk** [comment]
but the underlining works.

![изображение](https://github.com/user-attachments/assets/28ca9e5e-eec6-4edf-b3bd-d1f6aa836f4d)
