### ISSUE TITLE
[nextra-theme-docs] - head to accept callback with frontMatter meta for SEO

### ISSUE THREAD

**Issue by Djuki** [shuding/nextra#379]
At this moment, blog theme can accept callback with `title` and `meta` as arguments,

```
  head: ({ title, meta }) => (
    <>
      {meta.description && <meta name="description" content={meta.description} />}
      {meta.tag && <meta name="keywords" content={meta.tag} />}
      {meta.author && <meta name="author" content={meta.author} />}
    </>
  ),
```

This is not possible in docs theme. We can't use callback with docs theme. Is there any way to get frontMatter meta and set up different title/keywords and description for every page?

**Comment by shuding** [comment]
Which version of Nextra are you on? I think the latest alpha/beta version has this supported as well: https://github.com/shuding/nextra/blob/dd5a08e0b3d817244b6bc90cdd7268af8b2355b5/packages/nextra-theme-docs/src/head.tsx#L27

**Comment by Djuki** [comment]
@shuding 
```
    "nextra": "^2.0.0-beta.5",
    "nextra-theme-docs": "^2.0.0-beta.5",
```

**Comment by Djuki** [comment]
@shuding I recorded a video that may help us to see where the issue is and to find is this a global issue or not.

https://www.loom.com/share/ad54d4c96c64400fb8d87aaa458d00a4
