### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by CompeyDev** [shuding/nextra#380]
When attempting to build my self hosting docs, here is the error I get. For reference, the content in my `.mdx` file is below.

![image](https://user-images.githubusercontent.com/74418041/155556755-2d3e0b08-98a1-4326-a34c-47dafa00e220.png)

Contents:

<code>
# Self Hosting Instructions
1. Clone and checkout the release branch (or download the the latest release at [releases](https://github.com/TheAwesomeCoder05/MusicComp-v2/releases)):

```
git clone https://github.com/TheAwesomeCoder05/MusicComp-v2.git
cd MusicComp-v2
git checkout release
``` 
**OR**
<br>
The semi-updated version using CDNs at [here](https://www.devcomp.tk/MusicComp-v2/downloads).
<br>

2. CD to the directory and install the package and dependencies using:

```
bash -f setup.sh
```

**OR**

Manually install the packages using:

  <h3> i. NPM: </h3>
  
```
npm install musiccomp-discord-bot --legacy-peer-deps
```

  <h3> ii. Yarn: </h3>

```
yarn add musiccomp-discord-bot
```
Please do note that yarn package will always be 1 version ahead of the npm package. 

3. Edit the `botconfig.js` file and enter your Discord Token from [here](https://discord.com/developers/applications), along with a spotify API Token from [here](https://developer.spotify.com/dashboard/) and a YouTube API Token from [here](https://developers.google.com/youtube/registering_an_application).
4. Lastly run the following, to run the bot:
```
node index.js
```
</code>

**Comment by TheAwesomeCoder05** [comment]
Since GitHub keeps rendering it, this is the link to the raw file: https://raw.githubusercontent.com/TheAwesomeCoder05/nextra/master/pages/hosting/instructions.mdx

**Comment by leerob** [comment]
Hey! Looks like there is an unexpected character in there (based on the error). Could you try removing that?

**Comment by CompeyDev** [comment]
Doesn't look like there is though. What is the unexpected character exactly, there is not "!".

**Comment by shuding** [comment]
The file link shows 404 for me. As per the error message, did you have a HTML comment somewhere?

```html
<!-- ... -->
```

If so please change it to `{/* ... */}`.

**Comment by CompeyDev** [comment]
Oh sorry, my bad. I deleted the file later.
Here's the file:
https://raw.githubusercontent.com/CompeyDev/MusicComp-v2/production/docs/docs/SELFHOST.md

**Comment by CompeyDev** [comment]
> The file link shows 404 for me. As per the error message, did you have a HTML comment somewhere?
> 
> ```
> 
> ```
> 
> If so please change it to `{/* ... */}`.

Nope, I didn't.

**Comment by shuding** [comment]
Try changing the unclosed `<br>` to `<br/>`,  that could be the case.

**Comment by CompeyDev** [comment]
Alright. Let me try that out.

**Comment by CompeyDev** [comment]
Looks like the same error:
![image](https://user-images.githubusercontent.com/74418041/156984833-1a0901ef-8817-4207-a6c4-8ee17f348629.png)

**Comment by B2o5T** [comment]
@CompeyDev did you try the latest beta version of nextra? Do you have this error while building your project locally?

**Comment by CompeyDev** [comment]
Oh, I've not tried actually. And no, this error doesn't occur locally if I recall.

**Comment by B2o5T** [comment]
@CompeyDev do you have still an issue in the latest beta 2 version?

**Comment by CompeyDev** [comment]
Just tried, seems to work perfectly! 👍
