### ISSUE TITLE
Unable to Apply Background for Light and Dark Themes in theme.config.tsx

### ISSUE THREAD

**Issue by prernasyan** [shuding/nextra#3802]
**Description**
I am trying to set different background colors for light and dark themes in my theme.config.tsx file. However, the DocsThemeConfig type from nextra-theme-docs does not seem to support color or backgroundColor properties as outlined in the [Theme Color](https://nextra.site/docs/docs-theme/theme-configuration#theme-color) documentation.

**Expected Behavior**
I should be able to define distinct background colors for light and dark themes in theme.config.tsx to match the design requirements.

**Current Behavior**
The DocsThemeConfig type does not recognize color or backgroundColor, and there are no clear instructions in the documentation to achieve this functionality.

**Relevant Code**
Here is my current theme.config.tsx:

```
import { DocsThemeConfig } from "nextra-theme-docs";
import FooterContent from "./components/footer/FooterContent";

const config: DocsThemeConfig = {
  footer: {
    component: FooterContent,
  },
  editLink: {
    component: null,
  },
  feedback: {
    content: null,
  },
  sidebar: {
    defaultMenuCollapseLevel: 0,
  },
  toc: {
    extraContent: true,
    backToTop: true,
  },
};

export default config;
```

**Steps to Reproduce**
1. Create a theme.config.tsx file.
2. Attempt to set backgroundColor for light and dark themes.
3. Observe the lack of TypeScript support and documentation guidance.

**Additional Information**
How can I set different background colors for light and dark themes as per the documentation? Is there a workaround, or is this feature missing in the DocsThemeConfig type?

For example, I want to implement the following:

Light Theme: backgroundColor: "#ffffff"
Dark Theme: backgroundColor: "#000000"

Please clarify or provide an example implementation for achieving this.

**Comment by dimaMachina** [comment]
https://nextra.site/docs/docs-theme/theme-configuration#theme-color use follow format `RRR,GGG,BBB`

> [!WARNING]
>
> not `#...` or `rgb(RRR,GGG,BBB)`, so for color `#000000`, it should be `0,0,0`

<img width="877" alt="image" src="https://github.com/user-attachments/assets/ed65bde8-0925-4bd7-8e19-01fe7ac13e63" />

**Comment by arno-fukuda** [comment]
Example using you config:
```
import { DocsThemeConfig } from "nextra-theme-docs";
import FooterContent from "./components/footer/FooterContent";

const config: DocsThemeConfig = {
  footer: {
    component: FooterContent,
  },
  editLink: {
    component: null,
  },
  feedback: {
    content: null,
  },
  sidebar: {
    defaultMenuCollapseLevel: 0,
  },
  toc: {
    extraContent: true,
    backToTop: true,
  },
  backgroundColor: {
    light: "255,255,255",
    dark: "30,30,35",
  }
};

export default config;
```

**Comment by prernasyan** [comment]
Object literal may only specify known properties, and 'backgroundColor' does not exist in type '{ navigation?: boolean | { next: boolean; prev: boolean; }; banner?: { dismissible?: boolean; key?: string; text?: ReactNode | FC; }; chat?: { icon?: ReactNode | FC; link?: string; }; ... 25 more ...; i18n?: { ...; }[]; }'.ts(2353)

but I am getting this error

**Comment by arno-fukuda** [comment]
I believe you might still be on Nextra version 2?

Can you check in your `package.json`?

**Comment by prernasyan** [comment]
`  "nextra": "2.13.4",`
  
  I am using this version

**Comment by arno-fukuda** [comment]
The shared steps are for version 3.

**Comment by prernasyan** [comment]
`"nextra": "3.2.5",`

updated to the latest version still getting the same error

**Comment by prernasyan** [comment]
Thank you so much; I am able to resolve the issue.
