### ISSUE TITLE
withObserver doesn't work correctly and causes incorrect scroll highlighting.

### ISSUE THREAD

**Issue by cmunns** [shuding/nextra#381]
All markdown headers are being added instead of just the H2s.

<img width="2001" alt="Screen Shot 2022-02-24 at 3 11 45 PM" src="https://user-images.githubusercontent.com/1189523/155623606-34771632-ffaf-4c4a-bdd0-2913e8ec4599.png">

https://github.com/shuding/nextra/blob/1adf1c7db8ecdda2c6e1f0a2079ea139d76e09ea/packages/nextra-theme-docs/src/misc/theme.js#L59-L72

**Comment by dimaMachina** [comment]
closing since this issue seemss related to Nextra v1, feel free to reply if you still need help
