### ISSUE TITLE
Logo not showing up on smaller screens because of hidden style

### ISSUE THREAD

**Issue by akcanakci** [shuding/nextra#382]
in theme.config.js
```
logo: (
    <>
      <span className="mr-2 font-extrabold hidden md:inline">Nextra</span>
      <span className="text-gray-600 font-normal hidden md:inline">
        The Next.js Static Site Generator
      </span>
    </>
  ),
```

Span class of "hidden" (Line 7 and 8 to be exact) hides the site name and slogan at small screens (Below 768px). It should be removed from the first line at least. I guess having the site name or something up there would be nice for people.

**Comment by B2o5T** [comment]
It was fixed
