### ISSUE TITLE
Return Markdown elements from a react component that can be recognized and added to TOC

### ISSUE THREAD

**Issue by fanyf22** [shuding/nextra#3824]
I want to write a React component that returns things including a `##` title.

```mdx
const Header = ({ title }) => {
  return <h2>{title}</h2>
}

<Header title="This is the title" />
```

But currently, this will only render to

```markdown
<h2>This is the title</h2>
```

instead of

```markdown
## This is the title
```

There is a difference, since Nextra adds styles to `##` automatically, and also shows the titles in TOC, while `<h2>` tags won't be recognized.

How can I achieve the same effect as if I'm using `##`?

**Comment by dimaMachina** [comment]
I didn't get what do you want to achieve, add more details to your code example

**Comment by fanyf22** [comment]
> I didn't get what do you want to achieve, add more details to your code example

What I want to do is to write the MDX like:

```markdown
<Header title="This is the title" />
```

But currently, this will only render to

```markdown
<h2>This is the title</h2>
```

instead of

```markdown
## This is the title
```

How can I achieve the same effect as if I'm using `##`?

**Comment by dimaMachina** [comment]
do you want to have `<h2>` styles in your `<Header>`?

**Comment by fanyf22** [comment]
> do you want to have `<h2>` styles in your `<Header>`?

It would be better if I can apply `<h2>` styles of Nextra theme. But the main problem is that TOC does not include the title.

**Comment by dimaMachina** [comment]
only headings with markdown syntax are included in toc

**Comment by fanyf22** [comment]
> only headings with markdown syntax are included in toc

Is there a way to control the TOC manually?

**Comment by dimaMachina** [comment]
write your own, `rehype`, `remark`, `recma` plugin and do whatever you want with `useTOC` function
