### ISSUE TITLE
Different website layouts and design even with same versions.

### ISSUE THREAD

**Issue by janaSunrise** [shuding/nextra#385]
Sorry for this question being off-topic, and not related to this project/repo.

I noticed that the example docs theme is really different than what I have (Mine is the same as the nextra's official docs site in the `core` branch), and I'm confused how is it happening. I checked our configs (Almost same), Package versions (The same), and such things. But, I can't help notice it's really different.

Here's an attached screenshot of my docs site:

![Screenshot from 2022-03-01 17-55-03](https://user-images.githubusercontent.com/56873669/156168770-0eb03f08-929e-4211-a334-8da26acdd19a.png)

And, It's really different from the alpha docs site.

For debugging info, Here's info on the project:

Package manager used: `npm`

Package.json:
```json
"dependencies": {
    "next": "12.0.10",
    "nextra": "^2.0.0-alpha.24",
    "nextra-theme-docs": "^2.0.0-alpha.23",
    "react": "17.0.2",
    "react-dom": "17.0.2"
  },
  "devDependencies": {
    "autoprefixer": "^10.4.2",
    "eslint": "8.8.0",
    "eslint-config-next": "12.0.10",
    "postcss": "^8.4.6",
    "prettier": "^2.5.1",
    "tailwindcss": "^3.0.18"
  }
```

Next config:
```js
const withNextra = require('nextra')({
  // Theme
  theme: 'nextra-theme-docs',

  // Config location
  themeConfig: './theme.config.js',

  // Auto image import
  unstable_staticImage: true,

  // Content dump
  unstable_contentDump: true,

  // Stork search
  unstable_stork: false
});

const config = {
  reactStrictMode: true
};

module.exports = withNextra(config);
```

Let me know if anything is needed! Would be amazing if you can look into why the sites are so different - I really love the new layout and design, and that's why I want to get it too.

**Comment by janaSunrise** [comment]
Hi - can you check this pls @shuding

**Comment by janaSunrise** [comment]
You were right! Weirdly its `beta.5`. Here's the snippet from `package-lock`:

```json
"node_modules/nextra-theme-docs": {
      "version": "2.0.0-beta.5",
      "resolved": "https://registry.npmjs.org/nextra-theme-docs/-/nextra-theme-docs-2.0.0-beta.5.tgz",
      "integrity": "sha512-VUNdcyTBK5REuQNocWOeXaFY88RyZq9wsym4So0+6yQVJSpf8eYCLHKozQOC2v6cyqBP5zGFcaFq6rDRp3Zt9w==",
      "dependencies": {
        "@mdx-js/react": "^2.0.0-rc.2",
        "@reach/skip-nav": "^0.11.2",
        "classnames": "^2.2.6",
        "focus-visible": "^5.1.0",
        "github-slugger": "^1.3.0",
        "grapheme-splitter": "^1.0.4",
        "intersection-observer": "^0.12.0",
        "match-sorter": "^4.2.0",
        "next-themes": "^0.0.8",
        "parse-git-url": "^1.0.1",
        "prism-react-renderer": "^1.1.1",
        "react-innertext": "^1.1.5",
        "title": "^3.4.2"
      },
      "peerDependencies": {
        "next": ">=9.5.3",
        "react": ">=16.13.1",
        "react-dom": ">=16.13.1"
      }
    },
```

**Comment by andremalveira** [comment]
This layout is available in alpha version, you can change like nextra and nextra-theme versions to: 
```json
"dependencies": {

  "nextra": "2.0.0-alpha.29",
  "nextra-theme-docs": "2.0.0-alpha.29",

}
````
then delete node_modules folder and install dependencies again by running `yarn` .

**Comment by janaSunrise** [comment]
This worked!! Thank you so much! 😁
