### ISSUE TITLE
Can't seem to use < symbol anywhere without getting an unhandled rejection 

### ISSUE THREAD

**Issue by Ashtonian** [shuding/nextra#386]
Example.md

```
<= 5 or <1
```

**Comment by shuding** [comment]
Unfortunately this is by design in MDX, you can test it here: https://mdxjs.com/playground.

A workaround is to explicitly make it a string:

```
{'<= 5 or <1'}
```

**Comment by Ashtonian** [comment]
Ahh that makes sense. I'm using 2.0x beta with regular.md files.

**Comment by wooorm** [comment]
@shuding Note: mdx 2 can differentiate between `.md` files for markdown and `.mdx` files for MDX.
If that’s not happening here, then that’s probably something you can add to nextra?

**Comment by Ashtonian** [comment]
> 
> (and perhaps the unhandled rejection can also be cleaner?)

This would be very beneficial imo. This took a very long time to debug simply because it kept crashing.
