### ISSUE TITLE
Why does the  Nextra happen an error If I add the_meat.json in the not Top level folder.

### ISSUE THREAD

**Issue by SevenOfPaul** [shuding/nextra#3860]
_meat in Top folder
![d5df56e4bc17ffe75a9641eafa9ed371](https://github.com/user-attachments/assets/1d675f10-20b5-436d-b2e6-7ad41c1711b3)
the video of demo
https://github.com/user-attachments/assets/b11c82d5-f763-47f3-8eda-a5587d5b9a77

**Comment by dimaMachina** [comment]
seems you use nextra 2, support of nextra 2 is removed, update to nextra 3 where support of _meta.json files was removed more info in https://the-guild.dev/blog/nextra-3

**Comment by SevenOfPaul** [comment]
thanks,good luck.
