### ISSUE TITLE
Ability to include code snippets from files

### ISSUE THREAD

**Issue by jcbhmr** [shuding/nextra#3871]
**Is your feature request related to a problem? Please describe.** A clear and
concise description of what the problem is. Ex. I'm always frustrated when [...]

I have a bunch of examples that I would like to invoke as separate files (`go run ./pages/hello-world.go`) to test them and to allow anyone to open a new GitHub Codespace and immediately `go run ./......whatever` as well as include in documentation (in the `./pages/hello-world.mdx` page). I need them to be _real files_ because of external tooling.

**Describe the solution you'd like** A clear and concise description of what you
want to happen.

I would like something making to VitePress' https://vitepress.dev/guide/markdown#import-code-snippets feature:

```md
Here's an example "Hello, World!" program in Go:

<<< ./hello-world.go

You can run this example ... more prose
```

A pure MDX solution would probably work better with Nextra's focus on MDX and React stuff. I don't know how you'd do it but something like:

```mdx
Here's an example "Hello, World!" program in Go:

<CodeImport path="./hello-world.go" />

You can run this example ... more prose
```

**Describe alternatives you've considered** A clear and concise description of
any alternative solutions or features you've considered.

An alternative is to do something with static import analysis like:

```mdx
Here's an example "Hello, World!" program in Go:

import helloWorldGo from "./hello-world.go?text" // or whatever it is to get it as a string

<Code code={helloWorldGo} />

You can run this example ... more prose
```

**Additional context** Add any other context or screenshots about the feature
request here.

**Comment by dimaMachina** [comment]
https://github.com/shuding/nextra/issues/2568#issuecomment-1839578696

**Comment by jcbhmr** [comment]
Thank you. This solves my problem. I would recommend including this solution as a tip callout or something in the documentation.

**Comment by dimaMachina** [comment]
Feel free to send a pr
