### ISSUE TITLE
Edit in Github link is a little dumb

### ISSUE THREAD

**Issue by davesnx** [shuding/nextra#39]
It's generated with

```js
const filepath = route.slice(0, route.lastIndexOf('/') + 1)
const filepathWithName = filepath + filename

(config.siteGithub || config.github) + '/tree/master/pages' + filepathWithName
```

Which means there are 2 issues, don't respect the main-branch from github and doesn't respect the possibility to have the docs from another folder.

It would be a good idea to add a field inside config to represent that or have a way to know where's the git folder. 

Let me know what fits best and I can try to have some time to fix it!

Thanks

**Comment by shuding** [comment]
100% agreed! An ideal solution is to also remove the name "GitHub" from configurations and make it also available for GitLab and Bitbucket in the future, so I'd like to use the following configurations instead (w/ a new major release):

```js
"projectGit": "https://github.com/owner/project",
"docsGit": "https://github.com/owner/docs",
"docsBranch": "main", // defaults to `master`
"docsPath": "/docs" // defaults to `/`
```

Is there anything missing?
