### ISSUE TITLE
Support for showing a banner at the top

### ISSUE THREAD

**Issue by shuding** [shuding/nextra#391]

**Comment by mannybecerra** [comment]
Hey @shuding, are there more requirements that can be shared around this `banner at the top` request? It initially sparks my interest and would love to help out here once more details are known.

**Comment by shuding** [comment]
@mannybecerra Thanks for the quick response! We'd like to have something like this: https://turborepo.org, but actually I'm not sure about the design yet — we can work on adding the functionality first for sure and I'll tweak the details.

API should look like this:

```
banner: {
  content: () => element, // just like the "logo" option
  closable?: boolean,     // store the state in localStorage
  key?: string            // key for the localStorage item
}
```

Some thoughts:
- https://turborepo.org like the style in the light theme, but too much contrast in the dark mode
- https://vercel.com/home feels better
- https://tailwindcss.com/docs/installation inside the navbar, but tricky when there isn't much space left
- https://reactjs.org

**Comment by shuding** [comment]
Hey @mannybecerra, I'll take this if you are not working on it at the moment. :) 
I have some bandwidth to ship 2.0 and this is the last feature missing there.

**Comment by mannybecerra** [comment]
> Hey @mannybecerra, I'll take this if you are not working on it at the moment. :) 
> 
> I have some bandwidth to ship 2.0 and this is the last feature missing there.

Hey @shuding, Sorry for the delay, busy times at the day gig. But, yes - go for it, all yours! Thx 🙌🏼
