### ISSUE TITLE
LaTeX support

### ISSUE THREAD

**Issue by bryanhpchiang** [shuding/nextra#416]
Planning on using nextra with the docs template for a new project, and I was wondering:

- Is it possible to get LaTeX support inside the docs?
- The font seems to have changed. Would it be possible to get back to the old one (Inter)? 

Thanks!

**Comment by shuding** [comment]
For Inter, I think we can add a "googleFonts" option for better customization. The reason of using the system font by default is to avoid the initial blank screen.

For LaTeX, this is definitely a good thing to have. We can look into MDX plugin for KaTeX so we can support `$ ... $` and `$$ ... $$`.

**Comment by bryanhpchiang** [comment]
Sounds great. By the way, what's the VSCode theme / font used in the screenshot here: https://github.com/shuding/nextra/blob/master/public/demo.png? Thanks!

**Comment by shuding** [comment]
IIRC it's https://marketplace.visualstudio.com/items?itemName=kettanaito.nako.

**Comment by jeffreydyao** [comment]
@bryanhpchiang Hi! I've just done it for a site for a CS revision session at my university - it is possible. The relevant issue is #290. Here's what you need to do:

1. Install the following versions of `remark-math` and `rehype-katex`: 
```bash
yarn add rehype-katex@5.0.0 remark-math@4.0.0
````
2. In `next.config.js`:
```js
const remarkMath = require('remark-math')
const rehypeKatex = require('rehype-katex')

const withNextra = require('nextra')({
  theme: 'nextra-theme-docs',
  themeConfig: './theme.config.js',
  // ...
  mdxOptions: {
    remarkPlugins: [remarkMath],
    rehypePlugins: [rehypeKatex],
  },
})

module.exports = withNextra()
````
3. Create `/pages/_document.js` and add the KaTeX CSS so that equations render properly:
```js
import { Html, Head, Main, NextScript } from 'next/document'

export default function Document () {
  return (
    <Html>
      <Head>
        <link
          rel='stylesheet'
          href='https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.css'
          integrity='sha384-KiWOvVjnN8qwAZbuQyWDIbfCLFhLXNETzBQjA/92pIowpC0d2O3nppDGQVgwd2nB'
          crossorigin='anonymous'
        />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
````
This is successful against the current `core` branch.
