### ISSUE TITLE
Sitemap?

### ISSUE THREAD

**Issue by Suniron** [shuding/nextra#419]
Hey there!

Is it possible to generate a sitemap for a Nextra based project?

Thanks! :-)

**Comment by rgoomar** [comment]
@Suniron I was able to do so with adding the [next-sitemap](https://www.npmjs.com/package/next-sitemap) package and following the instructions in their docs. It was pretty simple and it generates a proper sitemap.

**Comment by Suniron** [comment]
Yes, sorry for this issue. In fact, it was really easy..

**Comment by shuding** [comment]
Still an enhancement that Nextra can probably have. Maybe we can look into including next-sitemap by default :)

**Comment by alecpetrosky** [comment]
Using nextra with next-sitemap and i18n generates sitemap for default language only.

**Comment by B2o5T** [comment]
I don't see the future for this issue, `next-sitemap` should be executed after `next build` command and the physical `next-sitemap` config should be present.

Unfortunately but there is no way of including/executing `next-sitemap` by default.
