### ISSUE TITLE
h2 tags are not generating anchor links

### ISSUE THREAD

**Issue by arishoham** [shuding/nextra#429]
I am using extra v 1.1.0, and according to the docs, h2 tags should generate anchor links, and be added to the sidebar automatically. Not Sure what other context is needed, but neither of these things hare happening.

Thanks!

**Comment by andremalveira** [comment]
Try using these versions, or the latest versions you can find at [core](https://github.com/shuding/nextra/tree/core) 
```json
"dependencies": {

  "nextra": "2.0.0-alpha.29",
  "nextra-theme-docs": "2.0.0-alpha.29",

}
````
then delete node_modules folder and install dependencies again by running `yarn` .

**Comment by FACOLOMBANI** [comment]
This version fixes anchor issue, but <Bleed> has overflow on menu.

**Comment by B2o5T** [comment]
@FACOLOMBANI do you have still `overflow on menu`? Can you send a screenshot?
