### ISSUE TITLE
Remarkplugins not recognized in @beta

### ISSUE THREAD

**Issue by pedrosousa13** [shuding/nextra#437]
If I update to beta to make the page titles work (not working in stable versions), it doesn't seem to load any of my mdxOptions.

The plugin worked in stable versions of `nextra` and `nextra-theme-docs`

Here's my current code for `next.config.js`

```js
const { remarkCodeHike } = require("@code-hike/mdx")
const theme = require("shiki/themes/material-palenight.json")

const withNextra = require('nextra')({
  theme: 'nextra-theme-docs',
  themeConfig: './theme.config.js',
  mdxOptions: {
    remarkPlugins: [[remarkCodeHike, { theme }]],
  },
  // optional: add `unstable_staticImage: true` to enable Nextra's auto image import
})
module.exports = withNextra()

```

Should I load them differently in @beta versions?

**Comment by B2o5T** [comment]
@pedrosousa13 Do you still have this problem?

**Comment by pedrosousa13** [comment]
@B2o5T It seems to be gone in latest beta. I will close this Issue.
