### ISSUE TITLE
Enable customisation of back button in posts 

### ISSUE THREAD

**Issue by mohsinht** [shuding/nextra#441]
The back button in nextra-blog-theme is not customisable. The code in core of nextra's blog theme is fairly simple.

Code here: https://github.com/shuding/nextra/blob/core/packages/nextra-theme-blog/src/meta.tsx

Allow adding custom code for back button or changing at least the content of it.

```
      {back ? (
        <Link href={back}>
          <a className="meta-back">Back</a>
        </Link>
      ) : null}
```

**Comment by B2o5T** [comment]
Duplicate https://github.com/shuding/nextra/issues/182
