### ISSUE TITLE
Syntax Highlighting For Blog Theme

### ISSUE THREAD

**Issue by jtfell** [shuding/nextra#448]
I can't figure out how to turn on syntax highlighting for code snippets when using the blog theme

**Comment by rgoomar** [comment]
@jtfell try using the GitHub-like language specifying syntax from any ones of the list from here - https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js

So like 
```
```lang-name
```

**Comment by jtfell** [comment]
I think my project is setup correctly, I can get syntax highlighting to work if I switch to the docs theme. When I change the theme to blog, it is no longer highlighted

**Comment by mayacoda** [comment]
[According to the documentation](https://nextra.vercel.app/advanced/code-highlighting#:~:text=nextra%2Dtheme%2Ddocs%20uses%20Prism%20and%20prism%2Dreact%2Drenderer%20to%20highlight%20the%20code%20blocks.), it seems that only the docs theme supports syntax highlighting.

Is there any guide for setting up the same for the blog theme as well?

**Comment by B2o5T** [comment]
@mayacoda works properly on blog also, take a look at blog example and of this post file https://github.com/shuding/nextra/blob/core/examples/blog/pages/posts/code-blocks.mdx
