### ISSUE TITLE
Code Block without language option

### ISSUE THREAD

**Issue by tamagoez** [shuding/nextra#450]
`[a={b=b}]` will cause error.
2nd `b` will recognize as command.
I tried MDX Playground, but it seems working fine.
![image](https://user-images.githubusercontent.com/87574268/165110856-13f75727-20db-4c11-9726-84d1b76dded5.png)
![image](https://user-images.githubusercontent.com/87574268/165110937-e64e502d-2c0e-4770-a8ef-7a542bf36971.png)

**Comment by shuding** [comment]
Hi @tamagoez did you figure out why it happens?

**Comment by tamagoez** [comment]
When I add `markdown` after ```, it worked.
When I use code block without any language, it will not show any code blocks, but plain text.
`[a={b=b}]` seems parsed as `b=b`(Javascript).

**Comment by shuding** [comment]
Thanks for the details, will keep this open and we can dig deeper in the future.

**Comment by numToStr** [comment]
FYI, Code blocks without language is working for me in blog-theme `v2.0.0-beta.13`

**Comment by B2o5T** [comment]
closing since now it's works fine 
<img width="237" alt="image" src="https://user-images.githubusercontent.com/7361780/185751508-cf0a93ec-e34c-43a0-a5d3-253bbc127615.png">
