### ISSUE TITLE
Issue with tab title

### ISSUE THREAD

**Issue by chilikasha** [shuding/nextra#452]
Hi,

Is it possible to fix how the tab title is displayed while the page is being loaded?
Thank you.
```
"nextra": "^1.1.0",
"nextra-theme-docs": "^1.2.6",
```

`titleSuffix: ' – Tiny tools',`

https://user-images.githubusercontent.com/3147449/165707080-b71b24ec-f503-478d-b0ae-5a782fb964ca.mov

<img width="320" alt="Screenshot 2022-04-28 at 10 02 25" src="https://user-images.githubusercontent.com/3147449/165707087-da64d061-ac4a-4750-b11b-feb6fa8f1310.png">

**Comment by shuding** [comment]
Could you try installing `next@canary`? This is fixed together with https://github.com/vercel/next.js/issues/35870.
