### ISSUE TITLE
Consume syntax highlighter as a component

### ISSUE THREAD

**Issue by alii** [shuding/nextra#453]
I would like to build a multi language syntax highlighter using `nextra-theme-docs@alpha`. What would be the best way to consume the highlighter in my own component?

I saw https://github.com/shuding/nextra/issues/262 mentioned that either Shiki or Code Hike were being used right now but wasn't able to figure out which one it was or how to use it 😄 

Thanks :) :heart:

**Comment by B2o5T** [comment]
Hi there! Do you still need help? If you need extend languages for code blocks, use the follow option
https://github.com/shuding/nextra/blob/6c58a89b067d5bafc04178390dab605059292344/packages/nextra/src/types.ts#L78
