### ISSUE TITLE
[Bug] NX / Monorepo : Missmatch using `rootDir`, NextJS can't find  `pages` folder

### ISSUE THREAD

**Issue by Thisisjuke** [shuding/nextra#454]
Hello, 

I have seen this thread : Not working inside a monorepo https://github.com/shuding/nextra/issues/151
The fix is working well for dev purposes !

However, lot of monorepos intruce build enhancement functionalities like : 
- https://nx.dev/next/overview
- https://nx.dev/packages/next/executors/build

Nextra is working well with NX except for path resolution at build time : there is a miss-match / side-effect with relative paths. 

> tsconfig.json
```.json
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "rootDir": ".",
    //...
  },
  "include": [...],
  "exclude": [...]
}
```
```shell
info  - Checking validity of types  
(node:8515) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir '/home/projects/workspace/pages'
```
Where the real path should be : ` "home/projects/workspace/apps/nextra-doc/pages")

So i add the right `rootDir`:
> tsconfig.json
```.json
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "rootDir": "./apps/nextra-doc",
    //...
  },
  "include": [...],
  "exclude": [...]
}
```
```shell
Failed to compile.
Type error: File '/home/projects/workspace/apps/nextra-doc/next.config.js' is not under 'rootDir' '/home/projects/workspace/apps/nextra-doc/apps/nextra-doc'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Root file specified for compilation
```
The path in the tsconfig.json is applied mandatory to build, but when used, its applied 2 times.

These relative paths and other things are handle by : 
```js
module.exports = withNx(nextConfig)
```

The best solution is that you let the possibility to use `withNx` with `withNextra` : 
You let NX generate the appropriate NextConfig, and then, you appy your own loader + mdx parser 

As this a chance to be fixed a day or not at all (outside the scope or else) ?

**I can provide a repository with all of this setup if you want to test or fix this issue !**

Thx for your time :v: !

**Comment by Thisisjuke** [comment]
Hello there,

I have fixed some issues with `next-compose-plugins` and the following setup :
```
const withNx = require('@nrwl/next/plugins/with-nx')
const withPlugins = require('next-compose-plugins');

const withNextra = require('nextra')({
  theme: 'nextra-theme-docs',
  themeConfig: './theme.config.js',
  unstable_staticImage: true,
})

const nextConfig = {
  nx: {
    svgr: true,
  },
  experimental: {
    externalDir: true,
  },
}

module.exports = withPlugins([
  withNextra,
  withNx,
], nextConfig);
```

The build is not working fully at the moment but it resolves some error with module.css setup and other things.

I will come back with more information if I fix my buid.
:v:

**Comment by Thisisjuke** [comment]
Hello again,

I have problems with inline SVG, I can't use :
```
  nx: {
    svgr: true,
  },
```
The generated webpack seems to ignore `.svg`. It's related to `SWC compiler`. 

## Work around

The solution that I found is to create a .babelrc inside the Nextra doc folder. 
https://nextjs.org/docs/advanced-features/customizing-babel-config

 ### __WARNING__ : 
It disables SWC compiler and enable Webpack compiler. You will lose all the performance and benefits you have with SWC. I really don't care because I don't have many pages and don't need performance or build optimization in my Nextra documentation website.
https://nextjs.org/docs/advanced-features/compiler#why-swc

> `.babelrc `
```
{
  "presets": ["@nrwl/next/babel"],
  "plugins": ["inline-react-svg"]
}
```

Can't Nextra handle inline SVG natively ?

**Comment by jaqua** [comment]
@Thisisjuke How did you solve the issue? Is it possible to use nextra in a NX monorepo? I tried get this working for quite a long time... without success

**Comment by Thisisjuke** [comment]
Hey @jaqua, it was working using the fix here: `https://github.com/shuding/nextra/issues/454#issuecomment-1119628276`.
But it was not using new Nextra v2.0. 

One additional tip is that you have to **NOT** have a `rootDir` value inside your in `tsconfig.json` file (might not be the case in recent version of Nextra / NX). 

What I have done during the couple last months was swithing to turborepo to have splited build flows because my stack is centered around the UI package and not the Nextra Doc application.

Also, check about this option inside `next.config.ts`:
```
experimental: {transpilePackages: ['@package']},
```
https://beta.nextjs.org/docs/api-reference/next.config.js#transpilepackages

**Comment by Brian-McBride** [comment]
Hrm, no. This doesn't seem to work in a Nx Monorepo. 

```
Error: > Couldn't find a `pages` directory. Please create one under the project root
```

**Comment by amaralc** [comment]
> Hrm, no. This doesn't seem to work in a Nx Monorepo.
> 
> ```
> Error: > Couldn't find a `pages` directory. Please create one under the project root
> ```

Same thing here.

**Comment by B2o5T** [comment]
Please create a reproduction repo

**Comment by StringKe** [comment]
@B2o5T 

repo: https://github.com/StringKe/with-nextra-nx

```
with-nextra-nx on  main via ⬢ v18.16.0 took 3.9s
➜ nx run docs:serve --verbose

> nx run docs:serve:development

- error Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error

 >  NX   > Couldn't find a `pages` directory. Please create one under the project root


Error: > Couldn't find a `pages` directory. Please create one under the project root
    at findPagesDir (/Users/chen/Downloads/with-nextra-nx/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/lib/find-pages-dir.js:104:19)
    at findPagesDirectory (/Users/chen/Downloads/with-nextra-nx/node_modules/.pnpm/nextra@2.6.0_next@13.4.1_react-dom@18.2.0_react@18.2.0/node_modules/nextra/dist/index.js:157:15)
    at Object.<anonymous> (/Users/chen/Downloads/with-nextra-nx/node_modules/.pnpm/nextra@2.6.0_next@13.4.1_react-dom@18.2.0_react@18.2.0/node_modules/nextra/dist/index.js:161:53)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/chen/Downloads/with-nextra-nx/apps/docs/next.config.js:5:20)

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target serve for project docs failed

   Failed tasks:

   - docs:serve:development

   Hint: run the command with --verbose for more details.

```

https://github.com/shuding/nextra/blob/main/packages/nextra/src/file-system.ts#L10

maybe try passing the path obtained by the `__dirname` API to nextra in `next.config.js`

**Comment by jdecastroc** [comment]
Experiencing the same with:
nx: 15.6.3
nextra: 2.10.0
next: 13.4.1

Any update on this issue?

**Comment by B2o5T** [comment]
@StringKe seems there are no issues on latest nx

I updated the following deps and `process.cwd()` resolves to right value

```json
    "@nx/js": "16.7.2",
    "@nx/linter": "16.7.2",
    "@nx/next": "^16.7.2",
    "@nx/react": "16.7.2",
    "@nx/workspace": "16.7.2",
```

**Comment by ihusemann** [comment]
I'm still seeing this issue when running the production build locally - both with Nextra v2 and v3.  [Repro here](https://github.com/ihusemann/nx-nextra) (uses Nextra v3). 

After running: 

```bash
npx nx build docs 

npx nx run docs:serve:production
```

I get error:

```
Error: > Couldn't find a `pages` directory. Please create one under the project root
    at Module.findPagesDir (/Users/ihusemann/repos/nx-nextra/node_modules/next/dist/lib/find-pages-dir.js:104:19)
    at findPagesDirectory (file:///Users/ihusemann/repos/nx-nextra/node_modules/nextra/dist/server/file-system.js:4:28)
    at file:///Users/ihusemann/repos/nx-nextra/node_modules/nextra/dist/server/file-system.js:10:19
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
Node.js v18.17.1
```

Anybody experiencing something similar or found a solution?  Everything runs fine with Next.js without Nextra. 

Using versions: 

```json
"@nx/js": "17.2.8",
"@nx/next": "17.2.8",
"@nx/react": "17.2.8",
"@nx/workspace": "17.2.8",
"nextra": "^3.0.0-alpha.10",
"nextra-theme-docs": "^3.0.0-alpha.10",
"next": "13.4.4"
```

**Comment by marcosluizfp** [comment]
I just did the following workaround on the repo root, and it worked for me:

```shell
ln -s apps/docs/pages pages
```

For sure, this is far from the best, but it works! Hope a final solution can be done soon on either nextra or nextjs.

See below my next.config.js

```js
//@ts-check

// eslint-disable-next-line @typescript-eslint/no-var-requires
const { composePlugins, withNx } = require('@nx/next');

const withNextra = require('nextra')({
  theme: 'nextra-theme-docs',
  themeConfig: './theme.config.jsx',
});

/**
 * @type {import('@nx/next/plugins/with-nx').WithNxOptions}
 **/
const nextConfig = {
  nx: {
    // Set this to true if you would like to use SVGR
    // See: https://github.com/gregberge/svgr
    svgr: false,
  },
  images: {
    unoptimized: true,
  },
};

const plugins = [
  // Add more Next.js plugins to this list if needed.
  withNextra,
  withNx,
];

module.exports = composePlugins(...plugins)(nextConfig);
```

**Comment by orthizar** [comment]
I had the same error and I used this workaround at the top of my next.config.js:
```ts
if (process.cwd() !== __dirname) {
  process.chdir(__dirname);
}
```
