### ISSUE TITLE
Syntax highlight behavior is different between versions

### ISSUE THREAD

**Issue by wtfiscrq** [shuding/nextra#461]
Hey 👋🏼

I'm having some issues to get syntax highlighting working properly. I've different behaviors with the stable, alpha and beta versions of Nextra.

For brevity purposes, I'm importing `prismjs/components/prism-rego` in the `pages/_app.jsx` and this is the `.mdx` file that's causing issues:

    Some code sample:

    ```rego
    package repository
    ```

### With `1.1.0` (current stable ATTOW):

<details>
<summary>

🔽 Everything compiles correctly but I don't get syntax highlighting (click to expand):

</summary>

![Screen Shot 2022-05-09 at 11 05 56 PM](https://user-images.githubusercontent.com/8532541/167506444-7f444389-6493-48ca-b371-2ef6806ea76f.png)

</details>

### With `2.0.0-alpha.50` (current alpha ATTOW):

<details>
<summary>

🔽 Doesn't even compile (click to expand):

</summary>

![Screen Shot 2022-05-09 at 11 04 34 PM](https://user-images.githubusercontent.com/8532541/167506841-616f46d8-58ba-441c-9c8e-87fcf2d67db9.png)

</details>

### With `2.0.0-beta.5` (current beta ATTOW):

<details>
<summary>

🔽 Compiles and works as expected (with `next dev`), but `next build` stops working* (click to expand):

</summary>

![Screen Shot 2022-05-09 at 11 11 49 PM](https://user-images.githubusercontent.com/8532541/167507158-a2d8a460-4ff6-479c-bff5-6a8d6e7a87b5.png)

</details>

**For reference, I'm on:**

```bash
$ node -v
v16.14.2

$ npm -v       
8.5.5
```

<details>
<summary>

__*__ The issue I have when upgrading to the `beta` versions is (click to expand):

</summary>

![Screen Shot 2022-05-09 at 11 14 32 PM](https://user-images.githubusercontent.com/8532541/167507444-63d80137-0773-4021-a4a5-5254ad288222.png)

</details>

Please, let me know if you need any further details.

Thanks in advance!

**Comment by crqra** [comment]
The issue with the errors using `npm run build` look to be related with something inside the `pages/features/mdx.mdx` file. I'm still trying to figure out what exactly. FYI I've generated the site using the template in Vercel.

**Comment by B2o5T** [comment]
Closed since issue related to nextra 1
