### ISSUE TITLE
floatTOC doesn't work when set to true

### ISSUE THREAD

**Issue by tomgenoni** [shuding/nextra#463]
Following the instructions in https://github.com/shuding/nextra/blob/master/pages/get-started.mdx I am not able to see the floating TOC using `floatTOC: true` in `theme.config.js`. I can tell it's doing something because the headings no longer appear in the left nav (see Configuration page screenshot) but they are not showing up in the right column.

<img width="1558" alt="Screen Shot 2022-05-15 at 9 39 13 PM" src="https://user-images.githubusercontent.com/1171072/168520890-5dd76391-4b1c-4fbd-9237-63d5a45b0ee7.png">

Anyone know how to fix this?

Also note the syntax highlighting is not working either but that's been captured in another ticket.

**Comment by shuding** [comment]
This feature is added in 2.0, which is currently in alpha still. You can check the code of [vercel/swr-site](https://github.com/vercel/swr-site) to see how it can be enabled.
