### ISSUE TITLE
Auto line breaked when inserting images

### ISSUE THREAD

**Issue by Kiotlin** [shuding/nextra#465]
I try to use ```![]()``` to insert several images into the same line.
Here is the effert that I expect:
> There are 3 images here.  ![Website](https://img.shields.io/website?up_message=up&url=https%3A%2F%2Fwww.google.com) ![Website](https://img.shields.io/website?up_message=up&url=https%3A%2F%2Fwww.google.com) ![Website](https://img.shields.io/website?up_message=up&url=https%3A%2F%2Fwww.google.com) Website is up.

Here is the effert what I got in reality:
![image](https://user-images.githubusercontent.com/21698963/169646399-b10b6e2e-1e3d-45b2-adac-53633ee41990.png)

I wonder that if the rendering result is just designed like this or is it possible for me to config it? 
Looking forward to your answers, thanks!

**Comment by B2o5T** [comment]
Do you steel need help ? try it like this 
https://github.com/shuding/nextra/blob/2682cab124dacbd3ffeb19dc492cd1704a0601f8/examples/swr-site/pages/index.en-US.mdx?plain=1#L110-L114
