### ISSUE TITLE
Nextra Layout is broken or not showing

### ISSUE THREAD

**Issue by Mikeultron** [shuding/nextra#470]
So i followed this [tutorial](https://www.youtube.com/watch?v=a_2vXCeW21I&ab_channel=LearntocodewithJames) on youtube to setup Nextra. I followed the steps, but our result is completely different.

### This is my result
![Nextra](https://user-images.githubusercontent.com/56322741/170072706-8490d0db-83cd-42b0-9880-e60e26e14abc.png)

### My folder structure
![Nextra-structure](https://user-images.githubusercontent.com/56322741/170073001-b688e66c-71db-46e9-9ad0-e027eb8d1a94.png)

### My package.json
![Nextra-package](https://user-images.githubusercontent.com/56322741/170073189-b7c1a9b8-e288-4c58-8caf-4bb9efdb8a92.png)

### My next.config.js
![Nextra-config](https://user-images.githubusercontent.com/56322741/170073315-5143f83c-7bfe-4441-89d5-8af411276f87.png)

### My theme.config.js
![Nextra-theme](https://user-images.githubusercontent.com/56322741/170073489-9da0c090-9222-438a-ad8e-db805e63b9e5.png)

### My _app.js
![App](https://user-images.githubusercontent.com/56322741/170073590-367bbf48-97fe-4aa7-93e1-fecad4b3ab6b.png)

Is it because of packages version?

## Edit

- I tried using the same package version but still not working
- (Work) I changed the .md file to .mdx and it works fine. This is kinda weird even though it works since the docs said we could use both .md or .mdx

**Comment by zunkelty** [comment]
Yes, same issue for me. I'm using version `2.0.0-alpha.48`

**Comment by Mikeultron** [comment]
> Yes, same issue for me. I'm using version `2.0.0-alpha.48`

Did you use .md or .mdx? I changed it to .mdx and it works fine

**Comment by zunkelty** [comment]
> https://github.com/shuding/nextra/blob/core/examples/docs/src/pages/_app.js
> 
> for alpha version, you need to update _app.js like this

Wow, thank you **so** much! I just spent > 1 hr trying to find my mistake.
