### ISSUE TITLE
Page theme with layout:full, sidebar:false, toc:false results in horizontal page scrollbar

### ISSUE THREAD

**Issue by robbear** [shuding/nextra#474]
A page with an empty `div` (or anything) using this theme in its `meta.json` results in a page with a horizontal scrollbar.
```
"theme": {
  "layout": "full",
  "sidebar": false,
  "toc": false
}
```

Setting `sidebar: true` eliminates the scrollbar. This appears to be the case since `sidebar:false` sets the `expand` directive in `nextra-theme-docs/src/index.tsx`. My workaround is to set `sidebar:true` just to force the css state I want, but logically it feels wrong.

(Current as of core commit `f11f6d5`)

**Comment by shuding** [comment]
Thanks for reporting! I'm trying to normalize the layouts with https://github.com/shuding/nextra/pull/471, so there will be only:
- 3-column layout, where you can enable/disable sidebar/toc
- full layout, where the main content will always try to expand
- raw layout, there's no sidebar/toc at all, no upper container

Hopefully it will make things easier!
