### ISSUE TITLE
When will a new stable version be released?

### ISSUE THREAD

**Issue by lucasbaquinoo** [shuding/nextra#477]
The last stable version released from `nextra` was 6 August 2021. And from `nextra-theme-docs` was on 27 March 2021.

Any news on when the new versions will be released?

**Comment by drewlustro** [comment]
❤️

**Comment by yakushevhk** [comment]
😏

**Comment by lucasbaquinoo** [comment]
@shuding can we help you in any way?

**Comment by shuding** [comment]
Hey @lucasbaquinoo and all! I’m sorry that I couldn't get faster on this. I have been testing out 2.0 with https://github.com/vercel/swr-site for a long time. So far the design of the docs theme feels good to go, but I haven’t started to work on the docs yet. That’s the biggest blocker as far as I can see.

If anyone wants to help, a PR to upgrade the current master branch to 2.0 alpha with new docs would be deeply appreciated. Then we can work on the content together and I can update the logo, card, etc. to prepare for the stable release 👍

**Comment by lucasbaquinoo** [comment]
> Hey @lucasbaquinoo and all! I’m sorry that I couldn't get faster on this. I have been testing out 2.0 with https://github.com/vercel/swr-site for a long time. So far the design of the docs theme feels good to go, but I haven’t started to work on the docs yet. That’s the biggest blocker as far as I can see.
> 
> If anyone wants to help, a PR to upgrade the current master branch to 2.0 alpha with new docs would be deeply appreciated. Then we can work on the content together and I can update the logo, card, etc. to prepare for the stable release +1

Good. I will work on it to help you.

**Comment by lucasbaquinoo** [comment]
@shuding I updated the documentation with the latest versions of the two libraries in alpha. I've hidden the Bleed page because of the styles protruding from the side menu. Perhaps something to be seen later specifically in the library.
