### ISSUE TITLE
Apply tailwind styling only to custom components

### ISSUE THREAD

**Issue by marc-wittwer** [shuding/nextra#492]
I created a custom component in a toplevel folder `components/Card.jsx`

```
const Card = ({ title }) => {
  return (
    <>
      <div className='bg-red-500 m-4'>
        <p>{title}</p>
      </div>
    </>
  )
}

export default Card
```

I installed tailwind into my project with the instructions: https://tailwindcss.com/docs/guides/nextjs

I added the `global.css` to the `_app.js`

```
// global.css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

I added the `Card` component to my `index.mdx` file and most of the template styling was overwritten and the styles of my `Card` component were applied.

```
// index.mdx
import Card from '../components/Card'

# Start

<Card title="hello" />
```

**How can I use the [nextra-theme-docs](https://github.com/vercel/swr-site) template and add tailwind styling to my custom components?**

Thanks in advance for your input.

**Comment by zakiego** [comment]
Maybe you just need to import it, like this?

https://raw.githubusercontent.com/shuding/nextra/master/pages/index.mdx

![image](https://user-images.githubusercontent.com/78015359/176987044-7e9e221e-d94e-481f-868e-02d723a38fb7.png)

**Comment by B2o5T** [comment]
@marc-wittwer do you still have this problem? I guess you don’t need this line `@tailwind base;` since `nextra-theme-docs`/`nextra-theme-blog` already import it

**Comment by marc-wittwer** [comment]
Thanks @B2o5T 
Removing `@tailwind base;` in the `global.css` solved it. Awesome!
