### ISSUE TITLE
Cannot change projectLinkIcon

### ISSUE THREAD

**Issue by marcoderso** [shuding/nextra#494]
Hello together!

I'm pretty new to Next.js, nextra etc. so sorry if the question sounds dumb.

I am not able to change the projectLinkIcon as shown in documentation.

Here's the Part used in the theme.config.js:

![image](https://user-images.githubusercontent.com/104020027/175495761-7ab1fdab-7fd9-4f2e-af2d-7f0c05b1fc56.png)

I'm using a png as the logo which is located in public as "instagram.png"

The Project compiles just fine on vercel, however there's still the github icon in the top right :/

I'm thankful for every help! :)

**Comment by zakiego** [comment]
Hello, can I see your code?

**Comment by marcoderso** [comment]
@zakiego yes ofc!

Here's the full theme.config.js

`import Image from 'next/image'
const instagram = '/instagram.png'

export default {
  projectLinkIcon: <instagram />,
  github: 'https://instagram.com/mitmischen',
  titleSuffix: ' – Nextra',
  nextLinks: true,
  prevLinks: true,
  search: true,
  customSearch: null, // customizable, you can use algolia for example
  darkMode: true,
  footer: true,
  footerText: `MIT ${new Date().getFullYear()} © Shu Ding.`,
  logo: (
    <>
      <Image src="/SamplePic6869.png" alt="MitMischen Logo" width={85} height={45} />
      <span className="text-gray-600 font-normal hidden md:inline">
          in Halle!
      </span>
    </>
  ),
  head: (
    <>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta name="description" content="Nextra: the next docs builder" />
      <meta name="og:title" content="Nextra: the next docs builder" />
    </>
  ),
}`


and if Github doesn't show it properly -  here's a Screenshot:

![image](https://user-images.githubusercontent.com/104020027/175890482-36018d7f-304a-48d3-be39-c75fbe5f28ee.png)

I'm using a png as the logo which is located in public as "instagram.png". But it still show's the Github Logo in the top right;

![image](https://user-images.githubusercontent.com/104020027/175890765-5205fd23-119f-4b65-8aec-f8235ee1170e.png)

**Comment by zakiego** [comment]
@marcoderso 

Sorry for being slow in responding

The easiest way to use `projectLinkIcon` is to upgrade Nextra to version 2

https://nextra-projecticon.vercel.app/

![image](https://user-images.githubusercontent.com/78015359/176986823-ccc35b8c-4419-4f9e-9277-bcf4d1a004b2.png)

You can see the code here

https://github.com/zakiego/nextra-projecticon/blob/896d123bfd51ad76e71442f6d14a3c77b397e64e/theme.config.js#L3

---

To see how to upgrade to Nextra version 2 you can use this as a reference because Nextra is still in beta, and the documentation for updating it is not yet available

https://github.com/fnapi/docs/pull/9

**Comment by ejcho623** [comment]
is there a way to remove (or update) the github icon without upgrading to v2? it seems like v2 is still not quite ready

it would be great to have an option to remove (or update) the default github icon

**Comment by B2o5T** [comment]
@ejcho623 there will be no more update for v1

**Comment by ejcho623** [comment]
thanks, in that case I'd recommend updating the docs (https://nextra.vercel.app/themes/docs/configuration#projectlinkicon) to indicate that this part cannot be removed or edited to avoid confusion to others like us.

**Comment by B2o5T** [comment]
@ejcho623 feel free to update to v2 and say your feedback, I'll close this issue since it's unrelated to v2
