### ISSUE TITLE
No color on code

### ISSUE THREAD

**Issue by FACOLOMBANI** [shuding/nextra#499]
When adding a code section, there is no code in render. Here is an example with ```diff
![Screenshot 2022-07-01 at 11 52 27](https://user-images.githubusercontent.com/11721821/176872100-86ee567c-2352-410f-bd81-40932861c15a.png)

**Comment by shuding** [comment]
Are you using the docs theme or blog theme?

**Comment by FACOLOMBANI** [comment]
Theme, but this was using released or beta version. It's fixed in alpha, but bleed does not work correctly with alpha. Is there going to be a release soon?

**Comment by FranciscoMoretti** [comment]
Do you have `prism-react-renderer` in your modules? I had to run  
```
yarn add prismjs prism-react-renderer 
```

**Comment by B2o5T** [comment]
try latest beta

**Comment by dsousa12** [comment]
Already installed the packages, but don't have colors.
Any solution?
