### ISSUE TITLE
Support `experimental.newNextLinkBehavior` setting

### ISSUE THREAD

**Issue by numToStr** [shuding/nextra#500]
Next.js 12.2 introduces `experimental.newNextLinkBehavior` which removes the need to add `<a/>` tag manually inside `next/link` but it introduces 2 problems

1. Now `nextra` renders nested `<a/>` tags

   - On `type: posts`

     ![image](https://user-images.githubusercontent.com/24727447/176994228-11db31fa-445a-48e5-bb20-5f1331c07320.png)

   - On post page
     
     ![image](https://user-images.githubusercontent.com/24727447/176994455-b6206949-8123-4cde-8772-08d0864a508e.png)

2. Because of the nested structure styles are not applied correctly on post title with `type: posts`

![image](https://user-images.githubusercontent.com/24727447/176994371-0b20d5c3-ab8b-408e-a510-f8435142ca6a.png)

---

Ref: https://github.com/vercel/next.js/pull/36436

**Comment by B2o5T** [comment]
I took this challenge on my own and made support both `true` and `false`. Currently, only for `nextra-theme-docs` but after this will be merged can refactor to use the same in `nextra-theme-blog`

**Comment by numToStr** [comment]
Thanks @B2o5T! For now supporting both cases should be fine, we can later remove the old case when Next.js v13 comes out as the new link behavior will be the default in that case.

**Comment by B2o5T** [comment]
closing since blog supports both next 12/13
