### ISSUE TITLE
Cannot use Nextra within a monorepo (webpack issue)

### ISSUE THREAD

**Issue by madebydor** [shuding/nextra#505]
Hi there,
I'm trying to run Nextra within a monorepo built with lerna (which I cannot share, sadly)
This is my file structure:

```
/repo-name
    /packages
        /package-name-1
        /package-name-2
    /nextra-docs <-- this is where my nextra code is
```

Now, I'm trying to use components from `package-name-1` by installing it as a dependency in my `nextra-docs` project.
Installation works, so I use the following inside `index.mdx`:

````
import { Button } from '@repo/package-name-1';
````

But sadly, the above causes the following error:
````
./node_modules/@repo/package-name-1/src/folder/folder/index.js
Module parse failed: Unexpected token (40:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
|         return (
>             <section ref={ref}>
|                 <WrappedComponent {...props}/>
|             </section>

````

Any idea how to solve this?
I'm using a fresh install of Nextra.

**Comment by B2o5T** [comment]
Unrelated issue to nextra since you don’t install it, your webpack don’t understand jsx angle brackets, https://babeljs.io/docs/en/babel-preset-react should help
