### ISSUE TITLE
Console warning when running local website

### ISSUE THREAD

**Issue by gr-qft** [shuding/nextra#51]
I'm seeing the following warning: 

![Screen Shot 2020-12-12 at 1 22 52 AM](https://user-images.githubusercontent.com/69383359/101977222-e8a66500-3c19-11eb-8fbc-a24587551b1c.png)

This doesn't seem to affect anything but it'd be great to understand and be able to remove it.

**Comment by B2o5T** [comment]
Hi @gr-qft, Do you still have this problem? In 2 beta version
