### ISSUE TITLE
Seems to be adding `not-prose` to code blocks on the latest blog theme

### ISSUE THREAD

**Issue by markmead** [shuding/nextra#513]
Just bumped Nextra to the versions used for your personal website and it appears to be adding `not-prose` to code blocks.

Is there anyway to turn that off?

Can be seen here - https://markmead-git-update-site-markmead.vercel.app/posts/alpine-textarea-auto-grow

**Comment by markmead** [comment]
To be fair, it's an improvement with that syntax highlighting, but it has knocked out some of the `margin` CSS.

**Comment by B2o5T** [comment]
@markmead Hey 👋, why do you want to remove `not-prose`?

**Comment by markmead** [comment]
It breaks the `margin` CSS that comes with the `prose` class from Tailwind CSS. It's not a huge issue as it can be fixed with some CSS and it has a huge improvement with the syntax highlighting.
