### ISSUE TITLE
🐛 bug(nextra): Page title can be `Untitled` for several cases

### ISSUE THREAD

**Issue by B2o5T** [shuding/nextra#514]
Found unexpected behaviour when page title can be `Untitled` for the following cases

### Case 1 (2 elements h1)

```mdx
# foo
# bar
```
Expected: foo
Current: bar

### Case 2 (h1 with code)

```mdx
# `foo`
```
Expected: foo
Current: Untitled

### Case 3 (h1 with code and text)

```mdx
# `foo` bar
```
Expected: foo bar
Current: Untitled

Solution: MDX2 recommends use [`rehype-mdx-title`](https://github.com/remcohaszing/rehype-mdx-title) <https://mdxjs.com/docs/extending-mdx/#list-of-plugins>

**Comment by gw-versent** [comment]
👍 

Same here
