### ISSUE TITLE
Add TypeScript config support

### ISSUE THREAD

**Issue by NuroDev** [shuding/nextra#530]
## What

I am yet to read through the changes due in v2 so sorry if this has already been added & I am not yet aware.

It would be a nice QoL improvement if we TypeScript / MJS config was supported out of the box using something like [`unconfig`](https://github.com/antfu/unconfig) as that way we can get type definitions in our config for better intellisense & type safe support (Of not anything needed but a nice to have)

If you're interested I am happy to help contribute towards the project & put together a PR to add support for it 🙂

**Comment by B2o5T** [comment]
You can already use mjs and ts/tsx extensions for your theme.config file, just provide right path for `withNextra` function

**Comment by jjangga0214** [comment]
@NuroDev Hi!
You can modify you next.config.js by providing right path for `withNextra` function, as @B2o5T.
Hereby I left an example for the case that you might not recall what is the `withNextra` function.

**next.config.js**:
```js
const withNextra = require('nextra')({
  // themeConfig: './theme.config.js',
  themeConfig: './theme.config.tsx',
  // Other options are omitted for brevity.
})

module.exports = withNextra()
```

**Comment by NuroDev** [comment]
Thanks for all the replies.
I am aware you can just change your config extension to end in `.ts` or `.tsx` & add a JSDoc type comment but I was meaning on adding something similar to Vite where they offer a [`defineConfig`](https://vitejs.dev/config/#config-intellisense) function so you don't have to add JSDoc type comments or anything & it's typed from the getgo.

**Comment by jjangga0214** [comment]
@NuroDev I agree that's a good idea. Currently, in the `core` branch, there's no exported interface or a function.

**Comment by dsousa12** [comment]
Any one already use typescript?

**Comment by ScreamZ** [comment]
Up ? ANy typings ?

**Comment by alamenai** [comment]
Any updates!

**Comment by dimaMachina** [comment]
https://nextra.site/docs/guide/advanced/typescript#type-definitions
