### ISSUE TITLE
Copy to Clipboard action for codeblocks

### ISSUE THREAD

**Issue by numToStr** [shuding/nextra#539]
### Problem

Currently, if someone wants to copy the codeblock contents they have to manually select the content and press <kbd>Ctrl-c</kbd>. This could be cumbersome to do if the codeblock is large.

### Solution

Add a `Copy To Clipboard` action; something similar to github's.

![image](https://user-images.githubusercontent.com/24727447/178981000-c7505b4a-b9dc-4d80-ac6e-18d5616de9fe.png)

**Comment by shuding** [comment]
Good thing to have! We'll need a syntax for that, maybe:

```markdown
```js copy
```

It can be used together with other options:

```markdown
```js copy showLineNumbers
```

**Comment by numToStr** [comment]
Ohh! I didn't thought about it earlier but making it opt-in would be cool. Also I agree with your syntax suggestion

```

```js copy

```

**Comment by B2o5T** [comment]
Yeah, and we can have theme config option to turn this option by default to `true`
