### ISSUE TITLE
How to add custom link to sidebar?

### ISSUE THREAD

**Issue by butthx** [shuding/nextra#550]
Hi, is there possible to add any website link to sidebar? I mean, on sidebar is not only the page which generated, but also contains links that point to other websites, or other paths that are not part of the generated page.

Thanks for your answer.

**Comment by B2o5T** [comment]
just add it to your`meta.json` file
<img width="254" alt="image" src="https://user-images.githubusercontent.com/7361780/185750406-49fc5635-a055-46a9-bb16-7842a3e6d48f.png">
<img width="332" alt="image" src="https://user-images.githubusercontent.com/7361780/185750411-6a5643a4-18a8-4131-956b-1dee8c913bc7.png">
