### ISSUE TITLE
[feature request] Option to pass custom toc component

### ISSUE THREAD

**Issue by aulneau** [shuding/nextra#564]
For [our docs](https://micro-stacks.dev/docs/overview) we have the option for folks to select which framework integration they want to use (react, svelte, etc). We have a special component that will render different content depending on which is selected. There are times where we want to have different headings depending on the tab selected, however due to the nature of the current default TOC component, we're forced to be consistent between tabs with regards to headings. 

I'm not sure the best solution for this, but one thing I thought of was being able to pass a custom table of contents component in the config like you can for the head, etc.

**Comment by B2o5T** [comment]
will be configurable in next release as `toc.component`

**Comment by aulneau** [comment]
@B2o5T your work is amazing tysm for all you do!

**Comment by B2o5T** [comment]
@aulneau thank you!
