### ISSUE TITLE
Locales import broken

### ISSUE THREAD

**Issue by aulneau** [shuding/nextra#587]
```ts
import { locales } from 'nextra/locales';
```

no longer works with beta.10:

<img width="864" alt="Screen Shot 2022-07-25 at 12 09 56 PM" src="https://user-images.githubusercontent.com/11803153/180835598-4c27656c-b966-4d31-b176-ac276cc0dac4.png">

**Comment by promer94** [comment]
I can't reproduce it. Which typescript version do you use and could you try reinstall node_modules ?

https://stackblitz.com/edit/nextjs-6fk5wr?file=pages%2Fmiddleware.ts

**Comment by shuding** [comment]
Yeah it seems like a TypeScript configuration issue, could you share your `tsconfig.json` content? Happy to reopen when there's a reproduction.
