### ISSUE TITLE
Search headlines are broken

### ISSUE THREAD

**Issue by pcho** [shuding/nextra#588]
In newest release from core branch. https://github.com/shuding/nextra/pull/582
![IMG_2450](https://user-images.githubusercontent.com/41922527/180841211-7d0697ae-7e84-42f2-aa72-280f137050d3.jpeg)

**Comment by B2o5T** [comment]
Nice catch, @promer94 changed the extension to `jsx` but forget to change `content` field in tailwind.config :)
