### ISSUE TITLE
Search broken when deploying to Vercel

### ISSUE THREAD

**Issue by pcho** [shuding/nextra#594]
I don’t know if it’s Nextra, Vercel, or my issue. But somehow, search is built and works locally but not when deployed. I’m using [nextra@2.0.0-beta.10](https://github.com/shuding/nextra/releases/tag/nextra%402.0.0-beta.10) and newest nextra-theme-docs, but with modified fonts/colors.

Any hints on what could be wrong?

![580BEFEB-FE10-41F2-9F27-E5E809BFAFAF](https://user-images.githubusercontent.com/41922527/180887735-83e2ac1c-9a00-44d8-b62b-e63e3653f121.jpeg)
![51E0032A-B359-44FA-A069-EBB650006F95](https://user-images.githubusercontent.com/41922527/180887782-e34d4385-bfc9-479e-ac9a-3ae44e74462f.jpeg)

**Comment by SincerelyFaust** [comment]
I'm using the `beta.12` version and I also deploy to Vercel, I'm experiencing the same issue.

**Comment by shuding** [comment]
Weird, from the second screenshot it seems that flexsearch isn't enabled and it's using the default one. If possible could you post the deployed link so I can take a deeper look?

**Comment by SincerelyFaust** [comment]
Here's mine
- Code
https://github.com/dahliaOS/documentation
- Deployment
https://docs.dahliaos.io

**Comment by shuding** [comment]
Taking a look now!

**Comment by shuding** [comment]
I think it's indeed a bug in latest Nextra beta, will fix it and cut a new release

**Comment by shuding** [comment]
Should be fixed in `nextra@2.0.0-beta.13` and `nextra-theme-docs@2.0.0-beta.13`

**Comment by pcho** [comment]
> Should be fixed in `nextra@2.0.0-beta.13` and `nextra-theme-docs@2.0.0-beta.13`

It is. Thanks. :)
