### ISSUE TITLE
Application error on Safari mobile with `v2.0.0-beta.9`

### ISSUE THREAD

**Issue by numToStr** [shuding/nextra#609]
### Problem

I recently got reports that my blog is giving `Application error: a client-side exception has occured` error on some browser. One of the browsers was Safari mobile. I downgraded `nextra` to `v2.0.0-beta.56` and `nextra-theme-blog` to `v2.0.0-beta.55` and everything seems to be working fine. Sadly, I wasn't able to test this myself as I don't own iOS devices.

Link: https://site-git-deps-numtostr.vercel.app/blog/lsp-neovim-retrospective

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/24727447/181482597-2b0c9f21-a505-4912-9c4f-e5c18b85bcfd.png)

</details>

### Packages
```json
"next": "^12.2.3",
"nextra": "2.0.0-beta.9",
"nextra-theme-blog": "2.0.0-beta.9",
"react": "^18.2.0",
"react-dom": "^18.2.0"
```

### Config

- `next.config.mjs`
```js
import nextra from "nextra";

const withNextra = nextra({
    theme: "nextra-theme-blog",
    themeConfig: "./theme.config.js",
    unstable_staticImage: true,
});

/**
 * @type {import('next').NextConfig}
 */
const config = {
    experimental: {
        browsersListForSwc: true,
        legacyBrowsers: false,
    },
    async redirects() {
        return [
            {
                source: "/tags",
                destination: "/blog",
                permanent: false,
            },
        ];
    },
};

export default withNextra(config);
```

- `theme.config.js`
```js
const theme = {
    darkMode: true,
    readMore: "Read More →",
    titleSuffix: ` - NAME`,
    head: Seo,
    footer: <Footer />,
};

export default theme;
```

**Comment by B2o5T** [comment]
Closed as completed https://github.com/shuding/nextra/pull/612
