### ISSUE TITLE
Convert markdown link to next/link

### ISSUE THREAD

**Issue by shuding** [shuding/nextra#620]
Links like `[](/about)` should be converted to `next/link` if the href is a relative path.

**Comment by B2o5T** [comment]
It’s already converts https://github.com/shuding/nextra/blob/4157b71f1dd4d0708960c2b8c26e63960f01599d/packages/nextra-theme-docs/src/misc/theme.tsx#L204

**Comment by shuding** [comment]
Ah, I think I’m running into a bug then, maybe because I’m using `layout: raw` for that page.
