### ISSUE TITLE
`style.css` isn't created when runing build inside nextra-theme-docs

### ISSUE THREAD

**Issue by pcho** [shuding/nextra#622]
As in topic `style.css` is missing from build. It displays: 

`Error: Failed to find 'nextra/code-highlighting/variables.css'`

**Comment by shuding** [comment]
Which version of Nextra are you on? Is it matching the theme’s version?

**Comment by pcho** [comment]
Yes, newest nextra and nextra-theme-docs. It works fine, when doing build from main folder, but not when building in packages.

**Comment by pcho** [comment]
Steps to reproduce (on the newest version too): 

`git clone —depth=1 -b core https://github.com/shuding/nextra.git` then move to nextra folder and run `pnpm install`. After that cd to packages/nextra and run `pnpm build`, next into nextra-theme-docs doing the same. After that moving to examples/docs and running `pnpm dev` will create an error:

```
error - ./src/pages/_app.js:1:0
Module not found: Can't resolve 'nextra-theme-docs/style.css'
> 1 | import 'nextra-theme-docs/style.css'
  2 | 
  3 | export default function Nextra({ Component, pageProps }) {
  4 |   const getLayout = Component.getLayout || (page => page)
```

Building from main nextra repository works fine.

**Comment by pcho** [comment]
I fixed it by adding build:tailwind into build command. ;-)
