### ISSUE TITLE
Bug: mdxcontent can't access component context 

### ISSUE THREAD

**Issue by promer94** [shuding/nextra#637]
Context has the correct value.
<img width="749" alt="Screen Shot 2022-08-05 at 11 32 07" src="https://user-images.githubusercontent.com/15878786/182995963-0983a14d-d590-482d-b763-5d91157cb140.png">

But mdxcontent does not
<img width="749" alt="Screen Shot 2022-08-05 at 11 31 51" src="https://user-images.githubusercontent.com/15878786/182995949-6cb73129-2d67-4567-aabd-64de417f3c75.png">

**Comment by promer94** [comment]
Because of https://github.com/shuding/nextra/blob/88f999ddb741fc388e4338a5aa4f9367ca49c7f6/examples/docs/next.config.js#L24

`MDXProvider` and `MDXContent` will use different instance of `@mdx-js/react`.

**Comment by shuding** [comment]
😭 `symlinks: false` was a trick to make https://nextjs.org/docs/basic-features/built-in-css-support#import-styles-from-node_modules work in our monorepo (it requires the CSS path to have `node_modules` inside).

Another work around that is too dirty is to rename `nextra-theme-docs/style.css` to `nextra-theme-docs/style_node_modules.css` or `nextra-theme-docs/_node_modules_/style.css` but 🙅
