### ISSUE TITLE
How to make flex search work

### ISSUE THREAD

**Issue by chilikasha** [shuding/nextra#644]
Hi,

```
"nextra": "2.0.0-beta.14",
"nextra-theme-docs": "2.0.0-beta.14",
```

config.js:
```
search: true,
unstable_flexsearch: true,
```
site is deployed to vercel, but the only things I can search for are side bar items' titles. Is there anything else required to make it work?

Thank you.

**Comment by B2o5T** [comment]
you should setup `unstable_flexsearch: true` in nextraConfig https://github.com/shuding/nextra/blob/48e0ac2d9b26d84c4331b9acf540cd897f8bf822/examples/swr-site/next.config.js#L4-L6

**Comment by chilikasha** [comment]
@B2o5T did as in comment above but didn't help.

**Comment by B2o5T** [comment]
Do you use latest beta? Beta 16?

**Comment by chilikasha** [comment]
yes, beta 16

Ср, 10 авг. 2022 г. в 00:12, Dimitri POSTOLOV ***@***.***>:

**Comment by B2o5T** [comment]
Do you use this repo? https://github.com/chilikasha/tinytools/blob/main/next.config.js

**Comment by chilikasha** [comment]
Sorry Dimitri, I used a wrong config file (a theme one). will change a bit
later. thank you

Ср, 10 авг. 2022 г. в 11:32, Dimitri POSTOLOV ***@***.***>:

**Comment by raproid** [comment]
@B2o5T what other params with  unstable_flexsearch besides codeblocks: true?
Now I get results from codeblocks, but still some results from the content of the page or the title in the sidebar are missing.
What I'm saying I'd love to get more results, as I know my content has em, but the search doesn't show a lot of them.

**Comment by B2o5T** [comment]
you can setup `unstable_flexsearch: true` for skip content from code-blocks.
And for about missing results, please create an issue with reproduction if possible
