### ISSUE TITLE
Locale from jsx/tsx files 

### ISSUE THREAD

**Issue by gr-qft** [shuding/nextra#66]
It seems to me from reading the file `loader.js` inside `nextra` that jsx files, such as `no.en.jsx`, are allowed. But even though **No** appears on the navigation sidebar, clicking it leads to 404 (since the **route** is   **no**). If however only `no.jsx` is created Nextjs takes over and it renders correctly. 

I don't know what the real intention here is. It seems to me if a file ends with jsx or tsx then the locale problem is perhaps treated directly by some logic inside the file itself (instead of having different files with essentially the same logic, layout etc.)? In that case would it be better to remove jsx as currently done inside `loader.js`? 

On the other hand, if something such as `no.en.jsx` is indeed what's wanted then some fix should be done, and `tsx` should be allowed also. I've played a bit with the code and here's 
the branch: 

https://github.com/gr-qft/nextra/tree/fix/jsx-tsx-files

Please let me know.

**Comment by B2o5T** [comment]
Use md/mdx files instead
