### ISSUE TITLE
Setup `renovate-bot` for automatic update dependencies

### ISSUE THREAD

**Issue by B2o5T** [shuding/nextra#664]

**Comment by B2o5T** [comment]
@shuding could you setup it? this will be nice since for example `next-theme@0.2.1` was just released and we could update it in 1 click :)

**Comment by shuding** [comment]
It seems a bit tricky to set it up for `core` instead of `master` (#842)

**Comment by B2o5T** [comment]
@shuding could you retry? 🙏

**Comment by shuding** [comment]
@B2o5T Sure!

**Comment by shuding** [comment]
Should be there now!
