### ISSUE TITLE
[nextra-theme-docs] Better navigation with breadcrumbs

### ISSUE THREAD

**Issue by dimaMachina** [shuding/nextra#666]
Currently, navigation with breadcrumbs can be accessible `only` if there is `index` page. I guess we can improve it
<img width="708" alt="image" src="https://user-images.githubusercontent.com/7361780/183658013-7a837eaa-e1ff-44fd-957b-df64abd8e5b7.png">

**Comment by shuding** [comment]
You can have this structure to make the folder work like a page:

```
introudction.mdx
introduction/
  a.mdx
  b.mdx
```

And then in the breadcrumb "Introduction" will be a link to introduction.mdx.

**Comment by shuding** [comment]
I was thinking about generating "summary" pages for folders automatically if they're missing, but can't think of a good way.

**Comment by alecpetrosky** [comment]
> You can have this structure to make the folder work like a page:
> 
> ```
> introudction.mdx
> introduction/
>   a.mdx
>   b.mdx
> ```
> 
> And then in the breadcrumb "Introduction" will be a link to introduction.mdx.

I'm very interested in getting this structure to work but with no success. Creating both introudction.mdx and introduction/ does not show subpages in the left navigation panel. How is possible to archive having both navigation folder with sub-items and "index" page to show up when clicking to such folder?

**Comment by d1onys1us** [comment]
> I was thinking about generating "summary" pages for folders automatically if they're missing, but can't think of a good way.

would this be something like this? https://docusaurus.io/docs/category/getting-started curious. because i have thought this would be very useful.

**Comment by dimaMachina** [comment]
navigation for breadcrumbs was improved in Nextra 3 already
