### ISSUE TITLE
Hide the sidebar

### ISSUE THREAD

**Issue by shuding** [shuding/nextra#67]
Make the sidebar toggleable in desktop screen size.

**Comment by B2o5T** [comment]
did this, will push PR soon ;)

**Comment by B2o5T** [comment]
@shuding I guess we can also add a new theme option for enabling/disabling this feature

https://user-images.githubusercontent.com/7361780/188286240-84e57eaf-7b37-40c7-8528-be91bd567691.mov

**Comment by shuding** [comment]
Beautiful! And yes I think this feature isn't needed by most people, but we can have an option to add it and set the default behavior.
