### ISSUE TITLE
Improve theme options interface

### ISSUE THREAD

**Issue by shuding** [shuding/nextra#676]
We have `customSearch`, `search`, `unstable_flexsearch`, `unstable_searchResultEmpty`, `searchPlaceholder` right now, which is really a bit messy.

I suggest to rename `unstable_flexsearch` to `searchIndex` for Nextra.

And doing the following change to the docs theme:

```js
search: true  // → enable search
              // (If `searchIndex` is enabled, here we use Flexsearch. Otherwise use the simple one)

search: false // → disable search

search: {
  placeholder?: string | (() => string)
  emptyResult?: ReactNode | FC
}

search: {
  customize?: ReactNode // → when this is enabled, we will not rendering our search element
                        // but you can put anything there. e.g. algolia search
}
```

**Comment by shuding** [comment]
And we should do this simplification for many other options, too.

```ts
footer?: boolean
footerText?: ReactNode | FC
footerEditLink?: ReactNode | FC
```

```ts
feedbackLink?: ReactNode | FC
feedbackLabels?: string
```

```ts
nextLinks?: boolean
prevLinks?: boolean

// maybe:
navigation?: boolean | { next?: boolean; prev?: boolean } = true
```

```ts
notFoundLink?: ReactNode | FC
notFoundLabels?: string
serverSideErrorLink?: ReactNode | FC
serverSideErrorLabels?: string
```

**Comment by B2o5T** [comment]
`footerEditLink` should be renamed to `editLink` because it's not in `footer` but in `TOC`

something like this?
```ts
  editLink?: ReactNode | FC
  footer?: boolean | {
    text?: ReactNode | FC
  }
  feedback?: boolean | {
    link?: ReactNode | FC
    labels?: string
  }
  notFound?: boolean | {
    link?: ReactNode | FC
    labels?: string
  }
  serverSideError?: boolean | {
    link?: ReactNode | FC
    labels?: string
  }
  navLinks?: boolean | { // or navigation
    next?: boolean
    prev?: boolean
  }
```

**Comment by B2o5T** [comment]
also we can add new option https://github.com/shuding/nextra/issues/669
```
  tocTitle?:  string = 'On This Page'
```

**Comment by B2o5T** [comment]
> We have `customSearch`, `search`, `unstable_flexsearch`, `unstable_searchResultEmpty`, `searchPlaceholder` right now, which is really a bit messy.
> 
> I suggest to rename `unstable_flexsearch` to `searchIndex` for Nextra.
> 
> And doing the following change to the docs theme:
> 
> ```js
> search: true  // → enable search
>               // (If `searchIndex` is enabled, here we use Flexsearch. Otherwise use the simple one)
> 
> search: false // → disable search
> 
> search: {
>   placeholder?: string | (() => string)
>   emptyResult?: ReactNode | FC
> }
> 
> search: {
>   customize?: ReactNode // → when this is enabled, we will not rendering our search element
>                         // but you can put anything there. e.g. algolia search
> }
> ```

I guess we can simplify with

```ts
 search: boolean | ReactFC | {
   placeholder?: string | (() => string)
   emptyResult?: ReactNode | FC
 }
```

**Comment by shuding** [comment]
All look good to me, I still prefer `navigation` over `pagination` though!

**Comment by B2o5T** [comment]
@shuding another options to group:
```ts
  // from
  floatTOC?: boolean
  tocExtraContent?: ReactNode | FC
  // to
  toc?: {
    float?: boolean
    extraContent?: ReactNode | FC
  }
```
