### ISSUE TITLE
Can't use `useRouter` inside `head`

### ISSUE THREAD

**Issue by shuding** [shuding/nextra#679]
For the docs theme, when you have this in the config:

```jsx
  head: function Head() {
    const router = useRouter()
    return (
      <>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        ...
```

`router` is going to be `null` because of https://github.com/vercel/next.js/issues/23559#issuecomment-828080139.

**Comment by B2o5T** [comment]
will be fixed in next release
