### ISSUE TITLE
[theme-blog] Estimated Reading Time

### ISSUE THREAD

**Issue by numToStr** [shuding/nextra#683]
### Problem

When visiting a blog post page, user doesn't get any clue about how long and how much time it will take to read the post.

### Solution

It would be nice if we can show estimated reading time like `10 min read` for blog post.

### Screenshot

![image](https://user-images.githubusercontent.com/24727447/184131363-23d4b3c7-a8e3-4ea6-876a-fda1ae73b69d.png)

Source: https://leerob.io/blog/rust

**Comment by B2o5T** [comment]
Helpful proposal!
