### ISSUE TITLE
feat: `#` href link for markdown head

### ISSUE THREAD

**Issue by jjangga0214** [shuding/nextra#685]
Hi!

GitHub provides a link for markdown head (e.g. h1, h2, ...) for readme.

For example,

<img width="540" alt="스크린샷 2022-08-12 오후 1 05 45" src="https://user-images.githubusercontent.com/28584151/184283277-54028568-c631-4e57-840d-075c3fd65404.png">

when I hover the head, then the chain icon appears.
And if clicked, the url with `#` href is copied to the clipboard.

I want the same/similar behavior in Nextra to this.

How do you think?

Thanks.

**Comment by numToStr** [comment]
> And if clicked, the url with # href is copied to the clipboard.

Is this the github's behaviour when you click on a markdown link? Because it certainly not working me.

Beside that you can easily copy the link from URL bar.

**Comment by jjangga0214** [comment]
@numToStr 
> Because it certainly not working me.
Ah yes you're right. The link is not copied, but just show up from the URL bar.
Unlink GitHub, I recall some other websites(e.g. docs generator) does have a clipboard feature, which is pretty convenient.

However, nextra still does not provide `#` anchor url. That's essentially what I want.

So, this feature request is in short,

1. Support `#` anchor href. (essential) (like GitHub)
2. Automatic copy to clipboard if clicked (optional)

**Comment by B2o5T** [comment]
> Let's support # anchor href. (like GitHub)

all headings already have anchors

> And (optionally) automatic copy to clipboard when clicked

I don't think we need it

**Comment by numToStr** [comment]
> I don't think we need it

Yeah, as this can be easily copied from the URL bar.

**Comment by shuding** [comment]
Yep we already have this.

**Comment by jjangga0214** [comment]
@shuding Oh, I see.
Which version does support the feature?
I am using `nextra@1.1.0` and `nextra-theme-docs@1.2.6`, and could not use the feature.
Do I have to migrate to unstable v2 beta to get the feature?
Thanks.

**Comment by B2o5T** [comment]
@jjangga0214 If you want to use new features, you can migrate to 2.0 beta, take a look of examples https://github.com/shuding/nextra/tree/core/examples
