### ISSUE TITLE
[nextra-theme-docs] Normal Search height overflow

### ISSUE THREAD

**Issue by EpicEmeraldPlayz** [shuding/nextra#694]
Problem:
---
When using normal search (not `flexsearch`) and having a long list of result it will overflow through the page height (occured on view-port of `tablet`- `desktop`)

Solution:
---
Apply the same CSS Rule from flexsearch (`.nextra-search.nextra-flexsearch ul`) to (`.nextra-search ul`)

```css
overflow: auto;
min-height: 100px;
max-height: min(calc(100vh - 5rem - env(safe-area-inset-bottom)),400px);
max-width: min(calc(100vw - 2rem),calc(100% + 20rem));
```

**Comment by B2o5T** [comment]
will be available in next beta
