### ISSUE TITLE
markdown inline codeblock not rendered as expected

### ISSUE THREAD

**Issue by YikSanChan** [shuding/nextra#70]
Hi @shuding I use your site https://github.com/shuding/site as a starting point to adopt next-theme-blog, and run into below problem.

`.md` file:

```markdown
你只需要配置 RemoteActorRefProvider(译者注：在最新版本的 Akka 中，只需设为`cluster`即可)。
```

rendered as:

![image](https://user-images.githubusercontent.com/17229109/102732491-b9fe4d80-42ef-11eb-8457-c1c836a71e76.png)

Note the `cluster` is not rendered as a normal markdown inline codeblock. Do you know why?

**Comment by shuding** [comment]
It's the default style of https://github.com/tailwindlabs/tailwindcss-typography. It is still monospace font but wrapped with backticks.

[Example](https://tailwindcss-typography.netlify.app): 
![image](https://user-images.githubusercontent.com/3676859/102775406-c524ac80-43c7-11eb-9cb9-c894d3ed1b0b.png)

I'll override the style anyways 👍

**Comment by YikSanChan** [comment]
@shuding I see. Allowing users to override it would also be great. Thank you so much for your help

**Comment by jngbng** [comment]
How can we override this configuration as in https://github.com/tailwindlabs/tailwindcss-typography/issues/18 ?

**Comment by B2o5T** [comment]
@jngbng thanks,
Finally solved, closed as completed https://github.com/shuding/nextra/pull/613
