### ISSUE TITLE
`useConfig` returns an empty structure in `theme.config.tsx` `head()`

### ISSUE THREAD

**Issue by robbear** [shuding/nextra#704]
I find that adding gray matter title/description/image to a page does not result in a populated `config` object as accessed from `useConfig` in `theme.config.tsx`. 

Below, the defaults are always in effect. This seems to have regressed since the `theme.config.tsx` migrated from `theme.config.js` and the recent new accessibility of `useConfig` from the docs site.
```
  head() {
    const config = useConfig();
    const description =
      config.meta.description ||
      "SWR is a React Hooks library for data fetching. SWR first returns the data from cache (stale), then sends the fetch request (revalidate), and finally comes with the up-to-date data again.";
    const image =
      config.meta.image ||
      "https://assets.vercel.com/image/upload/v1572282926/swr/twitter-card.jpg";
```

**Comment by robbear** [comment]
In case it's useful to note, in exploring I did find that `config` is properly populated in `nextra-theme-docs/src/index.tsx` in `Body` and `InnerLayout`:
https://github.com/shuding/nextra/blob/a8c588385f7a968125f5b9831f209292336b7674/packages/nextra-theme-docs/src/index.tsx#L77
https://github.com/shuding/nextra/blob/a8c588385f7a968125f5b9831f209292336b7674/packages/nextra-theme-docs/src/index.tsx#L158

But in both `examples/swr-site` and in my own site, the `config` object is unpopulated at the time you'd like to use the `config.meta.description` etc value in the theme `head` function:
https://github.com/shuding/nextra/blob/a8c588385f7a968125f5b9831f209292336b7674/examples/swr-site/theme.config.tsx#L73

**Comment by B2o5T** [comment]
will be fixed in next release
