### ISSUE TITLE
Active links not highlighted in sidebar in beta.17

### ISSUE THREAD

**Issue by gkaemmer** [shuding/nextra#710]
The styles on `li.active a` were removed in this PR: https://github.com/shuding/nextra/pull/691

This means that active links are no longer highlighted in the sidebar:
<img width="1277" alt="Screen Shot 2022-08-18 at 6 50 06 PM" src="https://user-images.githubusercontent.com/3156043/185508857-9867e492-b399-468e-bd65-5f09feb0e267.png">

I think we could just add those styles back to `styles.css`, right?

**Comment by B2o5T** [comment]
Thanks! Was my mistake due to big refactoring for rtl support and search inputs!
