### ISSUE TITLE
Only default locale in produced sitemap: nextra with next-sitemap and i18n

### ISSUE THREAD

**Issue by alecpetrosky** [shuding/nextra#712]
Using nextra with next-sitemap and i18n generates sitemap for default language only. But it perfectly generates all language versions on build as expected. It seems that next-sitemap ignores all other language subfolders (in my case /es/) generated by nextra except the default locale.

**next.config.js**

```
const withNextra = require('nextra')({
  theme: 'nextra-theme-docs',
  themeConfig: './theme.config.js',
  unstable_staticImage: true
})
module.exports = withNextra({
  i18n: {
    locales: ['en', 'es'],
    defaultLocale: 'en',
    // localeDetection: false,
  }
})
```
**package.json**

```
...
"postbuild": "next-sitemap"
...
```

Maybe related to #419, not sure.

**Comment by anaclumos** [comment]
Also would like to learn any updates.

**Comment by Prottoy2938** [comment]
Any solution yet?

**Comment by B2o5T** [comment]
closed by https://github.com/shuding/nextra/pull/2250

https://github.com/shuding/nextra/releases/tag/nextra%403.0.0-alpha.0
