### ISSUE TITLE
Support disabling/customizing the edit on GitHub link only for some pages

### ISSUE THREAD

**Issue by erezrokah** [shuding/nextra#729]
Hi 👋 Thank you for this lovely tool.

This feature request is somehow related to https://github.com/shuding/nextra/issues/662

We have a few pages that are autogenerated and don't map to a GitHub file.
In another case we transform the pages and they have a different name so the generated link is broken.

I would like to be able to customize the edit on GitHub link for specific pages, ideally by supplying a function to to `footerEditLink`.
An empty return value should indicate to remove the link, while a non empty string value should tell Nextra to use the value as the link.

**Comment by B2o5T** [comment]
will be customizable via `editLink.component` property in theme config in next release
