### ISSUE TITLE
Add utterances support to nextra-theme-blog

### ISSUE THREAD

**Issue by YikSanChan** [shuding/nextra#73]
https://utteranc.es/ is a popular comments "plugin" that manages comment data in GitHub repo. Would be great to have it built-in to nextra-theme-blog, or allow users to easily add it

**Comment by shuding** [comment]
Yeah I'm kinda focused on the docs theme at the moment, but it would be great to have a "footer"/"postFooter" option for the blog theme (so you can put any component there), as well as a dedicated section in the docs for disqus/utterances/analytics etc.

**Comment by YikSanChan** [comment]
@shuding Actually I tried putting the utterances script in footer, such as 

```html
        <section id="comments">
          <h4>
            <a href="">Comments</a>
          </h4>
          <div
            dangerouslySetInnerHTML={{
              __html: `<script src="https://utteranc.es/client.js"
                    repo="YikSanChan/yiksanchan.com"
                    issue-term="pathname"
                    label="comments"
                    theme="github-light"
                    crossorigin="anonymous"
                    async>
            </script>`,
            }}
          />
        </section>
```

However, it always takes a refresh to be able to see the widget, and when that happens I find the page is built from dev console. I am not familiar with how the SSR work, therefore not able to figure out how.

Any advice? @shuding

**Comment by shuding** [comment]
Did you try this? That `dangerouslySetInnerHTML` isn't necessary.

```jsx
<section id="comments">
<h4>
  <a href="">Comments</a>
</h4>
<script src="https://utteranc.es/client.js"
  repo="YikSanChan/yiksanchan.com"
  issue-term="pathname"
  label="comments"
  theme="github-light"
  crossorigin="anonymous"
  async />
</section>
```

**Comment by YikSanChan** [comment]
@shuding It is a good point, I remove the unnecessary `dangerouslySetInnerHTML` but the problem still exists.

This is the PR https://github.com/YikSanChan/site/pull/8 and here's the app https://site-git-utterances-support.yishengdd.vercel.app/

To reproduce:
1. Visit https://site-git-utterances-support.yishengdd.vercel.app/posts
2. Scroll to the bottom, should be able to find "Comments", but no widget is loaded
3. Simply refresh the page, the widget shows up

Before refresh:
![image](https://user-images.githubusercontent.com/17229109/103015730-cbb14200-44f5-11eb-9872-5026375c4035.png)
After refresh:
![image](https://user-images.githubusercontent.com/17229109/103015752-d4097d00-44f5-11eb-8664-b927d7c9deec.png)

I don't understand why 🤔

**Comment by B2o5T** [comment]
closing since the blog theme has `react-cusdis` comments
