### ISSUE TITLE
`react` and `react-dom` peerDependencies values are different in `nextra` package.json

### ISSUE THREAD

**Issue by robbear** [shuding/nextra#736]
https://github.com/shuding/nextra/blob/6c58a89b067d5bafc04178390dab605059292344/packages/nextra/package.json#L91

Is there a reason for this? By setting `"react-dom": ">=16.13.1"` to match `react`, I can get a clean `pnpm install` without warnings for a React 17 project build.

**Comment by B2o5T** [comment]
Your are right, this is a mistake
