### ISSUE TITLE
mdx syntax highlight: more language support

### ISSUE THREAD

**Issue by YikSanChan** [shuding/nextra#74]
I try to highlight my Scala code block with nextra-theme-blog and it doesn't work.

According to https://github.com/mdx-js/mdx/issues/1411, this is because prism-react-renderer doesn't support Scala by default. However, there seems to be a way to add support, as in https://github.com/FormidableLabs/prism-react-renderer#faq

Can you help add the support if it makes sense to you? Thank you

**Comment by shuding** [comment]
Yeah, you can do it by:
1. `yarn add prismjs prism-react-renderer`
2. add these to your _app.js:

```
import Prism from 'prism-react-renderer/prism'
(typeof global !== "undefined" ? global : window).Prism = Prism
require('prismjs/components/prism-scala')
```

Restart your app and it should work! I'll add a note to the docs.

**Comment by shuding** [comment]
Added https://nextra.vercel.app/docs/advanced/code-highlighting.

**Comment by YikSanChan** [comment]
I guess most of what https://nextra.vercel.app/ say also applies to nextra-theme-blog, is it correct?

**Comment by shuding** [comment]
Yep, most of the concepts are applied to both. Some specific styles/components like https://nextra.vercel.app/docs/built-in-components are docs only.
