### ISSUE TITLE
[theme-doc] fail to load a third party script using 'Script' tag with no error

### ISSUE THREAD

**Issue by Kiotlin** [shuding/nextra#757]
I want to add a [tooltip](https://na.finalfantasyxiv.com/lodestone/special/fankit/tooltip/) into one of my blog (based on .mdx file).

It should work and appear a window when hovering the 'a' tag like below, with just 2 lines of code:
<img width="570" alt="image" src="https://user-images.githubusercontent.com/21698963/187409032-67b8c0ff-263e-40ec-99f4-11b7cdfb14c9.png">
```html
...
<head>
    ...
    <title>Tooltip Test</title>
</head>
<body>
   ...
   <a href="https://na.finalfantasyxiv.com/lodestone/playguide/db/item/b2cab67854f/" class="eorzeadb_link">Dreadwyrm Blade</a>
    <script src="https://img.finalfantasyxiv.com/lds/pc/global/js/eorzeadb/loader.js?v2"></script>
   ...
</body>
...
```

So I tried to implement it with nextjs in one of my post like this:
```javascript
// post1.mdx
...
...text before...

import Script from 'next/script';
export function IconEmbed({link, text}) {
    const A = 'a';

    return (
        <>
            <A href={link} className="eorzeadb_link">{text}</A>
            <Script src="https://img.finalfantasyxiv.com/lds/pc/global/js/eorzeadb/loader.js?v2"/>
        </>
    );
}

...，头顶<IconEmbed link="https://jp.finalfantasyxiv.com/lodestone/playguide/db/item/54288cb0f6c/" text="DQ联动史莱姆帽子"/>的拉拉肥男性...
```
this post compiled with no error, and the 3rd party script also seems to be embeded under the page successfully. But when I try to hover the 'a' tag called 'DQ联动史莱姆帽子', the js script seems to be operated but with nothing appear (A seperate window just like the one shown in the 1st screenshot should have appeared but actually not)! no error thrown.

<img width="884" alt="Screen Shot 2022-08-30 at 19 19 43" src="https://user-images.githubusercontent.com/21698963/187413516-006d0a0a-d51c-4262-9c30-7ec37a5ba9ca.png">

I felt so weird. I'm a beginner of nextjs, so I'm not sure what really causes this issue (nextjs or nextra engine).

Waiting for someone's help....TAT

**Comment by Kiotlin** [comment]
Here is the [link](https://iken.moe/posts/ff14-dairy#%E6%9C%A8%E6%A1%A9%E8%BE%B9%E7%9A%84%E9%82%82%E9%80%85:~:text=Makoto%20Majima%E2%80%9D%EF%BC%8C%E5%A4%B4%E9%A1%B6-,DQ%E8%81%94%E5%8A%A8%E5%8F%B2%E8%8E%B1%E5%A7%86%E5%B8%BD%E5%AD%90,-%E7%9A%84%E6%8B%89%E6%8B%89%E8%82%A5) refering to the post.

**Comment by shuding** [comment]
DM'd over Twitter, I believe it's a styling issue with the tooltip lib because the wrapper has no size (w=0, h=0) but `overflow: hidden` which causes the content to be invisible.
