### ISSUE TITLE
[theme-blog] Copy to Clipboard is not visible

### ISSUE THREAD

**Issue by numToStr** [shuding/nextra#769]
You cannot see the button, but you can click on it. I believe this is a regression introduced by https://github.com/shuding/nextra/pull/751

Example: https://site-git-deps-numtostr.vercel.app/blog/vim-dot-repeat (hover over any code block)

**Comment by B2o5T** [comment]
Did you setup this options? https://github.com/shuding/nextra/blob/873561bb56084c803b4fb39e0fbb294b6c8aa8cb/examples/swr-site/next.config.js#L8

Or did you added `copy` in codeblock?

Example: 
````md
```js copy
````

**Comment by numToStr** [comment]
Yes, I did.

**Comment by B2o5T** [comment]
Did you set this option in next config? (not in theme config)

**Comment by B2o5T** [comment]
will be fixed in next release
