### ISSUE TITLE
ThemeSwitch layout problem in sites without localization

### ISSUE THREAD

**Issue by robbear** [shuding/nextra#776]
This problem can be observed in the `examples/docs` site as per the following two screen shots showing the element with an improperly hidden text `<span>` and clipped pop-up menu. This appears to be the case for sites without the accompanying localization selector as used by the example swr-site which does not display this problem.

![image](https://user-images.githubusercontent.com/1823198/187790701-b299f9cb-b06b-480b-bc8f-29e771ced007.png)

![image](https://user-images.githubusercontent.com/1823198/187790873-e7b39fc1-e713-43fd-aed3-ebfeece92241.png)

**Comment by B2o5T** [comment]
Thank you :) will be fixed in next release https://github.com/shuding/nextra/pull/763
