### ISSUE TITLE
Pages with long names don't overflow correctly on the sidebar

### ISSUE THREAD

**Issue by Phineas** [shuding/nextra#777]
Pages with long strings as titles (and no spaces) don't wrap how I'd expect them to.

**Expected behavior**: the page button container would expand and the text would wrap onto the next line **or** the sidebar width should expand to allow for the extra space

**Examples**:
![image](https://user-images.githubusercontent.com/6209808/187805993-8cd89df2-765f-4055-b9c9-a31be249ad10.png)
<img width="372" alt="Screen Shot 2022-09-01 at 1 09 39 AM" src="https://user-images.githubusercontent.com/6209808/187806077-3d771f3c-bb3e-4ae6-abfc-6616c340cb14.png">

**Comment by B2o5T** [comment]
Hi! which version of nextra do you use? seems like on the latest version there is no longer this issue
https://nextra-theme-docs-bnyeorrpr.vercel.sh/docs/advanced/more/loooooooooooooooooooong-title

**Comment by Phineas** [comment]
Ah! I thought that `alpha` was the latest version track so I was on alpha.56.

I upgraded to `beta.21` and the issue is fixed. Thank you!
