### ISSUE TITLE
Adding custom components overrides the theme.config.js

### ISSUE THREAD

**Issue by champsupertramp** [shuding/nextra#781]
I'm currently adding a custom component within the following structure:

/project/
  - /node_modules/
  - /components/
         - moduleTables.js <--- my custom component
  - /pages/
         - index.mdx
  - next.config.js
  - theme.config.js

Here's the issue: 

When I import the custom component to the .mdx file, the theme.config.js gets overridden or resets the Nextra Theme navigation. 

Here's a screenshot of the issue:
<img width="1413" alt="Screen Shot 2022-09-01 at 9 47 46 PM" src="https://user-images.githubusercontent.com/12200688/187930264-459e5154-dc60-41c4-a388-f03bd2409ecb.png">

Here's when I remove the component from the mdx file:
<img width="1413" alt="Screen Shot 2022-09-01 at 9 49 15 PM" src="https://user-images.githubusercontent.com/12200688/187930524-390e8069-8b41-425a-8251-1bdd0787c9d1.png">

Inside `moduleTables.js`

```
import UM_Table, { Irow } from 'react-tailwind-table'
import 'react-tailwind-table/dist/index.css'
import { um_module_row, um_module_col } from '../data/modules'
import React from 'react'

export default function () {
  const UM_MODULES_TABLE_STYLES = {

  }

  return (
    <UM_Table
      columns={um_module_col}
      rows={um_module_row}
      per_page={5}
      should_export={false}
      table_header=""
      show_search={true}
      striped={true}
      bordered={true}
      hovered={true}
      styling={UM_MODULES_TABLE_STYLES}
      no_content_text="No modules found"
    ></UM_Table>
  )
}
```

Inside the MDX file:
```
import UM_Modules from '../components/ModulesTable'
<UM_Modules/>
```

**Comment by B2o5T** [comment]
Hi! Can you add a reproduction repo?

**Comment by champsupertramp** [comment]
Hi @B2o5T  I'm sorry. I found the issue. 
This CSS file hides all the navigation elements: 
`import 'react-tailwind-table/dist/index.css'`

I'm marking this resolved now. Thank you
