### ISSUE TITLE
Allow overwriting theme-color meta tag

### ISSUE THREAD

**Issue by alii** [shuding/nextra#792]
I would like to overwrite the value of theme-color for our docs, but it's hard coded [here](https://github.com/shuding/nextra/blob/c4a978268a58f9e215f7c9e575bcc60274c02b06/packages/nextra-theme-docs/src/components/head.tsx#L32) and providing it yourself in the theme.config.js will not override it (I presume Next.js chooses the first "version" of it).

Would it be possible to perhaps have another config property that would be
```ts
metaThemeColor?: string | {
  dark: string;
  light: string;
};
```

Or even better, maybe it would be possible to detect when we are reimplementing it and allow it to use the value we overwrite?

Thank you !! :heart: :D

**Comment by alii** [comment]
Placing it in `_document.js` will in fact write it to the DOM, but safari for example will still fallback to the initial `<meta />`.

**Comment by B2o5T** [comment]
For which reason you need to override these properties?

**Comment by alii** [comment]
We were changing the theme of the Nextra top navigation bar and the browser navbar color did not match as it was being overwritten. Would be great if we could change it somehow :)

**Comment by B2o5T** [comment]
why you can't configure the theme via `primaryHue`/`primaryHue.dark`/`primaryHue.light` theme options?

**Comment by B2o5T** [comment]
Closing due silence
