### ISSUE TITLE
Tables span more than 100% on smaller devices

### ISSUE THREAD

**Issue by alii** [shuding/nextra#793]
I think an easy fix for this is adding `overflow-y-auto max-w-full`
![CleanShot 2022-09-02 at 14 43 34@2x](https://user-images.githubusercontent.com/25351731/188148545-58b8426e-0a46-42b2-b59a-e4a602f1e6ad.png)

I would love to make my first contributions to nextra, so if I could perhaps have some guidance where would be best to fix this I'll get a PR together :)

**Comment by B2o5T** [comment]
nice catch, will be fixed on next release

**Comment by alii** [comment]
Thank you!
