### ISSUE TITLE
Disappearing toc in Firefox

### ISSUE THREAD

**Issue by chilikasha** [shuding/nextra#800]
```
"next": "^12.2.4",
"nextra": "2.0.0-beta.21",
"nextra-theme-docs": "2.0.0-beta.21",
```
Firefox 104.
Please see video.
It's reproducible in Firefox for me (tried Chrome and Safari as well)

https://user-images.githubusercontent.com/3147449/188315013-f35bf3c0-d20b-41ee-a4c2-7975c1e270de.mov

**Comment by B2o5T** [comment]
Thanks, for the catch, it seems like firefox has different behaviour with `mask-image` style, will be fixed on next release
