### ISSUE TITLE
Sidebar items clickable when hidden

### ISSUE THREAD

**Issue by shuding** [shuding/nextra#808]
I guess these links are still clickable because the `ul` is `display: flex`:

![CleanShot 2022-09-05 at 12 53 59@2x](https://user-images.githubusercontent.com/3676859/188433012-a240cc9b-d6e9-4a8b-ab12-a04044bcb064.png)

**Comment by B2o5T** [comment]
I guess there is no issue, there are clickable when the sidebar is shown, and in your example, their container has `width: 0` because the sidebar is toggled be hidden
