### ISSUE TITLE
Smarter image optimization

### ISSUE THREAD

**Issue by shuding** [shuding/nextra#810]
Nextra currently modifies relative Markdown image paths to `next/image` such as `![](../../public/image.jpg)`. Another smart move we can do is to also handle `![](/image.jpg)` when it starts with `/` because it _should_ be from the public folder. Something like `join(relative(__dirname, appRoot), 'public', absoluteUrl)` may work.

There are exceptions though such as rewrites, so we can first check if that image exists in the public folder and if not, we don't do any modification there.

**Comment by B2o5T** [comment]
If image doesn’t exist we can show at least console warning, this will be more helpful
