### ISSUE TITLE
use getStaticProps and other ssr/ssg features inside of a .mdx file

### ISSUE THREAD

**Issue by alii** [shuding/nextra#816]
For our documentation at Hop, I would like to include the latest package version of one of our client libraries. Logically, the best way to do this with Next.js is to use getStaticProps with ISR. Is this possible inside of an mdx file? If not, would it even be possible to implement? Thank you so much :heart:

**Comment by B2o5T** [comment]
Possible https://nextra-v2-ggyzxlq24-shuding1.vercel.app/docs/guide/ssg

**Comment by shuding** [comment]
Yep the v1 docs also has this 👍

**Comment by alii** [comment]
Ahh so sorry how I missed this! Thank you!!

**Comment by alii** [comment]
Perhaps some light could be shed on how I could use the codeblock component inside of a component with SSG. For example I would like to include the version numbers here dynamically, but couldn't figure out how to embed the codeblock

![CleanShot 2022-09-07 at 12 19 25](https://user-images.githubusercontent.com/25351731/188866015-0fcc4850-5604-4191-8267-a635cfe5c059.png)

---

Our `Code` component is used by messing around with its `props.children`, but you pass in the output from mdx as the child

![CleanShot 2022-09-07 at 12 19 43](https://user-images.githubusercontent.com/25351731/188866125-826e135f-2d0f-4934-bb91-4aa00c982ff3.png)
