### ISSUE TITLE
Append extra component after the content or under the Navlinks

### ISSUE THREAD

**Issue by champsupertramp** [shuding/nextra#818]
Hi Gentlemen,

I'd like to know if there are proper ways to append content inside the main content or Navlinks without tweaking the core files of /nextra/ and /nextra-theme-doc/ ? Planning on adding a Survey feature in each page below them.

Thank you in advance.

**Comment by B2o5T** [comment]
Use this theme option https://github.com/shuding/nextra/blob/core/packages/nextra-theme-docs/src/types.ts#L24

**Comment by champsupertramp** [comment]
That was it! Thank you!
