### ISSUE TITLE
Error:  pragma and pragmaFrag cannot be set when runtime is automatic.

### ISSUE THREAD

**Issue by LinkSake** [shuding/nextra#82]
I followed the "Get Started" guide but when changing the initial `index.js` to a `index.md` file the following error appears:

```
SyntaxError: .../pages/index.md: pragma and pragmaFrag cannot be set when runtime is automatic.
```

I solved this by changing the react and react-dom version from 17.0.1 to ^16.13.1 on the package.json.
It may be a good idea to specify in the docs that Nextra dosen't support the new react version yet.

**Comment by mxschmitt** [comment]
Duplicate of that and see there too for a workaround: https://github.com/shuding/nextra/issues/27#issuecomment-753445806
