### ISSUE TITLE
Ability to show an icon next to codeblock's filename

### ISSUE THREAD

**Issue by shuding** [shuding/nextra#822]
![image](https://user-images.githubusercontent.com/3676859/189356401-e38ab468-fab5-4409-b234-cf2109293c47.png)

From https://docs.family.co/connectkit/fonts#fonts-example

**Comment by B2o5T** [comment]
How do you see the implementation of this? I can imagine the following:

## Hardcode for language + new theme option `codeLanguageIcons`

```ts
codeLanguageIcons: {
   sh: <SomeTerminalIcon />
   js: <SomeJsIcon />
}
```
````md
```sh
````

## Customizable by new `icon` prop + new theme option `codeIcons`

```ts
codeIcons: {
   terminal: <SomeTerminalIcon />
}
```
````md
```sh icon=terminal
````
