### ISSUE TITLE
seo?

### ISSUE THREAD

**Issue by ilyadynin** [shuding/nextra#825]
is it possible to optimize the individual pages for seo and set individual meta for each page, so that they get listed in google etc?

**Comment by shuding** [comment]
Yes it’s possible. You can set frontMatter for each page and use the `head` theme config to render them as meta tags.

**Comment by ilyadynin** [comment]
could you maybe explain a bit more about the frontMatter property and how to use it? would be very thankful

and I have a second questions - is it okay for seo, if I make two h1 headings with two # (and then hide the first one), because I want the actual page title to be longer than the one displayed in the h1 tag, and I am pulling the info out of the invisible one for the title and displaying the second one on the page

**Comment by ilyadynin** [comment]
so I get that I can set frontMatter in each page at the top and for the title it works, but the title is automatically assigned in the theme config, but what about the description? how can I pull this one into the theme config and should I use them as properties there then, like description={description}?
--- 
title: Title
description: Description
---

**Comment by B2o5T** [comment]
@ilyadynin https://github.com/shuding/nextra/issues/113#issuecomment-1286131857
