### ISSUE TITLE
Rename configurations

### ISSUE THREAD

**Issue by shuding** [shuding/nextra#826]
I'm working on the docs and noticed some option names that can be improved for better consistency and accuracy. This will be another breaking change for v2, hopefully the last one.

- [x] `banner.text` → `banner.content`
- [x] `footer.text` → `footer.content`
- [x] `editLink.text` → `editLink.content`
- [x] `feedback.link` → `feedback.content`
- [x] `bodyExtraContent` → `main.extraContent` (in the future we can configure the main content area here)
- [x] `i18n.text` → `i18n.name`
- [x] `projectChat` → `chat`
- [x] `github` → removed, use `project.link`

**Comment by B2o5T** [comment]
`unstable_faviconGlyph` Should be renamed too

**Comment by shuding** [comment]
I think all the `unstable_` can be removed since we've tested them for so long.

**Comment by raproid** [comment]
Is there a way to completely disable editLink?

If I remove the param, the link still shows as "Edit this page" and leads to the Nextra repo (apparently, it's the default value)

**Comment by raproid** [comment]
Thanks you very much!

**Comment by raproid** [comment]
Btw, you may consider shrinking space for lists. 

If, say, 
1. I start 
2. with a numbered list 
    * and then want to include a sublist
    * the sublist is separated by a huge line that is higher than a normal one

See the screenshots:
<img width="872" alt="Screen Shot 2022-09-26 at 10 36 06 PM" src="https://user-images.githubusercontent.com/22454517/192364850-22b7af44-ca40-49bd-93dd-c6a6e5712788.png">
<img width="872" alt="Screen Shot 2022-09-26 at 10 36 19 PM" src="https://user-images.githubusercontent.com/22454517/192364852-5edf7da5-069c-41ae-8295-51b6098b8fdc.png">

**Comment by raproid** [comment]
You may also want to introduce routing to the 404 page.

For example, adding a link "Back to the main page" below the 404 message. That wold improve user experience by tonnes, since otherwise the user doesn't have any means of navigating from the 404 page except the address bar.

<img width="438" alt="image" src="https://user-images.githubusercontent.com/22454517/192365872-e90b803e-a500-47d8-8b38-df50c1d2e0c6.png">

**Comment by B2o5T** [comment]
> You may also want to introduce routing to the 404 page.
> 
> For example, adding a link "Go to the main page"/"Return to the main page" below the 404 message. That would improve user experience by tonnes, since otherwise the user doesn't have any means of navigating from the 404 page within the web app, but only through the address bar and the browser arrows.
> 
> <img alt="image" width="438" src="https://user-images.githubusercontent.com/22454517/192365872-e90b803e-a500-47d8-8b38-df50c1d2e0c6.png">

It’s already introduced but not documented yet :), thanks for the catch!

**Comment by shuding** [comment]
@raproid 

> Btw, you may consider shrinking space for lists.

Yeah would love to fix that, could you open a new issue for that? Unrelated to this one.

**Comment by raproid** [comment]
@B2o5T can I have the param names and values for my own use?

Sure, doing it right now.

**Comment by B2o5T** [comment]
https://github.com/shuding/nextra/blob/core/examples/swr-site/pages/404.mdx
https://github.com/shuding/nextra/blob/core/examples/swr-site/pages/_meta.en-US.json

**Comment by raproid** [comment]
@B2o5T Thank you!

**Comment by raproid** [comment]
@shuding @B2o5T is there a way to make a page available directly by the URL but not list it in the sidebar menu?

**Comment by raproid** [comment]
@shuding @B2o5T sorry to be a bother, but is there a way to make a page available directly by the URL but not list it in the sidebar menu? I'm really interested in this feature.

**Comment by B2o5T** [comment]
@raproid could you describe more? Don't understand your question

**Comment by raproid** [comment]
@B2o5T I’m speaking about hiding a page from the sidebar menu. Eg, Docusaurus, which  I used before, would generate pages from every .md file in the source folder “docs” but I’d have to include them into the sidebar.js by hand for them to appear in the left sidebar navigation menu. If I didn’t, I’d be able to access the page directly by the URL, but it would be invisible for anybody who uses the left sidebar menu for navigation. 

It is nice for some content you want to expose only by the link to a specific audience.

**Comment by raproid** [comment]
@B2o5T makes sense?

**Comment by B2o5T** [comment]
@raproid try this https://github.com/shuding/nextra/blob/a04c128c240fdc1fd43f8f1bb6961a0eb99872eb/examples/swr-site/pages/_meta.en-US.json#L5

**Comment by raproid** [comment]
@B2o5T which beta version does this feature start from? 
Can I define settings for pages in dedicated JSON objects in beta 25?

**Comment by raproid** [comment]
@B2o5T it is working!!! Thank you very much!

**Comment by champsupertramp** [comment]
For those who are new like me, you need to change the following in the `theme.config.js` file

```
{
bodyExtraContent: ''
}
```

to

```
{
  main: {
   extraContent: '',
   }
}
```

**Comment by B2o5T** [comment]
```
footer: ReactNode | FC | { text: ReactNode | FC }
```

**Comment by B2o5T** [comment]
closed by https://github.com/shuding/nextra/pull/2250

https://github.com/shuding/nextra/releases/tag/nextra%403.0.0-alpha.0
