### ISSUE TITLE
[Feature] Import external markdown file

### ISSUE THREAD

**Issue by mxschmitt** [shuding/nextra#83]
It would be useful if `withLayout` would be kinda exposed so importing an existing markdown file on the disk from the parent directory e.g. could be imported without relying on `next-mdx-remote`.

**Comment by tvvignesh** [comment]
@shuding I tried to import an `mdx` and `md` file from within my `mdx` but didn't seem to work. Is it supported? Looking to have support for partials so that I can import other files like this.

```
---
id: typescript-react-apollo
title: TypeScript React Apollo
---

import '../plugins/client-note.md'

import '../generated-config/typescript-react-apollo.md'

## Usage Example

### With React Hooks
```

**Comment by shuding** [comment]
@tvvignesh Unfortunately that's not supported, you can only import React components currently.

**Comment by tvvignesh** [comment]
@shuding Thanks for letting me know 👍 Any way that we can use remark plugins to do this? For instance, https://github.com/dotansimha/remark-import-partial is a remark plugin which helps importing partials. Was not able to find any docs on using such plugins with Nextra. Possible? Thanks.

**Comment by B2o5T** [comment]
@shuding any updates for this one? In v2?
