### ISSUE TITLE
Not working as expected

### ISSUE THREAD

**Issue by EdgarGomez** [shuding/nextra#84]
For any reason I can't make it work properly. 

- Next and previous links are not working, always pointing to the same page. 
- Anchor links are not being displayed.
- Active menu in sidebar is not showing either.

I've followed the Get Started steps and tried again just cloning this repo. Getting the same problems on both approached.

**Comment by shuding** [comment]
Fixed in latest versions of `nextra` and `nextra-theme-docs`, thanks!
