### ISSUE TITLE
{main_tab} text inside the mdx content throws an error

### ISSUE THREAD

**Issue by champsupertramp** [shuding/nextra#841]
Hi Gentlemen,

Is the `{main_tab}` a reserved keyword?

It throws this error:
```
ReferenceError: main_tab is not defined
```

Here's what's inside the .mdx file:
```
/**
 * Um_profile_content_{main_tab}
 *
 * @param $args
 */
 ```

**Comment by B2o5T** [comment]
expected behaviour since MDX2 treat `{` as JavaScript expression
https://mdxjs.com/docs/troubleshooting-mdx/#problems-writing-mdx

refactor it to

````diff
+ ```
   /**
   * Um_profile_content_{main_tab}
   *
   * @param $args
   */
+ ```
````

**Comment by champsupertramp** [comment]
Hi @B2o5T  Thank you! I'm feeling dumb about this!
