### ISSUE TITLE
Copy-to-Clipboard with Rehype not working

### ISSUE THREAD

**Issue by champsupertramp** [shuding/nextra#847]
Hello!

I saw this attribute to enable the copy feature of the Rehype Code Highlighter:
https://github.com/shuding/nextra/blob/core/packages/nextra/src/mdx-plugins/rehype.js#L38

But it doesn't work when adding the attribute `copy=true`:
```
    ```js filename="hi123.js" {5} showLineNumbers=true copy=true
    import { useState, useEffect } from 'react';

    import { useState, useEffect } from 'react';

    import { useState, useEffect } from 'react';
    ```
```

Am I correct that the above attribute should work?

Versions:
```
    "next": "^12.2.0",
    "nextra": "^2.0.0-beta.20",
    "nextra-theme-docs": "^2.0.0-beta.20",
```

Kindest Regards,

**Comment by B2o5T** [comment]
Replace with

````
```js filename="hi123.js" {5} showLineNumbers copy
````

**Comment by champsupertramp** [comment]
Hi @B2o5T You're a demigod! I tried that earlier,  it wasn't working - it's working now! Weird! Thank you!
