### ISSUE TITLE
Rehype support highlighting with URL parameter

### ISSUE THREAD

**Issue by champsupertramp** [shuding/nextra#848]
Hello Gentlemen,

I hope to make the Rehype Code Highlighter support highlighting codes with URL parameters like the following:

http://localhost:3007/modules/overview?filename=my-file.js{2-3}

Has this been requested and should I look for another component for this case?

Thank you!

**Comment by shuding** [comment]
This is tricky, first you'll have to make your site always SSR, then you need a way to dynamically render the codeblock and pass options to it.

Overall this is a very strange use case to me, may I ask why you need that?

**Comment by B2o5T** [comment]
I think the same as @shuding, don’t see much benefit of it, also your query params should contain a param or hash of which code block you wanna change in the case if there are many code blocks on the page

**Comment by champsupertramp** [comment]
Hi @shuding  @B2o5T 

Thank you for taking the time for this inquiry!

I'm trying to connect the source links from this page:
<img width="1118" alt="Screen Shot 2022-09-17 at 12 25 18 AM" src="https://user-images.githubusercontent.com/12200688/190685928-ba6323a5-40ba-4341-b06c-8db5c77685db.png">


to this code page but I'm thinking I should just link it to our Github repo: 
<img width="1118" alt="Screen Shot 2022-09-17 at 12 25 27 AM" src="https://user-images.githubusercontent.com/12200688/190685968-f441559d-7f2c-41c9-867d-cbaadf525377.png">

**Comment by B2o5T** [comment]
closed as `too overkill`

**Comment by champsupertramp** [comment]
Hi @B2o5T 

Just to add for those who are using the rehype.

I've experienced performance issues when using rehype with source codes that have more than 1,000 lines. It was failing to deploy on Vercel servers.

Thank you
