### ISSUE TITLE
Performance issue when deploying on Vercel

### ISSUE THREAD

**Issue by champsupertramp** [shuding/nextra#867]
Hello Everyone,

I'm having issues when deploying my project on Vercel. It fails to compile on the Vercel. Has anyone done a project that has at least 10,000+ thousand .mdx files?

 I have a nextra project with 300+ mdx files. The following is my package.json

```
  "main": "index.js",
  "scripts": {
    "debug": "NODE_OPTIONS='--inspect' next",
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "clean": "rimraf .next .turbo"
  },
  "author": "Shu Ding",
  "license": "MIT",
  "dependencies": {
    "@docsearch/js": "3",
    "@heroicons/react": "v1",
    "@reach/skip-nav": "^0.16.0",
    "@react-icons/all-files": "^4.1.0",
    "focus-visible": "^5.1.0",
    "intersection-observer": "^0.10.0",
    "markdown-to-jsx": "^6.11.4",
    "next": ">=12",
    "nextra": "^2.0.0-beta.20",
    "nextra-theme-docs": "^2.0.0-beta.20",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-icons": "^4.4.0",
    "react-intersection-observer": "^8.26.2",
    "react-router-dom": "^6.3.0",
    "react-table": "^7.8.0",
    "react-tailwind-table": "^1.1.1"
  },
  "dependenciesMeta": {
    "nextra": {
      "injected": true
    },
    "nextra-theme-docs": {
      "injected": true
    }
  },
  "devDependencies": {
    "autoprefixer": "^10.4.2",
    "eslint-config-next": "^12.2.5",
    "postcss": "^8.4.5",
    "prettier": "^2.0.5",
    "tailwindcss": "^3.0.16"
  },
  "prettier": {
    "semi": false,
    "singleQuote": true,
    "embeddedLanguageFormatting": "off",
    "htmlWhitespaceSensitivity": "strict"
  }
```

Any help would be greatly appreciated.

Regards,

**Comment by B2o5T** [comment]
errors report from Vercel will be helpful also update nextra/nextra-theme-docs to latest beta

**Comment by champsupertramp** [comment]
Hi @B2o5T  I've already reported this to Vercel, and they told me that It takes so much memory, but I only have 300+ MDX files. It works well when I build it locally.

Here's a link to the reproduction: https://github.com/ultimatemember/docs-v3

**Comment by champsupertramp** [comment]
It was an issue with long codes with the syntax highlighter causing the issue. I've removed all MDX files that have issues with code highlighting and it deployed successfully on Vercel. Thank you!
