### ISSUE TITLE
Tailwind utility classes not working consistently

### ISSUE THREAD

**Issue by gigamesh** [shuding/nextra#868]
I'm able to get some tailwind utility classes to work . ex: The logo [in the upper left here](https://docs-git-gigamesh-styles-sound.vercel.app/) is using `fill-brand500`, generated from our tailwind.config.js colors, but if I try putting a `text-red-500` on any text tags, it doesn't work. Those classes don't seem to be part of the bundle. 

How do I get _all_ the default tailwind utility classes to work? 

Our repo is currently private, but should be public in the next few days so I can follow up then if you need to see the full code. Here are the relevant files though:

styles/globals.css:
```
@tailwind components;
@tailwind utilities;
// (not including `@tailwind base;` here based on another thread that said I shouldn't, since it is included 
// in the nextra-theme-docs css)

...
```

_app.js:
```
import 'nextra-theme-docs/style.css'
import '../styles/globals.css'

export default function Nextra({ Component, pageProps }) {
  return <Component {...pageProps} />
}
```

**Comment by B2o5T** [comment]
you don't need to import `nextra-theme-docs/style.css`

**Comment by gigamesh** [comment]
@B2o5T Thank you but that doesn't address the problem I'm having:

![image](https://user-images.githubusercontent.com/32403632/193871796-2fdcff33-d431-4789-bb7e-68d23a530457.png)

How do I get all of Tailwind's utility classes included?

**Comment by B2o5T** [comment]
see swr example to look up tailwind configuration 
<img width="410" alt="image" src="https://user-images.githubusercontent.com/7361780/193873237-a8015aec-94b5-47fd-9478-c8dadb081259.png">

**Comment by gigamesh** [comment]
Ah ok - I thought tailwind supplied all its default colors whether or not you have any custom colors object in theme.config.js, but that's not the case. Thanks!

**Comment by jasjamjos** [comment]
how did you make this work?
