### ISSUE TITLE
Expose a hook in order to handle theme switching (from light to dark and vice versa)

### ISSUE THREAD

**Issue by danielecapuano-dev** [shuding/nextra#873]
It would be nice if a method to handle the theme switching event.

By now a way to know if the user changes the theme is missing
I noticed that in the theme-switch component the next-themes package has been used
Maybe just exposing the same hook / the theme value could be a solution

**Comment by danielecapuano-dev** [comment]
Thank you for your reply!

I still can't figure out how to use it in a component. 

I've tried to import it like this:

```javascript
import { useTheme } from "nextra-theme-docs"
```

but this error is thrown: 

`TypeError: (0 , nextra_theme_docs_index__WEBPACK_IMPORTED_MODULE_1__.useTheme) is not a function`

What am I doing wrong?

**Comment by B2o5T** [comment]
Which version of nextra-theme-docs u use?

**Comment by danielecapuano-dev** [comment]
The version that I am currently using is `1.2.2`

If can be useful the file where I am importing the `useTheme` is in a folder named `components` which is at the same level of the `pages` folder

**Comment by B2o5T** [comment]
Use latest v2 beta
