### ISSUE TITLE
Switching between tabs causes jumping to the last clicked Heading in the On This Page menu

### ISSUE THREAD

**Issue by galleon8** [shuding/nextra#874]
URL to check the behavior: https://www.ankr.com/docs/advanced-api/query-methods/

1. At the URL provided, click any Heading in the On This Page menu (the one on the far right).
2. Scroll to any code snippet with tabs (for better illustration, use the one a bit further from your current position on the page).
3. Switch between tabs.

Here you are — you've just jumped to the Heading previously clicked in the menu!

**Comment by promer94** [comment]
https://github.com/shuding/nextra/pull/567 causes this problem. 

Switching tabs changes the document's height and triggers the ResizeObserver
https://github.com/shuding/nextra/blob/f7856a188b124c44cbe69e856a5c9c3311ac5833/packages/nextra-theme-docs/src/index.tsx#L29-L36
