### ISSUE TITLE
using projectLink and projectLinkIcon doesnt work

### ISSUE THREAD

**Issue by jasjamjos** [shuding/nextra#875]
adding the values projectLink and projectLinkIcon on the `theme.config.js` doesnt update the logo and url on the top right

**Comment by B2o5T** [comment]
Name of theme options were changed, take a look of new ones https://github.com/shuding/nextra/blob/f7856a188b124c44cbe69e856a5c9c3311ac5833/packages/nextra-theme-docs/src/types.ts#L19

**Comment by jasjamjos** [comment]
thanks, okay so instead of projectLink and projectIcon i tried it with:
```
project: {
  icon: <>...<>,
  link: "..."
}
```

still doesnt work for me

**Comment by B2o5T** [comment]
Are you using latest beta 2 version ?

**Comment by jasjamjos** [comment]
No, im using `"nextra": "^1.1.0",` as indicated on the package.json

**Comment by B2o5T** [comment]
There will be no more updates for v1, try v2 beta that will be released soon

**Comment by TinsFox** [comment]
> There will be no more updates for v1, try v2 beta that will be released soon

Where can I find V2 documentation?

**Comment by jasjamjos** [comment]
tried checking out the stable branch, its really different.. more complicated, is it possible to just use the master, and fix or remove the github logo on the top right?

**Comment by jasjamjos** [comment]
Just patched nextra-theme-docs, problem solved.. didnt update to the beta since I like the simplicity of the v1.

thanks

**Comment by B2o5T** [comment]
> Where can I find V2 documentation?

@TinsFox Currently, it's under development, check this PR https://github.com/shuding/nextra/pull/839 and click for latest [Preview – nextra-v2](https://nextra-v2-l1952s19u-shuding1.vercel.app/)

<img width="899" alt="image" src="https://user-images.githubusercontent.com/7361780/195459492-21d78c9b-9fcc-4d38-baf4-8e4949be03de.png">

**Comment by shuding** [comment]
> its really different.. more complicated

I disagree, v2 actually didn't add any complexity to get started. It has more features indeed but it even removed the [step 5](https://nextra.vercel.app/get-started) from v1 without adding more steps.

Maybe it's the docs which look more complicated because it supports more things. I'll collect feedback and improve that part. Let me know if you have thoughts though!
