### ISSUE TITLE
Shiki replacement?

### ISSUE THREAD

**Issue by yevgenypats** [shuding/nextra#876]
Hi team, we love the project here at CloudQuery (https://cloudquery.io).

Stumbled upon an issue with shiki. I tried to create a component that wraps shiki logic so we can create dynamic snippets (specifically for version pinning) and it wasn't possible due to:

- https://github.com/shikijs/shiki/issues/347 (still open issue and no real workaround)

Also, seems like the project got a bit stale - https://github.com/shikijs/shiki/issues/364

Wandering if worth looking into something else.

**Comment by shuding** [comment]
Right now we can't find a reliable replacement for Shiki. Things like JSX doesn't seem to work correctly with other popular libs.
