### ISSUE TITLE
Multiple sidebars

### ISSUE THREAD

**Issue by jaredpalmer** [shuding/nextra#9]
It would be great to be able to extend Nextra to support multiple sidebars.

I think it's possible to do this a few ways. One would be to specify root json files in a theme config.
```js
// theme.config.js
export default {
  ...
  sidebars: {
   reference: "reference.json"
   docs: "docs.json"
  }
}
```

Another way would be to use a filename prefix for the route's metadata files. If found, and if matching the prefix, it would then look for matches during the traversal. 

```js
- index.md
- meta.json  
- docs-meta.json
-- docs/
--- docs-meta.json
--- index.md
--- guides/
----- docs-meta.json
----- index.md
```

**Comment by jaredpalmer** [comment]
reactnative.dev

**Comment by pacocoursey** [comment]
Ah, so the sidebar on the right that shows the page-specific headings. I don't think that's possible atm.

Right now `nextra` provides the theme a `pageMap` object, which is basically the `pages/` directory file structure as a tree. Any theme can generate a page-based sidebar using that. The `pageMap` also includes the `frontMatter` data of all of the pages.

I think we could extend the `pageMap` to also include the list of headings to solve this case.

```js
  const pageMap = [
    {
      name: 'index',
      route: '/index',
      frontMatter: {...},
      headings: [
        {
          name: 'How to use these docs',
          level: 2,
          slug: 'how-to-use-these-docs'
        }
      ]
    }
  ]
```

Is that a good solution? What other desirable file metadata could we be missing?

**Comment by jaredpalmer** [comment]
Another design is to move the heading anchor links to a different table on contents nav on the right side of the page.

**Comment by jaredpalmer** [comment]
I actually meant for the ability to have multiple contextual sidebars not just the one sidebar for the whole site. Like have one sidebar for /docs and another for /api-reference that are totally different pageMaps

**Comment by shuding** [comment]
Sounds like a good feature we can add to the theme

**Comment by shuding** [comment]
The latest `nextra-theme-docs` now has a `floatingTOC: true` option to achieve this, example: https://swr.vercel.app/blog/swr-v1. We can close this now!

**Comment by abhisekmazumdar** [comment]
> I actually meant for the ability to have multiple contextual sidebars not just the one sidebar for the whole site. Like have one sidebar for /docs and another for /api-reference that are totally different pageMaps

This feature is necessary. We need to display different versions of the documentation, each with a distinct set of items in the sidebar. For instance:

https://example.com/v1 =>

sidebar:
Item 1  
Item 2  

https://example.com/v2 =>

sidebar:
Item 34  
Item 67  

I don't want the sidebar to list all items from both v1 and v2.

I see this is not possible with the latest alpha or stable version of Nextra.

**Comment by abhisekmazumdar** [comment]
Ok, I did some more research and found out this: https://nextra.site/docs/docs-theme/page-configuration#sub-docs

My use case can be achieved via sub docs as of now.
