### ISSUE TITLE
Is there a way to have dark mode on by default?

### ISSUE THREAD

**Issue by yairhaimo** [shuding/nextra#90]
As the title says.
Thanks!

**Comment by jamesrarmstrong** [comment]
You can add  `darkMode: true` to `theme.config.js`

**Comment by shuding** [comment]
Both Nextra themes are using https://github.com/pacocoursey/next-themes under the hood, so we can add a `defaultTheme` option and pass it to next-themes 👍

**Comment by Gimmeaphatbeat** [comment]
Any news?

**Comment by B2o5T** [comment]
@Gimmeaphatbeat docs has `nextThemes.defaultTheme`
are you looking for this option for blog theme?
https://github.com/shuding/nextra/blob/708d95d91d01e90cb6e1f0dafb58157199e8e6fd/packages/nextra-theme-docs/src/types.ts#L26

**Comment by JoshuaSmeda** [comment]
As @B2o5T mentioned:

Set
```
export default {
  nextThemes: {
    defaultTheme: 'dark'
  },
```
in your `theme.config` tsx / jsx.

**Comment by maulik-NeoXL** [comment]
copy the following code in your `theme.config.tsx/jsx`

```copy
  nextThemes: {
    defaultTheme: 'dark'
  },
```
