### ISSUE TITLE
How to set logo in the top-left corner with a custom URL?

### ISSUE THREAD

**Issue by raproid** [shuding/nextra#916]
Is it possible to set the logo link to, say, domain root?

E.g. the docs live under www.example.com/docs. Can I make the logo link go to www.example.com?
If yes, how?

**Comment by B2o5T** [comment]
I guess you need set `logoLink` option https://github.com/shuding/nextra/blob/core/packages/nextra-theme-docs/src/types.ts#L56

**Comment by raproid** [comment]
@B2o5T I realized it was a stupid idea and the logo should lead to the root of the current place, which is the docs. 

I'd love to put a link "Back to {name}" as a short text link to the right of the GitHub logo.
<img width="438" alt="Screen Shot 2022-10-31 at 2 30 33 AM" src="https://user-images.githubusercontent.com/22454517/198909883-7b5b42e1-4b85-472e-aa0b-3f7df590cac5.png">

Can I do it and how if yes?

**Comment by raproid** [comment]
A live example of this is Ignite CLI docs: https://docs.ignite.com/

**Comment by B2o5T** [comment]
this could be done after https://github.com/shuding/nextra/pull/907 will be merged

**Comment by raproid** [comment]
@B2o5T doesn't look like tis' merging any time soon. The author pointed to another pr.

**Comment by shuding** [comment]
#907 was merged, let us know if it's still an issue.
