### ISSUE TITLE
Adopt new types and styles for the Callout component (types and styles provided)

### ISSUE THREAD

**Issue by raproid** [shuding/nextra#917]
Hey, guys!

We've been working on a custom Callout component based on yours — one that features more callout types.

We've created such but got a bug when the user sets the "System" option for the dark-light mode.

Could you use [our styles and types](https://github.com/Ankr-network/ankr-docs/blob/main/src/components/Callout.jsx) and improve the Nextra Callout component?

This would benefit us all — you'll bring more callout types to the default Nextra Callout component and will have ready-to-use styles for them, and we won't have to debug our custom Callout component.

We're suggesting the following types:
1. default
2. note
3. info
4. tip
5. success
6. warning
7. error

For the styling, we're suggesting the following mapping:
1. default — grey (the "note" style in our component; neutral and fitting well the Nextra's white-black background).
2. note — yellow (the "warning" style in your component; pale yellow is oftentimes reserved for notes).
3. info — blue (the "info" style in our component).
4. tip — green (the "tip"/"success" style in our component).
5. success — green (the "tip"/"success" style in our component).
6. warning — orange (the "default" style in your component; warnings are oftentimes orange, while pale yellow is oftentimes reserved for notes).
7. error — red (the "error" style in your component).

As for icons, we're suggesting the following icons from the Unicode table:
1. default — better no icon; at the extreme, [page with curl](https://unicode.org/emoji/charts/full-emoji-list.html#1f4c3) or [label](https://unicode.org/emoji/charts/full-emoji-list.html#1f3f7), but better no icon at all.
2. note – [pencil](https://unicode.org/emoji/charts/full-emoji-list.html#270f)
3. info — [information](https://unicode.org/emoji/charts/full-emoji-list.html#2139)
4. tip — [gloves](https://unicode.org/emoji/charts/full-emoji-list.html#1f9e4) (no better option found on our side; can also be the [light bulb](https://unicode.org/emoji/charts/full-emoji-list.html#1f4a1) if it goes well with green in your opinion)
5. success — [check mark button](https://unicode.org/emoji/charts/full-emoji-list.html#2705)
6. warning — [warning](https://unicode.org/emoji/charts/full-emoji-list.html#26a0)
7. error — [error](https://unicode.org/emoji/charts/full-emoji-list.html#1f6ab)

**Comment by raproid** [comment]
@B2o5T @shuding

**Comment by B2o5T** [comment]
Hi @raproid! Could you show a deployed page with all rendered callouts?

**Comment by raproid** [comment]
@B2o5T sure. Here you go: https://ankr-docs-a8gz1x8y3-ankr-docs-team.vercel.app/callout-examples/ 

Please, use "Light" and "Dark" in the theme settings there. As I told you, our custom callout component has a bug and inverts the theme while the "System" option is set.

FYI, I also created a [new branch and edited the callout styles](https://github.com/Ankr-network/ankr-docs/blob/3fb9ecb055b1cd2d216796927fa7f5198ddfb462/src/components/Callout.jsx#L6) a bit.

**Comment by raproid** [comment]
Can also use svg for tip 

Green tip bulb
<svg class="svg-inline--fa fa-lightbulb fa-w-11" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="lightbulb" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 352 512" data-fa-i2svg=""><path fill="currentColor" d="M96.06 454.35c.01 6.29 1.87 12.45 5.36 17.69l17.09 25.69a31.99 31.99 0 0 0 26.64 14.28h61.71a31.99 31.99 0 0 0 26.64-14.28l17.09-25.69a31.989 31.989 0 0 0 5.36-17.69l.04-38.35H96.01l.05 38.35zM0 176c0 44.37 16.45 84.85 43.56 115.78 16.52 18.85 42.36 58.23 52.21 91.45.04.26.07.52.11.78h160.24c.04-.26.07-.51.11-.78 9.85-33.22 35.69-72.6 52.21-91.45C335.55 260.85 352 220.37 352 176 352 78.61 272.91-.3 175.45 0 73.44.31 0 82.97 0 176zm176-80c-44.11 0-80 35.89-80 80 0 8.84-7.16 16-16 16s-16-7.16-16-16c0-61.76 50.24-112 112-112 8.84 0 16 7.16 16 16s-7.16 16-16 16z"></path></svg>

**Comment by B2o5T** [comment]
> As I told you, our custom callout component has a bug and inverts the theme while the "System" option is set.

fix is simple

```diff
-const { theme } = useTheme()
+const { resolvedTheme } = useTheme()
```

also, you don't need to follow check, use `dark:` variant from Tailwind CSS, for example `dark:bg-white dark:border-white`

```
themes[type][theme === 'light' ? 'light' : 'dark'],
```

> Adopting the grey as note and green as tip/success would help the users tho, no?

I think `success` can be added since we have `warning` and `error`, and about `note` I don't have a preference I like the current `default` callout styles but if other maintainers from Nextra have different opinion, we can change it

**Comment by raproid** [comment]
Thx! Fixed our component!
