### ISSUE TITLE
Wrong aria attributes on nav elements

### ISSUE THREAD

**Issue by ernestd** [shuding/nextra#918]
We are using `aria-selected` for elements in `nav` (generated by `Navbar`)
This would be valid for wrappers with roles like `tablist` for instance.
If we want to preserve the `nav` wrapper we should use `aria-current` for the selected element instead.
This is affecting negatively the accessibility Lighthouse score in pages using it.
Reference: https://www.stefanjudis.com/blog/aria-selected-and-when-to-use-it/

**Comment by B2o5T** [comment]
fixed in https://github.com/shuding/nextra/pull/919
