### ISSUE TITLE
Missing Tabbed Components for Code Blocks

### ISSUE THREAD

**Issue by Subham-Maity** [shuding/nextra#924]
## Issue 👇

<h1 align = "center">  Need a react component so we can use it as a tabbed code block  <h1>
<p align="center">
        <img src="https://user-images.githubusercontent.com/278340/93467873-7eb64200-f8ee-11ea-88b5-afbc2e5f51ee.gif"/>
        </p>
<p align="center">
        <img src="https://user-images.githubusercontent.com/278340/93467902-84138c80-f8ee-11ea-9384-08ca6a9540ea.gif"/>
        </p>

**Comment by B2o5T** [comment]
use `Tabs`, `Tab` from `nextra-theme-docs` or you are looking similar thing for `nextra-theme-blog`?
https://github.com/shuding/nextra/blob/core/examples/swr-site/pages/index.en-US.mdx?plain=1#L14-L35

**Comment by Subham-Maity** [comment]
@B2o5T An error message appears when I try to use it, and I'm not sure how to use it 
![image](https://user-images.githubusercontent.com/97989643/198284740-065a9c83-7c7f-4b17-8402-6e47829289fc.png)

**Comment by B2o5T** [comment]
use nextra/nextra-theme-docs v2 beta

**Comment by Subham-Maity** [comment]
@B2o5T  I use this `add nextra@beta`  but didn't work can you tell me what steps to follow in order to update Nextra beta? 
How do I start on the development server?

**Comment by Subham-Maity** [comment]
**As you suggested, I upgraded to nextra/nextra-theme-docs v2 beta . Even though it works fine on the web server, it throws an error when I try to start it on the local server. Please help** @B2o5T 

![image](https://user-images.githubusercontent.com/97989643/198453715-231dc3aa-a9b1-4c6f-a73b-d1928e4c6123.png)

![image](https://user-images.githubusercontent.com/97989643/198457506-f6727a84-44ed-4d87-8a91-0b837b4e78f8.png)
