### ISSUE TITLE
Update `rehype-pretty-code`

### ISSUE THREAD

**Issue by ttwrpz** [shuding/nextra#934]
Due to new version rehype-pretty-code@0.4.0 have new ability to highlight multiple word atomiks/rehype-pretty-code#43, we should update to the latest, for maximum benefits

**Comment by B2o5T** [comment]
Hi @ttwrpz I tried to update, but found some unexpected error https://github.com/atomiks/rehype-pretty-code/issues/45

**Comment by B2o5T** [comment]
done by https://github.com/shuding/nextra/pull/1116, will be available in next release
