### ISSUE TITLE
Nextra 2.0.0 breaks on Next 13.0.0

### ISSUE THREAD

**Issue by verekia** [shuding/nextra#935]
I've been playing around with Nextra 2.0.0 and it was working great on Next `12.3.1`, but after updating to `13.0.0` I am now getting a spinner loading indefinitely in the browser tab. The project is still using the `pages` directory, not `app`.

```
"next": "13.0.0",
"nextra": "2.0.0-beta.38",
"nextra-theme-docs": "2.0.0-beta.38",
```

<img width="1242" alt="Screenshot 2022-10-27 at 13 38 05" src="https://user-images.githubusercontent.com/522007/198209457-6bdaafaf-6827-46d4-abaf-7ae5f9b5c5e0.png">

**Comment by B2o5T** [comment]
should be fixed on latest beta

**Comment by verekia** [comment]
Can confirm 2.0.1 works on 13.0.0 :)

**Comment by karlhorky** [comment]
@pawelkrystkiewicz can you open a new issue for Turbopack support and report back here?
