### ISSUE TITLE
Misaligned "no results found" when searching

### ISSUE THREAD

**Issue by chilikasha** [shuding/nextra#949]
Nextra beta 41
Firefox 106

![SCR-20221028-sn7](https://user-images.githubusercontent.com/3147449/198710198-7cacd652-8a73-4955-b1fe-bd13f3692611.png)
"no results found" is misaligned and borders at the top are not visible.
attached example from beta 16 as well.
![SCR-20221028-u92](https://user-images.githubusercontent.com/3147449/198710257-8a3ab513-64ed-48f7-a516-1485d140c675.png)

**Comment by B2o5T** [comment]
can't reproduce misaligned on the latest firefox

**Comment by B2o5T** [comment]
Closed due silence
