### ISSUE TITLE
Hidden page is visible

### ISSUE THREAD

**Issue by chilikasha** [shuding/nextra#951]
Nextra beta 41

```
"blog": {
    "title": "Blog",
    "type": "page",
    "hidden": true,
    "theme": {
      ...
    }
  },
```
![SCR-20221028-snx](https://user-images.githubusercontent.com/3147449/198711824-8ae1a2c4-1faa-4755-a132-3a8786163545.png)

**Comment by B2o5T** [comment]
https://github.com/shuding/nextra/pull/914
