### ISSUE TITLE
Multiple meta description tags

### ISSUE THREAD

**Issue by chilikasha** [shuding/nextra#962]
Hi,
I have a meta `description` tag set in `theme.config.js`, and some mdx files also have a description, thus such pages now have 2 meta descriptions. I think this issue was absent while on beta 16, and appeared after update to beta 41.
```
---
title: smth...
description: smth...
---
```
2.0.0-beta.41

**Comment by B2o5T** [comment]
Set you default description here https://github.com/shuding/nextra/blob/32cd3855cd0ae3c7687423bae6308a70cc28fd4c/examples/docs/src/theme.config.js#L60-L61
