### ISSUE TITLE
Bug when switching tabs

### ISSUE THREAD

**Issue by raproid** [shuding/nextra#964]
Problem:

1. The user visits a page, eg http://ankr.com/docs/advanced-api/nft-methods
2. The user clicks a ToC anchor inside the page, eg http://ankr.com/docs/advanced-api/nft-methods#ankr_getnftmetadata
<img width="1487" alt="image" src="https://user-images.githubusercontent.com/22454517/200793396-5f715987-71a7-4dbc-beea-9f4cda4e1104.png">
3. The user scrolls down to two tabs below, eg Request/Response.
<img width="1487" alt="image" src="https://user-images.githubusercontent.com/22454517/200793485-b8ddc010-0f08-4262-a0a2-789f27bfae70.png">
4. The user switches between tabs  Request/Response.  The tab is a button and is dynamically inserted into the DOM.
<img width="1487" alt="Screen Shot 2022-11-09 at 11 32 30 AM" src="https://user-images.githubusercontent.com/22454517/200793721-169c71e7-dfa0-49c7-9dda-2f9b4dae6156.png">
5. The result — the user gets scrolled back to the anchor when clicking on the next tab (when switching tabs)
<img width="1487" alt="image" src="https://user-images.githubusercontent.com/22454517/200793396-5f715987-71a7-4dbc-beea-9f4cda4e1104.png">

**Comment by raproid** [comment]
How to resolve this?

And where the code for this behavior lives in your code base?

**Comment by B2o5T** [comment]
try nextra/nextra-theme-docs `2.0.0-beta.41`

**Comment by B2o5T** [comment]
was fixed by https://github.com/shuding/nextra/pull/893
