### ISSUE TITLE
Cannot install Nextra using instructions on Vercel.com

### ISSUE THREAD

**Issue by DavidPIsaac** [shuding/nextra#967]
Followed instructions exactly.  Browser reports:

Unhandled Runtime Error
Error: Invalid <Link> with <a> child. Please remove <a> or use <Link legacyBehavior>.
Learn more: https://nextjs.org/docs/messages/invalid-new-link-with-extra-anchor
Call Stack
LinkComponent
node_modules\next\dist\client\link.js (252:22)

Any suggestions?

**Comment by ttwrpz** [comment]
The latest (`2.0.0-beta.41`) is not currently support Next.js 13

They are currently working on https://github.com/shuding/nextra/pull/946 and once this pull request is merged it should work again.
