### ISSUE TITLE
titleSuffix 2.0.0-beta.41

### ISSUE THREAD

**Issue by joshpollara** [shuding/nextra#969]
Customizing `titleSuffix` in `theme.config.tsx` is not working as expected

```
export default {
...
  titleSuffix: 'foobar',
....
```

Titles are still showing up as `$title -- Nextra`.

**Comment by B2o5T** [comment]
There is no longer titleSuffix option
Use follow option https://github.com/shuding/nextra/blob/32cd3855cd0ae3c7687423bae6308a70cc28fd4c/packages/nextra-theme-docs/src/constants.tsx#L50

**Comment by ojasuno** [comment]
I think this did the trick -- are you able to quickly glance, to make sure I am using this as designed ?!

```
useNextSeoProps: () => ({ titleTemplate: "MySiteTitle" }),
```
