### ISSUE TITLE
Support Chinese route path

### ISSUE THREAD

**Issue by shaodahong** [shuding/nextra#97]
1. Now go to `localhost:3000/前言` find `404`

```bash
$ yarn
$ yarn dev
```

and deploy when build, it's fine

2. Broken footer prev/next link

https://github.com/shaodahong/h5-interview

**Comment by shuding** [comment]
Thanks for reporting!

**Comment by shuding** [comment]
Should be related to https://github.com/vercel/next.js/issues/10084, needs to investigate more.

**Comment by shaodahong** [comment]
And blog Chinese tag is always broken, see https://biewen.me/tags/%E5%B9%B4%E7%BB%88%E6%80%BB%E7%BB%93

**Comment by B2o5T** [comment]
https://github.com/shuding/nextra/issues/983#issuecomment-1331425509
