### ISSUE TITLE
adding ? to the url causes the "Warning: Prop `className` did not match" error

### ISSUE THREAD

**Issue by livesimply** [shuding/nextra#972]
any ideas how to resolve that? it affects my ability to render content based on params

<img width="1549" alt="Screen Shot 2022-11-15 at 2 53 23 PM" src="https://user-images.githubusercontent.com/4743449/202041912-3f3728d5-05a9-4468-a541-b0881d780023.png">

**Comment by livesimply** [comment]
<img width="960" alt="Screen Shot 2022-11-15 at 3 07 37 PM" src="https://user-images.githubusercontent.com/4743449/202043801-9985a1eb-4a46-4776-8c36-8b7848831e38.png">

there's a mismatch between how server and client process params ^

**Comment by Subham-Maity** [comment]
@livesimply use nextra/nextra-theme-docs v2 beta

**Comment by livesimply** [comment]
@Subham-Maity , thanks! I like the previous UI though and also a similar problem arises with 2.0:

<img width="1555" alt="Screen Shot 2022-11-17 at 12 57 51 PM" src="https://user-images.githubusercontent.com/4743449/202558405-7251683b-b097-4675-99b6-49d950c50794.png">

**Comment by Subham-Maity** [comment]
@livesimply May be they are working on this issue #946

**Comment by B2o5T** [comment]
just tried and seems like this issue is goes away, feel free to respond if somebody still has this issue
