### ISSUE TITLE
New Posts not displayed on Site

### ISSUE THREAD

**Issue by daltonturner** [shuding/nextra#981]
When I add new `.md` files to the `/pages/posts/` directory in my Nextra blog they are not rendered on the site. 

Is there a limit to the number of files you can have in the `posts` directory? Am I doing something wrong here? Thank you for any help you may be able to offer!

**Comment by Subham-Maity** [comment]
Hey @daltonturner! Would you be able to provide your reproduction repository??

**Comment by daltonturner** [comment]
Hi @Subham-Maity -- here's a link to the [repo](https://github.com/daltonturner/Replica).

**Comment by Subham-Maity** [comment]
@daltonturner make `.mdx` the extension type

**Comment by daltonturner** [comment]
@Subham-Maity -- thanks, this seemed to work! I've been able to add files with the `.md` extension in the past. I'll stick with `.mdx` going forward. 😄
