### ISSUE TITLE
`.md` not render as mdx

### ISSUE THREAD

**Issue by wenerme** [shuding/nextra#982]
**next.config.js**

```js
const withNextra = require('nextra')({
  theme: 'nextra-theme-docs',
  themeConfig: './theme.config.js',
  unstable_staticImage: true,
})

module.exports = withNextra()
```

`.md` under `pages/schemas/README.md`

Rendered as 
<img width="813" alt="image" src="https://user-images.githubusercontent.com/1777211/203699643-76e17df0-f4b7-465f-8749-adf5ffe2d456.png">

```
$ pnpm -v
7.17.0
$ node -v
v16.17.1
```

```json
{
"dependencies": {
    "@types/node": "18.11.9",
    "@types/react": "18.0.25",
    "@types/react-dom": "18.0.8",
    "eslint": "8.27.0",
    "eslint-config-next": "^12",
    "mermaid": "^9.2.2",
    "next": "^12",
    "nextra": "^1.1.0",
    "nextra-theme-docs": "^1.2.6",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "typescript": "4.8.4"
  }
}
```

**Comment by B2o5T** [comment]
Use the latest v2 beta

**Comment by wenerme** [comment]
@B2o5T .md works, but. `Error: No language registration for regexp`

**Comment by B2o5T** [comment]
do the following for your regex code blocks

````diff
-```regexp
+```
````

**Comment by wenerme** [comment]
trying to make the highlight works with regexp, but can find how, give up.

**Comment by B2o5T** [comment]
@wenerme you can extend the custom language with `rehypePrettyCodeOptions` option, originally was asked in https://github.com/shuding/nextra/issues/555

**Comment by wenerme** [comment]
Thanks, will try that out.
