### ISSUE TITLE
Is there any way to use nextra without next?

### ISSUE THREAD

**Issue by fivethreeo** [shuding/nextra#984]
I wonder if it would be possible to use nextra without next.

 I see it is a webpack plugin. Would it be possible to get the pages with just webpack, webpack-dev-server and a theme with react-router?

**Comment by B2o5T** [comment]
Nope, `next` is required as peer dependency

**Comment by shuding** [comment]
Next.js is required and provides most of the core features for Nextra. It's more than just a webpack plugin
