### ISSUE TITLE
i18n page not being recognized as one

### ISSUE THREAD

**Issue by Nekidev** [shuding/nextra#998]
I have 2 locales, `en` and `es`. However, `index.en.mdx` and `index.es.mdx` are not being recognized as localized versions of `index.mdx`.

This is my project structure:
```
pages/
  _app.jsx
  _meta.en.mdx
  _meta.es.mdx
  index.en.mdx
  index.es.mdx
```

However, when navigating to either `/` or `/es` I get a 404. I need to go to `/index.es` or `/index.en` to see the document. These are the locales shown in each route:

- `/index.en`: Document in english, sidebar sometimes in english and sometimes in spanish, language button shows english
- `/es/index.en`: Document in english, sidebar sometimes in english and sometimes in spanish, language button shows spanish
- `/index.es`: Document in spanish, sidebar sometimes in english and sometimes in spanish, language button shows english
- `/es/index.es`: Document in spanish, sidebar sometimes in english and sometimes in spanish, language button shows spanish

The `NEXT_LOCALE` cookie has no effect in the language shown. The language select menu does not work most of the times, but sometimes it redirects to the index document with the same name in another locale path (ex. `/es/index.en`)

```jsx
// next.config.js
const withNextra = require("nextra")({
  theme: "nextra-theme-docs",
  themeConfig: "./theme.config.jsx",
});
module.exports = withNextra({
  i18n: {
    locales: ['en', 'es'],
    defaultLocale: 'en',
  }
});
```

```jsx
// theme.config.js
export default {
    ...
    i18n: [
        { locale: 'en', text: 'English' },
        { locale: 'es', text: 'Español' },
    ]
}
```

These are the versions used in the project:
```js
{
  "dependencies": {
    "next": "^13.0.6",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "nextra": "^2.0.0",
    "nextra-theme-docs": "^2.0.0"
  }
}
```

**Comment by danielschuster-muc** [comment]
I am not 100% sure if it is need or if there's another workaround, but I have a `middleware.js` file with the following content and that's fixes it for me. 
```js 
export { locales as middleware } from "nextra/locales";
```

**Comment by shuding** [comment]
Exactly what @danielschuster-muc said! We forgot to mention that in the docs, fixing now.
