### ISSUE TITLE
How to add a custom Component?

### ISSUE THREAD

**Issue by phenomen** [shuding/nextra#999]
I want to create a custom component (similar to build-in Callout) but it's not very clear how to approach this task.
Component code itself is trivial but I'm not sure where I'm supposed to put my `.tsx ` to import in mdx.

**Comment by GeekyMax-Ytiam** [comment]
Having the same problem, I can't figure out how to use component #1003

**Comment by shuding** [comment]
Hi all, I added an example here https://github.com/shuding/nextra-docs-template/pull/1. @pawelkrystkiewicz your code looks good to me, is the repository open sourced?

**Comment by phenomen** [comment]
After checking repos from Showcase I figured out how to do it correctly.
1. Create `./components` folder and add your components there.
2. Add basePath and components alies to `./tsconfig.json` like this:
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@components/*": ["components/*"]
    }
  }
}
```
4. Import components in mdx as `import [your-component] from @components/[your-component]`

**Comment by shuding** [comment]
Yes this is a common JS/TS use case, shouldn't be related to Nextra. You can either use relative imports or define `paths` in tsconfig.json. Let me know if there's anything else I can help 👍
